DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Catalog__c.object
<CustomObject>
    <description>Catalog of Sales Aids used for Fulfillment Requests</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Status of Catalog</description>
        <inlineHelpText>Catalog Status: only active catalogs will be processed for delivery</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account for vendor which supplies fulfillment requested from this catalog</description>
        <label>Fulfillment Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Catalogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransportProtocol__c</fullName>
        <description>Transport Protocol for utility sending request items selected from this catalog</description>
        <inlineHelpText>Transport Protocol for utility sending request items selected from this catalog</inlineHelpText>
        <label>TransportProtocol</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>EMAIL</fullName>
                </value>
                <value>
                    <fullName>FTP</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Catalog</label>
    <nameField>
        <label>Catalog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Catalog_Item__c.object
<CustomObject>
    <description>Catalog Items are the individual Sales Aids contained in a Catalog to be selected for fulfillment of a Request and Catalog Item Subscriptions</description>
    <fields>
        <fullName>Catalog__c</fullName>
        <description>Name of catalog which contains these fulfillment items</description>
        <label>Catalog</label>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Catalog Items</relationshipLabel>
        <relationshipName>R00N30000001usfKEAQ</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Status__c</fullName>
        <description>Status of Item in Catalog</description>
        <label>Item Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Owning_Organization__c</fullName>
        <description>Organization to which the solution belongs (SBU, BU). Need to reference solutions which relate to multiple SBUs (e.g. Envex) or BU&apos;s (e.g. Pyralux, Centari).</description>
        <label>Owning Organization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-Env</fullName>
                </value>
                <value>
                    <fullName>BI-Landscape Systems</fullName>
                </value>
                <value>
                    <fullName>BI-Surf</fullName>
                </value>
                <value>
                    <fullName>DDIS-PDP</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
                <value>
                    <fullName>DPT-A&amp;HF</fullName>
                </value>
                <value>
                    <fullName>DPT-Agriculture</fullName>
                </value>
                <value>
                    <fullName>DPT-Air and Filtration</fullName>
                </value>
                <value>
                    <fullName>DPT-Aramids</fullName>
                </value>
                <value>
                    <fullName>DPT-ASPS</fullName>
                </value>
                <value>
                    <fullName>DPT-Automotive</fullName>
                </value>
                <value>
                    <fullName>DPT-Chemical Industrial</fullName>
                </value>
                <value>
                    <fullName>DPT-Cleanroom/Pharma</fullName>
                </value>
                <value>
                    <fullName>DPT-Covers</fullName>
                </value>
                <value>
                    <fullName>DPT-Critical Clean</fullName>
                </value>
                <value>
                    <fullName>DPT-DPP</fullName>
                </value>
                <value>
                    <fullName>DPT-Envelopes</fullName>
                </value>
                <value>
                    <fullName>DPT-ES</fullName>
                </value>
                <value>
                    <fullName>DPT-Graphics</fullName>
                </value>
                <value>
                    <fullName>DPT-Ind Pkg &amp; Protection</fullName>
                </value>
                <value>
                    <fullName>DPT-Mechanical Industrial</fullName>
                </value>
                <value>
                    <fullName>DPT-Medical Fabrics</fullName>
                </value>
                <value>
                    <fullName>DPT-Medical Packaging</fullName>
                </value>
                <value>
                    <fullName>DPT-Medical Specialties</fullName>
                </value>
                <value>
                    <fullName>DPT-NOW</fullName>
                </value>
                <value>
                    <fullName>DPT-Optical</fullName>
                </value>
                <value>
                    <fullName>DPT-PM</fullName>
                </value>
                <value>
                    <fullName>DPT-Public Sector-ER</fullName>
                </value>
                <value>
                    <fullName>DPT-Public Sector-LE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Catalog Item</label>
    <nameField>
        <label>Catalog Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Request__c.object
<CustomObject>
    <description>Multiple purpose Object where various Requests and Transaction Types can be created and tracked throughout the system</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Main Contact this Request applies to</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Supplier__c</fullName>
        <label>Fulfillment Supplier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>R00N30000001Uvb0EAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owning_Organization__c</fullName>
        <label>Owning Organization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DPP-Parts</fullName>
                </value>
                <value>
                    <fullName>DPP-Polymers</fullName>
                </value>
                <value>
                    <fullName>IB</fullName>
                </value>
                <value>
                    <fullName>IB-Advanced Biofuels</fullName>
                </value>
                <value>
                    <fullName>IB-Bioactives-AN</fullName>
                </value>
                <value>
                    <fullName>IB-Bioactives-GP</fullName>
                </value>
                <value>
                    <fullName>IB-Bioactives-HPC</fullName>
                </value>
                <value>
                    <fullName>IB-Biomaterials</fullName>
                </value>
                <value>
                    <fullName>IB-Biorefineries-Biofuels</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sample_Request_Catalog__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sample Request Catalog</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalog__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_to_Contact__c</fullName>
        <description>The Contact person who receives the labels.</description>
        <label>Send to Contact</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Request</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Behind Schedule</fullName>
                </value>
                <value>
                    <fullName>In Approval</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
                <value>
                    <fullName>Error: Rejected by Supplier</fullName>
                </value>
                <value>
                    <fullName>Sent to Supplier</fullName>
                </value>
                <value>
                    <fullName>Accepted by Supplier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>RQ-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <recordTypes>
        <fullName>SalesAidCapture</fullName>
        <active>true</active>
        <description>Sales Aid Requests record type for Capture or Not Started Stage</description>
        <label>Sales Aid - Capture</label>
    </recordTypes>
    <recordTypes>
        <fullName>SalesAidSubmitted</fullName>
        <active>true</active>
        <label>Sales Aid - Submitted</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Request_Item__c.object
<CustomObject>
    <description>Line items on a Request</description>
    <fields>
        <fullName>Catalog_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Catalog Item which relates to this Request Item.  (i.e Sales Aid Fulfillment)</description>
        <label>Catalog Item</label>
        <referenceTo>Catalog_Item__c</referenceTo>
        <relationshipLabel>Request Items</relationshipLabel>
        <relationshipName>R00N30000001uwx6EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>The Request to which this Request Item is related</description>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Request Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The Supplier&apos;s acknowledgment of the Request Item</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Capture</fullName>
                    <default>true</default>
                    <label>Capture</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request Item</label>
    <nameField>
        <displayFormat>ITM-{YY}{MM}{DD}-{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/SampleRequestWS_UT.cls
/*
 *  Test class for testing:
 *  - Class SampleRequestWS 
 */
@istest
global class SampleRequestWS_UT {
    private static final Id SAR_CAPTURE_RTYPE   =   utilRT.getRT('Request__c','SalesAidCapture').Id;
    private static final Id SAR_SUBMITTED_RTYPE =   utilRT.getRT('Request__c','SalesAidSubmitted').Id;
    
    @isTest
    static void testCallout() {
        Account a = new Account();
        a.RecordTypeId = utilRT.getRT('Account','DuPont').Id;
        a.Name = 'Test';
        a.Country__c = 'UNITED STATES';
        a.Owning_Organization__c = 'AGCP';
        insert a;
        Catalog__c cat = new Catalog__c();
        cat.TransportProtocol__c = 'FTP';
        cat.Active__c = true;
        cat.Fulfillment_Supplier__c = a.Id;
        insert cat;
        Catalog_Item__c ci = new Catalog_Item__c();
        ci.Name = 'ItemTest';
        ci.Catalog__c = cat.Id;
        ci.Item_Status__c = 'Active';
        insert ci;
        Contact c=new Contact();
        c.LastName='test cont';
        insert c;
        Request__c r1=new Request__c();
        r1.RecordTypeId=SAR_CAPTURE_RTYPE;
        r1.Status__c = 'In Progress';
        r1.Sample_Request_Catalog__c=cat.Id;
        r1.Lead__c=null;
        r1.Contact__c=c.Id;
        r1.Send_to_Contact__c='testa testb';
        insert r1;
        Request_Item__c ri = new Request_Item__c();
        ri.Request__c = r1.Id;
        ri.Catalog_Item__c = ci.Id;
        insert ri;
        r1.RecordTypeId=SAR_SUBMITTED_RTYPE;
        r1.Status__c = 'In Progress';
        update r1;

        test.startTest();
        Test.setMock(HttpCalloutMock.class, new SampleRequestWS_UT.SampleRequestMockHttpResponse());
        /*r1.Stage__c = 'Submitted';
        update r1;*/
        List<Id> ids = new List<Id>();
        ids.add(r1.id);
        SampleRequestWS.callWS(ids);
        test.stopTest();
    }
    
    global class SampleRequestMockHttpResponse implements HttpCalloutMock{
        global HTTPResponse respond(HTTPRequest req) {
            Organization org = [SELECT InstanceName, IsSandbox FROM Organization];
            if (org.IsSandbox)
                System.assertEquals('http://testfulfillment.cgx.com/PmOmsws/order.asmx', req.getEndpoint());
            else
                System.assertEquals('http://fulfillment.cgx.com/PmOmsws/order.asmx', req.getEndpoint());
            System.assertEquals('GET', req.getMethod());
            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'text/xml');
            res.setBody('<AddOrderResponse xmlns="http://sma-promail/"><AddOrderResult><OrderSeqID>69916</OrderSeqID><OrderID>RQ-181675</OrderID></AddOrderResult></AddOrderResponse>');
            res.setStatusCode(200);
            return res;
        }
    }
}