DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>DPT_AP</fullName>
        <active>true</active>
        <businessProcess>I2C Sales Process</businessProcess>
        <label>DPT-AP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Opportunity_Company__c.object
<CustomObject>
    <description>Companies related to this opportunity</description>
    <fields>
        <fullName>Company_Role__c</fullName>
        <description>Role this company is playing in this opportunity</description>
        <label>Company Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Converter</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Development Customer</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>General Contractor</fullName>
                </value>
                <value>
                    <fullName>Indirect Customer</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Partner-Fabricator</fullName>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
                <value>
                    <fullName>System Manufacturer</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company associated with this Opportunity</description>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunity_Company</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity-Company</label>
    <nameField>
        <displayFormat>OPCO{YY}{MM}-{0000}</displayFormat>
        <label>OPCO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity-Companies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/RecordTypeSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Settings for a particular RecordType</description>
    <fields>
        <fullName>FullName__c</fullName>
        <description>RecordType FullName (Object API Name + &apos;.&apos; + DeveloperName)</description>
        <externalId>true</externalId>
        <inlineHelpText>RecordType DeveloperName</inlineHelpText>
        <label>FullName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OppCompanyRole__c</fullName>
        <description>This field stores the Opp Company Role values for DPP business.</description>
        <label>OppCompanyRole</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RecordType Settings</label>
</CustomObject>

DuPont DevSB/src/classes/ctrlOppCompanyMassAdd_UT.cls
@isTest
private class ctrlOppCompanyMassAdd_UT {
    public static testMethod void testOppCompanyMassAdd() {
        //[05102017] Merge&Spin: Added custom setting data to avoid test failure
        RecordTypeSettings__c RTSetting = new RecordTypeSettings__c();
        RTSetting.Name = 'Opportunity.DPT_AP';
        RTSetting.FullName__c = 'Opportunity_Company__c.DPP_Polymers';
        RTSetting.OppCompanyRole__c = 'abc&def';
        insert RTSetting;
        GeoValidation.DisableGeoValidationOverride=true;
        Account acc = new Account(name='TestCo: ', country__c='United States'); 
        insert acc;
        Opportunity opp = new Opportunity (account = acc, name='test', stagename='won', closedate=Date.TODAY(), recordTypeId = RType.getIdByDevName('Opportunity', 'DPT_AP') );
        insert opp;
        Test.startTest();
        PageReference pageRef = Page.OppCompanyMassAdd;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('oppid', opp.id);        
        ctrlOppCompanyMassAdd ctrl = new ctrlOppCompanyMassAdd();
        ctrl.getPickValues();
       //Will err
        ctrl.newRecords[0].Company__c=acc.id;
        ctrl.save();
        
        //Will not err
        ctrl.newRecords[0].Company_Role__c = 'OEM';
        ctrl.save();
        Test.stopTest();
    }  


}