DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Stage__c</fullName>
        <description>This is the stage or status of the account.</description>
        <label>Account Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Past</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/sma__MAFolder__c.object
<CustomObject>
    <fields>
        <fullName>sma__ParentFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Folder</label>
        <referenceTo>sma__MAFolder__c</referenceTo>
        <relationshipLabel>MapAnything Folders</relationshipLabel>
        <relationshipName>MapAnything_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MapAnything Folder</label>
    <nameField>
        <label>Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MapAnything Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/sma__MATerritory__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sma__Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>sma__MAFolder__c</referenceTo>
        <relationshipLabel>MapAnything Territories</relationshipLabel>
        <relationshipName>MapAnythingTerritories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MapAnything Territory</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MapAnything Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/MACreateShapeLayersByAccountBatchable.cls
// <AK 20170921> Made class schedulable
global class MACreateShapeLayersByAccountBatchable implements Database.Batchable<sObject>, Database.Stateful, Schedulable
{
    //usage: Database.executeBatch(new MACreateShapeLayersByAccountBatchable(), 25);
    global String shapeLayerFolderId {get ; set ;}
    
    // <AK 20170921> Made class schedulable *start
    global void execute(SchedulableContext SC)
    {
        database.executeBatch(new MACreateShapeLayersByAccountBatchable(), 25);
    }
                                  // Change Ends       
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        List<sma__MATerritory__c> territoriesToDelete = new List<sma__MATerritory__c>();
        
        for (sma__MATerritory__c terr : [SELECT Id FROM sma__MATerritory__c WHERE Auto_Created__c = true AND sma__Folder__r.Name = 'By Account' AND sma__Folder__r.sma__ParentFolder__r.Name = 'County'])
        {
            territoriesToDelete.add(terr);
        }
        
        delete territoriesToDelete;
        
        string AccountRecordTypeId = '';
        
        for (RecordType rt : [SELECT Id, Name, sObjectType FROM RecordType WHERE sObjectType = 'Account' AND Name = 'BI - Surfaces'])
        {
            AccountRecordTypeId = rt.Id;
        } 
        
        if (Test.isRunningTest())
        {
            return Database.getQueryLocator([SELECT Id, Name FROM Account 
                                            WHERE ((BI_Account_SubType__c = 'Distribution' AND RecordTypeId = :AccountRecordTypeId AND Account_Stage__c = 'Active') AND (Name LIKE '%- HQ%' OR Name LIKE 'Parksite%')) LIMIT 1]);
        }
        else
        {
            return Database.getQueryLocator([SELECT Id, Name FROM Account 
                                            WHERE ((BI_Account_SubType__c = 'Distribution' AND RecordTypeId = :AccountRecordTypeId AND Account_Stage__c = 'Active') AND (Name LIKE '%- HQ%' OR Name LIKE 'Parksite%'))]);
        }
        
        
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope)
    {
        MACustomLogic.MACreateShapeLayersByAccountBatchable_Execute(scope);
    }
    
    global void finish(Database.BatchableContext BC)
    {
        list<string> EmailAddresses = new list<string>();
        
        EmailAddresses.add(UserInfo.getUserEmail());

        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.ToAddresses = EmailAddresses;
        message.Subject = 'Shape Layers by Account Batch Complete';
        message.PlainTextBody = 'The batch for Generating Shape Layers by Account has finished.';
        
        Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage> {message};
        Messaging.SendEmailResult[] rslts = Messaging.sendEmail(messages);
    }
    
    
}