DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Email__c.object
<CustomObject>
    <description>Each record represents a unique email in the system, user for:
-Privacy Notification</description>
    <fields>
        <fullName>Bounced__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Bounced is captured at the record on the eMail object and pushed to Leads &amp; Contact records based on email address. Whenever a lead and contact eMail is updated the bounced flag is released.</description>
        <label>Bounced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to LastModified Contact</description>
        <inlineHelpText>LastModified Contact</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email Address (External Id Unique)</description>
        <externalId>true</externalId>
        <inlineHelpText>Email Address</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to LastModified Lead</description>
        <inlineHelpText>LastModified Lead</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalContacts__c</fullName>
        <description>Total number of Contacts with this email.</description>
        <label>Total Contacts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalLeads__c</fullName>
        <description>Total Number of Leads with this email</description>
        <label>Total Leads</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Email</label>
    <nameField>
        <label>EM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Bounced__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Bounced is captured at the record on the eMail object and pushed to Leads &amp; Contact records based on email address. Whenever a lead and contact eMail is updated the bounced flag is released.</description>
        <inlineHelpText>This is a READ ONLY field which is updated from a corresponding record in the eMail object.</inlineHelpText>
        <label>Bounced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin_Channel_Type__c</fullName>
        <inlineHelpText>Channel Type of the DuPont touch point where this lead was collected. This can be different from the channel where the customer heard from us (use Lead Source for this purpose)</inlineHelpText>
        <label>Origin Channel Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Data File</fullName>
                </value>
                <value>
                    <fullName>eMail</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Face to Face</fullName>
                </value>
                <value>
                    <fullName>Paper Mail</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Website-Secure</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>globalEmail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to global Email record.</description>
        <label>GlobalEmail</label>
        <referenceTo>Email__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/EmailBase_UT.cls
/*******************************************************************************
Copyright © 2013 DuPont. All rights reserved. 
Author: Thomas Snyder
Email: thomas.snyder@usa.dupont.com, tom@3ddd.com
Description:  UT for EmailBase (Privacy Notification) 
********************************************************************************/
@isTest
private class EmailBase_UT {
  
  
  /*
  static testMethod void testPersonAccount() {  
    delete [Select id from Email__c where email__c like '%emailbaseut.com'];
    
    Id RTypeId = [
            SELECT r.Id, r.Name, r.DeveloperName, r.IsPersonType 
            FROM RecordType r 
            WHERE sObjectType = 'Account' AND IsPersonType=True LIMIT 1
        ].Id;
    Account a =new Account(recordtypeid=RTypeId, PersonLastNameLocal='TestPersonAcc', PersonEmail='testpa@emailbaseut.com', country__c='United States', Type='Customer');
    insert a;
  
    System.assertEquals(0,[Select id from Email__c where email__c like '%emailbaseut.com'].size());

  }
  */
  
 static testMethod void test1() {  
    delete [Select id from Email__c where email__c like '%emailbaseut.com'];

    System.assertEquals(0,[Select id from Email__c where email__c like '%emailbaseut.com'].size());
    Lead l = new Lead(lastname='tester', company='acme', email='test1@emailbaseut.com');
    insert l;

    Account a =new Account(name='TestCo', country__c='United States', Type='Customer');
    insert a;
        
    Contact c =new Contact(accountid=a.id, lastname='TestCo: ', email='test1@emailbaseut.com');
    insert c;  
    
    //Check both lead and contact are referenced, totaled and connected to correct global email.
    LIST<Email__c> em = [Select id, TotalLeads__c, TotalContacts__c, Contact__c, Lead__c from Email__c where email__c='test1@emailbaseut.com'];
 //PKH   System.assertEquals(1, em.size());   
 //PKH   System.assertEquals(em[0].id,[Select globalEmail__c from Lead where id=:l.id].globalEmail__c);
 //PKH   System.assertEquals(1, em[0].TotalLeads__c);
 //PKH   System.assertEquals(em[0].id,[Select globalEmail__c from Contact where id=:c.id].globalEmail__c);
 //PKH   System.assertEquals(1, em[0].TotalContacts__c);
 //PKH   System.assertEquals(l.id, em[0].Lead__c);
 //PKH   System.assertEquals(c.id, em[0].Contact__c);
    
    ContactHandler.InProcess = false;
    c.email='test2@emailbaseut.com';
    update c;
    
    
    //Since the Contact changed email...
    //Check that new Email__c only the reflects the contact and is referenced, totaled and connected.
    LIST<Email__c> em2 = [Select id, TotalLeads__c, TotalContacts__c, Contact__c from Email__c where email__c='test2@emailbaseut.com'];
//PKH    System.assertEquals(1, em2.size());
//PKH    System.assertEquals(0, em2[0].TotalLeads__c);
    LIST<Contact> testC = [Select globalEmail__c from Contact where id=:c.id];
//PKH    System.assertEquals(em2[0].id,testC[0].globalEmail__c);
//PKH    System.assertEquals(c.id,em2[0].Contact__c);
//PKH    System.assertEquals(1, em2[0].TotalContacts__c);    

    //Also, Since the Contact changed email...
    //Check previous Email__c record only reflects the lead and NOT the contact
    em.clear();
    em = [Select id, TotalLeads__c, TotalContacts__c, Contact__c, Lead__c from Email__c where email__c='test1@emailbaseut.com'];
//PKH    System.assertEquals(1, em.size());
//PKH    System.assertEquals(em[0].id,[Select globalEmail__c from Lead where id=:l.id].globalEmail__c);
//PKH    System.assertEquals(1, em[0].TotalLeads__c);
//PKH    System.assertNotEquals(em[0].id,[Select globalEmail__c from Contact where id=:c.id].globalEmail__c);
//PKH    System.assertEquals(0, em[0].TotalContacts__c);
//PKH    System.assertEquals(l.id, em[0].Lead__c);
//PKH    System.assertEquals(null, em[0].Contact__c);
    
    Test.startTest();
    //[PriyaK30022017] commented batch class execution and excuting scheduled class
    //Database.executeBatch(new batchEmailRefresh(),200);
    String sch = '0 0 0 15 3 ? 2022';
    system.schedule('Test Email refresh batch schedule', sch, new SchedBatchEmailRefresh()); 
    //[PriyaL30022017] End
    Test.stopTest();
  }


  static testMethod void test_SpecialLogic() {  
    delete [Select id from Email__c where email__c like '%emailbaseUT.com'];
    Account a =new Account(name='TestCo', country__c='United States', Type='Competitor');
    insert a;
    Contact c =new Contact(accountid=a.id, lastname='TestCo: ', email='test1@emailbaseUT.com');
    insert c;  
    
    LIST<Email__c> em = [Select id, TotalLeads__c, TotalContacts__c from Email__c where email__c='test1@emailbaseUT.com'];
    System.assertEquals(0, em.size());
    
        
    Lead l = new Lead(lastname='tester', company='acme', email='testev@emailbaseut.com', Origin_Channel_Type__c='Event');
    insert l;
    
    Account a2 =new Account(name='TestCo', country__c='United States', Account_Sub_Type__c='Sales Agency');
    insert a2;
    Contact c2 =new Contact(accountid=a2.id, lastname='TestCo: ', email='sa@emailbaseUT.com');
    insert c2;
    

  }

  static testMethod void test_Bounce() {  
    delete [Select id from Email__c where email__c like '%emailbaseUT.com'];

    LIST<Email__c> em = [Select id, TotalLeads__c, TotalContacts__c from Email__c where email__c='bounce@emailbaseUT.com'];
//PKH    System.assertEquals(0, em.size());
    Email__c email= new Email__c(email__c='bounce@emailbaseUT.com', CurrencyIsoCode='USD');
        insert email;
        system.debug('*****************'+email);
        Lead l = new Lead(bounced__c = false, lastname='tester', company='acme', email=email.email__c, Origin_Channel_Type__c='Event');
        insert l;
        LIST<Email__c> em1 = new LIST<Email__c>();
        em1 =[Select id, TotalLeads__c, email__c, TotalContacts__c, bounced__c from Email__c where id=: email.id];
        
//PKH    System.assertEquals(1, em1.size());    
    Test.startTest();
    system.debug ('////12234');
    EmailHandler.InProcess=false;
    em1[0].Bounced__c=true;
    update em1[0];

    boolean bounce = [Select Bounced__c from Lead where id=:l.id].Bounced__c;
    //System.assertEquals(true, bounce);    
    Test.stopTest();
    
  }


}