DuPont DevSB/src/objects/Account_Material__c.object
<CustomObject>
    <description>Custom object to link Account &amp; Contacts with Materials</description>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Material__c.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ERP Material – General Data</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Account-Materials</relationshipLabel>
        <relationshipName>R00N30000002iTg2EAE</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account-Material</label>
    <nameField>
        <displayFormat>AMID-{MMYY}-{000000}</displayFormat>
        <label>AM ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account-Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlDataAnalysis_UT.cls
@isTest
private class ctrlDataAnalysis_UT {


  static testMethod void test1() {

        PageReference pageRef = Page.DataAnalysis;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('fname', 'Account.Type');      
        ApexPages.currentPage().getParameters().put('lim', '10');  
        ApexPages.currentPage().getParameters().put('gtype', 'recordtype');    
        ctrlDataAnalysis ctrl = new ctrlDataAnalysis();
        ctrl.analyze();  
        ctrl.getPieData();
        
        for (DataAnalysis.Record r : ctrl.results) {
            system.debug(r.fields);
        }
        ctrl.gtype='program';
        ctrl.analyze();
        
        
        ctrl.sobjectType='Account_Material__c'; 
        ctrl.sObjectType_onChange();
        ctrl.field='Product_Name__c';
        ctrl.gtype=null;
        ctrl.analyze();
        ctrl.gtype='program';
        ctrl.groupByFilter='%abc%';
        ctrl.analyze();
        ctrl.gtype='recordtype';
        ctrl.analyze();
        ctrl.customAnalyze();

    }  
    
}