DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Behind Schedule</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/MyControll_UT.cls
@isTest
private class MyControll_UT {

    public static testMethod void myUnitTest() {
        test.startTest(); 
        Account acc = new Account();     
        acc.Name='ParentAccount'; 
        acc.country__c='United States'; 
        insert acc;
         //someId = '005a0000008XJ8N';
           Opportunity opp=new Opportunity();
           opp.account = acc;
           opp.name='test';
           opp.stagename='target';
           opp.closeDate=Date.Today();
           opp.CurrencyIsoCode='USD';
//opportunityList = [select  accountid, name,closedate, stagename from opportunity where (Status__c='Active') order by closedate asc limit 1];                            
       
          // opportunityList.add(opp);
           //insert opportunityList;
           insert opp;
        //Test.setCurrentPage(myVfPage);  
        system.currentPageReference().getParameters().put('Id', opp.Id);
   

        
        
        List<Opportunity> opportunityList = new List<Opportunity>();
        
           MyControll myc =  new MyControll();
            
             //myc.MyControll();
              //myc.MyControll(opp.id);    
              myc.save();
              myc.getmycontroll();

           test.stopTest();   
           
           
 }
}