DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Group__c</fullName>
        <label>Customer Group</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/ERP_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Account_Group__c</fullName>
        <description>The account group is a classifying feature within customer master records. The account group determines in which number range the customer account number should be; whether the number is assigned by the user or by the system; which specifications are necessary or possible in the master record.</description>
        <label>Account Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>The city of this customer as stored in SAP.</description>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <description>The country of this customer as stored in SAP.</description>
        <label>Country Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country of this customer as stored in SAP.</description>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <description>Key with which the customer can be identified within the SAP system.Gives an alphanumeric key, which clearly identifies the customer or vendor in the SAP system.</description>
        <label>Customer Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DUNS_Number__c</fullName>
        <description>The Data Universal Numbering System or D-U-N-S® Number is D&amp;B&apos;s copyrighted, proprietary means of identifying business entities on a location-specific basis. This unique nine-digit sequence provided by D&amp;B recognized as the universal standard for identifying and keeping track of a company</description>
        <label>DUNS Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the Source Cluster + Customer Code + Sales Org Code + Distribution Channel Code + Division Code to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Organizational Group ( as ERP Sales Area ).</description>
        <label>Sales Area</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>ERP Customers</relationshipLabel>
        <relationshipName>ERP_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO_Box__c</fullName>
        <description>The Post Office Box of this customer as stored in SAP.</description>
        <label>PO Box</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <description>Geographical region this customer is located as stored in SAP.</description>
        <label>State/Province Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>The street of this customer as stored in SAP.</description>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_of_Payment__c</fullName>
        <description>Key for defining payment terms composed of cash discount percentages and payment periods. It is used in sales orders, purchase orders, and invoices.</description>
        <label>Terms of Payment</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZIP_Postal_Code__c</fullName>
        <description>The ZIP or postal code of this customer as stored in SAP.</description>
        <label>ZIP/Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ERP Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/OrgGroup__c.object
<CustomObject>
    <description>Identifies a fundamental framework or collection of entities, assets. people, processes etc. which are related for administrative purposes in Force.com. (example of use cases: identify a Sales Area grouping of master data from SAP; identify metadata asset grouping for a CRM Program; identify security asset grouping used for a program sharing model, etc.)</description>
    <fields>
        <fullName>Account_Rule__c</fullName>
        <description>These values drive the business logic to determine which ERP Customer to create new accounts. The Account group on ERP Customer is where these values are compared.</description>
        <inlineHelpText>These values drive the business logic to determine which ERP Customer to create new accounts. The Account group on ERP Customer is where these values are compared.</inlineHelpText>
        <label>Account Rule</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Price Reference Customer</fullName>
                </value>
                <value>
                    <fullName>Z001 ( Sold-to party )</fullName>
                </value>
                <value>
                    <fullName>Z002 (Ship-to party)</fullName>
                </value>
                <value>
                    <fullName>Z003 (Payer)</fullName>
                </value>
                <value>
                    <fullName>Z004 (Bill-to party)</fullName>
                </value>
                <value>
                    <fullName>Z012 (Hierarchy node)</fullName>
                </value>
                <value>
                    <fullName>Z100 (Plant/Distribution Ctr)</fullName>
                </value>
                <value>
                    <fullName>ZCOA (COA Recipient)</fullName>
                </value>
                <value>
                    <fullName>ZCPD (One-time cust.(int.no.)</fullName>
                </value>
                <value>
                    <fullName>ZCSR (Customer Service Rep)</fullName>
                </value>
                <value>
                    <fullName>ZEND (End User)</fullName>
                </value>
                <value>
                    <fullName>ZEXC ( Sold-to party )</fullName>
                </value>
                <value>
                    <fullName>ZISS Intrasub sale @ mkt price</fullName>
                </value>
                <value>
                    <fullName>ZLOG (Port)</fullName>
                </value>
                <value>
                    <fullName>ZMAR (Marine partner)</fullName>
                </value>
                <value>
                    <fullName>ZSRP (Sales Representative)</fullName>
                </value>
                <value>
                    <fullName>ZSUB (Dupont Subsidiary)</fullName>
                </value>
                <value>
                    <fullName>ZZ-Field not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the Sales Org Code + Distribution Channel Code + Division Code to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PHI-LA</fullName>
                </value>
                <value>
                    <fullName>PHI-AFRICA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Organizational Group</label>
    <nameField>
        <displayFormat>OG-{0000000000}</displayFormat>
        <label>Org Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Groups</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>The DuPont Business (Business Unit) or legal entity</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ERPCustomerHandler.cls
/*******************************************************************************
Copyright © 2012 DuPont. All rights reserved. 
Author: Thomas Snyder
Email: thomas.snyder@usa.dupont.com, tom@3ddd.com
Description:  Trigger Handler for ERPCustomer__c 
********************************************************************************/
public class ERPCustomerHandler extends TriggerHandlerBase {

public static final string RTYPE_ERP_ACCOUNT = Rtype.getIdByDevName('Account','ERP_Account');

  public override void bulkafter(){
        if ( Trigger.IsUpdate || Trigger.IsInsert ) {
            processAccountSync();
             /*<SravanthiLakkimsetty20140918>
            Description: call the class method for Attaching the ERP customer with Account...
            <--ChangesStarted-->*/
            ctrlLinkERPCustToAccount ctrlLinkERPCustToAccountinstance = new ctrlLinkERPCustToAccount();
            ctrlLinkERPCustToAccountinstance.onTrigger();
             //<--ChangesFinished-->  
        }
    }


//*****************************************************************************************
// helper Methods
//*****************************************************************************************

   public static void processAccountSync() {
    
        LIST<Account> accountsToUpsert = new LIST<Account>();
        for( ERP_Customer__c cust : [ SELECT Id, Name, Customer_Code__c, Account_Group__c, DUNS_Number__c, Terms_of_Payment__c,
                        ZIP_Postal_Code__c, Street__c, State_Province__c, PO_Box__c, Country__c, Country_Code__c, City__c,
                        OrgGroup__r.OwnerId, OrgGroup__r.Account_Rule__c, External_ERP_ID__c,
                        (Select Id from Accounts__r)
                        FROM ERP_Customer__c 
                        WHERE Id in: Trigger.new] ) {
            
            //Does this SalesArea subscribe to this Customer's Account group?
            system.debug('------cust.Account_Group__c:'+cust.Account_Group__c);
            system.debug('------cust.OrgGroup__r.Account_Rule__c:'+cust.OrgGroup__r);
            if ( cust.OrgGroup__r.Account_Rule__c!=null && ( cust.OrgGroup__r.Account_Rule__c.contains(cust.Account_Group__c)) ) {
                
                if (cust.Accounts__r.size()==0) {
                    //No accounts related, create one...
                    Account acc = new Account(name=cust.Name, 
                        ownerid         =cust.OrgGroup__r.OwnerId,
                        recordtypeid    =RTYPE_ERP_ACCOUNT
                        //muti-currency not setup yet ,CurrencyIsoCode  =cust.CurrencyIsoCode
                        );
                    customerToAccount(cust,acc);
                    accountsToUpsert.add(acc);
                }
                else {
                    //loop through accounts and update the ERP fields
                    for ( Account acc : cust.Accounts__r ) {
                        customerToAccount(cust,acc);
                        accountsToUpsert.add(acc);
                    }
                }
            }   
        } //next cust
        
        //save accounts
        if (accountsToUpsert.size()>0) {
            system.debug('upsert: '+accountsToUpsert);
            LIST<Database.Upsertresult> res = database.upsert(accountsToUpsert, false);
            system.debug(res);
        }
        
    }
    
    
    
    //used for both inserts and updates to copy the master data from customer to account
    public static void customerToAccount(ERP_Customer__c cust, Account acc) {
        acc.ERP_Customer__c             =cust.id;
        acc.ERP_Account_Name__c         =cust.Name;
        acc.country__c                  =cust.Country__c;
        acc.Terms_Of_Payment__c         =cust.Terms_of_Payment__c;
        acc.ERP_Account_Code__c         =cust.Customer_Code__c;
        acc.Non_unique_External_ID__c   =cust.External_ERP_ID__c;
        //acc.ERP_Account_Group__c      =cust.Account_Group__c; //does not match
        acc.ERPAccountType__c           =cust.Account_Group__c;
        acc.DUNS_Number__c              =Util.StringToDecimal(cust.DUNS_Number__c);
        //TODO: determine if we need to blockformat, and/or country specific lauout
        acc.ERPAddress__c               = formatAddress(cust.Street__c,cust.City__c,cust.State_Province__c, cust.ZIP_Postal_Code__c, cust.Country__c);
    }
    

    private static string formatAddress(string street, string city, string state, string postalCode, string country) {
            string s='';
            if (Street != null)         s += Street + '\n';
            if (City != null )          s += City + ', ';
            if (State != null )         s += State + ' ';
            if (PostalCode!= null )     s += PostalCode;
            if (Country != null )       s += '\n'+ Country;
            return s;
        }
}

/*
public with sharing class ERPCustomerHander {
    
    /*
    
public static MAP<id, ERP_Customer__c>  filterERPCustomersWithoutAccount(MAP<id, ERP_Customer__c> custs);  //returns: MAP<id, ERP_Customer__c>
    //Get set of ERPCustomersWithAccount
    SET<id>  erpWithAcc = (for .. [Select distinct ERP_Customer__c from Account where ERP_Customer__c in custs.keyset();]
    return custs.remove(erpWithAcc);
}
    
    
    
    
public static MAP<id, Program__c>  getBusinessRules(MAP<id, ERP_Customer__c> custs) {
     //returns: MAP<ERP Customer.id, Program>
    1.  MAP<id,id>  mapProgram = //MAP<Program.id,ERP_Customer.id> loop through and get a set of all Programs;
    2.  SELECT all the business rule fields in program__c where program id=mapProgram.keyset();
    3.return MAP<ERP_Customer__c.id, Program__c>

}

public Account createAccountFromERPCustomer(ERP_Customer__c cust) {
...
}


public void override AfterUpdate(MAP<id, ERP_Customer__c> custs) {
    MAP<id, ERP_Customer__c> filteredCusts = filterERPCustomersWithoutAccount(custs);
    MAP<id, Program__c> rules = getBusinessRules(filteredCusts);
    
    LIST<Account> AccountsToInsert = new LIST<Account>();
    for (ERP_Customer__c c: filteredCusts) {
        rule=rules.get(c.id);
        if (rule....)
            AccountsToInsert.add(createAccountFromERPCustomer(c));
    }
}


*/