DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Group__c</fullName>
        <label>Customer Group</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/ERP_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Account_Group__c</fullName>
        <description>The account group is a classifying feature within customer master records. The account group determines in which number range the customer account number should be; whether the number is assigned by the user or by the system; which specifications are necessary or possible in the master record.</description>
        <label>Account Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Organizational Group ( as ERP Sales Area ).</description>
        <label>Sales Area</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>ERP Customers</relationshipLabel>
        <relationshipName>ERP_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ERP Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/OrgGroup__c.object
<CustomObject>
    <description>Identifies a fundamental framework or collection of entities, assets. people, processes etc. which are related for administrative purposes in Force.com. (example of use cases: identify a Sales Area grouping of master data from SAP; identify metadata asset grouping for a CRM Program; identify security asset grouping used for a program sharing model, etc.)</description>
    <fields>
        <fullName>Account_Rule__c</fullName>
        <description>These values drive the business logic to determine which ERP Customer to create new accounts. The Account group on ERP Customer is where these values are compared.</description>
        <inlineHelpText>These values drive the business logic to determine which ERP Customer to create new accounts. The Account group on ERP Customer is where these values are compared.</inlineHelpText>
        <label>Account Rule</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Price Reference Customer</fullName>
                </value>
                <value>
                    <fullName>Z001 ( Sold-to party )</fullName>
                </value>
                <value>
                    <fullName>Z002 (Ship-to party)</fullName>
                </value>
                <value>
                    <fullName>Z003 (Payer)</fullName>
                </value>
                <value>
                    <fullName>Z004 (Bill-to party)</fullName>
                </value>
                <value>
                    <fullName>Z012 (Hierarchy node)</fullName>
                </value>
                <value>
                    <fullName>Z100 (Plant/Distribution Ctr)</fullName>
                </value>
                <value>
                    <fullName>ZCOA (COA Recipient)</fullName>
                </value>
                <value>
                    <fullName>ZCPD (One-time cust.(int.no.)</fullName>
                </value>
                <value>
                    <fullName>ZCSR (Customer Service Rep)</fullName>
                </value>
                <value>
                    <fullName>ZEND (End User)</fullName>
                </value>
                <value>
                    <fullName>ZEXC ( Sold-to party )</fullName>
                </value>
                <value>
                    <fullName>ZISS Intrasub sale @ mkt price</fullName>
                </value>
                <value>
                    <fullName>ZLOG (Port)</fullName>
                </value>
                <value>
                    <fullName>ZMAR (Marine partner)</fullName>
                </value>
                <value>
                    <fullName>ZSRP (Sales Representative)</fullName>
                </value>
                <value>
                    <fullName>ZSUB (Dupont Subsidiary)</fullName>
                </value>
                <value>
                    <fullName>ZZ-Field not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Organizational Group</label>
    <nameField>
        <displayFormat>OG-{0000000000}</displayFormat>
        <label>Org Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ERPCustomerHandler_UT.cls
/*******************************************************************************
Copyright © 2012 DuPont. All rights reserved. 
Author: Thomas Snyder
Email: thomas.snyder@usa.dupont.com, tom@3ddd.com
Description:  ERPCustomerHandler Unit Test(s)
********************************************************************************/
@isTest
private class ERPCustomerHandler_UT {

	static testMethod void test_SyncAccounts() {

   		Test.startTest();
   		
   		OrgGroup__c p1 = new OrgGroup__c(Account_Rule__c='SOLD-TO');
   		OrgGroup__c p2 = new OrgGroup__c(Account_Rule__c='SOLD-TO;SHIP-TO');
		OrgGroup__c p3 = new OrgGroup__c(Account_Rule__c=null);
		insert new OrgGroup__c[]{p1,p2,p3};
		
		ERP_Customer__c c1 = new ERP_Customer__c(name='Cust 1', Account_Group__c='SOLD-TO', OrgGroup__c=p1.id);
		ERP_Customer__c c2 = new ERP_Customer__c(name='Cust 2', Account_Group__c='SHIP-TO', OrgGroup__c=p2.id);
		ERP_Customer__c c3 = new ERP_Customer__c(name='Cust 3', Account_Group__c='SOLD-TO', OrgGroup__c=p3.id);
		insert new ERP_Customer__c[]{c1,c2,c3};
		system.debug(c1);
		//try {
			Account ac1=[Select Id, ERP_Account_Name__c from Account where ERP_Customer__c=:c1.id];
			Account ac2=[Select Id, ERP_Account_Name__c from Account where ERP_Customer__c=:c2.id];
			system.debug(ac1);
			system.assertEquals('Cust 1',ac1.ERP_Account_Name__c);
			system.assertEquals('Cust 2',ac2.ERP_Account_Name__c);
			system.assertEquals(0,[Select Id, Name from Account where ERP_Customer__c=:c3.id].size());	
		//}catch(Exception ex) {}
	
		
        Test.stopTest();
       
    }  
	
}