DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Call_Report__c.object
<CustomObject>
    <description>Sales Team Members&apos; Call Report documentation.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Reports</relationshipLabel>
        <relationshipName>R00N30000001Uzc5EAC</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attendees__c</fullName>
        <label>Attendees</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Call_Date__c</fullName>
        <description>Actual Start Date of the meeting</description>
        <label>Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Face To Face</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Phone-Inbound</fullName>
                </value>
                <value>
                    <fullName>Phone-Outbound</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Geography__c</referenceTo>
        <relationshipLabel>Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Overall status of this Call</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Behind Schedule</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Completed &amp; Reviewed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <description>Main topic of this call report</description>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Logistics</fullName>
                </value>
                <value>
                    <fullName>Packaging</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Sales Call</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Call report:  Pre-call Planner, Post interaction call report</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call Report Only</fullName>
                </value>
                <value>
                    <fullName>Competitor Summary</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Monthly Highlight and Call Report</fullName>
                </value>
                <value>
                    <fullName>Monthly Highlight Only</fullName>
                </value>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Pre-Call Planner</fullName>
                    <default>true</default>
                    <label>Pre-Call Planner</label>
                </value>
                <value>
                    <fullName>Weekly Highlight</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Call Report</label>
    <nameField>
        <label>Call Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Geography__c.object
<CustomObject>
    <fields>
        <fullName>Code2__c</fullName>
        <description>Unique code across the parent. This field is required and unique across all records with the same parent area.  External Id.  
TODO: Add a trigger to enforce this two key uniqueness.</description>
        <externalId>true</externalId>
        <label>SubCode</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <description>Unique code for the this area.  This field is required and unique across all records.</description>
        <externalId>true</externalId>
        <label>Code</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <description>administrative level of territory in geo hierarchy
1=Region, 2=Sub-Region, 3=Country, 4=State, 5=County or similar,6=postalcode</description>
        <label>Level</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geography</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Rule__c.object
<CustomObject>
    <description>Contains record type specific rules which will return a score, approver or other values based on a criteria</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>The checkbox will allow users to control active/inactive rule and manage the rules better.</description>
        <inlineHelpText>Uncheck to make the rule inactive</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Range__c</fullName>
        <description>Stores the range of  scores and corresponding grades to that scores.</description>
        <label>Range</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <description>This custom field contains the record Type Name.</description>
        <label>Rule Record Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Type__c</fullName>
        <description>For capturing the application where the rule will be used</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dynamic Approval</fullName>
                </value>
                <value>
                    <fullName>Scoring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sobject_Type__c</fullName>
        <description>This custom field is used to recognize the type of SObject.</description>
        <label>Sobject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Rule_Item__c.object
<CustomObject>
    <description>Rule Items is child record of rule with specific field level criteria</description>
    <fields>
        <fullName>Field_API__c</fullName>
        <description>object.FieldAPI Name ex:Lead.Influence_Type__c</description>
        <label>Field API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>The checkbox will allow users to control active/inactive ruleitems and manage the ruleitems better.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <description>This field is used for selecting the operator Type.</description>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>contains</fullName>
                </value>
                <value>
                    <fullName>equals</fullName>
                </value>
                <value>
                    <fullName>excludes</fullName>
                </value>
                <value>
                    <fullName>greaterOrEqual</fullName>
                </value>
                <value>
                    <fullName>greaterThan</fullName>
                </value>
                <value>
                    <fullName>includes</fullName>
                </value>
                <value>
                    <fullName>lessOrEqual</fullName>
                </value>
                <value>
                    <fullName>lessThan</fullName>
                </value>
                <value>
                    <fullName>notContain</fullName>
                </value>
                <value>
                    <fullName>notEquals</fullName>
                </value>
                <value>
                    <fullName>startsWith</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rule__c</fullName>
        <description>This is the Rule Item and the Rule Object master detail relationship field.</description>
        <label>Rule</label>
        <referenceTo>Rule__c</referenceTo>
        <relationshipLabel>Rule Items</relationshipLabel>
        <relationshipName>Rule_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>The return score for application</description>
        <label>Score</label>
        <precision>5</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>The field picklist value to be compared</description>
        <inlineHelpText>The picklist value to be compared with. Note the value has to be exactly same as the one in the field&apos;s picklist</inlineHelpText>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Rule Item</label>
    <nameField>
        <label>Rule Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/callReportingHandler_UT.cls
@isTest
private class callReportingHandler_UT{

    static testMethod void callReportScoring(){
    List<Call_Report__c> callReportList=new List<Call_Report__c>();
    //[01022017] Merge&Spin: Removed Hard coding of record type Id
    //updated sObjectType to fix test failure
    string AGCP_CPC_LA_Simple_RType = RType.getIdByDevName('Account','AGCP_CPC_LA_Simple');
    string AGCP_CPC_LA_RType = RType.getIdByDevName('Call_Report__c','AGCP_CPC_LA');
    Account acc=new Account(Name='testAccount',recordtypeid= AGCP_CPC_LA_Simple_RType,Country__c='INDIA');
    insert acc;
    Geography__c grphy=new Geography__c(Name='Indiana',Code__c='SR_TMENA',Code2__c='TMENA',Level__c=2.00,CurrencyIsoCode='USD');
    insert grphy;
    Date myDate = date.newinstance(1960, 2, 17);
    Rule__c ruleObj=new Rule__c(Name='Call Report Scoring LA',IsActive__c=true,SObject_Type__c='Call_Report__c',Record_Type__c='AGCP_CPC_LA',Rule_Type__c='Scoring',Range__c='70=A&50=B&30=C&10=D&0=E');
    insert ruleObj;
    Rule_Item__c ruleItemObj=new Rule_Item__c(Name='TestRuleItem1',IsActive__c=true,Field_API__c='Topic__c',Rule__c=ruleObj.id,Operator__c='equals',Value__c='Logistics',Score__c=2);
    insert ruleItemObj;
    Rule_Item__c ruleItemObj1=new Rule_Item__c(Name='TestRuleItem2',IsActive__c=true,Field_API__c='Topic__c',Rule__c=ruleObj.id,Operator__c='equals',Value__c='Application',Score__c=2);
    insert ruleItemObj1;
    Rule_Item__c ruleItemObj2=new Rule_Item__c(Name='TestRuleItem3',IsActive__c=true,Field_API__c='Topic__c',Rule__c=ruleObj.id,Operator__c='equals',Value__c='Packaging Destination',Score__c=2);
    insert ruleItemObj2;
    Rule_Item__c ruleItemObj3=new Rule_Item__c(Name='TestRuleItem4',IsActive__c=true,Field_API__c='Topic__c',Rule__c=ruleObj.id,Operator__c='equals',Value__c='Illegal Products',Score__c=2);
    insert ruleItemObj3;
    Rule_Item__c ruleItemObj4=new Rule_Item__c(Name='TestRuleItem5',Field_API__c='Topic__c',Rule__c=ruleObj.id,Operator__c='equals',Value__c='Correct Use of PPE',Score__c=2);
    insert ruleItemObj4;
    Rule_Item__c ruleItemObj5=new Rule_Item__c(Name='TestRuleItem6',Field_API__c='Topic__c',Rule__c=ruleObj.id,Operator__c='equals',Value__c='DuPont School Project',Score__c=3.5);
    insert ruleItemObj5;
    
    Call_Report__c callRprtObj;
    Call_Report__c callRprtObj1;
    for(Integer k=0;k<1;k++){
        //KT [11072017]: To remove Level_of_Effort_hours__c=235,Distance_Traveled__c=45.00, reference
        callRprtObj=new Call_Report__c(Name='smplCallRprt',Topic__c='Application',recordTypeId=AGCP_CPC_LA_RType ,Account__c=acc.Id,Status__c='Planned',Call_Date__c=myDate ,
                             Channel__c='Phone',Type__c='Call Report Only',Attendees__c='testUser1',Geography__c=grphy.id);
        //KT [11072017]: To remove ,Level_of_Effort_hours__c=231,Distance_Traveled__c=234.00, reference
        callRprtObj1=new Call_Report__c(Name='smplCallRprt1',Topic__c='DuPont School Project',recordTypeId=AGCP_CPC_LA_RType, Account__c=acc.Id,Status__c='Planned',Call_Date__c=myDate ,
                             Type__c='Call Report Only', Channel__c='Phone',Attendees__c='testUser2',Geography__c=grphy.id);
    }
    callReportList.add(callRprtObj);
    callReportList.add(callRprtObj1);
    Insert callReportList;
    //assert the result of the ruleEngine
    // To remove score__c reference 
    //if(callReportList.get(0).score__c!=null)
    //    System.assertEquals(2.0, callReportList.get(0).score__c);        
     
    callReportList.get(0).Topic__c='Logistics';    
    update callReportList;           
    }
  }