DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aerospace and Aircraft</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Apparel and Textile</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Biotechnology</fullName>
                </value>
                <value>
                    <fullName>Chemical Industry</fullName>
                </value>
                <value>
                    <fullName>Construction and Architecture</fullName>
                </value>
                <value>
                    <fullName>Consumer Goods</fullName>
                </value>
                <value>
                    <fullName>Electrical and Electronics</fullName>
                </value>
                <value>
                    <fullName>Energy Solutions</fullName>
                </value>
                <value>
                    <fullName>Food and Nutrition</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Health Care and Medical</fullName>
                </value>
                <value>
                    <fullName>Industrial and Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Marine and Rail Transportation</fullName>
                </value>
                <value>
                    <fullName>Military and Law Enforcement</fullName>
                </value>
                <value>
                    <fullName>Oil and Gas</fullName>
                </value>
                <value>
                    <fullName>Packaging</fullName>
                </value>
                <value>
                    <fullName>Plastics and Elastomers</fullName>
                </value>
                <value>
                    <fullName>Printing and Publishing</fullName>
                </value>
                <value>
                    <fullName>Pulp and Paper</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Safety</fullName>
                </value>
                <value>
                    <fullName>Utilities and Mining</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>13-(Energy) Oil &amp; Gas  Extraction</fullName>
                </value>
                <value>
                    <fullName>32-(Mfg)Stone, Clay, Glass &amp; Concrete Products</fullName>
                </value>
                <value>
                    <fullName>36-(Mfg)Electronic &amp; Other Electrical Equip. &amp; Components, except Computer Equipment</fullName>
                </value>
                <value>
                    <fullName>37-(Mfg)Transportation Equipment</fullName>
                </value>
                <value>
                    <fullName>43-United States Postal Service</fullName>
                </value>
                <value>
                    <fullName>45-(Transp)Transporation by Air</fullName>
                </value>
                <value>
                    <fullName>65-Real Estate</fullName>
                </value>
                <value>
                    <fullName>Adhesive and Sealants</fullName>
                </value>
                <value>
                    <fullName>Advertising/Marketing</fullName>
                </value>
                <value>
                    <fullName>Aerospace/Aircraft</fullName>
                </value>
                <value>
                    <fullName>Agriculture, forestry and animal farming</fullName>
                </value>
                <value>
                    <fullName>APPAREL &amp; HOME FURNISHING</fullName>
                </value>
                <value>
                    <fullName>Architectural Services</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Automotive Industry</fullName>
                </value>
                <value>
                    <fullName>BI-ComNew-All</fullName>
                </value>
                <value>
                    <fullName>BI-ComNew-Education</fullName>
                </value>
                <value>
                    <fullName>BI-ComNew-Food</fullName>
                </value>
                <value>
                    <fullName>BI-ComNew-Furniture</fullName>
                </value>
                <value>
                    <fullName>BI-ComNew-Healthcare</fullName>
                </value>
                <value>
                    <fullName>BI-ComNew-Hotels</fullName>
                </value>
                <value>
                    <fullName>BI-ComNew-Infrastructure</fullName>
                </value>
                <value>
                    <fullName>BI-ComNew-Military</fullName>
                </value>
                <value>
                    <fullName>BI-ComNew-Offices</fullName>
                </value>
                <value>
                    <fullName>BI-ComNew-Public Spaces</fullName>
                </value>
                <value>
                    <fullName>BI-ComNew-Retail</fullName>
                </value>
                <value>
                    <fullName>BI-ComNew-Transportation</fullName>
                </value>
                <value>
                    <fullName>BI-ComNew-Wall Cladding</fullName>
                </value>
                <value>
                    <fullName>BI-ComReno-All</fullName>
                </value>
                <value>
                    <fullName>BI-ComReno-Education</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Behind Schedule</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ClonePlusController_UT.cls
/*******************************************************************************
Author: Alex Cottner
Author Email: acottner@sssworld.com
Description: Advanced clone page controller test case. 
//[06142017] Merge&Spin: Changed Test objects from DSS_CT_Proposal to Account and Opportunity
********************************************************************************/
@isTest
private class ClonePlusController_UT {
    static testMethod void myUnitTest() {
        
        
        // TO DO: implement unit test
        Account acc = generateTestProposal();
        
        PageReference pageRef = new PageReference('/apex/CloneRecord?id=' + acc.Id + '&childobjecttypes=Opportunity');
        Test.setCurrentPage(pageRef);
        
        ClonePlusController c = new ClonePlusController();
        c.initialiseObjectsForCloning();
        System.assertEquals('Test Account', c.objectName);
        System.assertEquals('Account', c.objectTypeName);
        
        PageReference newPage = c.doClone();
   //     DSS_CT_Proposal__c clonedProposal = [select Id, Name from DSS_CT_Proposal__c where Id != :proposal.Id limit 1];
   			Account ac =[Select id, Name from Account where id != :acc.id limit 1];
        System.assertEquals('/' + ac.Id, newPage.getUrl());
       // List<DSS_CT_Proposal_Item__c> clonedProposalDetails = [select Id from DSS_CT_Proposal_Item__c where Proposal__c = :clonedProposal.Id];
      List<Opportunity> oppList = [Select id from Opportunity where AccountId = :ac.id];
        System.assertEquals(1, oppList.size());
        //  System.assertEquals(3, clonedProposalDetails.Size());
        
    }
    
    static Account generateTestProposal() {
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.RecordTypeId = RType.getIdByDevName('Account','BI_Surfaces'); 
        acc.Country__c = 'UNITED STATES';
        acc.Industry = 'Other';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.id;
        opp.Name = 'Test Opportunity';
        opp.Industry__c = 'Solar';
        opp.Market_Segment__c = 'Acid';
        opp.CloseDate = Date.today();
        opp.StageName = 'Target';
        opp.Status__c = 'In Progress';
        insert opp;
        
        
        
        return acc;
    }
}