DuPont DevSB/src/objects/Account_Material__c.object
<CustomObject>
    <description>Custom object to link Account &amp; Contacts with Materials</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account-Materials</relationshipLabel>
        <relationshipName>R00N30000002iTfiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Material__c.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ERP Material – General Data</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Account-Materials</relationshipLabel>
        <relationshipName>R00N30000002iTg2EAE</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account-Material</label>
    <nameField>
        <displayFormat>AMID-{MMYY}-{000000}</displayFormat>
        <label>AM ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account-Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/GDLActivityAutomation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Being used in GDLActivityAutomation</description>
    <fields>
        <fullName>Setting_Name__c</fullName>
        <label>Setting Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <type>TextArea</type>
    </fields>
    <label>GDLActivityAutomation</label>
</CustomObject>

DuPont DevSB/src/objects/Material__c.object
<CustomObject>
    <description>Custom object to capture or track materials.  May be used for products as well as substances (i.e. REACH);   Typically used for product lists related to an Account or Opportunity  (i.e. partner products, developmental products or confidential products) when a &quot;secure&quot; product object is required; organization wide security default for this custom object is set to &quot;Private&quot; instead of &apos;Public Read/Write&quot; as in the standard &apos;Products&apos; object.</description>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/GDLGetAccountMaterials.cls
/*****************************************************************************
Author: Rohit saini
Email: rohitkumar.saini@tcs.com
Description:  class to send AccountMaterials in GDL periodic activity

********************************************************************************/

@RestResource(urlMapping='/GetAccountMaterials/*')
global with sharing class GDLGetAccountMaterials{
    //wrapper class starts
    public class Wrapper{
        public List<cls_records> records;
    }
    public class cls_records{
        public String accMatId;
    }
    //wrapper class ends
    
    @HttpGet   
    global static String GetAccountMaterialIds() {
        RestRequest req = RestContext.request;
        List<Account_Material__c> accMaterials2=new List<Account_Material__c>();
        string type=req.params.get('type');
        
        try{
            if(type=='Surfaces'){
                 string query='';
                for(GDLActivityAutomation__c setting: [select id, Setting_Name__c, Value__c from GDLActivityAutomation__c where Setting_Name__c='AcctMatrlids_Surf' order by createdDate ]){
                    if(setting.Setting_Name__c=='AcctMatrlids_Surf'){
                        query+=setting.Value__c+' ';
                    }
                }
                system.debug('query::'+query);
                accMaterials2=database.query(query);

            }else{
                string query='';
                for(GDLActivityAutomation__c setting: [select id, Setting_Name__c, Value__c from GDLActivityAutomation__c where Setting_Name__c='AcctMatrlids_Tyvek' order by createdDate ]){
                    if(setting.Setting_Name__c=='AcctMatrlids_Tyvek'){
                        query+=setting.Value__c+' ';
                    }
                }
                system.debug('query::'+query);
                accMaterials2=database.query(query);
                           
            }
         
            system.debug(LoggingLevel.ERROR, 'accList size : ' + accMaterials2.size());    
            
                JsonGenerator gen=JSON.createGenerator(true);
                gen.writeStartObject();//json starts
                gen.writeFieldName('records');
                gen.writeStartArray();//record array starts
                for(Account_Material__c a : accMaterials2){
                        gen.writeStartObject();
                        gen.writeStringField('accMatId',a.id);
                        gen.writeEndObject();
                }
                
            gen.writeEndArray();//record array ends
            gen.writeEndObject();//json ends 
            
            String prettyJson=gen.getAsString();
            return prettyJson;
        }
        catch(Exception e){
            system.debug(LoggingLevel.ERROR, 'Error : ' + e.getMessage());
            return e.getMessage();
        }
    }
    
    
    @HttpPost   
    global static String GDLGetAccountMaterials() {
        List<Account_Material__c> accMaterials=new List<Account_Material__c>();
        RestRequest req = RestContext.request;
        try{
            system.debug(LoggingLevel.ERROR,'req.requestBody : ' + req.requestBody.toString());
          Wrapper wrap = (Wrapper) JSON.deserialize(req.requestBody.toString(), Wrapper.class);
             Set<String> accMatIds=new Set<String>();
            if(wrap.records.size()>0){
                system.debug('$$$ wrap.records.size()>0');
                for(cls_records cr : wrap.records){
                    accMatIds.add(cr.accMatId);
                }
               string query='';
                for(GDLActivityAutomation__c setting: [select id, Setting_Name__c, Value__c from GDLActivityAutomation__c where Setting_Name__c='GetAcctMatrls' order by createdDate ]){
                    if(setting.Setting_Name__c=='GetAcctMatrls'){
                        query+=setting.Value__c+' ';
                    }
                }
                system.debug('query::'+query);
                accMaterials=database.query(query);
            }
            JsonGenerator gen=JSON.createGenerator(true);
            gen.writeStartObject();//json starts
                gen.writeFieldName('records');
                gen.writeStartArray();//record array starts
                    for(Account_Material__c a : accMaterials){
                        if(String.isNotBlank(a.Product_Name__c) && String.isNotBlank(a.Product_Name__r.name)){
                            gen.writeStartObject();
                            gen.writeStringField('id',a.id);
                            gen.writeStringField('accID',a.Account_Name__c);
                            gen.writeStringField('matId',a.Product_Name__c);
                           
                            System.debug(LoggingLevel.Error, 'prod Name::'+a.Product_Name__r.name);
                            if(a.Product_Name__r.name.containsAny('\"')){
                             String temp=a.Product_Name__r.name.replace('\"','DBLEQUOTE');
                          
                                System.debug(LoggingLevel.Error, 'prod Name::'+temp);
                            
                                gen.writeStringField('matName',temp);
                            }else{
                               gen.writeStringField('matName',a.Product_Name__r.name);
                           }    
                        gen.writeEndObject();
                        }
                     }
                gen.writeEndArray();//record array ends
            gen.writeEndObject();//json ends 
            
            String prettyJson=gen.getAsString();
            system.debug(LoggingLevel.Error, 'prettyJson : ' + prettyJson);
            return prettyJson;
        }
        catch(Exception e){
            system.debug('Error : ' + e.getMessage());
            return e.getMessage();
        }    
    }
}