DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Group__c</fullName>
        <label>Customer Group</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group_2__c</fullName>
        <label>Customer Group 2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org 1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/CS_Account_Load_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used for storing all the used values in Accounts Batch processes.</description>
    <fields>
        <fullName>AccountGroup__c</fullName>
        <label>AccountGroup</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountOwnerUserName__c</fullName>
        <description>This field will hold the username.</description>
        <inlineHelpText>This field will hold the username of static user &quot;Customer Service&quot; created in application.</inlineHelpText>
        <label>Account Owner User Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountOwner__c</fullName>
        <label>Account Owner</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType_Name__c</fullName>
        <label>RecordType Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name_General__c</fullName>
        <description>To capture the general Data Record type name</description>
        <label>Record Type Name - General</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CS_AccountLoadSettings</label>
</CustomObject>

DuPont DevSB/src/objects/CS_YKPartnerMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will be used for mapping YK Partner types to their Service Centers</description>
    <fields>
        <fullName>Shared_Service_Center__c</fullName>
        <label>Shared Service Center</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>CS YK Partner Mapping</label>
</CustomObject>

DuPont DevSB/src/objects/ERP_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Account_Group_Code__c</fullName>
        <description>The account group is a classifying feature within customer master records. The account group determines in which number range the customer account number should be; whether the number is assigned by the user or by the system; which specifications are necessary or possible in the master record.</description>
        <label>Account Group Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Group__c</fullName>
        <description>The account group is a classifying feature within customer master records. The account group determines in which number range the customer account number should be; whether the number is assigned by the user or by the system; which specifications are necessary or possible in the master record.</description>
        <label>Account Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>The city of this customer as stored in SAP.</description>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country of this customer as stored in SAP.</description>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <description>Key with which the customer can be identified within the SAP system.Gives an alphanumeric key, which clearly identifies the customer or vendor in the SAP system.</description>
        <label>Customer Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_General_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the record that contains the SAP general data for this customer, which can be shared across sales orgs.</description>
        <label>Customer - General Data</label>
        <referenceTo>ERP_Customer__c</referenceTo>
        <relationshipLabel>ERP Customers</relationshipLabel>
        <relationshipName>ERP_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Group_2_Code__c</fullName>
        <description>Identifies a particular group of customers (for example, wholesale or retail).</description>
        <label>Customer Group 2 Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group_2__c</fullName>
        <description>Identifies a particular group of customers (for example, wholesale or retail).</description>
        <label>Customer Group 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group_9_Code__c</fullName>
        <label>Customer Group 9 Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group_9__c</fullName>
        <label>Customer Group 9</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deletion_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates in the future this record is to be deleted or not, however they are not physically deleted yet for history maintenance purposes. This deletion applies in the specified sales area only.</description>
        <label>Deletion Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel_Code__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_Code__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Account__c</fullName>
        <description>This Field has been created as a part of req.123</description>
        <label>ERP Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ERP_YKPartnerCode__c</fullName>
        <description>This Field will capture Partner Function Code Value and will be updated by Workflow &quot;CS_UpdateERPCustomerYKPartnerCode&quot;.</description>
        <label>YK Partner Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the Source Cluster + Customer Code + Sales Org Code + Distribution Channel Code + Division Code to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <description>Language code for the customer from the ERP system.</description>
        <label>Language Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language for the customer from the ERP system.</description>
        <label>Language</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Box__c</fullName>
        <description>The Post Office Box of this customer as stored in SAP.</description>
        <label>PO Box</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org. Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Search_Term__c</fullName>
        <description>Search term for the customer from the ERP system.  Example: &quot;IBM&quot;.</description>
        <label>Search Term</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Cluster__c</fullName>
        <description>Specific SAP box or cluster where the data of this record originates.</description>
        <label>Source Cluster</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>The street of this customer as stored in SAP.</description>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fLanguage_Code_General__c</fullName>
        <description>Language Code from the related ERP Customer General record</description>
        <formula>Customer_General_Data__r.Language_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language Code (General)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fLanguage_General__c</fullName>
        <description>Language from the related ERP Customer General record</description>
        <formula>Customer_General_Data__r.Language__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language (General)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fSearch_Term_General__c</fullName>
        <description>Search term from the related ERP Customer General record</description>
        <formula>Customer_General_Data__r.Search_Term__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Search Term (General)</label>
        <type>Text</type>
    </fields>
    <label>ERP Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>SAP Partner Code / User ID (sales rep, CSR, etc.) of this user and is the unique record identifier for this person from SAP.</description>
        <externalId>true</externalId>
        <inlineHelpText>SAP Partner Code / User ID (sales rep, CSR, etc.) of this user and is the unique record identifier for this person from SAP.</inlineHelpText>
        <label>External ERP ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrl_CSTriggerAccountUpdate.cls
/**
 * Description: This class is acting as a controller for the page page_TriggerAccountUpdate responsible for executing the batch via the action method.
 * @author Sanchit Dua
 * email sanchit.dua@accenture.com
 * Change history (key updates):
 * 20th May, 2015 -> created the class
 * 26th May, 2015 -> added a remote action method 
 * 28th Jul, 2015 -> AA - Added Condition to prevent update of ERP Customer(AA 20150730).
 * 09th Oct,2015  -> SB - Deleted the logic(Code) for last modified date check and limit for manual 'Trigger Account Updates'(SB20151009)
 * 14thOct,2015->AA- Modified the code in order to removed redunadant code , added method calling "utilData.erpCust_AccountfieldsMapping".(AA20151014) 
 * ERP Customer's ERP Relationship on  corresponding Account record's ZR Partner Field. (PD08102015)
 * @ Abinand Aravazhi 
 * 20th Jan, 2016 --> Changed logic to include General Account Creation 
               --> Changes Indicated with the Tag <AA01202016>

 
 
 */
 
global without sharing class ctrl_CSTriggerAccountUpdate {
    private PageReference theView;
    private static final Map<String, String> partnerCodeWithCountryCode;
    private static final string SOBJECTNAME = 'Account';
    private static final string OPENBRACE = ' (';
    private static final string CLOSEBRACE = ')';
    private static final string RECORDTYPENAME = 'CS_ERPCustomer';
    private static final string STATUS_ACTIVE = 'Active';
    private static final string STATUS_INACTIVE = 'Inactive';
    private static final String PROFILENAME = 'Customer Service';
    private static final String INITIAL_VAL = '';
    private static final String ADMINPROFILE = 'System Administrator';
    private static final String ERPRECORDTYPENAME= 'ERP Relationship - Person';
    private static final String ERRMSG = System.Label.CS_Account_Update_Error_Access;
    private static final String ERRMSGFILTER = System.Label.CS_Account_Update_Error_Filter;
    private static final  String ERRMSGDEF = System.Label.CS_Account_Update_Error_Default;
    private static final String SUCCESSMSG = System.Label.CS_Account_Update_Success;
     private utilCSBatchErrorLog  batchErrorLog;
         

    Static {
        partnerCodeWithCountryCode = new Map<String, String>();
        for(CS_YKPartnerMapping__c partner: CS_YKPartnerMapping__c.getall().values()) {
            partnerCodeWithCountryCode.put(partner.Name,partner.Shared_Service_Center__c);
        }
    } 
    /**
     * Standard Controller
     * @param sc
     */
    public ctrl_CSTriggerAccountUpdate(ApexPages.StandardController sc) {
        theView = sc.view();
         batchErrorLog = new utilCSBatchErrorLog();
    } // END init

    /**
     * Remote Action Method
     * @return - the HTML data made from the constants
     */
    @RemoteAction
    global static String upsertAccount(String eRPID){
         Boolean errorOcc ;
         utilCSBatchErrorLog  batchErrorLog = new utilCSBatchErrorLog();
         Integer lmt = Limits.getLimitQueryRows();
         Set<String> partnerCodes = new Set<String>(); 
         CS_Account_Load_Settings__c accountLoad;
         Map<Id,ERP_Customer__c> erpMap = new Map<Id,ERP_Customer__c>();
         Map<Id,Account> accMap =new Map<Id,Account>();
         ERP_Customer__c erpCustomer;
         Account account;
         utilCSAccountLoad utilData = new utilCSAccountLoad();
    
 
        // check for User's profile it should be either "Customer Service"/"System Administarto" in order to execute the functionality
        if(![ SELECT Id, Name FROM Profile WHERE Id =: UserInfo.getProfileId() AND ( Name =: PROFILENAME OR Name =: ADMINPROFILE ) LIMIT: lmt].isEmpty()){
             //get the record type id of Account's Record Type "CS_ERPCustomer"
             RecordType recType = [select id from RecordType where sobjectType =:SOBJECTNAME and DeveloperName =:RECORDTYPENAME limit :lmt];
             if( !CS_Account_Load_Settings__c.getall().isEmpty() )
                accountLoad = CS_Account_Load_Settings__c.getall().values()[0];  
             if(CS_YKPartnerMapping__c.getInstance() != null){
                for(CS_YKPartnerMapping__c partner: CS_YKPartnerMapping__c.getall().values()) 
                        partnerCodes.add(partner.Name);         
             }
             //get the "Customer Service" static user record
             List<User> userRecId = [select Id from User where Username =:accountLoad.AccountOwnerUserName__c limit 1];
             /* SB 20151009 -- Deleted the logic(Code) for last modified date check and limit for manual 'Trigger Account Updates' */
             For(ERP_Customer__c erp : [Select Id, Name, RecordType.Name, Account_Group__c,fLanguage_Code_General__c,fLanguage_General__c,fSearch_Term_General__c,Customer_General_Data__c, ERP_Account__c, Account_Group_Code__c,Language__c,Language_Code__c, ERP_YKPartnerCode__c, Source_Cluster__c,Sales_Org_Code__c,Sales_Org__c, City__c, Country__c, Customer_Group_2__c,Distribution_Channel_Code__c,Distribution_Channel__c,Division_Code__c,Division__c, Customer_Group_2_Code__c,Customer_Group_9__c, Customer_Group_9_Code__c, PO_Box__c, Street__c, Customer_Code__c, Search_Term__c, External_ERP_ID__c, Deletion_Flag__c FROM ERP_Customer__c WHERE Account_Group__c = :accountLoad.AccountGroup__c AND id =:eRPID AND (Recordtype.Name =: accountLoad.RecordType_Name__c OR Recordtype.Name =: accountLoad.Record_Type_Name_General__c) AND (ERP_YKPartnerCode__c != NULL OR (ERP_YKPartnerCode__c = NULL AND ERP_Account__c =:accountLoad.AccountOwner__c ))]) {
                erpMap.put(erp.Id,erp);
             }
             if(erpMap!=null && !erpMap.isempty()){
                 erpCustomer=erpMap.values();
             System.debug('______'+erpCustomer.Recordtype.Name+'___'+accountLoad.Record_Type_Name_General__c);
             if(erpCustomer.Recordtype.Name==accountLoad.Record_Type_Name_General__c){
                 Map<Id,ERP_Customer__c > erpCustMap = new Map<Id,ERP_Customer__c>();    
                 // AA01202016 - Calling the New function in Util Class.
                 errorOcc =utilData.erpCust_AccountfieldsMapping(erpCustMap,null,batchErrorLog,accountLoad.AccountOwnerUserName__c, false, erpMap);               
             }else{              
             //check if ERP Customer has an customer service account associated
                for(Account acc : [select id,name,Status__c,recordTypeId,ERP_Customer__c,Country__c,ERP_Account_Code__c,ERP_CustomerGroup9__c,ERP_DistChannelCode__c,ERP_DistChannelDescription__c,ERP_DivisionCode__c,ERP_DivisionDescription__c ,ERP_Account_Group__c ,ERP_LanguageDescription__c ,ERP_LanguageCode__c ,ERP_YKPartnerCode__c ,ERP_SalesOrgCode__c ,ERP_SalesOrgDescription__c ,ERP_SourceCluster__c ,ERP_Street__c ,PO_Box__c ,ERP_SearchTerm__c ,External_ID__c ,ERP_Company_Code__c ,ERP_CustomerServiceCenter__c ,OwnerId from Account where ERP_Customer__c=:eRPID limit 1]){
                    accMap.put(eRPID,acc);
                }
                if(accMap!=null && !accMap.isempty()){
                          // AA01202016 - Calling the New function in Util Class.
                    errorOcc =utilData.erpCust_AccountfieldsMapping(erpMap,accMap,batchErrorLog,accountLoad.AccountOwnerUserName__c, false, null);
                }else{
                    if(!partnerCodeWithCountryCode.containskey(erpCustomer.ERP_YKPartnerCode__c) || erpCustomer.Deletion_Flag__c==true){
                        return ERRMSGFILTER;
                    }else{
                         // AA01202016 - Calling the New function in Util Class.
                        errorOcc =utilData.erpCust_AccountfieldsMapping(erpMap,null,batchErrorLog,accountLoad.AccountOwnerUserName__c, false, null);
                        if(!errorOcc){
                             erpCustomer.ERP_Account__c =accountLoad.AccountOwner__c;
                             update erpCustomer;
                        }
                    }
                }
             }
             If(errorOcc)
               return ERRMSGDEF;
             else
                return SUCCESSMSG;
        }else{
            return ERRMSGFILTER;
        }  
    }else
        return ERRMSG;
    } // END global static String callBatch()
} // END public class ctrl_CSTrgiggerAccountUpdate