DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Main Communication channel used during the execution of this campaign</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>eMail</fullName>
                </value>
                <value>
                    <fullName>email-Video</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Face to Face</fullName>
                </value>
                <value>
                    <fullName>Multiple</fullName>
                </value>
                <value>
                    <fullName>Paper mail</fullName>
                </value>
                <value>
                    <fullName>Paper Mail-Literature</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Press-Advertisement</fullName>
                </value>
                <value>
                    <fullName>Seminar</fullName>
                </value>
                <value>
                    <fullName>Trade Show</fullName>
                </value>
                <value>
                    <fullName>Web-Advertising</fullName>
                </value>
                <value>
                    <fullName>Web-Content Sharing</fullName>
                </value>
                <value>
                    <fullName>Web-Other</fullName>
                </value>
                <value>
                    <fullName>Web-Social Media</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
                <value>
                    <fullName>Webmeeting</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Website-Global</fullName>
                </value>
                <value>
                    <fullName>Website-Local</fullName>
                </value>
                <value>
                    <fullName>With Distributor</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Initiative__c.object
<CustomObject>
    <description>Sell-side Project or Initiative</description>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Main communication channel this initiative is using</description>
        <inlineHelpText>Main communication channel this initiative is using</inlineHelpText>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct Mail Campaign</fullName>
                </value>
                <value>
                    <fullName>eMail</fullName>
                </value>
                <value>
                    <fullName>Face to Face</fullName>
                </value>
                <value>
                    <fullName>Multiple</fullName>
                </value>
                <value>
                    <fullName>Paper Mail</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Press</fullName>
                </value>
                <value>
                    <fullName>Press-Advertisement</fullName>
                </value>
                <value>
                    <fullName>Seminar</fullName>
                </value>
                <value>
                    <fullName>Trade Show</fullName>
                </value>
                <value>
                    <fullName>Web-Advertising</fullName>
                </value>
                <value>
                    <fullName>Web-eLearning</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>list of product lines that can be associated with an initiative</description>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Montelli</fullName>
                </value>
                <value>
                    <fullName>Corian® Solid Surface</fullName>
                </value>
                <value>
                    <fullName>Corian® Quartz</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this Initiative</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <color>#F3D904</color>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Behind Schedule</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <color>#33CC00</color>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                    <color>#CC0000</color>
                    <label>Abandoned</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
                <value>
                    <fullName>Preparation</fullName>
                </value>
                <value>
                    <fullName>Rep Estimation</fullName>
                </value>
                <value>
                    <fullName>District Review</fullName>
                </value>
                <value>
                    <fullName>Area Review</fullName>
                </value>
                <value>
                    <fullName>DP BU Meeting</fullName>
                </value>
                <value>
                    <fullName>DP Supply Meeting</fullName>
                </value>
                <value>
                    <fullName>BU Allocations</fullName>
                </value>
                <value>
                    <fullName>District Allocations</fullName>
                </value>
                <value>
                    <fullName>Rep Allocations</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Initiative</label>
    <nameField>
        <label>Initiative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlEventToCallReport_UT.cls
/*******************************************************************************
Copyright © 2017 DuPont. All rights reserved. 
Author: Shyam Bansal
Email: bansal.shyam@tcs.com
Description:  Unit Test(s) for : ctrlEventToCallReport
*******************************************************************************/
//[01182017] Merge&Spin : Moved test method from main class 'ctrlEventToCallReport' to create new test class and updated test method.  
@isTest
public class ctrlEventToCallReport_UT {
    public static testMethod void test_ctrlMyProfile1() {

        geoValidation.DisableGeoValidationOverride=true;
        //Add tester as Contact and add to lst Campaign as status = member-transactional
        Account a = new Account(name='test', Country__c='United States');
        insert a;
        Contact c = new Contact(lastname='test', Accountid=a.id, Contact_Country__c='United States');
        insert c;
        Initiative__c Initiative = new Initiative__c();
            Initiative.Name = 'TestInitiative';
            //KT [11072017]: To remove season__c reference
            //Initiative.season__c = 'Winter';
            //KT [11072017]: To remove Profile_Year__c reference
            //Initiative.Profile_Year__c = '2014';
            Initiative.Product_Line__c = 'Sorghum';
            insert Initiative;      
        Event ev = new Event(
            //AccountId             = a.id  //not writable
            WhoId               = c.id
            ,whatId             = Initiative.Id
            ,Subject            = 'Subject Text'
            ,Direction__c       = 'Outbound'
            ,Status__c          = 'Completed'
            ,Description        = 'Description Text'
            ,Channel__c         = 'Face to Face'
            ,Activity_Type__c   = 'Customer Interaction'
            ,ActivityDateTime   = DateTime.now()
            ,location           = 'my office'
            ,DurationInMinutes  = 60
            );
        insert ev;

        Test.startTest();
    //  PageReference pageRef = Page.EventToCallReport;
        PageReference pageRef = new PageReference('/apex/EventToCallReport?id='+ev.id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.currentPage().getParameters().put('id',ev.id);
        ctrlEventToCallReport controller = new ctrlEventToCallReport();
        controller.init();
        system.debug('----event--->'+controller.event);
        system.debug('----callReport--->'+controller.callReport);
        
       PageReference pg = new PageReference('/apex/EventToCallReport');
       Test.setCurrentPage(pg);
        ctrlEventToCallReport ctrl = new ctrlEventToCallReport();
        ctrl.init();

        ev.whatId = a.Id;
        update ev;
        PageReference pg1 = new PageReference('/apex/EventToCallReport?id='+ev.id);
        Test.setCurrentPage(pg1);
        
        ApexPages.currentPage().getParameters().put('id',ev.id);
        ctrlEventToCallReport ctrl1 = new ctrlEventToCallReport();
        ctrl1.init();
        Test.stopTest();
    
    }   
}