DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/External_Initiative__c.object
<CustomObject>
    <description>Detailed information from an external data source provided in an automated feed (project, lead, or opportunity data).</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment_L2__c</fullName>
        <description>External initiative subsegment.</description>
        <label>Segment L2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment_L3__c</fullName>
        <description>Captures further external initiative detail.</description>
        <label>Segment L3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Announced</fullName>
                </value>
                <value>
                    <fullName>Study</fullName>
                </value>
                <value>
                    <fullName>Pre-Planning</fullName>
                </value>
                <value>
                    <fullName>Request for Proposals</fullName>
                </value>
                <value>
                    <fullName>Request for Qualifications</fullName>
                </value>
                <value>
                    <fullName>Pre-Design</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Planning Schematics</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Design Development</fullName>
                </value>
                <value>
                    <fullName>Final Planning</fullName>
                </value>
                <value>
                    <fullName>Construction Documents</fullName>
                </value>
                <value>
                    <fullName>Pre-tender</fullName>
                </value>
                <value>
                    <fullName>Pre-qualification</fullName>
                </value>
                <value>
                    <fullName>Tender</fullName>
                </value>
                <value>
                    <fullName>Bid</fullName>
                </value>
                <value>
                    <fullName>Bidding</fullName>
                </value>
                <value>
                    <fullName>GC Bidding</fullName>
                </value>
                <value>
                    <fullName>GC Bidding-Invitation</fullName>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Sub-bidding</fullName>
                </value>
                <value>
                    <fullName>Sub bidding</fullName>
                </value>
                <value>
                    <fullName>Bid result</fullName>
                </value>
                <value>
                    <fullName>Bid Results</fullName>
                </value>
                <value>
                    <fullName>Epc award</fullName>
                </value>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Execution</fullName>
                </value>
                <value>
                    <fullName>Sub-Award</fullName>
                </value>
                <value>
                    <fullName>Subcontract Award</fullName>
                </value>
                <value>
                    <fullName>Construct</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Total value of external initiative.</description>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>External Initiative</label>
    <nameField>
        <label>External Initiative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Initiatives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Opp_ParkSite_Batch_Assertion__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used in BatchOppSFDCToSFDCBatchable to send opportunities to parksite</description>
    <fields>
        <fullName>Parksite_Batch_Assertion__c</fullName>
        <description>Please use either &quot;Auto&quot; or &quot;Manual&quot; only</description>
        <inlineHelpText>Please use either &quot;Auto&quot; or &quot;Manual&quot; only</inlineHelpText>
        <label>Parksite Batch Assertion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Opp ParkSite Batch Assertion</label>
</CustomObject>

DuPont DevSB/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CLT-Fluid</fullName>
                </value>
                <value>
                    <fullName>CLT-Surfaces</fullName>
                </value>
                <value>
                    <fullName>CLT-Tyvek</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Initiative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>External Initiative (or project managed by a partner or other 3rd party) related to this opportunity</description>
        <label>External Initiative</label>
        <referenceTo>External_Initiative__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parksite_Batch_Assertion__c</fullName>
        <label>Parksite Batch Assertion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <inlineHelpText>DuPont Product/Brand proposed or used after Opportunity closes.</inlineHelpText>
        <label>Product</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adhesive (1 layer)</fullName>
                </value>
                <value>
                    <fullName>Adhesive (2 layer)</fullName>
                </value>
                <value>
                    <fullName>Adhesive Clad</fullName>
                </value>
                <value>
                    <fullName>Adhesiveless Clad</fullName>
                </value>
                <value>
                    <fullName>Appeel®</fullName>
                </value>
                <value>
                    <fullName>Artistri®</fullName>
                </value>
                <value>
                    <fullName>BAX</fullName>
                </value>
                <value>
                    <fullName>BAX Ala Carte</fullName>
                </value>
                <value>
                    <fullName>BAX ESA</fullName>
                </value>
                <value>
                    <fullName>BAX Q7</fullName>
                </value>
                <value>
                    <fullName>BAX Q7 Ala Carte</fullName>
                </value>
                <value>
                    <fullName>BAX Q7 ESA</fullName>
                </value>
                <value>
                    <fullName>BAX Standard</fullName>
                </value>
                <value>
                    <fullName>Biosecurity Kits</fullName>
                </value>
                <value>
                    <fullName>Coated</fullName>
                </value>
                <value>
                    <fullName>ColorSystem</fullName>
                </value>
                <value>
                    <fullName>Consulting-OE</fullName>
                </value>
                <value>
                    <fullName>Consulting-Safety</fullName>
                </value>
                <value>
                    <fullName>Cool-Guard</fullName>
                </value>
                <value>
                    <fullName>Copier Printer belts</fullName>
                </value>
                <value>
                    <fullName>Corian® Solid Surface</fullName>
                </value>
                <value>
                    <fullName>Coverlay/Bondply</fullName>
                </value>
                <value>
                    <fullName>Cromaprint</fullName>
                </value>
                <value>
                    <fullName>Cyrel ®</fullName>
                </value>
                <value>
                    <fullName>Cyrel ® EASY EFE</fullName>
                </value>
                <value>
                    <fullName>Cyrel ® EASY EFX</fullName>
                </value>
                <value>
                    <fullName>Cyrel ® EASY EPR</fullName>
                </value>
                <value>
                    <fullName>Cyrel ® EASY ESP</fullName>
                </value>
                <value>
                    <fullName>Decon Shower</fullName>
                </value>
                <value>
                    <fullName>Discrete-Safety</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/BatchOppSFDCToSFDCBatchable_UT.cls
@isTest
public class BatchOppSFDCToSFDCBatchable_UT {
    static testMethod void createTestData() {
            Test.startTest();
            
              Opp_ParkSite_Batch_Assertion__c dataSOQL = Opp_ParkSite_Batch_Assertion__c.getOrgDefaults();

              if (dataSOQL.Id <> null) {
                  dataSOQL.Parksite_Batch_Assertion__c = 'Auto';
                  update dataSOQL;
              }
              else{
                  dataSOQL.Parksite_Batch_Assertion__c = 'Auto';
                  dataSOQL.SetupOwnerId=UserInfo.getOrganizationId();
                  insert dataSOQL;
              }
            
            Account acc =  
            //[select id from Account where Name ='Parksite (IL) Tyvek - HQ' AND country__C='UNITED STATES'];
            new Account(Name ='Parksite (IL) Tyvek - HQ',country__C='US');
            insert acc;
            External_Initiative__c ei = new External_Initiative__c(name='BI NA Test EI 3', Segment_L2__c='Test', Segment_L3__c='New Construction', Stage__c='Bidding',value__c=27800000);
            insert ei;
            RecordType rt = [Select id from RecordType where name = 'BI-NA MHC Opportunity' LIMIT 1];
            
            Opportunity opp1    = new Opportunity(name='BI-NA MHC Opportunity For Parksite 6',Parksite_Batch_Assertion__c ='Auto',AccountId=acc.id, product__c = 'Adhesive (1 layer)', Account=acc, Amount=25000000,Application_Type__c='CLT-Tyvek',stageName='Propose',closeDate=Date.newinstance(2014,9,30),   recordtypeid=rt.id, External_Initiative__c=ei.id);
            Opportunity opp2   = new Opportunity(name='BI-NA MHC Opportunity For Parksite  7',Parksite_Batch_Assertion__c ='Auto',AccountId=acc.id, product__c = 'Adhesive (1 layer)', Account=acc,Amount=25000000,Application_Type__c='CLT-Tyvek',stageName='Propose',closeDate=Date.newinstance(2014,9,30),  recordtypeid=rt.id, External_Initiative__c=ei.id, Description='OverRide');
            Opportunity opp3   = new Opportunity(name='BI-NA MHC Opportunity For Parksite  8',Parksite_Batch_Assertion__c ='Auto',AccountId=acc.id, product__c = 'Adhesive (1 layer)', Account=acc,Amount=25000000,Application_Type__c='CLT-Tyvek',stageName='Propose',closeDate=Date.newinstance(2014,9,30),  recordtypeid=rt.id, External_Initiative__c=ei.id);
            Opportunity opp4   = new Opportunity(name='BI-NA MHC Opportunity For Parksite  9',Parksite_Batch_Assertion__c ='Manual',AccountId=acc.id,product__c = 'Adhesive (1 layer)', Account=acc,Amount=25000000,Application_Type__c='CLT-Tyvek',stageName='Propose',closeDate=Date.newinstance(2014,9,30),  recordtypeid=rt.id, External_Initiative__c=ei.id);
            Opportunity opp5   = new Opportunity(name='BI-NA MHC Opportunity For Parksite  10',Parksite_Batch_Assertion__c ='Manual',AccountId=acc.id,product__c = 'Adhesive (1 layer)', Account=acc,Amount=25000000,Application_Type__c='CLT-Tyvek',stageName='Propose',closeDate=Date.newinstance(2014,9,30),  recordtypeid=rt.id, External_Initiative__c=ei.id);
            
            //acc =  [select id from Account where Name ='Parksite (NE) Surfaces' LIMIT 1];//new Account(Name ='Parksite (IL) Tyvek - HQ',country__C='US');
            //insert acc;
            ei = new External_Initiative__c(name='BI NA Test EI 4', Segment_L2__c='Clinic', Segment_L3__c='New Construction', Stage__c='Bidding',value__c=27800000);
            insert ei;
            rt = [Select id from RecordType where name = 'BI-NA Surfaces Dodge' LIMIT 1];
            
            Opportunity opp6    = new Opportunity(name='BI-NA MHC Opportunity For Parksite 6',AccountId=acc.id, Account=acc, product__c = 'Adhesive (1 layer)', Amount=20000000,Application_Type__c='CLT-Surfaces',stageName='Propose',closeDate=Date.newinstance(2014,9,30),   recordtypeid=rt.id, External_Initiative__c=ei.id);
            Opportunity opp7    = new Opportunity(name='BI-NA MHC Opportunity For Parksite 6',AccountId=acc.id, Account=acc, product__c = 'Adhesive (1 layer)', Amount=20000000,Application_Type__c='CLT-Surfaces',stageName='Propose',closeDate=Date.newinstance(2014,9,30),   recordtypeid=rt.id, External_Initiative__c=ei.id,description='Override');
            List<Opportunity> opps = new List<Opportunity>();
            
            opps.add(opp1);
            opps.add(opp2);
            opps.add(opp3);
            opps.add(opp4);
            opps.add(opp5);
            opps.add(opp6);
            opps.add(opp7);
            insert opps;
            
            ctrlOppSFDCToSFDC cos2s = new ctrloppSFDCToSFDC(opps);
            
            List<ID> oppExistingIds = new List<ID>();
            List<PartnerNetworkRecordConnection> existingRecords = [select Id, Status, ConnectionId, LocalRecordId from PartnerNetworkRecordConnection where LocalRecordId  In  : opps LIMIT 1000];
            for(PartnerNetworkRecordConnection existingRecord : existingRecords){
                oppExistingIds.add(existingRecord.LocalRecordId);
            }
            
            update opps;
            
            BatchOppSFDCToSFDCBatchable bosts = new BatchOppSFDCToSFDCBatchable();
            
            Database.executeBatch(bosts,1000);
            Test.stopTest();
    }
    
    static testMethod void createTestData2() {
            Test.startTest();
            
              Opp_ParkSite_Batch_Assertion__c dataSOQL = Opp_ParkSite_Batch_Assertion__c.getOrgDefaults();

              if (dataSOQL.Id <> null) {
                  dataSOQL.Parksite_Batch_Assertion__c = 'Manual';
                  update dataSOQL;
              }
              else{
                  dataSOQL.Parksite_Batch_Assertion__c = 'Manual';
                  dataSOQL.SetupOwnerId=UserInfo.getOrganizationId();
                  insert dataSOQL;
              }
            
            Account acc =  
            //[select id from Account where Name ='Parksite (IL) Tyvek - HQ' AND country__C='UNITED STATES'];
            new Account(Name ='Parksite (IL) Tyvek - HQ',country__C='US');
            insert acc;
            External_Initiative__c ei = new External_Initiative__c(name='BI NA Test EI 3', Segment_L2__c='Test', Segment_L3__c='New Construction', Stage__c='Bidding',value__c=27800000);
            insert ei;
            RecordType rt = [Select id from RecordType where name = 'BI-NA MHC Opportunity' LIMIT 1];
            
            Opportunity opp1    = new Opportunity(name='BI-NA MHC Opportunity For Parksite 6',Parksite_Batch_Assertion__c ='Auto',AccountId=acc.id, Account=acc, Amount=25000000,Application_Type__c='CLT-Tyvek',product__c = 'Adhesive (1 layer)',stageName='Propose',closeDate=Date.newinstance(2014,9,30),   recordtypeid=rt.id, External_Initiative__c=ei.id);
            Opportunity opp2   = new Opportunity(name='BI-NA MHC Opportunity For Parksite  7',Parksite_Batch_Assertion__c ='Auto',AccountId=acc.id, Account=acc,Amount=25000000,Application_Type__c='CLT-Tyvek',product__c = 'Adhesive (1 layer)',stageName='Propose',closeDate=Date.newinstance(2014,9,30),  recordtypeid=rt.id, External_Initiative__c=ei.id, Description='OverRide');
            Opportunity opp3   = new Opportunity(name='BI-NA MHC Opportunity For Parksite  8',Parksite_Batch_Assertion__c ='Auto',AccountId=acc.id, Account=acc,Amount=25000000,Application_Type__c='CLT-Tyvek',stageName='Propose',product__c = 'Adhesive (1 layer)',closeDate=Date.newinstance(2014,9,30),  recordtypeid=rt.id, External_Initiative__c=ei.id);
            Opportunity opp4   = new Opportunity(name='BI-NA MHC Opportunity For Parksite  9',Parksite_Batch_Assertion__c ='Manual',AccountId=acc.id, Account=acc,Amount=25000000,Application_Type__c='CLT-Tyvek',stageName='Propose',product__c = 'Adhesive (1 layer)',closeDate=Date.newinstance(2014,9,30),  recordtypeid=rt.id, External_Initiative__c=ei.id);
            Opportunity opp5   = new Opportunity(name='BI-NA MHC Opportunity For Parksite  10',Parksite_Batch_Assertion__c ='Manual',AccountId=acc.id, Account=acc,Amount=25000000,Application_Type__c='CLT-Tyvek',stageName='Propose',product__c = 'Adhesive (1 layer)',closeDate=Date.newinstance(2014,9,30),  recordtypeid=rt.id, External_Initiative__c=ei.id);
            
            //acc =  [select id from Account where Name ='Parksite (NE) Surfaces' LIMIT 1];//new Account(Name ='Parksite (IL) Tyvek - HQ',country__C='US');
            //insert acc;
            ei = new External_Initiative__c(name='BI NA Test EI 4', Segment_L2__c='Clinic', Segment_L3__c='New Construction', Stage__c='Bidding',value__c=27800000);
            insert ei;
            rt = [Select id from RecordType where name = 'BI-NA Surfaces Dodge' LIMIT 1];
            
            Opportunity opp6    = new Opportunity(name='BI-NA MHC Opportunity For Parksite 6',AccountId=acc.id, Account=acc, Amount=20000000,Application_Type__c='CLT-Surfaces',stageName='Propose',closeDate=Date.newinstance(2014,9,30), product__c = 'Adhesive (1 layer)',recordtypeid=rt.id, External_Initiative__c=ei.id);
            Opportunity opp7    = new Opportunity(name='BI-NA MHC Opportunity For Parksite 6',AccountId=acc.id, Account=acc, Amount=20000000,Application_Type__c='CLT-Surfaces',stageName='Propose',closeDate=Date.newinstance(2014,9,30), product__c = 'Adhesive (1 layer)',  recordtypeid=rt.id, External_Initiative__c=ei.id,description='Override');
            List<Opportunity> opps = new List<Opportunity>();
            
            opps.add(opp1);
            opps.add(opp2);
            opps.add(opp3);
            opps.add(opp4);
            opps.add(opp5);
            opps.add(opp6);
            opps.add(opp7);
            insert opps;
            
            ctrlOppSFDCToSFDC cos2s = new ctrloppSFDCToSFDC(opps);
            
            List<ID> oppExistingIds = new List<ID>();
            List<PartnerNetworkRecordConnection> existingRecords = [select Id, Status, ConnectionId, LocalRecordId from PartnerNetworkRecordConnection where LocalRecordId  In  : opps LIMIT 1000];
            for(PartnerNetworkRecordConnection existingRecord : existingRecords){
                oppExistingIds.add(existingRecord.LocalRecordId);
            }
            
            update opps;
            
            BatchOppSFDCToSFDCBatchable bosts = new BatchOppSFDCToSFDCBatchable();
            
            Database.executeBatch(bosts,1000);
            Test.stopTest();
    }
}