DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Stage__c</fullName>
        <description>This is the stage or status of the account.</description>
        <label>Account Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Past</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Geography__c.object
<CustomObject>
    <fields>
        <fullName>Code2__c</fullName>
        <description>Unique code across the parent. This field is required and unique across all records with the same parent area.  External Id.  
TODO: Add a trigger to enforce this two key uniqueness.</description>
        <externalId>true</externalId>
        <label>SubCode</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <description>Unique code for the this area.  This field is required and unique across all records.</description>
        <externalId>true</externalId>
        <label>Code</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Level_Name__c</fullName>
        <description>Country specific name to define this administrative level</description>
        <label>Level Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <description>administrative level of territory in geo hierarchy
1=Region, 2=Sub-Region, 3=Country, 4=State, 5=County or similar,6=postalcode</description>
        <label>Level</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Numeric_Code__c</fullName>
        <description>Numeric code used for this area,  if available.</description>
        <label>Numeric Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geography</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Geography_Mapping__c.object
<CustomObject>
    <description>Complementary object to Geography. Used for multiple assignments of records at a specific Geography level.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Geography Mapping</relationshipLabel>
        <relationshipName>Geography_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Geography Mapping</relationshipLabel>
        <relationshipName>Geography_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Geography</label>
        <referenceTo>Geography__c</referenceTo>
        <relationshipLabel>Geography Mapping</relationshipLabel>
        <relationshipName>Geography_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Geography_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geography Mapping</label>
    <nameField>
        <displayFormat>GM-{00000000}</displayFormat>
        <label>Geography Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Geography Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Targeted Geographical scope of this opportunity (Region or Region-Subregion).</description>
        <label>Geography</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AP-ANZ</fullName>
                </value>
                <value>
                    <fullName>AP-ASEAN</fullName>
                </value>
                <value>
                    <fullName>AP-EA</fullName>
                </value>
                <value>
                    <fullName>AP-EA-ASEAN</fullName>
                </value>
                <value>
                    <fullName>AP-EA-ASEAN-ANZ</fullName>
                </value>
                <value>
                    <fullName>AP-EA-ASEAN-Cambodia/Laos/Myanmar</fullName>
                </value>
                <value>
                    <fullName>AP-EA-ASEAN-Indonesia</fullName>
                </value>
                <value>
                    <fullName>AP-EA-ASEAN-Malaysia</fullName>
                </value>
                <value>
                    <fullName>AP-EA-ASEAN-Philippines</fullName>
                </value>
                <value>
                    <fullName>AP-EA-ASEAN-Singapore</fullName>
                </value>
                <value>
                    <fullName>AP-EA-ASEAN-Thailand</fullName>
                </value>
                <value>
                    <fullName>AP-EA-ASEAN-Vietnam</fullName>
                </value>
                <value>
                    <fullName>AP-EA-Japan</fullName>
                </value>
                <value>
                    <fullName>AP-EA-Korea</fullName>
                </value>
                <value>
                    <fullName>AP-GCHINA</fullName>
                </value>
                <value>
                    <fullName>AP-GChina-China</fullName>
                </value>
                <value>
                    <fullName>AP-GChina-HK</fullName>
                </value>
                <value>
                    <fullName>AP-GChina-Taiwan</fullName>
                </value>
                <value>
                    <fullName>AP-INDIA</fullName>
                </value>
                <value>
                    <fullName>AP-JAPAN</fullName>
                </value>
                <value>
                    <fullName>AP-KOREA</fullName>
                </value>
                <value>
                    <fullName>AP-NA</fullName>
                </value>
                <value>
                    <fullName>AP-SA</fullName>
                </value>
                <value>
                    <fullName>AP-SA-Bangladesh</fullName>
                </value>
                <value>
                    <fullName>AP-SA-India</fullName>
                </value>
                <value>
                    <fullName>AP-SA-Sri Lanka</fullName>
                </value>
                <value>
                    <fullName>AP-SEA-ANZ</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>EMEA-CEE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Behind Schedule</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/sma__MAFolder__c.object
<CustomObject>
    <fields>
        <fullName>sma__ParentFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Folder</label>
        <referenceTo>sma__MAFolder__c</referenceTo>
        <relationshipLabel>MapAnything Folders</relationshipLabel>
        <relationshipName>MapAnything_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MapAnything Folder</label>
    <nameField>
        <label>Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MapAnything Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/sma__MATerritory__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MapAnything Territories</relationshipLabel>
        <relationshipName>MapAnything_Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auto_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>MapAnything Territories</relationshipLabel>
        <relationshipName>MapAnything_Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sma__Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>sma__MAFolder__c</referenceTo>
        <relationshipLabel>MapAnything Territories</relationshipLabel>
        <relationshipName>MapAnythingTerritories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MapAnything Territory</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MapAnything Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/MACreateShapeLayersBatchableTest.cls
/*******************************************************************************
CopyrightÂ© 2016 DuPont. All rights reserved.
Author: Matt Peoples 
Email: mpeoples@mapanything.com
Description: Customization for Map Anything Batches
********************************************************************************/
/*
 * Modification log
 * ==================================================================================================
 * ver                         Date                  Author                              Modification                                                                           Timestamp       
 * ---                         ----                  --------------                      ------------                                                                       -------------------------       
 * 1.0                       2016-12-22              Rohit saini                   Modified the Class for removing seeAllData tag and create necessary data in test class       RS12222016      
*/


@isTest
private class MACreateShapeLayersBatchableTest 
{
    private static testMethod void PrimaryTestMethods() 
    {   //<RS12222016> Start
        MA_Color_Code__c m=new MA_Color_Code__c(name='#ae4ad2');
        insert m;
        //<RS12222016> end
        string RandomHexColor = MACustomLogic.RandomHexColor();
        MACustomLogic.DisplayLimitInformation();
        string CountryTwoCodeToThreeCode = MACustomLogic.CountryTwoCodeToThreeCode('US');
    }

    

    private static testMethod void testAccountBatchable() 
    {
        sma__MAFolder__c countyFolder = new sma__MAFolder__c(Name='County');
        insert countyFolder;

        sma__MAFolder__c accountFolder = new sma__MAFolder__c(Name='By Account', sma__ParentFolder__c=countyFolder.Id);
        insert accountFolder;

        sma__MATerritory__c delAccountTerr = new sma__MATerritory__c(Name='Test', Auto_Created__c=true, sma__Folder__c=accountFolder.Id);
        insert delAccountTerr;
        //<RS12222016> Start                                                                                                                                         
        RecordType rt = [SELECT Id, Name, sObjectType FROM RecordType WHERE sObjectType = 'Account' AND Name = 'BI - Surfaces' limit 1];
        
        List<Account> lstAccount=new List<Account>();
        Account a=new Account(name='Parksite test', recordTypeId=rt.id, BI_Account_SubType__c= 'Distribution', Account_Stage__c = 'Active');
        lstAccount.add(a);
       Account a2=new Account(name='Parksite test2', recordTypeId=rt.id, BI_Account_SubType__c= 'Distribution', Account_Stage__c = 'Active');
        lstAccount.add(a2);
        
        insert lstAccount;
       
        Geography__c   geoNew5 = new Geography__c(Name='North America', Code__c='R_NORTH_AMERICA',Level__c=5,Code2__c='NORTH_AMERICA', Level_Name__c='County');
        insert geoNew5;

        Id GeoMappingRecordTypeId = Schema.SObjectType.Geography_Mapping__c.getRecordTypeInfosByName().get('MHC Surfaces').getRecordTypeId();
        
        List<Geography_Mapping__c> lstGm=new List<Geography_Mapping__c>();
        Geography_Mapping__c gm=new Geography_Mapping__c( Account__c=a.id, RecordTypeId=GeoMappingRecordTypeId, Geography__c=geoNew5.id);
        lstGm.add(gm);
        Geography_Mapping__c gm2=new Geography_Mapping__c( Account__c=a2.id, RecordTypeId=GeoMappingRecordTypeId, Geography__c=geoNew5.id);
        lstGm.add(gm2);
        
        insert lstGm;
        //<RS12222016> end
        MACreateShapeLayersByAccountBatchable batch1 = new MACreateShapeLayersByAccountBatchable();
        Database.executeBatch(batch1);
    }
    
    private static testMethod void testUserBatchable() 
    {
        sma__MAFolder__c countyFolder = new sma__MAFolder__c(Name='County');
        insert countyFolder;
        
        sma__MAFolder__c userFolder = new sma__MAFolder__c(Name='By User', sma__ParentFolder__c=countyFolder.Id);
        insert userFolder;
        
        sma__MATerritory__c delUserTerr = new sma__MATerritory__c(Name='Test', Auto_Created__c=true, sma__Folder__c=userFolder.Id);
        insert delUserTerr;
        //<RS12222016> Start
        User u=[select id, name from user where profile.name='BI-NA Distributor Partner' and IsActive = true limit 1];
        
        List<Geography__c> lstGEO=new List<Geography__c>();
        Geography__c   geoNew5 = new Geography__c(Name='Division No. 4', Code__c='AB-4804',Level__c=5, Code2__c='4804', Level_Name__c='County');
        lstGEO.add(geoNew5); 
        Geography__c   geoNew6 = new Geography__c(Name='Choctaw', Code__c='84001023',Level__c=5, Code2__c='01023', Level_Name__c='County');
        lstGEO.add(geoNew6);
        
        insert lstGEO;
        

        Id GeoMappingRecordTypeId = Schema.SObjectType.Geography_Mapping__c.getRecordTypeInfosByName().get('MHC Surfaces').getRecordTypeId();
        
        List<Geography_Mapping__c> lstGM=new List<Geography_Mapping__c>();
        
        Geography_Mapping__c gm=new Geography_Mapping__c( User__c=u.id, RecordTypeId=GeoMappingRecordTypeId, Geography__c=geoNew5.id);
        lstGM.add(gm);
        Geography_Mapping__c gm2=new Geography_Mapping__c( User__c=u.id, RecordTypeId=GeoMappingRecordTypeId, Geography__c=geoNew5.id);
        lstGM.add(gm2);
        
        Geography_Mapping__c gm3=new Geography_Mapping__c( User__c=u.id, RecordTypeId=GeoMappingRecordTypeId, Geography__c=geoNew6.id);
        lstGM.add(gm3);
        Geography_Mapping__c gm4=new Geography_Mapping__c( User__c=u.id, RecordTypeId=GeoMappingRecordTypeId, Geography__c=geoNew6.id);
        lstGM.add(gm4);
        
        insert  lstGM;       
        //<RS12222016> end
        MACreateShapeLayersByUserBatchable batch1 = new MACreateShapeLayersByUserBatchable();
        Database.executeBatch(batch1);
    }

    private static testMethod void testContactBatchable() 
    {
        sma__MAFolder__c stateFolder = new sma__MAFolder__c(Name='State');
        insert stateFolder;
        
        sma__MAFolder__c contactFolder = new sma__MAFolder__c(Name='By Contact', sma__ParentFolder__c=stateFolder.Id);
        insert contactFolder;
        
        sma__MATerritory__c delContactTerr = new sma__MATerritory__c(Name='Test', Auto_Created__c=true, sma__Folder__c=contactFolder.Id);
        insert delContactTerr;
        //<RS12222016> Start
        List<Account> lstAccount=new List<Account>();
        
         Account a=new Account(name='BI (Building Innovations)',  Status__c = 'Active');
         lstAccount.add(a);
        insert lstAccount;
        
        RecordType rt = [SELECT Id, Name, sObjectType FROM RecordType WHERE sObjectType = 'Contact' AND Name = 'BI-NA Contact' limit 1];
        
        List<Contact> lstContacts=new List<Contact>();
        Contact c=new Contact(lastname='Parksite test', recordTypeId=rt.id, Status__c = 'Active', AccountId=a.id);
        lstContacts.add(c);
        Contact c2=new Contact(lastname='Parksite test2', recordTypeId=rt.id, Status__c = 'Active', AccountId=a.id);
        lstContacts.add(c2);
        
        insert lstContacts;
       
        List<Geography__c> lstGeo=new List<Geography__c>();
        Geography__c   geoNew5 = new Geography__c(Name='CA', Numeric_Code__c=6,  Code__c='US-CA',Level__c=4,Code2__c='CA', Level_Name__c='State');
        lstGeo.add(geoNew5);

        Geography__c   geoNew6 = new Geography__c(Name='Hamburg', Numeric_Code__c=3, Code__c='DE-HH',Level__c=4,Code2__c='HH', Level_Name__c='Province');
        lstGeo.add(geoNew6);
        
        insert lstGeo;
        
        Id GeoMappingRecordTypeId = Schema.SObjectType.Geography_Mapping__c.getRecordTypeInfosByName().get('BI-NA Opportunity Owner 2').getRecordTypeId();
        List<Geography_Mapping__c> lstGM=new List<Geography_Mapping__c>();
        Geography_Mapping__c gm=new Geography_Mapping__c( Contact__c=c.id, RecordTypeId=GeoMappingRecordTypeId, Geography__c=geoNew5.id, Owning_Organization__c='BI-Surf');
        lstGM.add(gm);
        Geography_Mapping__c gm2=new Geography_Mapping__c( Contact__c=c2.id, RecordTypeId=GeoMappingRecordTypeId, Geography__c=geoNew5.id, Owning_Organization__c='BI-Surf');
        lstGM.add(gm2);
        Geography_Mapping__c gm3=new Geography_Mapping__c( Contact__c=c2.id, RecordTypeId=GeoMappingRecordTypeId, Geography__c=geoNew5.id, Owning_Organization__c='BI-Surf');
        lstGM.add(gm3);
        Geography_Mapping__c gm4=new Geography_Mapping__c( Contact__c=c2.id, RecordTypeId=GeoMappingRecordTypeId, Geography__c=geoNew6.id, Owning_Organization__c='BI-Surf');
        lstGM.add(gm4);
        Geography_Mapping__c gm5=new Geography_Mapping__c( Contact__c=c2.id, RecordTypeId=GeoMappingRecordTypeId, Geography__c=geoNew6.id, Owning_Organization__c='BI-Surf');
        lstGM.add(gm5);
        
        insert lstGM;
      
        //<RS12222016> end
        MACreateShapeLayersByContactBatchable batch1 = new MACreateShapeLayersByContactBatchable();
        Database.executeBatch(batch1);
    }
    
    private static testMethod void testAccountBatchPage() 
    {   
        ShapeLayerBatchPage b = new ShapeLayerBatchPage();
        b.RunAccountBatch();
    }

    private static testMethod void testUserBatchPage() 
    {   
        ShapeLayerBatchPage b = new ShapeLayerBatchPage();
        b.RunUserBatch();
    }
    
    private static testMethod void testContactBatchPage() 
    {   
        ShapeLayerBatchPage b = new ShapeLayerBatchPage();
        b.RunContactBatch();
    }   
}