DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Group__c</fullName>
        <label>Customer Group</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/ERP_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Account_Group__c</fullName>
        <description>The account group is a classifying feature within customer master records. The account group determines in which number range the customer account number should be; whether the number is assigned by the user or by the system; which specifications are necessary or possible in the master record.</description>
        <label>Account Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>The city of this customer as stored in SAP.</description>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country of this customer as stored in SAP.</description>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <description>Key with which the customer can be identified within the SAP system.Gives an alphanumeric key, which clearly identifies the customer or vendor in the SAP system.</description>
        <label>Customer Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the Source Cluster + Customer Code + Sales Org Code + Distribution Channel Code + Division Code to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language for the customer from the ERP system.</description>
        <label>Language</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Geographical region this customer is located as stored in SAP.</description>
        <label>State/Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>The street of this customer as stored in SAP.</description>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <label>Tax Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VAT_Number__c</fullName>
        <label>VAT Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZIP_Postal_Code__c</fullName>
        <description>The ZIP or postal code of this customer as stored in SAP.</description>
        <label>ZIP/Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ERP Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/ERP_Customer_Localization__c.object
<CustomObject>
    <description>Used to manage the translations of customer master data, as stored in SAP.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>The city of this customer as stored in SAP.</description>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country of this customer as stored in SAP.</description>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <description>Name of the customer.</description>
        <label>Customer Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Customer__c</fullName>
        <description>Master record that this localization record is the translation of.</description>
        <label>ERP Customer</label>
        <referenceTo>ERP_Customer__c</referenceTo>
        <relationshipLabel>ERP Customer Localizations</relationshipLabel>
        <relationshipName>ERP_Customer_Localizations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the Source Cluster + Customer Code + Language to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>The language of the translation</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AF</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>DA</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>EL</fullName>
                </value>
                <value>
                    <fullName>EN</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>ET</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>HE</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>HU</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>JA</fullName>
                </value>
                <value>
                    <fullName>KO</fullName>
                </value>
                <value>
                    <fullName>LT</fullName>
                </value>
                <value>
                    <fullName>LV</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>NL</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
                <value>
                    <fullName>PL</fullName>
                </value>
                <value>
                    <fullName>PT</fullName>
                </value>
                <value>
                    <fullName>RO</fullName>
                </value>
                <value>
                    <fullName>RU</fullName>
                </value>
                <value>
                    <fullName>SK</fullName>
                </value>
                <value>
                    <fullName>SL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Geographical region this customer is located as stored in SAP.</description>
        <label>State/Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>The street of this customer as stored in SAP.</description>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZIP_Postal_Code__c</fullName>
        <description>The ZIP or postal code of this customer as stored in SAP.</description>
        <label>ZIP/Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ERP Customer Localization</label>
    <nameField>
        <displayFormat>CL-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Customer Localizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/ERP_Relationship__c.object
<CustomObject>
    <description>Used to manage the types of relationships an ERP customer might have (Sold-To, Ship-To, End User, etc.)</description>
    <fields>
        <fullName>ERP_Customer__c</fullName>
        <description>Identifies the ERP Customer this record belongs to</description>
        <label>ERP Customer</label>
        <referenceTo>ERP_Customer__c</referenceTo>
        <relationshipLabel>ERP Relationships</relationshipLabel>
        <relationshipName>ERP_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the Source Cluster + Customer Code + Sales Org Code + Distribution Channel Code + Division Code + Partner Counter + Partner Function Code to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Identifies the CSR or Sales Representative as stored in SAP.</description>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_ERP_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the ERP Customer partner record (e.g. the Ship-to).</description>
        <label>Related ERP Customer</label>
        <referenceTo>ERP_Customer__c</referenceTo>
        <relationshipLabel>ERP Relationships (Related ERP Customer)</relationshipLabel>
        <relationshipName>ERP_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ERP Relationship</label>
    <nameField>
        <displayFormat>ERP-R{000000000}</displayFormat>
        <label>ERP Relationship  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>SAP Partner Code / User ID (sales rep, CSR, etc.) of this user and is the unique record identifier for this person from SAP.</description>
        <externalId>true</externalId>
        <inlineHelpText>SAP Partner Code / User ID (sales rep, CSR, etc.) of this user and is the unique record identifier for this person from SAP.</inlineHelpText>
        <label>External ERP ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlCOBCustomerSearch_UT.cls
@isTest
public class ctrlCOBCustomerSearch_UT
{    
    public static final string CST_Account_Rtype= Rtype.getIdByDevName('Account','CS_ERPCustomer');
    public static final string CST_Case_Number_CS_InternalRequest_Rtype = Rtype.getIdByDevName('Case','CS_InternalRequest');
    public static testMethod void CustomerSearch1()
    {
        test.startTest();
        
        Id CustCrRecordTypeId = Schema.SObjectType.Customer_Data_Request__c.getRecordTypeInfosByName().get('New Customer Creation').getRecordTypeId();
        Id ERPExtendedRecordTypeId = Schema.SObjectType.ERP_Customer__c.getRecordTypeInfosByName().get('ERP Customer - Extended Data').getRecordTypeId();      
        Id ERPCustomerGeneral= Schema.SObjectType.ERP_Customer__c.getRecordTypeInfosByName().get('ERP Customer - General Data').getRecordTypeId();
        //GroupMember gr = [SELECT GroupId,UserOrGroupId from GroupMember where UserOrGroupId =: UserInfo.getUserId()];
            
            
        ERP_Customer__c ERPCust = new ERP_Customer__c();
        ERPCust.Account_Group__c='Z001 ( Sold-to party )';
        ERPCust.City__c='Bangalore';
        ERPCust.State__c ='Karnataka';
        ERPCust.Street__c = 'JP Nagar';
        ERPCust.VAT_Number__c='00123';
        ERPCust.Tax_Code__c='V007';
        ERPCust.ZIP_Postal_Code__c='560068';
        ERPCust.Customer_Code__c='C6457';
        ERPCust.RecordTypeId=ERPExtendedRecordTypeId;
        ERPCust.Name ='Test';
        insert ERPCust;
        
         ERP_Customer__c ERPCust1 = new ERP_Customer__c();
        ERPCust1.Account_Group__c='Z001 ( Sold-to party )';
        ERPCust1.City__c='Bangalore';
        ERPCust1.State__c ='Karnataka';
        ERPCust1.Street__c = 'JP Nagar';
        ERPCust1.VAT_Number__c='00123';
        ERPCust1.Tax_Code__c='V007';
        ERPCust1.ZIP_Postal_Code__c='560068';
        ERPCust1.Customer_Code__c='C6457';
        ERPCust1.RecordTypeId=ERPExtendedRecordTypeId;
        ERPCust1.Name ='Test';
        insert ERPCust1;
        
        ERP_Customer__c ERPCustGeneral = new ERP_Customer__c();
        ERPCustGeneral.Account_Group__c='Z001 ( Sold-to party )';
        ERPCustGeneral.City__c='Bangalore';
        ERPCustGeneral.State__c ='Karnataka';
        ERPCustGeneral.Street__c = 'JP Nagar';
        ERPCustGeneral.VAT_Number__c='00123';
        ERPCustGeneral.Tax_Code__c='V007';
        ERPCustGeneral.ZIP_Postal_Code__c='560068';
        ERPCustGeneral.Customer_Code__c='C6457';
        ERPCustGeneral.RecordTypeId=ERPCustomerGeneral;
        ERPCustGeneral.Name ='Test';
        insert ERPCustGeneral;
              
        ERP_Customer_Localization__c ErpLocal = new ERP_Customer_Localization__c();
        ErpLocal.Language__c='EN';
        ErpLocal.ERP_Customer__c=ERPCust.Id;
        insert ErpLocal;
        
        ERP_Relationship__c vERPRelation = new ERP_Relationship__c();
        vERPRelation.ERP_Customer__c=ERPCust.Id;
        vERPRelation.Related_ERP_Customer__c=ERPCust.Id;
        vERPRelation.Name__c='TestRel';
        insert vERPRelation;
        
        Account vAccount = new Account();
        vAccount.Name='TestAccount';
        vAccount.OwnerId = userInfo.getUserId();
        vAccount.ERP_Customer__c=ERPCust.Id;
        vAccount.ERP_Company_Code__c='E456';
        vAccount.VAT_Number__c='V768';
        vAccount.Country__c='India';
//[05112017] Merge&Spin: Added record type attribute to account record
        vAccount.RecordTypeId = RType.getIdByDevName('Account','ERP_Account');
        insert vAccount;
        
        Account AccountGeneral= new Account();
        AccountGeneral.Name='TestAccountGeneral';
        AccountGeneral.OwnerId = userInfo.getUserId();
        AccountGeneral.VAT_Number__c='V768';
        AccountGeneral.Country__c='India';
 //[05112017] Merge&Spin: Added record type attribute to account record
        AccountGeneral.RecordTypeId = RType.getIdByDevName('Account','ERP_Customer_General');
        insert AccountGeneral;

/*PKH        
        SVMXListSettings__c sv = new SVMXListSettings__c(Name='WarrantyLA',Static_Value__c = 'WarrantyLA');
        insert sv;
        SVMXListSettings__c sv1 = new SVMXListSettings__c(Name='ContractLA',Static_Value__c = 'WarrantyLA');
        insert sv1;
        SVMXListSettings__c sv2 = new SVMXListSettings__c(Name='BillableEMEA',Static_Value__c = 'WarrantyLA');
        insert sv2;
        SVMXListSettings__c sv3 = new SVMXListSettings__c(Name='WarrantyEMEA',Static_Value__c = 'WarrantyLA');
        insert sv3;
        SVMXListSettings__c sv4 = new SVMXListSettings__c(Name='Hardware ServiceEMEA',Static_Value__c = 'WarrantyLA');
        insert sv4;
        SVMXListSettings__c sv5 = new SVMXListSettings__c(Name='Hardware SalesEMEA',Static_Value__c = 'WarrantyLA');
        insert sv5;
        SVMXListSettings__c sv6 = new SVMXListSettings__c(Name='ContractEMEA',Static_Value__c = 'WarrantyLA');
        insert sv6;
        SVMXListSettings__c sv7 = new SVMXListSettings__c(Name='Uptime ContractTypeEMEA',Static_Value__c = 'WarrantyLA');
        insert sv7;
        SVMXListSettings__c sv8 = new SVMXListSettings__c(Name='Uptime ContractEMEA',Static_Value__c = 'WarrantyLA');
        insert sv8;

PKH*/        

        Case cas = new Case(subject='Unit Test', Status='New',recordtypeId = CST_Case_Number_CS_InternalRequest_Rtype );
        insert cas;
        
        PageReference pageRef = Page.COBCustomerSearch;
        Test.setCurrentPage(pageRef);   
        ApexPages.currentPage().getParameters().put('qp', 'yyyy');    
        ctrlCOBCustomerSearch vCOBCust = new ctrlCOBCustomerSearch();
        
        List<ctrlCOBCustomerSearch.CustomerWrapperClass> CustomerWrapperList1 = new List<ctrlCOBCustomerSearch.CustomerWrapperClass>();
        ctrlCOBCustomerSearch.CustomerWrapperClass vWrpper1 = new ctrlCOBCustomerSearch.CustomerWrapperClass(ERPCust.Id,'Test','abc','67','100','Test1','C100','SOrg45',true,'Bangalore','Karnataka','India','560068','Bommanahalli','ERPClust','2345','Channel1','Div1',true,'Active','xyz'); 
        CustomerWrapperList1.add(vWrpper1);
        
        List<ctrlCOBCustomerSearch.CustomerWrapperClass> CustomerWrapperList2 = new List<ctrlCOBCustomerSearch.CustomerWrapperClass>();
        ctrlCOBCustomerSearch.CustomerWrapperClass vWrpper2 = new ctrlCOBCustomerSearch.CustomerWrapperClass(ERPCust.Id,'Test1','abc','69','100','Test1','C100','SOrg45',true,'Bangalore','Karnataka','India','560078','JP Nagar','ERPClust','2345','Channel1','Div5',true,'Active','xyz'); 
        CustomerWrapperList2.add(vWrpper2);
        
        List<ctrlCOBCustomerSearch.AccountWrapperClass> AccountWrapperList = new List<ctrlCOBCustomerSearch.AccountWrapperClass>();  
        ctrlCOBCustomerSearch.AccountWrapperClass vWrapper1 = new ctrlCOBCustomerSearch.AccountWrapperClass(vAccount.Id,'Test','V-002','TestRegion','India','Test-003','TsetType',true,'TestName','SFDC',CustCrRecordTypeId,vAccount.OwnerId,'TestSBU','093475867234');
        AccountWrapperList.add(vWrapper1);
        
        ctrlCOBCustomerSearch.AccountWrapperClass vWrapper2 = new ctrlCOBCustomerSearch.AccountWrapperClass(vAccount.Id,'Test','V-002','TestRegion','India','Test-003','TsetType',true,'TestName','SFDC',CST_Account_Rtype,vAccount.OwnerId,'TestSBU','093475867234');
        vCOBCust.CustomerRelatedAccountWrapperList = new List<ctrlCOBCustomerSearch.AccountWrapperClass>();
        vCOBCust.CustomerRelatedAccountWrapperList.add(vWrapper2);
        
        
      //  vCOBCust.currentSelectionCustomerId2='a1B19000000HVv0';
        vCOBCust.currentSelectionCustomerName2='Test';
        vCOBCust.accountSearchCustomer='TestSearch';
        vCOBCust.ExistingERPCustomer='TestExistERP';
        vCOBCust.caseNumberinfo='TestCase';
        vCOBCust.getLanguages();
        vCOBCust.TypeOfTable='Customer';              
        vCOBCust.getSearch(); 
        
        vCOBCust.identifyCST='CST Customer';      
        vCOBCust.TypeofSearchProceed();
        
        vCOBCust.search = 'Duplicate Search';
        vCOBCust.selectSelected=true;
        vCOBCust.identifyCST ='CST Customer';
        vCOBCust.TypeofSearchProceed();
        vCOBCust.cdr.Case_Number__c = cas.Id;
        vCOBCust.TypeofSearchProceed();
        //vCOBCust.findMatchCustomers();
        
       // vCOBCust.setSearch('Duplicate Search');
       // vCOBCust.findMatchCustomers();
        
        vCOBCust.localLanguage='EN';
        vCOBCust.CustName='Test';
        vCOBCust.findMatchCustomers();
        
        vCOBCust.identifyCST='CST Customer';
        vCOBCust.currentSelectionAccountId=null;
        vCOBCust.openDownloadPopUpFlag();
        vCOBCust.search='Extend a Customer';
        vCOBCust.redirectLink();
        
        vCOBCust.currentSelectionCustomerId= ERPCust.Id;
        vCOBCust.currentSelectionCustomerName= ERPCust.Name;
        
        vCOBCust.currentSelectionCustomerId2= ERPCust.Id;
        vCOBCust.currentSelectionCustomerName2= ERPCust.Name;
        
        vCOBCust.currentSelectionCustomerId3= ERPCust.Id;
        vCOBCust.currentSelectionCustomerName3= ERPCust.Name;
        vCOBCust.currentSelectionAccountId = vAccount.Id;
        vCOBCust.openDownloadPopUpFlag(); 
        vCOBCust.IsListRender3 = true;
        vCOBCust.redirectLink();
        vCOBCust.search='Modify Search';
        vCOBCust.redirectLink();
        vCOBCust.search='Duplicate Search';
        vCOBCust.redirectLink();
        vCOBCust.identifyCST='Non CST Customer';
        vCOBCust.redirectLink();
        
        vCOBCust.getDisableCustExtendPrevious();
        vCOBCust.getDisableCustExtendNext();
        vCOBCust.getCustomer_total_size3();
        vCOBCust.getPageNumberExtend();
        vCOBCust.Customer_total_size3=1;
        
        vCOBCust.getTotalPagesExtend();
         vCOBCust.CustName='Testing';
        vCOBCust.search='Modify Search';
        vCOBCust.currentSelectionCustomerAccountGroup='test';
        vCOBCust.ClearCustomerList();
        
        vCOBCust.search='Extend a Customer';
        vCOBCust.identifyCST='Non CST Customer';
        vCOBCust.ClearCustomerList();
        vCOBCust.identifyCST='CST Customer';
        vCOBCust.ClearCustomerList();
        
        vCOBCust.CustName1='Test';
        vCOBCust.VAT1 = 'V768';
        vCOBCust.Country1= 'India';
        vCOBCust.GenericAccountSearch();
        VCOBCust.findMatchCustomers();
        
        vCOBCust.CustName1='gfhjhgjh';
        vCOBCust.VAT1 = 'eyu';
        vCOBCust.Country1= 'Inhgjhdia';
        vCOBCust.AccountGrp1= 'sold';
        vCOBCust.identifyCST='CST Customer';
        vCOBCust.GenericAccountSearch();
        
        vCOBCust.search='Modify Search';
        vCOBCust.isGenericAccountSearchExecute=true;
        VCOBCust.extendsearch();
        VCOBCust.findMatchCustomers();
        vCOBCust.CustomerWrapperList1.add(vWrpper1);
        vCOBCust.AccountSearch();
        
        vCOBCust.identifyCST='Non CST Customer';
        vCOBCust.AccountSearch();
        vCOBCust.IsListRender = true;
        vCOBCust.IsListRender2= true;
        vCOBCust.CustomerWrapperList2.add(vWrpper2);
        vCOBCust.AccountSearch();
        vCOBCust.ClearCustomerList2();
        
        vCOBCust.search='Extend a Customer';
        ctrlCOBCustomerSearch.CustomerWrapperClass vWrpper3 = new ctrlCOBCustomerSearch.CustomerWrapperClass(ERPCust.Id,'Test1','abc','69','100','Test1','C100','SOrg45',true,'Bangalore','Karnataka','India','560078','JP Nagar','ERPClust','2345','Channel1','Div5',true,'Active','xyz');
        vCOBCust.CustomerWrapperList2.add(vWrpper3);
        vCOBCust.IsListRender2= false;
        vCOBCust.IsListRender3= true;
        
        vCOBCust.AccountSearch();
        vCOBCust.ClearAccountList();
        vCOBCust.ClearCustomerList2();
        vCOBCust.isGenericAccountSearchExecute=false;
        vCOBCust.IsCustomerRelatedAccountListRender=true; 
        VCOBCust.extendsearch();
        
        vCOBCust.search='Duplicate Search';
        vCOBCust.CustName2='Test';
        vCOBCust.VAT2='V768';
        vCOBCust.Country2= 'India';
        vCOBCust.localLanguage='';
        vCOBCust.isCustomerExtendedSearchExecute= true;
        vCOBCust.populateCustomer();
        vCOBCust.GenericAccountSearch();
        vCOBCust.TypeOfTable='Customer';
        vCOBCust.Next();  
        
        vCOBCust.TypeOfTable='GenericAccount';
        vCOBCust.Next();
        vCOBCust.Previous();
        vCOBCust.TypeOfTable='RelatedAccount';
        vCOBCust.Next(); 
        vCOBCust.Previous();
        vCOBCust.TypeOfTable='CustomerExtendSearch';
        vCOBCust.Next(); 
        vCOBCust.Previous();
        vCOBCust.end();
        vCOBCust.TypeOfTable='Customer';
        
        vCOBCust.TypeOfTable='RelatedAccount';
        
        
        
        vCOBCust.GenericAccount_total_size=50;
        vCOBCust.RelatedAccount_total_size=40;       
        vCOBCust.Customer_total_size=35;
        
        vCOBCust.TypeOfTable='Customer';       
        vCOBCust.end();
        
        vCOBCust.TypeOfTable='GenericAccount';       
        vCOBCust.end();
        
        vCOBCust.TypeOfTable='RelatedAccount';       
        vCOBCust.end();
        
        vCOBCust.getDisablePrevious();
        vCOBCust.getDisableNext();
        vCOBCust.getCustomer_total_size();
        vCOBCust.getPageNumber();
        
        vCOBCust.GenericAccount_total_size=50;
        vCOBCust.RelatedAccount_total_size=40;       
        vCOBCust.Customer_total_size=35;
        vCOBCust.getRelatedAccountTotalPages();
        vCOBCust.getTotalPages();
        vCOBCust.getDisableGenericAccountPrevious();
        vCOBCust.getDisableGenericAccountNext();
        vCOBCust.getDisableRelatedAccountPrevious();
        vCOBCust.getDisableRelatedAccountNext();
        vCOBCust.getRelatedAccount_total_size();
        vCOBCust.getGenericAccount_total_size();
        vCOBCust.getGenericAccountPageNumber();
        vCOBCust.getRelatedAccountPageNumber();
        
        vCOBCust.GenericAccount_total_size=100;
        vCOBCust.RelatedAccount_total_size=100;       
        vCOBCust.Customer_total_size=200;              
        vCOBCust.getGenericAccountTotalPages();
        
       vCOBCust.onChangeSearch();
       vCOBCust.search='Extend a Customer';
        vCOBCust.CustName2='Test';
       // vCOBCust.populateCustomer();
        
        ctrlCOBCustomerSearch.CustomerWrapperClass vWrpper4 = new ctrlCOBCustomerSearch.CustomerWrapperClass(ERPCustGeneral.Id,'abc','Test1','69','100','Test1','C100','SOrg45',true,'Bangalore','Karnataka','India','560078','JP Nagar','ERPClust','2345','Channel1','Div5',true,'Active','xyz');
        vCOBCust.CustomerWrapperList1=new List<ctrlCOBCustomerSearch.CustomerWrapperClass>();
        vCOBCust.CustomerWrapperList1.clear();
        vCOBCust.CustomerWrapperList1.add(vWrpper4);
        vCOBCust.IsListRender2= false;
        vCOBCust.IsListRender= true;
        vCOBCust.AccountSearch();
        

            
             
       test.stopTest();
  }  
  
   public static testMethod void CustomerSearch2(){
        Id CustCrRecordTypeId = Schema.SObjectType.Customer_Data_Request__c.getRecordTypeInfosByName().get('New Customer Creation').getRecordTypeId();
        Id ERPExtendedRecordTypeId = Schema.SObjectType.ERP_Customer__c.getRecordTypeInfosByName().get('ERP Customer - Extended Data').getRecordTypeId();      
        Id ERPCustomerGeneral= Schema.SObjectType.ERP_Customer__c.getRecordTypeInfosByName().get('ERP Customer - General Data').getRecordTypeId();
        //GroupMember gr = [SELECT GroupId,UserOrGroupId from GroupMember where UserOrGroupId =: UserInfo.getUserId()];
            
            
        ERP_Customer__c ERPCust = new ERP_Customer__c();
        ERPCust.Account_Group__c='Z001 ( Sold-to party )';
        ERPCust.City__c='Bangalore';
        ERPCust.State__c ='Karnataka';
        ERPCust.Street__c = 'JP Nagar';
        ERPCust.VAT_Number__c='00123';
        ERPCust.Tax_Code__c='V007';
        ERPCust.ZIP_Postal_Code__c='560068';
        ERPCust.Customer_Code__c='C6457';
        ERPCust.RecordTypeId=ERPExtendedRecordTypeId;
        ERPCust.Name ='Test';
        insert ERPCust;
        
         ERP_Customer__c ERPCust1 = new ERP_Customer__c();
        ERPCust1.Account_Group__c='Z001 ( Sold-to party )';
        ERPCust1.City__c='Bangalore';
        ERPCust1.State__c ='Karnataka';
        ERPCust1.Street__c = 'JP Nagar';
        ERPCust1.VAT_Number__c='00123';
        ERPCust1.Tax_Code__c='V007';
        ERPCust1.ZIP_Postal_Code__c='560068';
        ERPCust1.Customer_Code__c='C6457';
        ERPCust1.RecordTypeId=ERPExtendedRecordTypeId;
        ERPCust1.Name ='Test';
        insert ERPCust1;
        
        ERP_Customer__c ERPCustGeneral = new ERP_Customer__c();
        ERPCustGeneral.Account_Group__c='Z001 ( Sold-to party )';
        ERPCustGeneral.City__c='Bangalore';
        ERPCustGeneral.State__c ='Karnataka';
        ERPCustGeneral.Street__c = 'JP Nagar';
        ERPCustGeneral.VAT_Number__c='00123';
        ERPCustGeneral.Tax_Code__c='V007';
        ERPCustGeneral.ZIP_Postal_Code__c='560068';
        ERPCustGeneral.Customer_Code__c='C6457';
        ERPCustGeneral.RecordTypeId=ERPCustomerGeneral;
        ERPCustGeneral.Name ='Test';
        insert ERPCustGeneral;
              
        ERP_Customer_Localization__c ErpLocal = new ERP_Customer_Localization__c();
        ErpLocal.Language__c='EN';
        ErpLocal.ERP_Customer__c=ERPCust.Id;
        ErpLocal.Customer_Name__c ='Test';
        ErpLocal.External_ERP_ID__c='WB1-55420944-C';
        insert ErpLocal;
        
        ERP_Relationship__c vERPRelation = new ERP_Relationship__c();
        vERPRelation.ERP_Customer__c=ERPCust.Id;
        vERPRelation.Related_ERP_Customer__c=ERPCust.Id;
        vERPRelation.Name__c='TestRel';
        insert vERPRelation;
        
        Account vAccount = new Account();
        vAccount.Name='TestAccount';
        vAccount.OwnerId = userInfo.getUserId();
        vAccount.ERP_Customer__c=ERPCust.Id;
        vAccount.ERP_Company_Code__c='E456';
        vAccount.VAT_Number__c='V768';
        vAccount.Country__c='India';
//[05112017] Merge&Spin: Added record type attribute to account record
       vAccount.RecordTypeId = RType.getIdByDevName('Account','ERP_Account');
        insert vAccount;
        
        Account AccountGeneral= new Account();
        AccountGeneral.Name='TestAccountGeneral';
        AccountGeneral.OwnerId = userInfo.getUserId();
        AccountGeneral.VAT_Number__c='V768';
        AccountGeneral.Country__c='India';
//[05112017] Merge&Spin: Added record type attribute to account record
       AccountGeneral.RecordTypeId = RType.getIdByDevName('Account','ERP_Customer_General');
        insert AccountGeneral;

/*
        
        SVMXListSettings__c sv = new SVMXListSettings__c(Name='WarrantyLA',Static_Value__c = 'WarrantyLA');
        insert sv;
        SVMXListSettings__c sv1 = new SVMXListSettings__c(Name='ContractLA',Static_Value__c = 'WarrantyLA');
        insert sv1;
        SVMXListSettings__c sv2 = new SVMXListSettings__c(Name='BillableEMEA',Static_Value__c = 'WarrantyLA');
        insert sv2;
        SVMXListSettings__c sv3 = new SVMXListSettings__c(Name='WarrantyEMEA',Static_Value__c = 'WarrantyLA');
        insert sv3;
        SVMXListSettings__c sv4 = new SVMXListSettings__c(Name='Hardware ServiceEMEA',Static_Value__c = 'WarrantyLA');
        insert sv4;
        SVMXListSettings__c sv5 = new SVMXListSettings__c(Name='Hardware SalesEMEA',Static_Value__c = 'WarrantyLA');
        insert sv5;
        SVMXListSettings__c sv6 = new SVMXListSettings__c(Name='ContractEMEA',Static_Value__c = 'WarrantyLA');
        insert sv6;
        SVMXListSettings__c sv7 = new SVMXListSettings__c(Name='Uptime ContractTypeEMEA',Static_Value__c = 'WarrantyLA');
        insert sv7;
        SVMXListSettings__c sv8 = new SVMXListSettings__c(Name='Uptime ContractEMEA',Static_Value__c = 'WarrantyLA');
        insert sv8;
 */

        Case cas = new Case(subject='Unit Test', Status='New',recordtypeId = CST_Case_Number_CS_InternalRequest_Rtype );
        insert cas;
       ctrlCOBCustomerSearch vCOBCust1 = new ctrlCOBCustomerSearch();
       vCOBCust1.CustName1 = 'Test';
       vCOBCust1.identifyCST='Non CST Customer';
       vCOBCust1.search='Extend a Customer';
       vCOBCust1.GenericAccountSearch();
       ctrlCOBCustomerSearch.AccountWrapperClass vWrapper2 = new ctrlCOBCustomerSearch.AccountWrapperClass(vAccount.Id,'Test','V-002','TestRegion','India','Test-003','TsetType',true,'TestName','SFDC',CST_Account_Rtype,vAccount.OwnerId,'TestSBU','093475867234');
        vCOBCust1.CustomerRelatedAccountWrapperList = new List<ctrlCOBCustomerSearch.AccountWrapperClass>();
        vCOBCust1.CustomerRelatedAccountWrapperList.add(vWrapper2);
       vCOBCust1.IsCustomerRelatedAccountListRender=true;
       vCOBCust1.IsGenericAccountListRender=false;
       vCOBCust1.currentSelectionAccountId=null;
       vCOBCust1.extendsearch();
       vCOBCust1.IsGenericAccountListRender=true;
       vCOBCust1.extendsearch();
       vCOBCust1.setSearch('Extend');
       vCOBCust1.localLanguage='Chinese';
       vCOBCust1.CustName1 = 'Test';
       vCOBCust1.customerQuery();
       Profile p1 =[SELECT Id FROM Profile where name='Customer Service' limit 1];  
        User U1= new User(Firstname='System',Alias='SUser', Email='Sai_Lakkimsetty@infosys.com', 
        User_Country__c='UNITED STATES', profileid = p1.id,
        Username='User4@dupont.com.test4', LastName='user',
        TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US',
        EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
        insert U1;  
        
        
        Account vAccount1 = new Account();
        vAccount1.Name='TestAccount';
        vAccount1.OwnerId = U1.Id;
        vAccount1.ERP_Customer__c=ERPCust.Id;
        vAccount1.ERP_Company_Code__c='E456';
        vAccount1.VAT_Number__c='V768';
        vAccount1.Country__c='India';
        insert vAccount1;
        system.RunAs(U1){
            List<Account> acc = new List<Account>();
            acc.add(vAccount1);
            vCOBCust1.AccountShareList(acc);
        }
       
   }
    
}