DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Case_Action__c.object
<CustomObject>
    <description>The specific Actions that are taken as a result of the case</description>
    <fields>
        <fullName>ActionSubtype__c</fullName>
        <description>The specific Action taken (related to the Type) as a result of this case</description>
        <inlineHelpText>The specific Action taken (related to the Type) as a result of this case</inlineHelpText>
        <label>Action Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ActionType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Change Material/Batch</fullName>
                </value>
                <value>
                    <fullName>Corrective Actions</fullName>
                </value>
                <value>
                    <fullName>Customer Return Material</fullName>
                </value>
                <value>
                    <fullName>Customer Sell Seed as Grain</fullName>
                </value>
                <value>
                    <fullName>Customer Visit</fullName>
                </value>
                <value>
                    <fullName>Defective Product Pull-Out</fullName>
                </value>
                <value>
                    <fullName>Field Test</fullName>
                </value>
                <value>
                    <fullName>Lab Analysis</fullName>
                </value>
                <value>
                    <fullName>Material Restitution - Current Sales Campaign</fullName>
                </value>
                <value>
                    <fullName>Material Restitution - Future Sales Campaign</fullName>
                </value>
                <value>
                    <fullName>Material Return</fullName>
                </value>
                <value>
                    <fullName>Monetary Restitution</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Pardon Debt</fullName>
                </value>
                <value>
                    <fullName>Preventive Actions</fullName>
                </value>
                <value>
                    <fullName>Product Replacement</fullName>
                </value>
                <value>
                    <fullName>Sale as Grain</fullName>
                </value>
                <value>
                    <fullName>Sample Collection</fullName>
                </value>
                <value>
                    <fullName>Sample Pictures &amp; Details</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>The type or category of the Action taken as a result of this case</description>
        <inlineHelpText>The type or category of the Action taken as a result of this case</inlineHelpText>
        <label>Action Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Investigation</fullName>
                </value>
                <value>
                    <fullName>Post Investigation</fullName>
                </value>
                <value>
                    <fullName>Solution</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>The related Case</description>
        <inlineHelpText>The related Case</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Actions</relationshipLabel>
        <relationshipName>Case_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Case Action</label>
    <nameField>
        <displayFormat>CAID-{0000000}</displayFormat>
        <label>Case Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlCaseActionMassAdd.cls
public with sharing class ctrlCaseActionMassAdd {
	
	private integer NUM_ROWS = 5;
	public LIST<Case_Action__c> newRecords				{ get; set; }
	public string id									{ get; set; }
	public string rtype									{ get; set; }
	public string ErrMsg								{ get; set; }
	//public Case_Action__c tmp							{ get; set; }
	
	public ctrlCaseActionMassAdd() { 
	//public ctrlCaseObjectMassAdd(ApexPages.StandardController controller) {
		id			=ApexPages.currentPage().getParameters().get('cid');
		rtype		=ApexPages.currentPage().getParameters().get('rt');
		string sz	=ApexPages.currentPage().getParameters().get('sz');
		if (Util.stringToInteger(sz)!=null) 
			NUM_ROWS=Util.stringToInteger(sz);		
		
		Case_Action__c tmp = new Case_Action__c(case__c=id);
		if (!Util.IsBlank(rtype))
			tmp.recordtypeid=rtype;
			
		newRecords = new LIST<Case_Action__c>();
		for (integer i=0; NUM_ROWS>i; i++) {
			newRecords.add(tmp.clone());
		}	
	}
	
	//ActionSubtype__c, ActionType__c
	public PageReference Save() {
		ErrMsg='';
		 LIST<Case_Action__c> insertions = new  LIST<Case_Action__c>();
		 boolean err=false;
		for (Case_Action__c r : newRecords) {
			if ( r.ActionType__c!=null && r.ActionSubtype__c!=null )
				insertions.add(r);
			else if ( r.ActionType__c!=null && r.ActionSubtype__c==null ) {
				ErrMsg=Label.CaseActionMassAddError_001;
				err=true;
				}
		}
		if (!err) {
			insert insertions;
			return Done();
		}
		else { 
			return null;
			}
	}
	
	public PageReference Done() {
		return new PageReference('/'+id);
	}

//*****************************************************************************************
// TEST Method(s)
//*****************************************************************************************
   public static testMethod void test_ctrlCaseActionMassAdd() {

		GeoValidation.DisableGeoValidationOverride=true;
		Account acc = new Account(name='TestCo: ', country__c='United States'); 
		insert acc;
		Case cs = new Case (account = acc); // stagename='won', closedate=Date.TODAY() );
		insert cs;
        Test.startTest();
        PageReference pageRef = Page.CaseActionMassAdd;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('cid', cs.id);
		ApexPages.currentPage().getParameters().put('rt', null);
		ApexPages.currentPage().getParameters().put('sz', '6');          
        ctrlCaseActionMassAdd ctrl = new ctrlCaseActionMassAdd(); //ctrlCaseObjectMassAdd(new ApexPages.StandardController(new Case_Action__c()));
       
       //Will err
        ctrl.newRecords[0].ActionType__c='some val';
        ctrl.save();
        
		//Will not err
        ctrl.newRecords[0].ActionSubtype__c = 'some other val';
        ctrl.save();
        Test.stopTest();
    }  
}