DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Group__c</fullName>
        <label>Customer Group</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group_2__c</fullName>
        <label>Customer Group 2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org 1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/CS_Account_Load_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used for storing all the used values in Accounts Batch processes.</description>
    <fields>
        <fullName>AccountGroup__c</fullName>
        <label>AccountGroup</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountOwnerUserName__c</fullName>
        <description>This field will hold the username.</description>
        <inlineHelpText>This field will hold the username of static user &quot;Customer Service&quot; created in application.</inlineHelpText>
        <label>Account Owner User Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountOwner__c</fullName>
        <label>Account Owner</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType_Name__c</fullName>
        <label>RecordType Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendErrorNotificationTo__c</fullName>
        <label>Send Error Notification To</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CS_AccountLoadSettings</label>
</CustomObject>

DuPont DevSB/src/objects/CS_YKPartnerMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will be used for mapping YK Partner types to their Service Centers</description>
    <label>CS YK Partner Mapping</label>
</CustomObject>

DuPont DevSB/src/objects/ERP_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Account_Group_Code__c</fullName>
        <description>The account group is a classifying feature within customer master records. The account group determines in which number range the customer account number should be; whether the number is assigned by the user or by the system; which specifications are necessary or possible in the master record.</description>
        <label>Account Group Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Group__c</fullName>
        <description>The account group is a classifying feature within customer master records. The account group determines in which number range the customer account number should be; whether the number is assigned by the user or by the system; which specifications are necessary or possible in the master record.</description>
        <label>Account Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>The city of this customer as stored in SAP.</description>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country of this customer as stored in SAP.</description>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <description>Key with which the customer can be identified within the SAP system.Gives an alphanumeric key, which clearly identifies the customer or vendor in the SAP system.</description>
        <label>Customer Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_General_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the record that contains the SAP general data for this customer, which can be shared across sales orgs.</description>
        <label>Customer - General Data</label>
        <referenceTo>ERP_Customer__c</referenceTo>
        <relationshipLabel>ERP Customers</relationshipLabel>
        <relationshipName>ERP_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Group_2_Code__c</fullName>
        <description>Identifies a particular group of customers (for example, wholesale or retail).</description>
        <label>Customer Group 2 Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group_2__c</fullName>
        <description>Identifies a particular group of customers (for example, wholesale or retail).</description>
        <label>Customer Group 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group_9_Code__c</fullName>
        <label>Customer Group 9 Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group_9__c</fullName>
        <label>Customer Group 9</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deletion_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates in the future this record is to be deleted or not, however they are not physically deleted yet for history maintenance purposes. This deletion applies in the specified sales area only.</description>
        <label>Deletion Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel_Code__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_Code__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Account__c</fullName>
        <description>This Field has been created as a part of req.123</description>
        <label>ERP Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ERP_YKPartnerCode__c</fullName>
        <description>This Field will capture Partner Function Code Value and will be updated by Workflow &quot;CS_UpdateERPCustomerYKPartnerCode&quot;.</description>
        <label>YK Partner Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the Source Cluster + Customer Code + Sales Org Code + Distribution Channel Code + Division Code to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <description>Language code for the customer from the ERP system.</description>
        <label>Language Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language for the customer from the ERP system.</description>
        <label>Language</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Box__c</fullName>
        <description>The Post Office Box of this customer as stored in SAP.</description>
        <label>PO Box</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org. Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Search_Term__c</fullName>
        <description>Search term for the customer from the ERP system.  Example: &quot;IBM&quot;.</description>
        <label>Search Term</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Cluster__c</fullName>
        <description>Specific SAP box or cluster where the data of this record originates.</description>
        <label>Source Cluster</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>The street of this customer as stored in SAP.</description>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fLanguage_Code_General__c</fullName>
        <description>Language Code from the related ERP Customer General record</description>
        <formula>Customer_General_Data__r.Language_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language Code (General)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fLanguage_General__c</fullName>
        <description>Language from the related ERP Customer General record</description>
        <formula>Customer_General_Data__r.Language__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language (General)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fSearch_Term_General__c</fullName>
        <description>Search term from the related ERP Customer General record</description>
        <formula>Customer_General_Data__r.Search_Term__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Search Term (General)</label>
        <type>Text</type>
    </fields>
    <label>ERP Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/batchCSAccountInitialLoad.cls
/*******************************************************************************
Copyright © 2015 DuPont. All rights reserved.
Author: Prerna Chandak
Email: prerna.chandak@accenture.com
Description: Batch Process to do a Daily Load from ERP Customer into Account object. 

Change history (key updates):
@author sanchit.dua
email sanchit.dua@accenture.com
20th April, 2015 -> added line 61 to 80
20th April, 2015 -> 112 to 156
20th April, 2015 -> 164 to 168

28th October,2015-> Queried for fLanguage_General__c,fLanguage_Code_General__c,fSearch_Term_General__c fields with timestamp <SB20151028>

@ Abinand Aravazhi 
20th Jan, 2016 --> Changed logic to include General Account Creation 
               --> Changes Indicated with the Tag <AA01202016>

 ********************************************************************************/

/* This class will load the data from ERP Customers into Account object. */
global class batchCSAccountInitialLoad implements Database.Batchable<sObject>, Database.Stateful {
    global utilCSBatchErrorLog batchErrorLog;
    
    private static final string ERROR_MSG = ' .Trace: ';
    private static final String INITIAL_VAL = '';
    private Integer lmt = Limits.getLimitQueryRows();
    private static Set<String> partnerCodes = new Set<String>();
    private static CS_Account_Load_Settings__c accountLoad;
    global boolean erroredOut;
    private static final string ZRCode ='ZR';
    private static final string USER_ERROR = 'Error: the ERP Customers to be updated doensn\'t exist.';
    private static final string accountLoadNotExist = 'Custom Settings CS_Account_Load_Settings__c does not exist.';
    private static final string partnerCodesNotExist = 'Custom Settings CS_YKPartnerMapping__c does not exist.';
    private static final string toAddressNotExist = 'SendErrorNotificationTo__c field value of CS_Account_Load_Settings__c custom settings does not exist.';

    private static final String query = 'SELECT Name, Account_Group__c, Account_Group_Code__c,'+
    '        Language__c,Language_Code__c,fLanguage_General__c,fLanguage_Code_General__c, '+
    '        ERP_YKPartnerCode__c, Source_Cluster__c,RecordTypeid,ERP_Account__c,Customer_General_Data__c,'+
    '        Sales_Org_Code__c,Sales_Org__c, City__c, Country__c, '+
    '        Customer_Group_2__c,Distribution_Channel_Code__c,'+
    '        Distribution_Channel__c,Division_Code__c,Division__c, '+
    '        Customer_Group_2_Code__c, Customer_Group_9__c, '+
    '        Customer_Group_9_Code__c, Street__c, PO_Box__c, '+
    '        Customer_Code__c,Search_Term__c,fSearch_Term_General__c, External_ERP_ID__c , Deletion_Flag__c '+
    '        FROM ERP_Customer__c                                                   '+
    '        WHERE Account_Group__c = \'<accountGroup>\' AND Deletion_Flag__c = False '+
    '        AND (ERP_YKPartnerCode__c IN:partnerCodes)'+
    '        AND Recordtype.Name =\'<recordTypeName>\' limit ';
    
    private static final String accountGroupPlaceHolder = '<accountGroup>';
    private static final String rtPlaceHolder = '<recordTypeName>';
    private static final String ERPRECORDTYPENAME= 'ERP Relationship - Person';
    
    static {
        //partnerCodes = new Set<String>();
        if( !CS_Account_Load_Settings__c.getall().isEmpty() )
            accountLoad = CS_Account_Load_Settings__c.getall().values()[0];
        for(CS_YKPartnerMapping__c partner: CS_YKPartnerMapping__c.getall().values()) 
                partnerCodes.add(partner.Name);
        
    }
   
    
    /*Description :  This method is used for logging the errors. */
    public batchCSAccountInitialLoad(){
        batchErrorLog = new utilCSBatchErrorLog();
        erroredOut = false;
    }
    
    /* Start Method: To fetch the records to be processed */
    global Database.QueryLocator start(Database.BatchableContext BC){   
        System.LoggingLevel level = LoggingLevel.FINEST;
            if(accountLoad == NULL){
                System.debug(logginglevel.ERROR, Label.CS_ErrorMessage+accountLoadNotExist );
                erroredOut = true;
                throw new IntentionalException();
            }
            
            if(partnerCodes.isEmpty()){
                System.debug(logginglevel.ERROR, Label.CS_ErrorMessage+partnerCodesNotExist);
                erroredOut = true;
                throw new IntentionalException();
            }
            
            if(accountLoad.SendErrorNotificationTo__c == NULL){
                System.debug(logginglevel.ERROR, Label.CS_ErrorMessage+toAddressNotExist);
                erroredOut = true;
                throw new IntentionalException();
            } 
            Database.QueryLocator q = Database.getQueryLocator(query.replace(accountGroupPlaceHolder, accountLoad.AccountGroup__c).replace(rtPlaceHolder, accountLoad.RecordType_Name__c)+lmt );
            Database.QueryLocatorIterator it =  q.iterator();
            if(it.hasNext()){
            

                return q;}

            else{
            
                erroredOut = NULL;
                return q;
            }    
    } // END start()

    /*Execute Method: This method is used to create/update accounts from the ERP Customer records. */
    global void execute(Database.BatchableContext BC, List<sobject> scope) {
      
      
      
       if( erroredOut != NULL && !erroredOut ){
            Map<Id,ERP_Customer__c> erpCustomerMap = new Map<Id,ERP_Customer__c>();
        
            for(Sobject sobj: scope){
                ERP_Customer__c customer = (ERP_Customer__c) sobj;
                erpCustomerMap.put(customer.id, customer);
            }
            Map<Id,ERP_Customer__c> duplicateErpCustomerMap = new Map<Id, ERP_Customer__c>();

            for(Id customerId: erpCustomerMap.keySet())
                duplicateErpCustomerMap.put(customerId, erpCustomerMap.get(customerId));
                     

            utilCSAccountLoad data =  new utilCSAccountLoad();
            // AA01202016 - Calling the New function in Util Class.
            if(!(erroredOut=data.erpCust_AccountfieldsMapping(erpCustomerMap, null, batchErrorLog, accountLoad.AccountOwnerUserName__c, erroredOut,null))){
                List<ERP_Customer__c> erpCustToUpdate = new List<ERP_Customer__c>();
                for(ERP_Customer__c ec :duplicateErpCustomerMap.values()){
                    if(!batchErrorLog.erpIdWithMsg.isEmpty() || !batchErrorLog.erpIds.isEmpty()){
                        if(batchErrorLog.erpIdWithMsg.containsKey(ec.id) || batchErrorLog.erpIds.contains(ec.id)){
                            continue;
                        }
                    }
                    ec.ERP_Account__c = accountLoad.AccountOwner__c;
                    erpCustToUpdate.add(ec);
                }
                String errMessage = INITIAL_VAL ;
            } // END if
        } // END if      
    } // END execute()

    /* Finish Method: This method will catch the errors occured(if any) while records are created/updated. */
    global void finish(Database.BatchableContext BC) {
        AsyncApexJob apexJobs = [SELECT Id,
                                 ApexClass.name
                                 FROM AsyncApexJob 
                                 WHERE Id =:BC.getJobId() limit :lmt];
        utilCSEmail.finishEmail(batchErrorLog, apexJobs.ApexClass.name, erroredOut);
      
    } // END finish()
    /**
     * Class responsible for providing custom exception
     * @author Sanchit Dua
     * email sanchit.dua@accenture.com
     */
    public without sharing class IntentionalException extends Exception {}
    
}