DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>DPT_AP</fullName>
        <active>true</active>
        <businessProcess>I2C Sales Process</businessProcess>
        <label>DPT-AP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Opportunity_Products__c.object
<CustomObject>
    <description>List of Products relevent to a given opportunity</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Name of the opportunity this Product is applicable to</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity-Product</label>
    <nameField>
        <displayFormat>OPPR{YY}{MM}-{0000}</displayFormat>
        <label>Opportunity-Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity-Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/lookupFieldTest_UT.cls
@isTest(SeeAllData=True)
private class lookupFieldTest_UT{

 static testMethod void lookupFieldTestMeth(){
 Test.startTest();
 
 Account acc = new Account(name='TestCo: ', country__c='United States'); 
    insert acc;
    UtilRT.RT rt = UtilRT.getRT('Opportunity', 'DPT_AP');
        Opportunity opp = new Opportunity (RecordTypeId=rt.Id, account = acc, name='test', stagename='target', closeDate=Date.Today(), CurrencyIsoCode='USD');
    insert opp;
        opportunity_products__c oprod = new opportunity_products__c(opportunity__c=opp.Id);
        
           insert oprod;
        system.currentPageReference().getParameters().put('Id',null);
        
        ApexPAges.StandardController sc = new ApexPages.StandardController(oprod);
         lookupFieldTest lp =  new lookupFieldTest(sc);
         lp.getlookupFieldTest();
       Test.stopTest();
        
       
 }
 }