DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Received &amp; Activated</fullName>
                </value>
                <value>
                    <fullName>Sent for Printing</fullName>
                </value>
                <value>
                    <fullName>Sent to Business Analyst</fullName>
                </value>
                <value>
                    <fullName>Sent to Business Mgr</fullName>
                </value>
                <value>
                    <fullName>Sent to Contract Owner-Draft</fullName>
                </value>
                <value>
                    <fullName>Sent to Contract Owner-Final</fullName>
                </value>
                <value>
                    <fullName>Sent to Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Sent to Legal-Draft</fullName>
                </value>
                <value>
                    <fullName>Sent to Legal-Execution</fullName>
                </value>
                <value>
                    <fullName>Signed &amp; Mailed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to Business Manager</fullName>
                </value>
                <value>
                    <fullName>Send for Reviewing</fullName>
                </value>
                <value>
                    <fullName>Sent to Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Send to Product Line Manager</fullName>
                </value>
                <value>
                    <fullName>Sent to PLM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Expiration_Date__c</fullName>
        <label>Contract Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Location__c</fullName>
        <inlineHelpText>Where will the physical contract be stored?</inlineHelpText>
        <label>Contract Location</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Opportunity that is associated with this Contract Agreement</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Contract to this contract</description>
        <label>Related Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Related Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Step_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This Field Determines the step number of the approval process</description>
        <label>Step Number</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The kind of contract</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party (non-DuPont)</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>DuPont</fullName>
                </value>
                <value>
                    <fullName>Main Agreement</fullName>
                </value>
                <value>
                    <fullName>Non-Disclosure Agreement</fullName>
                </value>
                <value>
                    <fullName>Supplemental Agreement</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>OneDuPont_Contracts_Approved</fullName>
        <active>true</active>
        <label>OneDuPont Contracts - Approved</label>
    </recordTypes>
    <recordTypes>
        <fullName>OneDupont_Contracts</fullName>
        <active>true</active>
        <label>OneDupont Contracts</label>
    </recordTypes>
    <recordTypes>
        <fullName>OneDupont_Contracts_Activated</fullName>
        <active>true</active>
        <label>OneDupont Contracts - Activated</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>The status of the Opportunity in the Approval Process</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Expiration_Date__c</fullName>
        <description>Date the contract related to this opportunity expires</description>
        <label>Contract Expiration Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EPass_ID__c</fullName>
        <description>Positive identification of individuals accessing DuPont computer systems.</description>
        <label>E-Pass ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Grouping__c</fullName>
        <description>DuPont Business</description>
        <inlineHelpText>DuPont Business (abbrev)</inlineHelpText>
        <label>User Grouping</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>DC&amp;F</fullName>
                </value>
                <value>
                    <fullName>DPM</fullName>
                </value>
                <value>
                    <fullName>DPS</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Owning_Org__c</fullName>
        <description>Primary &quot;Owning Organisation&quot; this user belongs to</description>
        <label>User Owning Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-Env</fullName>
                </value>
                <value>
                    <fullName>BI-Surf</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>CORP-CS</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-ES</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PM</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PS</fullName>
                </value>
                <value>
                    <fullName>DPT-Aramids</fullName>
                </value>
                <value>
                    <fullName>DPT-Automotive</fullName>
                </value>
                <value>
                    <fullName>DPT-Car Protection</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP</fullName>
                </value>
                <value>
                    <fullName>DPT-NOW</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IAL</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>LEGL</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Corp Marketing</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Customer Care</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-IT</fullName>
                </value>
                <value>
                    <fullName>DPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Region__c</fullName>
        <label>User Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ContractHandler_UT.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
/*******************************************************************************
Copyright © 2011 DuPont. All rights reserved. 
Author: Vinayak Vijayakumar
Email: Vinayak.Vijayakumar@usa.dupont.com
Date : 29th May 2011
Description : Test class for ContractHandler

 * Modification Log 
 * ============================================================================= 
 * Ver   Date        Author                 Modification 
 * ---   ---------   ----------- ----------------------------------------------- 
 * 1.0   19-Sep-11   Vinayak VijayaKumar    Initial Code
 * 1.1   19-Sep-11   Vinayak Vijayakumar    Changed Rtype.getIdByName to Rtype.getIdByDevName, 
                                           as there was Translation Issue.
 * 1.2   26-Jul-12   Ibtesamuddin Mohammed  Added Test Functionality for dynamic Approval                                
 **************************************************************************************************************/

@isTest
private class ContractHandler_UT{

    static testMethod void testContracts() {
        // TO DO: implement unit test
        final Id CONT_ONE_DUPONT_APPR_RTYPE=Rtype.getIdByDevName('Contract','OneDupont_Contracts_Approved');
        final Id CONT_ONE_DUPONT_RTYPE=Rtype.getIdByDevName('Contract','OneDupont_Contracts');
        final Id CONT_ONE_DUPONT_ACTIVATED_RTYPE=Rtype.getIdByDevName('Contract','OneDupont_Contracts_Activated');
        final Id BI_EMEA_CONTRACTS=Rtype.getIdByDevName('Contract','BI_Contracts');
        final Id DSS_CONTRACT_RTYPE = Rtype.getIdByDevName('Contract','DSS_Global_Contracts');
        Profile p1 = [select id from profile where Name='System Administrator' limit 1];
        UserRole r1= [Select id from UserRole where Name='PS CRM' limit 1];
        User user1 = new User(LastName='XYZ',UserRoleId=r1.Id,ProfileId=p1.Id,Alias='ain123',EmailEncodingKey='UTF-8',TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',LanguageLocaleKey='en_US',Email='Vinayak.Vijayakumar@infosys.com',UserName='Vinayak.Vijayakumar.test@usa.dupont.com.t12', EPass_ID__c='NA0000',User_Owning_Org__c='AGCP-CPC',User_Country__c='India',User_Grouping__c='CPC',User_Region__c='Latin America');
        User user2 = new User(LastName='XYZ1',UserRoleId=r1.Id,ProfileId=p1.Id,Alias='ain1234',EmailEncodingKey='UTF-8',TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',LanguageLocaleKey='en_US',Email='Vinayak.Vijayakumar@infosys.com',UserName='Vinayak.Vijayakumar.test@usa.dupont.com.t123', EPass_ID__c='NA0000',User_Owning_Org__c='AGCP-CPC',User_Country__c='India',User_Grouping__c='CPC',User_Region__c='Latin America',ManagerId=user1.id);
        insert user1;
        insert user2;
        User sysUser = new User(LastName='XYZ1',UserRoleId=r1.Id,ProfileId=p1.Id,Alias='ain12345',EmailEncodingKey='UTF-8',TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',LanguageLocaleKey='en_US',Email='Vinayak.Vijayakumar@infosys.com',UserName='Vinayak.Vijayakumar.sys@usa.dupont.com.t12', EPass_ID__c='NA0000',User_Owning_Org__c='AGCP-CPC',User_Country__c='India',User_Grouping__c='CPC',User_Region__c='Latin America');
        insert sysUser;
        List<Approval.ProcessSubmitRequest> reqList = new List<Approval.ProcessSubmitRequest>();
        List<Contract> insertContractList = new List<Contract>();
        List<Contract> updateContractList = new List<Contract>();

        System.runAs ( sysUser ) {
            try{

//Unit test code for dynamic approval logic - start
                Account accc = new Account(name='test Account1', country__c = 'UNITED STATES',ownerId=sysUser.Id);
                insert accc;
                //KT [11072017]: To remove sector__c ='Services', reference
                Opportunity opp = new Opportunity (account = accc, name='test', stagename='target', closeDate=Date.Today(), CurrencyIsoCode='USD',Amount=1600000);
                Contact c1 = new Contact (accountid=accc.id, firstName='one', lastname='tester', email='test1@test.com',Title='beta tester 1', Prefered_Language__c='ENGLISH', mailingState='DE');
                insert opp;
                insert c1;
                For(Integer i = 0;i<100;i++){
                    //Contract contr1 = new Contract(Name='Unit Test'+i,AccountId=accc.Id,Status='Draft',Category__c='Non-Standard',StartDate=Date.Today(),Opportunity__c=opp.id,CustomerSigned=c1,RecordTypeId=DSS_CONTRACT_RTYPE,ownerId=sysUser.Id,CurrencyIsoCode='USD');
                    Contract contr1 = new Contract(Name='Unit Test'+i,AccountId=accc.Id,Status='Draft',StartDate=Date.Today(),Opportunity__c=opp.id,CustomerSigned=c1,RecordTypeId=DSS_CONTRACT_RTYPE,ownerId=sysUser.Id,CurrencyIsoCode='USD');
                    insertContractList.add(contr1);
                }

                insert insertContractList;
                For(Contract c : insertContractList){
                    c.Step_Number__c = 1;
                    updateContractList.add(c);
                    Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitrequest();
                    app.setObjectId(c.Id);
                    reqList.add(app);
                }

                Test.startTest();
                update updateContractList;
                approval.ProcessResult[] result = Approval.process(reqList);

//Unit test code for dynamic approval logic - end


                Account acc1 = new Account(name='test Account1', country__c = 'UNITED STATES', ERP_Customer_Sold_To__c='ABC123',ownerId=User1.Id);
                insert acc1;
                Contract contr1 = new Contract(Name='Unit Test',AccountId=acc1.Id,Status='Draft',RecordTypeId=CONT_ONE_DUPONT_RTYPE,ownerId=User2.Id);
                insert contr1;
                contr1.RecordTypeId=CONT_ONE_DUPONT_APPR_RTYPE;
                update contr1;
                Attachment attach1=new Attachment(); 
                attach1.Name='Unit Test Attachment';
                attach1.OwnerId = user1.Id;
                Blob bodyBlob1=Blob.valueOf('Unit Test Attachment Body1');
                attach1.body=bodyBlob1;
                attach1.parentId=contr1.id;
                attach1.ContentType='application/pdf';
                insert attach1;
                contr1.status='Activated';
                update contr1;                

                Contract contr2 = new Contract(Name='Unit Test',AccountId=acc1.Id,Status='Draft',RecordTypeId=CONT_ONE_DUPONT_RTYPE,ownerId=User2.Id);
                insert contr2;    
                contr1.RecordTypeId=CONT_ONE_DUPONT_APPR_RTYPE;
                contr2.Related_Contract__c=contr1.Id;
                update contr2;

                Attachment attach2=new Attachment(); 
                attach2.Name='Unit Test Attachment';
                attach2.OwnerId = user2.Id;
                Blob bodyBlob2=Blob.valueOf('Unit Test Attachment Body2');
                attach2.body=bodyBlob2;
                attach2.parentId=contr2.id;
                attach2.ContentType='application/pdf';
                insert attach2;

                Attachment attach3=new Attachment(); 
                attach3.Name='Unit Test Attachment';
                attach3.OwnerId = user2.Id;
                Blob bodyBlob3=Blob.valueOf('Unit Test Attachment Body3');
                attach3.body=bodyBlob3;
                attach3.parentId=contr2.id;
                attach3.ContentType='application/msword';
                insert attach3;

                contr2.RecordTypeId=CONT_ONE_DUPONT_ACTIVATED_RTYPE;
                contr2.Approval_Status__c='Received & Activated';
                contr2.status='Activated';

                update contr2;    
                Account acc2 = new Account(name='test Account2', country__c = 'UNITED STATES', ERP_Customer_Sold_To__c='ABC123',ownerId=User2.Id);
                insert acc2;
                List<Contract> contr3 = new List<Contract>();
                contr3.add(new Contract(Name='Unit Test 1',AccountId=acc2.Id,Status='Draft',RecordTypeId=BI_EMEA_CONTRACTS,ownerId=User2.Id,Type__c='DuPont',Contract_Location__c='ABCD',StartDate=Date.today(),Contract_Expiration_Date__c=Date.today().addYears(10)));

                insert contr3;

            }
            catch(DMLException e){
                e.getMessage();
            }

        }
    }
}