DuPont DevSB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Stage__c</fullName>
        <description>This is the stage or status of the account.</description>
        <label>Account Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Past</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Qualification__c.object
<CustomObject>
    <description>List of current or past Qualifications and Certifications of this Partner or Account</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Name of the account this Qualification is about</description>
        <inlineHelpText>Name of the account this Qualification is about</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N30000001rblYEAQ</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Certified_In_Area__c</fullName>
        <inlineHelpText>CRCFI - Corian Residential
ZRAMI - Zodiaq Residential Manufacturer 
ZRAZI - Zodiaq Residential Installer 
DWSRCI - CAN - Weatherization Residential 
DWSCCI - Weatherization Commercial 
DWSCCIFA - Fluid Applied</inlineHelpText>
        <label>Certified In Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CRCFI</fullName>
                </value>
                <value>
                    <fullName>ZRAMI</fullName>
                </value>
                <value>
                    <fullName>ZRAZI</fullName>
                </value>
                <value>
                    <fullName>DWSRCI</fullName>
                </value>
                <value>
                    <fullName>DWSCCI</fullName>
                </value>
                <value>
                    <fullName>DWSCCIFA</fullName>
                </value>
                <value>
                    <fullName>DWSRCI - CAN</fullName>
                </value>
                <value>
                    <fullName>AIA Speaker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Channel Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_Email__c</fullName>
        <label>Primary Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_Name__c</fullName>
        <label>Primary Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage in the lifecycle of this Qualification of this Account</description>
        <inlineHelpText>Stage in the lifecycle of this Qualification of this Account</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Approving</fullName>
                </value>
                <value>
                    <fullName>Evaluate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Qualify</fullName>
                </value>
                <value>
                    <fullName>Target</fullName>
                </value>
                <value>
                    <fullName>Candidate Nomination</fullName>
                </value>
                <value>
                    <fullName>Completed Training</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Qualfication</description>
        <inlineHelpText>Type of Qualfication</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Brand License</fullName>
                </value>
                <value>
                    <fullName>Certification</fullName>
                </value>
                <value>
                    <fullName>Community Access</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>HAP (Hazard Air Pollutants) Regulation</fullName>
                </value>
                <value>
                    <fullName>Marketing Capability</fullName>
                </value>
                <value>
                    <fullName>Marketing Certification</fullName>
                </value>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>Point Of Sale</fullName>
                </value>
                <value>
                    <fullName>Product Certification</fullName>
                </value>
                <value>
                    <fullName>Re-Certification</fullName>
                </value>
                <value>
                    <fullName>Sales Capability</fullName>
                </value>
                <value>
                    <fullName>Sales Certification</fullName>
                </value>
                <value>
                    <fullName>Sales Tool</fullName>
                </value>
                <value>
                    <fullName>Service Capability</fullName>
                </value>
                <value>
                    <fullName>Technology License</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Qualification</label>
    <nameField>
        <displayFormat>QL{YY}{MM}-{0000}</displayFormat>
        <label>Qualification Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <recordTypes>
        <fullName>BI_NA_Certification_Env</fullName>
        <active>true</active>
        <description>Record Type for envelopes in BI-NA Certification process</description>
        <label>BI-NA Certification Env</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EPass_ID__c</fullName>
        <description>Positive identification of individuals accessing DuPont computer systems.</description>
        <label>E-Pass ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>INDIA</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Grouping__c</fullName>
        <description>DuPont Business</description>
        <inlineHelpText>DuPont Business (abbrev)</inlineHelpText>
        <label>User Grouping</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>DC&amp;F</fullName>
                </value>
                <value>
                    <fullName>DPM</fullName>
                </value>
                <value>
                    <fullName>DPS</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Owning_Org__c</fullName>
        <description>Primary &quot;Owning Organisation&quot; this user belongs to</description>
        <label>User Owning Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-Env</fullName>
                </value>
                <value>
                    <fullName>BI-Surf</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>CORP-CS</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-ES</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PM</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PS</fullName>
                </value>
                <value>
                    <fullName>DPT-Aramids</fullName>
                </value>
                <value>
                    <fullName>DPT-Automotive</fullName>
                </value>
                <value>
                    <fullName>DPT-Car Protection</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP</fullName>
                </value>
                <value>
                    <fullName>DPT-NOW</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IAL</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>LEGL</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Corp Marketing</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Customer Care</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-IT</fullName>
                </value>
                <value>
                    <fullName>DPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Region__c</fullName>
        <label>User Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/productsChanged_UT.cls
@isTest(SeeAllData=true)
public class productsChanged_UT{

    static testMethod void testproductsChanged_UT() {
        Profile p1 = [select id from profile where Name='System Administrator' limit 1];
        UserRole r1= [Select id from UserRole where Name='PS CRM' limit 1];
        User u1 = new User(LastName='abc',UserRoleId=r1.Id,ProfileId=p1.Id,Alias='test123',EmailEncodingKey='UTF-8',TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',LanguageLocaleKey='en_US',Email='Naga_Neelam@Infosys.com',UserName='Naga_Neelam@Infosys.com.test', EPass_ID__c='ib2423',User_Owning_Org__c='CORP',User_Country__c='INDIA',User_Grouping__c='CORP',User_Region__c='Asia Pacific');
        insert u1;
    Final Id Rec1=RType.getIdByDevName('Qualification__c','BI_NA_Certification_Env');
     System.runAs(u1){
     Test.startTest();
    
        Account abc = new Account(Name='TestAccount', Site='INDIA', Type='Customer', BI_Account_SubType__c = 'Distribution', Account_Stage__c = 'Active', Country__c = 'UNITED STATES', Owning_Organization__c = 'BI-Env', ShippingStreet = 'Electronics City', ShippingCity = 'Bengaluru', ShippingState = 'Karnataka', ShippingPostalCode = '560100', ShippingCountry = 'INDIA');
        insert abc;
        ApexPages.currentPage().getParameters().put('accid', abc.id);
        
        Qualification__c q1 = new Qualification__c(Account_Name__c = abc.id, Certified_In_Area__c = 'DWSRCI', Primary_Contact_Name__c = 'xyz', Primary_Contact_Email__c = 'naga.neelam@infosys.com', Type__c = 'Certification', Stage__c = 'Completed Training', Channel_Manager__c = u1.id, Training_Completed__c = 'DuPont™ StraightFlash™', Products_Changed__c=false, RecordTypeId = Rec1);

        insert q1;

        Qualification__c q2 = new Qualification__c(Account_Name__c = abc.id, Certified_In_Area__c = 'DWSRCI', RecordTypeId =Rec1, Primary_Contact_Name__c = 'NAGA', Primary_Contact_Email__c = 'Naga_Neelam@Infosys.com', Type__c = 'Certification', Stage__c = 'Complete', Channel_Manager__c = u1.id, Training_Completed__c = 'DuPont™ StraightFlash™', Products_Changed__c=true);
        insert q2;
        
        ProductsChanged ProdsChanged = new ProductsChanged(new ApexPages.StandardController(q2));
        ProdsChanged.getisProductButtonDisabled();
        ProdsChanged.geturlForTriggeringDDP();
        ProdsChanged.urlForTriggeringDDP();
        
        
        Qualification__c q3 = new Qualification__c(Account_Name__c = abc.id, Certified_In_Area__c = 'DWSRCI', RecordTypeId = rec1, Primary_Contact_Name__c = 'NAGA', Primary_Contact_Email__c = 'Naga_Neelam@Infosys.com', Type__c = 'Certification', Stage__c = 'Complete', Channel_Manager__c = u1.id, Training_Completed__c = 'DuPont™ StraightFlash™', Products_Changed__c=false);
        insert q3;
        
        ProductsChanged ProdsChanged3 = new ProductsChanged (new ApexPages.StandardController(q3));
        
    Test.stopTest();     
    
    }
  }
}