DuPont DevSB/src/objects/Application__c.object
<CustomObject>
    <description>The main object that represents a custom unit of work that will drive an Estimate</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Applications Description</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>Application that is not in production</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Issue__c.object
<CustomObject>
    <description>Object used to submit and track Issues, Ideas, Questions, or Requests for SFDC Administration Team.  Also used for Data Modelling and Project Issues.</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>This contains the SFDC application (eg CUPS, CLS, etc.) that this Issue relates to. This field should not contain any non-SFDC related applications.</description>
        <inlineHelpText>Fill the related SFDC Application for this issue. If the Issue is not specific to an application or a Standard functionality then select &apos;CRM (Standard Functionality)&apos;</inlineHelpText>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI-EMEA Complaint Handling</fullName>
                </value>
                <value>
                    <fullName>BI-EMEA E-registration for Montelli</fullName>
                </value>
                <value>
                    <fullName>BI EMEA E-Warranty</fullName>
                </value>
                <value>
                    <fullName>CRM (Standard functionality)</fullName>
                </value>
                <value>
                    <fullName>Customer On-boarding</fullName>
                </value>
                <value>
                    <fullName>Customer Service Console</fullName>
                </value>
                <value>
                    <fullName>Digital Sales Aid - iPad App</fullName>
                </value>
                <value>
                    <fullName>DIMC Call handling</fullName>
                </value>
                <value>
                    <fullName>DocuSign/Drawloop</fullName>
                </value>
                <value>
                    <fullName>DPS-CIC Interface</fullName>
                </value>
                <value>
                    <fullName>DPS-CP for Salesforce</fullName>
                </value>
                <value>
                    <fullName>DPS GetFeedback</fullName>
                </value>
                <value>
                    <fullName>DPS Kevlar Automotive Hose Selector</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP Value Chain Service</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP Value Chain Service Platform</fullName>
                </value>
                <value>
                    <fullName>DPT Nomex Portal</fullName>
                </value>
                <value>
                    <fullName>Electric Arc</fullName>
                </value>
                <value>
                    <fullName>Eloqua</fullName>
                </value>
                <value>
                    <fullName>EMEA-DPT Lead Scoring</fullName>
                </value>
                <value>
                    <fullName>Global Dealer/Locator</fullName>
                </value>
                <value>
                    <fullName>Partner Portal</fullName>
                </value>
                <value>
                    <fullName>Price Approval</fullName>
                </value>
                <value>
                    <fullName>Product Finder</fullName>
                </value>
                <value>
                    <fullName>Product Scheduling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Issue__c</fullName>
        <displayFormat>IS ID-{00000000}</displayFormat>
        <label>Issue #</label>
        <type>AutoNumber</type>
    </fields>
    <label>Issue</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Describes special user or access information</description>
        <label>Description</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/emailPQRInbound.cls
/**
 * Email services are automated processes that use Apex classes
 * to process the contents, headers, and attachments of inbound
 * email.
 * // 1/13/2017 - Merge&Spin - Added Application field value
 */
global class emailPQRInbound implements Messaging.InboundEmailHandler {

//use label not name????
public static final string ISSUE_RTYPEID = Issue__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Issues and Ideas').recordTypeId;


    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        handleInboundEmail(email);
        // Always set the result to true. No need to send an email back to the user 
        Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
        result.success = true;
        // Return the result for the Apex Email Service
        return result;
    }
    
 private void handleInboundEmail(Messaging.inboundEmail email)  {
        
        //Add Issue
        Issue__c iss = new Issue__c();
        if (email.plainTextBody != null) iss.Description__c = email.plainTextBody;
        if (email.subject != null)  {   if (email.subject.length()>80)
                                            iss.name = email.subject.substring(0,79);
                                        else 
                                            iss.name = email.subject;
        } else                          iss.name = 'No Subject';
        if (ISSUE_RTYPEID != null)  iss.recordTypeId = ISSUE_RTYPEID;
     // 1/13/2017 - Merge&Spin - Added Application field value
        iss.Application__c = 'CRM (Standard functionality)';
        //if (OwnerId != null)          xtIER.Contact__c = ContactId;//OwnerId = contacts[0].OwnerId    
        insert iss;
        
        EmailLib.AttachAttachments(iss.Id, email);
        EmailLib.AttachHtmlBody(iss.Id, email.htmlBody);    
        
 }

/*********************************************************************************************************  
**********************************************************************************************************/
    
  static testMethod void test1() {
    
    Test.startTest();
    EmailLib.CreateTestEmail(new emailPQRInbound(),'testPQR@dupont.com','long subject, long subject, long subject, long subject, long subject, long subject , long subject , long subject ');   
    EmailLib.CreateTestEmail(new emailPQRInbound(),'testPQR@dupont.com');   
    EmailLib.CreateTestEmail(new emailPQRInbound(),'testPQR@dupont.com',null); //no subject
    Test.stopTest();
    }
    


}