DuPont DevSB/src/objects/Application__c.object
<CustomObject>
    <description>The main object that represents a custom unit of work that will drive an Estimate</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Applications Description</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Used Fully</fullName>
                </value>
                <value>
                    <fullName>Partially Used</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Offline</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>Application that is not in production</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Batch_Monitor__c.object
<CustomObject>
    <fields>
        <fullName>AsyncApexJob_Id__c</fullName>
        <label>AsyncApexJob Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Batch_Job_Error__c</fullName>
        <label>Batch Job Error</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SFDC_Instance__c</fullName>
        <label>SFDC Instance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>related_Issue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>related Issue</label>
        <referenceTo>Issue__c</referenceTo>
        <relationshipLabel>Batch Monitors</relationshipLabel>
        <relationshipName>Batch_Monitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Batch Monitor</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Monitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Issue__c.object
<CustomObject>
    <description>Object used to submit and track Issues, Ideas, Questions, or Requests for SFDC Administration Team.  Also used for Data Modelling and Project Issues.</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>This contains the SFDC application (eg CUPS, CLS, etc.) that this Issue relates to. This field should not contain any non-SFDC related applications.</description>
        <inlineHelpText>Fill the related SFDC Application for this issue. If the Issue is not specific to an application or a Standard functionality then select &apos;CRM (Standard Functionality)&apos;</inlineHelpText>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI-EMEA Complaint Handling</fullName>
                </value>
                <value>
                    <fullName>BI-EMEA E-registration for Montelli</fullName>
                </value>
                <value>
                    <fullName>BI EMEA E-Warranty</fullName>
                </value>
                <value>
                    <fullName>CRM (Standard functionality)</fullName>
                </value>
                <value>
                    <fullName>Customer On-boarding</fullName>
                </value>
                <value>
                    <fullName>Customer Service Console</fullName>
                </value>
                <value>
                    <fullName>Digital Sales Aid - iPad App</fullName>
                </value>
                <value>
                    <fullName>DIMC Call handling</fullName>
                </value>
                <value>
                    <fullName>DocuSign/Drawloop</fullName>
                </value>
                <value>
                    <fullName>DPS-CIC Interface</fullName>
                </value>
                <value>
                    <fullName>DPS-CP for Salesforce</fullName>
                </value>
                <value>
                    <fullName>DPS GetFeedback</fullName>
                </value>
                <value>
                    <fullName>DPS Kevlar Automotive Hose Selector</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP Value Chain Service</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP Value Chain Service Platform</fullName>
                </value>
                <value>
                    <fullName>DPT Nomex Portal</fullName>
                </value>
                <value>
                    <fullName>Electric Arc</fullName>
                </value>
                <value>
                    <fullName>Eloqua</fullName>
                </value>
                <value>
                    <fullName>EMEA-DPT Lead Scoring</fullName>
                </value>
                <value>
                    <fullName>Global Dealer/Locator</fullName>
                </value>
                <value>
                    <fullName>Partner Portal</fullName>
                </value>
                <value>
                    <fullName>Price Approval</fullName>
                </value>
                <value>
                    <fullName>Product Finder</fullName>
                </value>
                <value>
                    <fullName>Product Scheduling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adhoc</fullName>
                </value>
                <value>
                    <fullName>Correct (Break/Fix)</fullName>
                </value>
                <value>
                    <fullName>Data migration/Go-live</fullName>
                </value>
                <value>
                    <fullName>Enhance (Design)</fullName>
                </value>
                <value>
                    <fullName>Routine</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Issue__c</fullName>
        <displayFormat>IS ID-{00000000}</displayFormat>
        <label>Issue #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Related_Issue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Issue related to this issue</description>
        <label>Related Issue</label>
        <referenceTo>Issue__c</referenceTo>
        <relationshipLabel>Related Issues</relationshipLabel>
        <relationshipName>Related_Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFDC_Instance__c</fullName>
        <description>The SFDC Organizational Instance associated with this Issue</description>
        <inlineHelpText>Please select the SFDC Organizational instance (or environment) associated with this Issue.</inlineHelpText>
        <label>SFDC Instance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CRM</fullName>
                    <default>true</default>
                    <label>CRM</label>
                </value>
                <value>
                    <fullName>Utility (PA)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <color>#0B6FCE</color>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                    <color>#78C953</color>
                    <label>Accepted</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <color>#E27001</color>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>DuPont Review</fullName>
                    <color>#A845DC</color>
                    <label>DuPont Review</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                    <color>#F3D904</color>
                    <label>On Hold</label>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                    <color>#A53711</color>
                    <label>Waiting</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <color>#33FF33</color>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                    <color>#FF0000</color>
                    <label>Escalated</label>
                </value>
                <value>
                    <fullName>Reassigned</fullName>
                    <color>#419249</color>
                    <label>Reassigned</label>
                </value>
                <value>
                    <fullName>Approved by Review Team</fullName>
                    <color>#B6E32E</color>
                    <label>Approved by Review Team</label>
                </value>
                <value>
                    <fullName>Not Applicable/System Hard Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Category or type of issue, idea, request, or risk</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Analytics-Reporting</fullName>
                </value>
                <value>
                    <fullName>Analytics-Tagging</fullName>
                </value>
                <value>
                    <fullName>Approval Process</fullName>
                </value>
                <value>
                    <fullName>Architecture Review</fullName>
                </value>
                <value>
                    <fullName>Audit IT Controls</fullName>
                </value>
                <value>
                    <fullName>Business Process</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Charts &amp; Dashboards</fullName>
                </value>
                <value>
                    <fullName>Connect for Lotus Notes</fullName>
                </value>
                <value>
                    <fullName>Connect Offline</fullName>
                </value>
                <value>
                    <fullName>Content</fullName>
                </value>
                <value>
                    <fullName>Content-Data</fullName>
                </value>
                <value>
                    <fullName>Content-Image</fullName>
                </value>
                <value>
                    <fullName>Content-Text</fullName>
                </value>
                <value>
                    <fullName>Content-Tool</fullName>
                </value>
                <value>
                    <fullName>Content-Translations</fullName>
                </value>
                <value>
                    <fullName>Content-Video</fullName>
                </value>
                <value>
                    <fullName>CRM Content</fullName>
                </value>
                <value>
                    <fullName>CRM-Data</fullName>
                </value>
                <value>
                    <fullName>CRM-Integration</fullName>
                </value>
                <value>
                    <fullName>CRM-Tool</fullName>
                </value>
                <value>
                    <fullName>Custom Design</fullName>
                </value>
                <value>
                    <fullName>Data</fullName>
                </value>
                <value>
                    <fullName>Data Model</fullName>
                </value>
                <value>
                    <fullName>Data Model - Field</fullName>
                </value>
                <value>
                    <fullName>Data Model - Picklist</fullName>
                </value>
                <value>
                    <fullName>Data Model Review</fullName>
                </value>
                <value>
                    <fullName>Design Review</fullName>
                </value>
                <value>
                    <fullName>Desktop Settings</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Issue</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Describes special user or access information</description>
        <label>Description</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/batch_jobMonitoring.cls
/*****************************************************************************
Author: Rohit saini
Email: rohitkumar.saini@tcs.com
Date: 1/19/2016
Description: class to monitor job failures, to create batch monitor object record and to create issue for batch failure.
@version  1.0

<VL20160920>
Last Modified By    :   Vijay Laxmi
Last Modified Date  :   20 Sep 2016
Description         :   Adding a field name (SFDC_Instance__c) to batch monitor object 

********************************************************************************/


global class batch_jobMonitoring implements Schedulable, Database.Batchable<sObject> {
    public static final Integer batchJobSize=2;
    public static final string sfdcInstance=label.Current_Org_SFDC_Instance; //'One DuPont Corporate';
    public static final string RTYPE_ISSUE = Rtype.getIdByDevName('Issue__c','DuPont Administration');
    public static final Id systemAdminId=[select id, name from user where name ='BatchSFDC DeployUser' limit 1].id;
   public static final Id sfdcAdminQueueId=[select id, DeveloperName from group where DeveloperName = 'SFDCAdminSupport' limit 1].id;
    global void execute(SchedulableContext SC) {
          Id batchJobId = Database.executeBatch(new batch_jobMonitoring(), batchJobSize);
        }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        DateTime lastRun=system.now()-7;
        List<Batch_Monitor__c> lstExistingbatchMonitor= [select id, name, createdDate from Batch_Monitor__c order by createdDate desc];
        if(lstExistingbatchMonitor!=null && lstExistingbatchMonitor.size()>0){
            lastRun=lstExistingbatchMonitor.get(0).createdDate;
        }
        //system.debug('lastRun::'+lastRun);
        String queryString='select id, TotalJobItems, status, NumberOfErrors, MethodName, JobType, JobItemsProcessed, ExtendedStatus, CompletedDate,'+
            'ApexClassID,ApexClass.Name from asyncApexjob where (status=\'failed\' or ExtendedStatus!=null or NumberOfErrors>0 ) and CompletedDate > :lastRun and JobType in (\'BatchApex\', \'ScheduledApex\')';
        if(Test.isrunningTest()){
           queryString='select id, TotalJobItems, status, NumberOfErrors, MethodName, JobType, JobItemsProcessed, ExtendedStatus, CompletedDate,'+
            'ApexClassID, ApexClass.Name from asyncApexjob limit 2';
       }
       return Database.getQueryLocator(queryString);
    }
    public void execute(Database.BatchableContext BC, List<sObject> Scope){
        List<AsyncApexjob> failedjobs=(List<AsyncApexjob>)Scope;
        List<Batch_Monitor__c> lstNewbatchMonitor=new  List<Batch_Monitor__c>();
        for(AsyncApexjob job: failedjobs){
            lstNewbatchMonitor.add(createBatchMonitor(job));
        }
        insert lstNewbatchMonitor;
        
        /*
            Map<Issue__c, Batch_Monitor__c> issueBMMap= createIssues(lstNewbatchMonitor);
           if(issueBMMap!=null && issueBMMap.Keyset()!=null && issueBMMap.Keyset().size()>0){
          Map<string, Batch_Monitor__c> IssuestringBMMap= new Map<string, Batch_Monitor__c>() ;
           for(Issue__c issue: issueBMMap.keySet()){
            IssuestringBMMap.put(issue.name+issue.Description__c, issueBMMap.get(issue));  
           }
            List <Issue__c> listIssues=new List<Issue__c>();
            listIssues.addAll(issueBMMap.Keyset());
           insert listIssues;
      
           for(Issue__c issue: listIssues){
             IssuestringBMMap.get(issue.name+issue.Description__c).related_issue__c=issue.id;
         }
         update  IssuestringBMMap.values();

        }*/
        
    }
    public void finish(Database.BatchableContext BC){
        
     }
   
    Batch_Monitor__c createBatchMonitor(AsyncApexjob job){
        Batch_Monitor__c bm=new Batch_Monitor__c();
        bm.name='Error in ';
        if(job.ApexClass.name!=null){
           bm.name+='class: '+job.ApexClass.name; 
        }
        if(job.MethodName!=null){
           bm.name+=' method name: '+job.MethodName; 
        }
        bm.name=(bm.name.length()>80?bm.name.substring(0,79): bm.name);
                
        if(job.ExtendedStatus!=null){
            bm.Batch_Job_Error__c=(job.ExtendedStatus.length()>255?job.ExtendedStatus.substring(0,254): job.ExtendedStatus);
        }
        
        if(job.Id!=null){
            bm.AsyncApexJob_Id__c=job.Id;
        }
        
        bm.Status__c=job.status;
          //<Start> <VL20160920>
        bm.SFDC_Instance__c=sfdcInstance;
        //<End> <VL20160920>
        bm.Description__c='method name: '+job.MethodName+
            ',\r\n class name: '+ job.ApexClass.name+
            ',\r\n TotalJobItems:'+job.TotalJobItems+
            ',\r\n JobItemsProcessed:'+job.JobItemsProcessed+
            ',\r\n NumberOfErrors:'+job.NumberOfErrors+
            ',\r\n JobType:'+job.JobType+
            ',\r\n CompletedDate:'+job.CompletedDate+
            ',\r\n Exception: '+ job.ExtendedStatus;
        bm.Description__c=bm.Description__c.length()>32768?bm.Description__c.substring(0, 32767):bm.Description__c;
          return bm;
          
    }
    
  /*Map<Issue__c, Batch_Monitor__c> createIssues( List<Batch_Monitor__c> lstNewbatchMonitor){
    List<String> lstSubjects=new List<String>();
      for(Batch_Monitor__c bm: lstNewbatchMonitor){
          string s='Batch Job Failure ';
          if(bm.name!=null){
              s+=bm.name;
              s=(s.length()>80?s.substring(0, 79):s);
              
             system.debug('s::'+s);

              lstSubjects.add(s);
          }
      }
         
      List<Issue__c> existingIssues=[select id, name from issue__c where name in :lstSubjects and status__c!='Completed'];
      Set<String> setSubject=new Set<String> ();
      for(Issue__c issue: existingIssues){
          setSubject.add(issue.name);
          system.debug('::'+issue.name);

      }
      List<Batch_Monitor__c> toProcess=new List<Batch_Monitor__c>();
      for(Batch_Monitor__c bm: lstNewbatchMonitor){
          string issueName='Batch Job Failure '+bm.name;
          system.debug('issueName'+issueName);
          if(!setSubject.contains(issueName.length()>80?issueName.substring(0, 79):issueName)){
              toProcess.add(bm);
              system.debug('issueName'+issueName);
          }
      }
     
      Map<Issue__c, Batch_Monitor__c> issueToBatchMonitorMap=new Map<Issue__c, Batch_Monitor__c>();
        for(Batch_Monitor__c bm: toProcess){
          issueToBatchMonitorMap.put(createIssue(bm), bm); 
        }
        return issueToBatchMonitorMap;
    }
    
      Issue__c createIssue(Batch_Monitor__c bm){
    Issue__c issue = new Issue__c();
    issue.SFDC_Instance__c=sfdcInstance;
    issue.Type__c='Other';
    issue.Classification__c= 'Correct (Break/Fix)'; 
    issue.Status__c='Not started';
    issue.RecordTypeId=RTYPE_ISSUE;
    issue.Severity__c='Medium';
    issue.Application__c='CRM(Standard functionality)';
    issue.Name='Batch Job Failure ';
    if(bm.name!=null){
      issue.Name+=bm.name;
    }
    issue.Name=(issue.Name.length()>80?issue.Name.substring(0, 79):issue.Name);
    issue.Description__c=bm.Description__c+'\r\n\r\n Batch monitor record id:'+bm.Id;
    issue.Submitted_By__c=systemAdminId;
    issue.Submitted_DateTime__c=Date.Today();
    issue.ownerid=sfdcAdminQueueId;  
    return issue;  
      
    }*/
    
    
}