DuPont DevSB/src/objects/BA_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BAC_Currency__c</fullName>
        <label>BAC Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BAC_Progress__c</fullName>
        <label>BAC Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Campaigns</fullName>
                </value>
                <value>
                    <fullName>Requirements Commenced</fullName>
                </value>
                <value>
                    <fullName>Specifications Generated</fullName>
                </value>
                <value>
                    <fullName>Solutioning Started</fullName>
                </value>
                <value>
                    <fullName>Solutions Created</fullName>
                </value>
                <value>
                    <fullName>Pricing Completed</fullName>
                </value>
                <value>
                    <fullName>Commercials Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Body_Armor_Configuration_ID__c</fullName>
        <externalId>true</externalId>
        <label>Body Armor Configuration ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Budget_for_Year_1__c</fullName>
        <label>Budget Year 1</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_for_Year_2__c</fullName>
        <label>Budget Year 2</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_for_Year_3__c</fullName>
        <label>Budget Year 3</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Closure_Reason__c</fullName>
        <label>Closure Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract awarded to DuPont / Partner and fulfilled</fullName>
                </value>
                <value>
                    <fullName>Contract awarded to competitor</fullName>
                </value>
                <value>
                    <fullName>Tender differed / postponed</fullName>
                </value>
                <value>
                    <fullName>Tender Cancelled</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Closure_Remark__c</fullName>
        <label>Closure Remark</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Created_by_IOS__c</fullName>
        <label>Created by (IOS)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_date_IOS__c</fullName>
        <label>Created date (IOS)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_User_Country__c</fullName>
        <label>End User Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Name__c</fullName>
        <label>End User Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Region__c</fullName>
        <label>End User Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Helmets__c</fullName>
        <label>Number of Helmets (Total)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Helmets_Y1__c</fullName>
        <label>Number of Helmets Y1</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Helmets_Y2__c</fullName>
        <label>Number of Helmets Y2</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Helmets_Y3__c</fullName>
        <label>Number of Helmets Y3</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Plates_Y1__c</fullName>
        <label>Number of Plates Y1</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Plates_Y2__c</fullName>
        <label>Number of Plates Y2</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Plates_Y3__c</fullName>
        <label>Number of Plates Y3</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Plates__c</fullName>
        <label>Number of Plates (Total)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Vest_Y1__c</fullName>
        <label>Number of Vest Y1</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Vest_Y2__c</fullName>
        <label>Number of Vest Y2</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Vest_Y3__c</fullName>
        <label>Number of Vest Y3</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Vest__c</fullName>
        <label>Number of Vest (Total)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sensitive_Destination_Committee_Approv__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sensitive Destination Committee Approv.</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre- Tender Solicitation</fullName>
                </value>
                <value>
                    <fullName>Tender in progress</fullName>
                </value>
                <value>
                    <fullName>Tender Bid Submissions</fullName>
                </value>
                <value>
                    <fullName>Solutions Evaluation</fullName>
                </value>
                <value>
                    <fullName>Tender Contract Award</fullName>
                </value>
                <value>
                    <fullName>Campaign Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Budget__c</fullName>
        <label>Total Budget</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>last_modified_date_IOS__c</fullName>
        <label>last modified date (iOS)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>last_modify_by_IOS__c</fullName>
        <label>last modify by (IOS)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>technicalOfferSubmissionDate__c</fullName>
        <label>technicalOfferSubmissionDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>tenderSubmissionDate__c</fullName>
        <label>tenderSubmissionDate</label>
        <type>DateTime</type>
    </fields>
    <label>BA Configuration</label>
    <nameField>
        <label>BA Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/BAC_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BA_Configuration__c</fullName>
        <label>BA Configuration</label>
        <referenceTo>BA_Configuration__c</referenceTo>
        <relationshipName>BAC_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BAC_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA Team Member</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/CtrlSaveBodyArmorConfigurationDetails.cls
/*******************************************************************************
(C)2015
Author: krishnaveni duggaraju
Email: krishnaveni.duggaraju@tcs.com
Description:  This class insers the all BodyArmorConfiguration.



 ********************************************************************************/

@RestResource(urlMapping = '/SaveBAC/*')
global class CtrlSaveBodyArmorConfigurationDetails{

public class bacWrapperClass
{
    Public BA_Configuration__c bac;
    Public String Name;
    Public Boolean Active;
    Public String BAC_Progress;
    Public String BodyArmorConfigurationID;
    Public Integer Budget_for_Year_1;
    Public Integer Budget_for_Year_2;
    Public Integer  Budget_for_Year_3;
    Public String Closure_Reason;
    Public String Closure_Remark;
    Public String Created_by_IOS;
    Public DateTime Created_date_IOS;
    Public Date End_Date;
    Public String End_User_Country;
    Public String End_User_Region;
    Public String End_User_Name;
    Public DateTime last_modified_date_IOS;
    Public String last_modify_by_IOS;
    Public Integer No_of_Helmets;
    Public Integer Number_of_Plates;
    Public Integer Number_of_Helmets_Y1;
    Public Integer Number_of_Helmets_Y2;
    Public Integer Number_of_Helmets_Y3;
    Public Integer Number_of_Plates_Y1;
    Public Integer Number_of_Plates_Y2;
    Public Integer Number_of_Plates_Y3;
    Public Integer Number_of_Vest;
    Public Integer Number_of_Vest_Y1;
    Public Integer Number_of_Vest_Y2;
    Public Integer Number_of_Vest_Y3;
   // Public String Phase;
    Public Date Start_Date;
    Public String Status;
    Public Integer Total_Budget;
    Public String teamMemberUserId;
    Public Boolean Sensitive_country_flag;
    Public String Sensitive_country_Comment;
    Public String CurrencyIsoCode;
    Public DateTime tenderSubmissionDate;
    Public DateTime technicalOfferSubmissionDate;
}


    @HttpPost
    global static CtrlKevlarSvcHelper.ReturnDropDownClass doPost() {
        CtrlKevlarSvcHelper h = new CtrlKevlarSvcHelper();
        List<bacWrapperClass> bwcList = new List<bacWrapperClass>();
        List<string> teamMembers= null;
        String rJSON;
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        try{ 
            system.debug('req.requestBody : ' + req.requestBody.toString());
            List<bacWrapperClass> bacList= (List<bacWrapperClass>) JSON.deserialize(req.requestBody.toString(), List<bacWrapperClass>.class);
            List<BA_Configuration__c> newBAC = new List<BA_Configuration__c>();
            for(bacWrapperClass qt : bacList){        
                BA_Configuration__c bac = new BA_Configuration__c();
                bac.name= qt.name;
                bac.Active__c= qt.Active;
                bac.BAC_Progress__c = qt.BAC_Progress;
                bac.Body_Armor_Configuration_ID__c  = qt.BodyArmorConfigurationID;
                bac.Budget_for_Year_1__c= qt.Budget_for_Year_1;
                bac.Budget_for_Year_2__c= qt.Budget_for_Year_2;
                bac.Budget_for_Year_3__c= qt.Budget_for_Year_3;
                bac.Closure_Reason__c= qt.Closure_Reason;
                bac.Closure_Remark__c= qt.Closure_Remark;
                bac.Created_by_IOS__c= qt.Created_by_IOS;
                bac.Created_date_IOS__c= qt.Created_date_IOS;
                bac.End_Date__c= qt.End_Date;
                bac.End_User_Name__c= qt.End_User_Name;             
                bac.End_User_Country__c= qt.End_User_Country;
                bac.End_User_Region__c= qt.End_User_Region;
                bac.last_modified_date_IOS__c= qt.last_modified_date_IOS;
                bac.last_modify_by_IOS__c= qt.last_modify_by_IOS; 
                bac.No_of_Helmets__c= qt.No_of_Helmets;           
                bac.Number_of_Helmets_Y1__c= qt.Number_of_Helmets_Y1;
                bac.Number_of_Helmets_Y2__c= qt.Number_of_Helmets_Y2;
                bac.Number_of_Helmets_Y3__c= qt.Number_of_Helmets_Y3;
                bac.Number_of_Plates__c= qt.Number_of_Plates;
                bac.Number_of_Plates_Y1__c= qt.Number_of_Plates_Y1;
                bac.Number_of_Plates_Y2__c= qt.Number_of_Plates_Y2;
                bac.Number_of_Plates_Y3__c= qt.Number_of_Plates_Y3;
                bac.Number_of_Vest__c= qt.Number_of_Vest;
                bac.Number_of_Vest_Y1__c= qt.Number_of_Vest_Y1;
                bac.Number_of_Vest_Y2__c= qt.Number_of_Vest_Y2;
                bac.Number_of_Vest_Y3__c = qt.Number_of_Vest_Y3;         
                bac.Start_Date__c= qt.Start_Date;
                bac.Status__c= qt.Status;
                bac.Total_Budget__c = qt.Total_Budget;
                bac.Sensitive_Destination_Committee_Approv__c = qt.Sensitive_country_flag;
                bac.Comment__c= qt.Sensitive_country_Comment;
                bac.BAC_Currency__c = qt.CurrencyIsoCode;
                bac.tenderSubmissionDate__c = qt.tenderSubmissionDate;
                bac.technicalOfferSubmissionDate__c = qt.technicalOfferSubmissionDate;
                
                //start
                if(qt.teamMemberUserId != null){
                teamMembers = qt.teamMemberUserId.split(';');
                    for(String tm : teamMembers){
                        bacWrapperClass bwc = new bacWrapperClass();
                        bwc.bac = bac;
                        bwc.teamMemberUserId = tm;             
                        bwcList.add(bwc);
                    }
                }
                //end           
               newBAC.add(bac); 
            }
            upsert newBAC Body_Armor_Configuration_ID__c;
            //database.insert(newBAC);
            //starts TM code
            if(!bwcList.isEmpty()){
                List<BAC_Team_Member__c> tmList = new List<BAC_Team_Member__c>();
                for(bacWrapperClass bb : bwcList){
                    BAC_Team_Member__c bacTM = new BAC_Team_Member__c();
                    bacTM.BA_Configuration__c = bb.bac.Id;
                    bacTM.Team_Member_Name__c = bb.teamMemberUserId;
                    tmList.add(bacTM);
                }
                database.insert(tmList);
            }     
            List<String> result = new List<String>();
            result.add('Success');       
            system.debug('SaveBodyArmorConfiguration result : ' +newBAC );
            return new CtrlKevlarSvcHelper.ReturnDropDownClass(h.dataSent, h.getMessage('200'),h.getResponseMessage('508'),'508',result, null, 'No Error'); 
         }
         catch(Exception e){
         	system.debug('Error----------'+e.getMessage());
            return new CtrlKevlarSvcHelper.ReturnDropDownClass(h.dataNotSent, h.getMessage('203'),'Insert or Update failed!',null, null, null, '203');
         }
    }
}