DuPont DevSB/src/objects/BA_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BAC_Progress__c</fullName>
        <label>BAC Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Campaigns</fullName>
                </value>
                <value>
                    <fullName>Requirements Commenced</fullName>
                </value>
                <value>
                    <fullName>Specifications Generated</fullName>
                </value>
                <value>
                    <fullName>Solutioning Started</fullName>
                </value>
                <value>
                    <fullName>Solutions Created</fullName>
                </value>
                <value>
                    <fullName>Pricing Completed</fullName>
                </value>
                <value>
                    <fullName>Commercials Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre- Tender Solicitation</fullName>
                </value>
                <value>
                    <fullName>Tender in progress</fullName>
                </value>
                <value>
                    <fullName>Tender Bid Submissions</fullName>
                </value>
                <value>
                    <fullName>Solutions Evaluation</fullName>
                </value>
                <value>
                    <fullName>Tender Contract Award</fullName>
                </value>
                <value>
                    <fullName>Campaign Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BA Configuration</label>
    <nameField>
        <label>BA Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Body_Armor_Solution__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BA_Configuration__c</fullName>
        <label>BA Configuration</label>
        <referenceTo>BA_Configuration__c</referenceTo>
        <relationshipName>Body_Armor_Solutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BP_BM_Areal_Density__c</fullName>
        <label>BP BM Areal Density</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BP_Comment__c</fullName>
        <label>BP Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BP_Plate_Solution_Thickness__c</fullName>
        <label>BP Plate Solution Thickness</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BP_Weight__c</fullName>
        <label>BP Weight</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BP_areal_density__c</fullName>
        <label>BP areal density</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BP_tile_Thickness__c</fullName>
        <label>BP tile thickness</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Backing_Material_BP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Backing Material BP</label>
        <referenceTo>Material_Master__c</referenceTo>
        <relationshipName>Body_Armor_Solutions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Backing_Material_FP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Backing Material FP</label>
        <referenceTo>Material_Master__c</referenceTo>
        <relationshipName>Body_Armor_Solutions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Backing_Material_SP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Backing Material SP</label>
        <referenceTo>Material_Master__c</referenceTo>
        <relationshipName>Body_Armor_Solutions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Backing_layers_BP__c</fullName>
        <label>No. of backing layers BP</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Backing_layers_FP__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of backing layers FP</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Backing_layers_SP__c</fullName>
        <label>No. of backing layers SP</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Body_Armor_Solution_ID_iOS__c</fullName>
        <externalId>true</externalId>
        <label>Body Armor Solution ID iOS</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FP_BM_Areal_Density__c</fullName>
        <label>FP BM Areal Density</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FP_Comment__c</fullName>
        <label>FP Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FP_Plate_Solution_Thickness__c</fullName>
        <label>FP Plate Solution Thickness</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FP_Weight__c</fullName>
        <label>FP Weight</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FP_areal_density__c</fullName>
        <label>FP areal density</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FP_tile_Thickness__c</fullName>
        <label>FP tile thickness</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Material_Master_BP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material Master BP</label>
        <referenceTo>Material_Master__c</referenceTo>
        <relationshipLabel>BA Solutions (Material Master BP)</relationshipLabel>
        <relationshipName>Body_Armor_Solutions_BP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Material_Master_FP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material Master FP</label>
        <referenceTo>Material_Master__c</referenceTo>
        <relationshipLabel>BA Solutions (Material Master FP)</relationshipLabel>
        <relationshipName>Body_Armor_Solution_FP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Material_Master_SP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material Master SP</label>
        <referenceTo>Material_Master__c</referenceTo>
        <relationshipLabel>BA Solutions (Material Master SP)</relationshipLabel>
        <relationshipName>Body_Armor_Solutions_SP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No_Of_Layers_BP__c</fullName>
        <label>No Of Layers BP</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Layers_FP__c</fullName>
        <label>No Of Layers FP</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Layers_SP__c</fullName>
        <label>No Of Layers SP</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SP_BM_Areal_Density__c</fullName>
        <label>SP BM Areal Density</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SP_Comment__c</fullName>
        <label>SP Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SP_Plate_Solution_Thickness__c</fullName>
        <label>SP Plate Solution Thickness</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SP_Weight__c</fullName>
        <label>SP Weight</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SP_areal_density__c</fullName>
        <label>SP areal density</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SP_tile_thickness__c</fullName>
        <label>SP tile thickness</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_weight_of_L_size__c</fullName>
        <label>Total weight of L size</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_weight_of_M_size__c</fullName>
        <label>Total weight of M size</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_weight_of_S_size__c</fullName>
        <label>Total weight of S size</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_weight_of_XL_size__c</fullName>
        <label>Total weight of XL size</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_weight_of_XS_size__c</fullName>
        <label>Total weight of XS size</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_weight_of_XXL_size__c</fullName>
        <label>Total weight of XXL size</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>BA Solution</label>
    <nameField>
        <label>Solution  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Material_Master__c.object
<CustomObject>
    <fields>
        <fullName>Material_Type__c</fullName>
        <label>Material Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>HAP</fullName>
                </value>
                <value>
                    <fullName>HAP backing Material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BA Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Materials</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Material_Type__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_Layers__c</fullName>
        <label>Number of Layers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Material__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BA Material Master</label>
        <referenceTo>Material_Master__c</referenceTo>
        <relationshipLabel>BA Materials Types</relationshipLabel>
        <relationshipName>Materials_Type</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA Material Type</label>
    <nameField>
        <label>Select Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Material Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/CtrlPopulateHAPSolutionService_UT.cls
/*******************************************************************************
(C)2016
Author: krishnaveni duggaraju
Email: krishnaveni.duggaraju@tcs.com
Description:  This class tests the CtrlPopulateHAPSolutionService.
 ********************************************************************************/
@isTest
private class CtrlPopulateHAPSolutionService_UT {
   
    public static Kevlar_Response_Messages__c m1,m2,m3,m4;
    public static List<Kevlar_Response_Messages__c> InsertList = new List<Kevlar_Response_Messages__c>();
    public static Body_Armor_Solution__c bas,bas1;
    public static List<Body_Armor_Solution__c> basList = new List<Body_Armor_Solution__c>();
    public static List<Material_Type__c> mtypeList = new List<Material_Type__c>();
    public static User user1;
    public static BA_Configuration__c dat1;
    public static  Material_Master__c mm,mm1,mm2 ;
    public static Material_Type__c mtype,mtype1;
    public static Profile p;
    static{
        m1 = testData_Kevlar_UT.getMessage1(); 
        InsertList.add(m1);       
        m4 = testData_Kevlar_UT.getMessage25();
        InsertList.add(m4);  
        m2 = testData_Kevlar_UT.getMessage2(); 
        InsertList.add(m2);  
        m3 = testData_Kevlar_UT.getMessage3();
        InsertList.add(m3);  
        insert InsertList;
    p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
    user1 = new User();     
    user1.Username = 'testName1@abc.com';
    user1.LastName = 'name';
    user1.Alias = 'tn';
    user1.CommunityNickname = 'test';
    user1.TimeZoneSidKey = 'America/Chicago';
    user1.LocaleSidKey = 'en_US';
    user1.EmailEncodingKey = 'UTF-8';
    user1.ProfileId = p.id;
    user1.LanguageLocaleKey = 'en_US';
    user1.email = 'testName1@abc.com';
    user1.isActive = true;
    insert user1;
    
    dat1=new BA_Configuration__c ();
    dat1.Name='abcd';
    dat1.Active__c= true;
    dat1.status__c='Tender in progress';
    dat1.BAC_Progress__c='New Campaigns';
    dat1.ownerid = user1.id;
    insert dat1;
     
    String rdId1 = [Select Id From RecordType Where SobjectType = 'Body_Armor_Solution__c' and Name = 'HAP Solution'].Id;
    
  
    
    mm = new Material_Master__c();
    mm.Material_Type__c = 'Dupont';
    insert mm;
  
    mm1 = new Material_Master__c();
    mm1.Material_Type__c = 'test';
    insert mm1;
  
    mm2 = new Material_Master__c();
    mm2.Material_Type__c = 'test1';
    insert mm2;
    
    
    bas = new Body_Armor_Solution__c();
    bas.BA_Configuration__c = dat1.id;
    bas.name='hap solution1';
    bas.RecordTypeId=rdId1;
    bas.Active__c= true;
    bas.Backing_Material_FP__c= mm.id;
    bas.Backing_Material_BP__c= mm1.id;
    bas.Backing_Material_SP__c= mm2.id;
    bas.BP_areal_density__c = 2;
    bas.FP_areal_density__c = 2;
    bas.SP_areal_density__c = 2;
    bas.BP_Plate_Solution_Thickness__c = 2;
    bas.FP_Plate_Solution_Thickness__c = 2;
    bas.SP_Plate_Solution_Thickness__c = 2;
    bas.Body_Armor_Solution_ID_iOS__c = 'abcs123';
    bas.SP_tile_Thickness__c = 2;
    bas.BP_tile_Thickness__c = 2;
    bas.FP_tile_Thickness__c = 2;
    bas.Backing_layers_BP__c = 2;
    bas.Backing_layers_FP__c = 2;
    bas.Backing_layers_SP__c = 2;
    bas.SP_BM_Areal_Density__c = 2;
    bas.FP_BM_Areal_Density__c = 2;
    bas.BP_BM_Areal_Density__c = 2;
    bas.No_Of_Layers_BP__c = 2;
    bas.No_Of_Layers_FP__c = 2;
    bas.No_Of_Layers_SP__c = 2;
    bas.BP_Weight__c = 2;
    bas.FP_Weight__c = 2;
    bas.SP_Weight__c = 2;
    bas.Total_weight_of_XS_size__c = 12;
    bas.Total_weight_of_S_size__c = 12;
    bas.Total_weight_of_M_size__c = 12;
    bas.Total_weight_of_L_size__c = 12;
    bas.Total_weight_of_XL_size__c = 12;
    bas.Total_weight_of_XXL_size__c = 12;
    bas.Material_Master_SP__c = mm2.id;
    bas.Material_Master_BP__c = mm1.id;
    bas.Material_Master_FP__c = mm.id;
    bas.SP_Comment__c  = 'xxxxx';    
    bas.FP_Comment__c  = 'xxxxx';  
    bas.BP_Comment__c  = 'xxxxx';  
    bas.Comments__c = 'tttttt';
    basList.add(bas);
    System.debug('Inserted bas: '+ bas.Id);
    bas1 = new Body_Armor_Solution__c();
    bas1.BA_Configuration__c = dat1.id;
    bas1.name='';
    bas1.RecordTypeId=rdId1;
    bas1.Active__c= true;
    bas1.Backing_Material_FP__c= mm.id;
    bas1.Backing_Material_BP__c= mm1.id;
    bas1.Backing_Material_SP__c= mm2.id;
    bas1.BP_areal_density__c = null;
    bas1.FP_areal_density__c = null;
    bas1.SP_areal_density__c = null;
    bas1.BP_Plate_Solution_Thickness__c = null;
    bas1.FP_Plate_Solution_Thickness__c = null;
    bas1.SP_Plate_Solution_Thickness__c = null;
    bas1.Body_Armor_Solution_ID_iOS__c = 'test';
    bas1.SP_tile_Thickness__c = null;
    bas1.BP_tile_Thickness__c = null;
    bas1.FP_tile_Thickness__c = null;
    bas1.Backing_layers_BP__c = null;
    bas1.Backing_layers_FP__c = null;
    bas1.Backing_layers_SP__c = null;
    bas1.SP_BM_Areal_Density__c = null;
    bas1.FP_BM_Areal_Density__c = null;
    bas1.BP_BM_Areal_Density__c = null;
    bas1.No_Of_Layers_BP__c = null;
    bas1.No_Of_Layers_FP__c = null;
    bas1.No_Of_Layers_SP__c = null;
    bas1.BP_Weight__c = null;
    bas1.FP_Weight__c = null;
    bas1.SP_Weight__c = null;
    bas1.SP_Comment__c  = '';    
    bas1.FP_Comment__c  = '';  
    bas1.BP_Comment__c  = '';
    bas1.Comments__c = '';
    bas1.Total_weight_of_XS_size__c = null;
    bas1.Total_weight_of_S_size__c = null;
    bas1.Total_weight_of_M_size__c = null;
    bas1.Total_weight_of_L_size__c = null;
    bas1.Total_weight_of_XL_size__c = null;
    bas1.Total_weight_of_XXL_size__c = null;
    basList.add(bas1);      
    insert basList; 
    
    
  /*  mtype = new Material_Type__c();
    mtype.name = 'test2';
    mtype.SAP_Material__c = mm.Id;   
  //  mtype.Number_of_Layers__c = '2';
    mtype.Body_Armor_SAP_Solution__c = bas.id;
    mtype.Material_used__c = 'Dupont';
    mtype.GSM__c = 2;
    mtype.Comments__c= 'xxxxxxx';
    mtypeList.add(mtype);      
    mtype1 = new Material_Type__c();
    mtype1.name = 'test2';
    mtype1.SAP_Material__c = mm.Id;   
  //  mtype1.Number_of_Layers__c = '2';
    mtype1.Body_Armor_SAP_Solution__c = bas1.id;
    mtype1.Material_used__c = 'Dupont';
    mtype1.GSM__c = 2;
    mtype1.Comments__c= 'xxxxxxx';
    mtypeList.add(mtype1);      
    insert mtypeList;*/
    }
static testMethod void testDoPost() {
 // Adding dummy value   
    String JsonMsg='{'+
    '"bacConfigurationID" : "'+dat1.id+'"'+
    '}';
    Test.startTest();

    RestRequest req = new RestRequest(); 
    RestResponse res = new RestResponse();
    req.requestURI = '/services/apexrest/PopulateHAPSolution';  
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueof(JsonMsg);
    RestContext.request = req;
    RestContext.response= res;


    CtrlPopulateHAPSolutionService testTHR=new CtrlPopulateHAPSolutionService();   
    CtrlPopulateHAPSolutionService.doPost(); 
    Test.stopTest();
    }
   
}