DuPont DevSB/src/objects/BA_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BAC_Currency__c</fullName>
        <label>BAC Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BAC_Progress__c</fullName>
        <label>BAC Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Campaigns</fullName>
                </value>
                <value>
                    <fullName>Requirements Commenced</fullName>
                </value>
                <value>
                    <fullName>Specifications Generated</fullName>
                </value>
                <value>
                    <fullName>Solutioning Started</fullName>
                </value>
                <value>
                    <fullName>Solutions Created</fullName>
                </value>
                <value>
                    <fullName>Pricing Completed</fullName>
                </value>
                <value>
                    <fullName>Commercials Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Body_Armor_Configuration_ID__c</fullName>
        <externalId>true</externalId>
        <label>Body Armor Configuration ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Budget_for_Year_1__c</fullName>
        <label>Budget Year 1</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_for_Year_2__c</fullName>
        <label>Budget Year 2</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_for_Year_3__c</fullName>
        <label>Budget Year 3</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Closure_Reason__c</fullName>
        <label>Closure Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract awarded to DuPont / Partner and fulfilled</fullName>
                </value>
                <value>
                    <fullName>Contract awarded to competitor</fullName>
                </value>
                <value>
                    <fullName>Tender differed / postponed</fullName>
                </value>
                <value>
                    <fullName>Tender Cancelled</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Closure_Remark__c</fullName>
        <label>Closure Remark</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Created_by_IOS__c</fullName>
        <label>Created by (IOS)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_date_IOS__c</fullName>
        <label>Created date (IOS)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_User_Country__c</fullName>
        <label>End User Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Name__c</fullName>
        <label>End User Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Region__c</fullName>
        <label>End User Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Helmets__c</fullName>
        <label>Number of Helmets (Total)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Helmets_Y1__c</fullName>
        <label>Number of Helmets Y1</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Helmets_Y2__c</fullName>
        <label>Number of Helmets Y2</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Helmets_Y3__c</fullName>
        <label>Number of Helmets Y3</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Plates_Y1__c</fullName>
        <label>Number of Plates Y1</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Plates_Y2__c</fullName>
        <label>Number of Plates Y2</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Plates_Y3__c</fullName>
        <label>Number of Plates Y3</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Plates__c</fullName>
        <label>Number of Plates (Total)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Vest_Y1__c</fullName>
        <label>Number of Vest Y1</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Vest_Y2__c</fullName>
        <label>Number of Vest Y2</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Vest_Y3__c</fullName>
        <label>Number of Vest Y3</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Vest__c</fullName>
        <label>Number of Vest (Total)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sensitive_Destination_Committee_Approv__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sensitive Destination Committee Approv.</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_of_IT__c</fullName>
        <label>Source of IT</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CIT-Brazil</fullName>
                </value>
                <value>
                    <fullName>DKC-Hyderabad ~India</fullName>
                </value>
                <value>
                    <fullName>ETC-Meyrin ~Switzerland</fullName>
                </value>
                <value>
                    <fullName>Richmond ~USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre- Tender Solicitation</fullName>
                </value>
                <value>
                    <fullName>Tender in progress</fullName>
                </value>
                <value>
                    <fullName>Tender Bid Submissions</fullName>
                </value>
                <value>
                    <fullName>Solutions Evaluation</fullName>
                </value>
                <value>
                    <fullName>Tender Contract Award</fullName>
                </value>
                <value>
                    <fullName>Campaign Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Budget__c</fullName>
        <label>Total Budget</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>last_modified_date_IOS__c</fullName>
        <label>last modified date (iOS)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>last_modify_by_IOS__c</fullName>
        <label>last modify by (IOS)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>technicalOfferSubmissionDate__c</fullName>
        <label>technicalOfferSubmissionDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>tenderSubmissionDate__c</fullName>
        <label>tenderSubmissionDate</label>
        <type>DateTime</type>
    </fields>
    <label>BA Configuration</label>
    <nameField>
        <label>BA Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/BAC_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BA_Configuration__c</fullName>
        <label>BA Configuration</label>
        <referenceTo>BA_Configuration__c</referenceTo>
        <relationshipName>BAC_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>Team_Member_Name__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Text(Team_Member_Name__r.User_Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Team_Member_Name__r.Email</formula>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Team_Member_Name__r.User_Region__c)</formula>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BAC_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA Team Member</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Email__c.object
<CustomObject>
    <description>Each record represents a unique email in the system, user for:
-Privacy Notification</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to LastModified Contact</description>
        <inlineHelpText>LastModified Contact</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email Address (External Id Unique)</description>
        <externalId>true</externalId>
        <inlineHelpText>Email Address</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>Email</label>
    <nameField>
        <label>EM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Role_in_Kevlar__c</fullName>
        <label>Role in Kevlar</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Export Control</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Market Communications</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Product Management</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/CtrlMyBACService.cls
/*******************************************************************************
(C)2015
Author: krishnaveni duggaraju
Email: krishnaveni.duggaraju@tcs.com
Description:  This class returns the my BAC input is userid.

Change History:                                                                  Date:  
1. PS 1060931 - Modified code to add new fields in Query                        7/02/2016 

 ********************************************************************************/
@RestResource(urlMapping='/MyBAC/*')
global class CtrlMyBACService{

     global class userWrapper{
        public String userId;
    }
     /* PS1060931 - added 2 fields in query */
    global static String generateQuery(){
        String queryString='SELECT Id,Name,OwnerId,Active__c,Source_of_IT__c,Body_Armor_Configuration_ID__c,BAC_Currency__c,BAC_Progress__c,technicalOfferSubmissionDate__c,tenderSubmissionDate__c,'+
               'Budget_for_Year_1__c,Budget_for_Year_2__c,Budget_for_Year_3__c,Closure_Reason__c,Closure_Remark__c,Created_by_IOS__c,'+
               'Created_date_IOS__c,End_Date__c,End_User_Name__c,End_User_Country__c,End_User_Region__c,last_modified_date_IOS__c,'+
               'last_modify_by_IOS__c,No_of_Helmets__c,Number_of_Helmets_Y1__c,Number_of_Helmets_Y2__c,Number_of_Helmets_Y3__c,'+
               'Number_of_Plates_Y1__c,Number_of_Plates_Y2__c,Number_of_Plates_Y3__c,Number_of_Plates__c,Number_of_Vest__c,Number_of_Vest_Y1__c,'+
               'Number_of_Vest_Y2__c,Number_of_Vest_Y3__c,Start_Date__c,Status__c,Total_Budget__c,Comment__c,Sensitive_Destination_Committee_Approv__c,LastModifiedDate,'+
               '(SELECT Team_Member_Name__c,Team_Member_Name__r.name,Active__c,Region__c,Country__c,Team_member_Name__r.role_in_kevlar__c,'+
               'Contact__c,Email__c FROM BAC_Team_Members__r) FROM BA_Configuration__c';
        return queryString;
    }
    
    @HttpPost
    global static CtrlKevlarSvcHelper.ReturnBACClass doPost(){
        CtrlKevlarSvcHelper h = new CtrlKevlarSvcHelper(); 
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        List<BA_Configuration__c> listBAC = new List<BA_Configuration__c>();
        List<BA_Configuration__c> baConfigResult = new List<BA_Configuration__c>();
        List<BA_Configuration__c> baConfigResult1= new List<BA_Configuration__c>();
        String query='';
        String queryTemp='';
        Integer PTS_Status = 0,TIP_Status = 0,TBS_Status = 0,SE_Status = 0,TCA_Status = 0,CC_Status = 0,NC_Progress = 0,RC_Progress = 0,SG_Progress = 0,SS_Progress = 0,SC_Progress = 0,PC_Progress = 0,CG_Progress = 0;
        Map<String,Integer> statusMap = new Map<String,Integer>();
        Map<String,Integer> progressMap = new Map<String, Integer>();
        List<String> progressList=new List<String>();
        List<String> statusList=new List<String>();
        
        try{
            system.debug('req.requestBody : ' + req.requestBody.toString());
            userWrapper userWrap = (userWrapper) JSON.deserialize(req.requestBody.toString(), userWrapper.class);     
            User loggedInUser=[Select Role_in_Kevlar__c from User where Id=:userWrap.userId AND IsActive=true];
            if(loggedInUser<>null && loggedInUser.Role_in_Kevlar__c.equalsIgnoreCase('Admin')){
                query=generateQuery();
                baConfigResult=Database.query(query);
            }
            else{
                query=generateQuery();
                query=query + ' WHERE OwnerId ='+ '\'' + userWrap.userId + '\'' + ' limit 1000';
                system.debug('in non admin query: ' + query);
                baConfigResult=Database.query(query);
                queryTemp=generateQuery();
                queryTemp=queryTemp + ' WHERE Id IN (Select BA_Configuration__c from BAC_Team_Member__c where Team_Member_Name__c =' + '\'' + userWrap.userId + '\'' +' ) LIMIT 1000';
                baConfigResult1=Database.query(queryTemp);
            }
            listBAC.addAll(baConfigResult);
            listBAC.addAll(baConfigResult1);
            listBAC.sort();
            
            Schema.DescribeFieldResult progressSchema = BA_Configuration__c.BAC_Progress__c.getDescribe();    
            List<Schema.PicklistEntry> c = progressSchema.getPicklistValues();		
            for(Integer i=0;i<c.size();i++){
                 progressList.add(c[i].getvalue());   
            }  
            Schema.DescribeFieldResult statusSchema = BA_Configuration__c.status__c.getDescribe();    
            List<Schema.PicklistEntry> statusValues = statusSchema.getPicklistValues();		
            for(Integer i=0;i<statusValues.size();i++){
                 statusList.add(statusValues[i].getvalue());   
            }
            for(BA_Configuration__c BACs :listBAC){
                //map for campaign status
                Integer count;
                if(statusMap.containsKey(BACs.status__c)){
                    count =statusMap.get(BACs.status__c); 
                }
                else{
                    count = 0;
                }
                count = count + 1; 
                statusMap.put(BACs.status__c,count);
                //map for campaign progress
                Integer progressCount;
                if(progressMap.containsKey(BACs.BAC_Progress__c)){
                    progressCount =progressMap.get(BACs.BAC_Progress__c); 
                }
                else{
                    progressCount = 0;
                }
                progressCount = progressCount + 1; 
                progressMap.put(BACs.BAC_Progress__c,progressCount);
            }
            
            for(String statusKey : statusList){
                Integer statusCount;
                if(statusMap.containsKey(statusKey)){
                    statusCount =statusMap.get(statusKey); 
                }
                else{
                   statusCount=0; 
                }
                statusMap.put(statusKey,statusCount);
            }
            for(String progressKey : progressList){
                Integer progressCount;
                if(progressMap.containsKey(progressKey)){
                    progressCount =progressMap.get(progressKey); 
                }
                else{
                   progressCount=0; 
                }
                progressMap.put(progressKey,progressCount);
            }
            return new CtrlKevlarSvcHelper.ReturnBACClass(h.dataSent, h.getMessage('200'),h.getResponseMessage('510'),'510',listBAC,progressMap,statusMap, null,'No Error');
        }
        catch(Exception e){
            System.debug('Error----------'+e.getMessage());
            return new CtrlKevlarSvcHelper.ReturnBACClass(h.dataNotSent, h.getMessage('203'),e.getMessage(),null,null, null, null,null, '203');
        }
    }
}