DuPont DevSB/src/objects/BA_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BAC_Progress__c</fullName>
        <label>BAC Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Campaigns</fullName>
                </value>
                <value>
                    <fullName>Requirements Commenced</fullName>
                </value>
                <value>
                    <fullName>Specifications Generated</fullName>
                </value>
                <value>
                    <fullName>Solutioning Started</fullName>
                </value>
                <value>
                    <fullName>Solutions Created</fullName>
                </value>
                <value>
                    <fullName>Pricing Completed</fullName>
                </value>
                <value>
                    <fullName>Commercials Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre- Tender Solicitation</fullName>
                </value>
                <value>
                    <fullName>Tender in progress</fullName>
                </value>
                <value>
                    <fullName>Tender Bid Submissions</fullName>
                </value>
                <value>
                    <fullName>Solutions Evaluation</fullName>
                </value>
                <value>
                    <fullName>Tender Contract Award</fullName>
                </value>
                <value>
                    <fullName>Campaign Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BA Configuration</label>
    <nameField>
        <label>BA Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/BA_Push_Notification_Log__c.object
<CustomObject>
    <description>Stores push notifications mapping for each campaign corresponding to every user related to that campaign</description>
    <fields>
        <fullName>BA_Configuration__c</fullName>
        <label>BA Configuration</label>
        <referenceTo>BA_Configuration__c</referenceTo>
        <relationshipLabel>BA Push Notification Logs</relationshipLabel>
        <relationshipName>BA_Push_Notification_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsNotificationRead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>indicates whether notification was read by the receiver or not</description>
        <label>Is Notification Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Push_Notification_Receiver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>indicates the user for which we have to show the notification bell on campaign list</description>
        <label>Push Notification Receiver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BA_Push_Notification_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA Push Notification Log</label>
    <nameField>
        <displayFormat>PushNotification-{000000}</displayFormat>
        <label>Push Notification Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BA Push Notification Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Kevlar_Response_Messages__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Kevlar_Response_Messages</label>
</CustomObject>

DuPont DevSB/src/classes/CtrlGetPushNotificationMapService_UT.cls
/*******************************************************************************
(C)2016
Author: krishnaveni duggaraju
Email: krishnaveni.duggaraju@tcs.com
Description:  This class creates the data for CtrlGetPushNotificationMapService test classes

 ********************************************************************************/
@isTest
private class CtrlGetPushNotificationMapService_UT {
    public static Kevlar_Response_Messages__c m1,m2,m3,m4;
    public static List<Kevlar_Response_Messages__c> respMsgList = new List<Kevlar_Response_Messages__c>(); 
    public static Profile  p;
    public static User user1;
    public static BA_Configuration__c bac;
    public static BA_Push_Notification_Log__c pushNotificationLog;
    static{
    m1 = testData_Kevlar_UT.getMessage1(); 
    respMsgList.add(m1);
    m3 = testData_Kevlar_UT.getMessage3();
    respMsgList.add(m3);  
    insert respMsgList;
    
    p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
    
    user1 = new User();     
    user1.Username = 'testName1@abc.com';
    user1.LastName = 'name';
    user1.Alias = 'tn';
    user1.CommunityNickname = 'test';
    user1.TimeZoneSidKey = 'America/Chicago';
    user1.LocaleSidKey = 'en_US';
    user1.EmailEncodingKey = 'UTF-8';
    user1.ProfileId = p.id;
    user1.LanguageLocaleKey = 'en_US';
    user1.email = 'testName1@abc.com';
    user1.isActive = true;
    insert user1;
    
    bac = new BA_Configuration__c();
    bac.Name='abcd';
    bac.Active__c= true;
    bac.status__c='Tender in progress';
    bac.BAC_Progress__c='New Campaigns';
    bac.ownerid = user1.id;
    insert bac;
    
    pushNotificationLog = new BA_Push_Notification_Log__c();
    pushNotificationLog.BA_Configuration__c = bac.id;
    pushNotificationLog.IsNotificationRead__c = true;
    pushNotificationLog.Push_Notification_Receiver__c = user1.id;
    insert pushNotificationLog;
    
    }
 static testMethod void testDoPost() {
 
    String JsonMsg='{'+
    '"receiverID" : "'+user1.id+'"'+
    '}';
    Test.startTest();
    RestRequest req = new RestRequest(); 
    RestResponse res = new RestResponse();
    req.requestURI = '/services/apexrest/GetPushNotificationMap';  
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueof(JsonMsg);
    RestContext.request = req;
    RestContext.response= res;
    CtrlGetPushNotificationMapService testGetPushLog=new CtrlGetPushNotificationMapService();   
    CtrlGetPushNotificationMapService.doPost(); 
    Test.stopTest();
 }

}