DuPont DevSB/src/objects/BA_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BAC_Progress__c</fullName>
        <label>BAC Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Campaigns</fullName>
                </value>
                <value>
                    <fullName>Requirements Commenced</fullName>
                </value>
                <value>
                    <fullName>Specifications Generated</fullName>
                </value>
                <value>
                    <fullName>Solutioning Started</fullName>
                </value>
                <value>
                    <fullName>Solutions Created</fullName>
                </value>
                <value>
                    <fullName>Pricing Completed</fullName>
                </value>
                <value>
                    <fullName>Commercials Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Body_Armor_Configuration_ID__c</fullName>
        <externalId>true</externalId>
        <label>Body Armor Configuration ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sensitive_Destination_Committee_Approv__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sensitive Destination Committee Approv.</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre- Tender Solicitation</fullName>
                </value>
                <value>
                    <fullName>Tender in progress</fullName>
                </value>
                <value>
                    <fullName>Tender Bid Submissions</fullName>
                </value>
                <value>
                    <fullName>Solutions Evaluation</fullName>
                </value>
                <value>
                    <fullName>Tender Contract Award</fullName>
                </value>
                <value>
                    <fullName>Campaign Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BA Configuration</label>
    <nameField>
        <label>BA Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/BA_Push_Notification_Log__c.object
<CustomObject>
    <description>Stores push notifications mapping for each campaign corresponding to every user related to that campaign</description>
    <fields>
        <fullName>BA_Configuration__c</fullName>
        <label>BA Configuration</label>
        <referenceTo>BA_Configuration__c</referenceTo>
        <relationshipLabel>BA Push Notification Logs</relationshipLabel>
        <relationshipName>BA_Push_Notification_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsNotificationRead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>indicates whether notification was read by the receiver or not</description>
        <label>Is Notification Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Push_Notification_Receiver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>indicates the user for which we have to show the notification bell on campaign list</description>
        <label>Push Notification Receiver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BA_Push_Notification_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA Push Notification Log</label>
    <nameField>
        <displayFormat>PushNotification-{000000}</displayFormat>
        <label>Push Notification Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BA Push Notification Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/BAC_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BA_Configuration__c</fullName>
        <label>BA Configuration</label>
        <referenceTo>BA_Configuration__c</referenceTo>
        <relationshipName>BAC_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BAC_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA Team Member</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Body_Armor_Solution__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BA_Configuration__c</fullName>
        <label>BA Configuration</label>
        <referenceTo>BA_Configuration__c</referenceTo>
        <relationshipName>Body_Armor_Solutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Body_Armor_Solution_ID_iOS__c</fullName>
        <externalId>true</externalId>
        <label>Body Armor Solution ID iOS</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <label>BA Solution</label>
    <nameField>
        <label>Solution  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Material_Master__c.object
<CustomObject>
    <fields>
        <fullName>GSM__c</fullName>
        <label>GSM</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Material_Orign__c</fullName>
        <label>Material Orign</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DuPont</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Material_Type__c</fullName>
        <label>Material Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>HAP</fullName>
                </value>
                <value>
                    <fullName>HAP backing Material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BA Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Materials</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Material_Type__c.object
<CustomObject>
    <fields>
        <fullName>Body_Armor_SAP_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Body Armor SAP Solution</label>
        <referenceTo>Body_Armor_Solution__c</referenceTo>
        <relationshipLabel>BA Material Types</relationshipLabel>
        <relationshipName>Materials_Type</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>GSM__c</fullName>
        <label>GSM</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Material_used__c</fullName>
        <label>Material used</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_Layers__c</fullName>
        <label>Number of Layers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Material__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BA Material Master</label>
        <referenceTo>Material_Master__c</referenceTo>
        <relationshipLabel>BA Materials Types</relationshipLabel>
        <relationshipName>Materials_Type</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA Material Type</label>
    <nameField>
        <label>Select Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Material Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Solution_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BAM_Margin__c</fullName>
        <label>BAM Margin</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>BA_Configuration__c</fullName>
        <label>BA Configuration</label>
        <referenceTo>BA_Configuration__c</referenceTo>
        <relationshipName>Solution_Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cost_Comment__c</fullName>
        <label>Cost Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Cost_Of_Outer_Carrier__c</fullName>
        <label>Cost Of Outer Carrier</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_Of_SAP_Pouches__c</fullName>
        <label>Cost Of SAP Pouches</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Material_Wastage_Comment__c</fullName>
        <label>Material Wastage Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SAP_Material_Wastage__c</fullName>
        <label>SAP Material Wastage</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Select_SAP_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select SAP Solution</label>
        <referenceTo>Body_Armor_Solution__c</referenceTo>
        <relationshipLabel>BA Solutions Pricing (Select SAP Solution)</relationshipLabel>
        <relationshipName>Solution_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_cost_of_Body_Armour_for_size_L__c</fullName>
        <label>Total cost of  Body Armour for size L</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_cost_of_Body_Armour_for_size_M__c</fullName>
        <label>Total cost of  Body Armour for size M</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_cost_of_Body_Armour_for_size_S__c</fullName>
        <label>Total cost of  Body Armour for size S</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_cost_of_Body_Armour_for_size_XL__c</fullName>
        <label>Total cost of  Body Armour for size XL</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_cost_of_Body_Armour_for_size_XS__c</fullName>
        <label>Total cost of  Body Armour for size XS</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_cost_of_Body_Armour_for_size_XXL__c</fullName>
        <label>Total cost of  Body Armour for size XXL</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>BA Solution Pricing</label>
    <nameField>
        <label>Solution Pricing</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Solutions Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/CtrlSolutionPricingTriggerHandler_UT.cls
/*******************************************************************************
(C)2016
Author: krishnaveni duggaraju
Email: krishnaveni.duggaraju@tcs.com
Description:  This class tests the CtrlSolutionPricingTriggerHandler
 ********************************************************************************/
@isTest
private class CtrlSolutionPricingTriggerHandler_UT {
    public static Profile p;
    public static User user1;
    public static BA_Configuration__c  bac;
    public static BA_Push_Notification_Log__c push;
    public static BAC_Team_Member__c btm1;
    public static Body_Armor_Solution__c bas;
    public static  Material_Master__c mm;
    public static Material_Type__c mtype;
    public static Solution_Pricing__c sp;
    static testMethod void testDoPost() {
    
        p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        List<User> userList = new List<User>();
        user1 = new User();     
        user1.Username = 'testName1@abc.com';
        user1.LastName = 'name';
        user1.Alias = 'tn';
        user1.CommunityNickname = 'test';
        user1.TimeZoneSidKey = 'America/Chicago';
        user1.LocaleSidKey = 'en_US';
        user1.EmailEncodingKey = 'UTF-8';
        user1.ProfileId = p.id;
        user1.LanguageLocaleKey = 'en_US';
        user1.email = 'testName1@abc.com';
        user1.isActive = true;   
        insert user1;
        
        bac= new BA_Configuration__c();
        bac.name='test';     
        bac.Body_Armor_Configuration_ID__c='ABCD123456';
        bac.Active__c = true; 
        bac.Status__c = 'Tender in progress';
        bac.BAC_Progress__c = 'New Campaigns';
        bac.Sensitive_Destination_Committee_Approv__c = true;
        bac.ownerid = user1.id;
        insert bac;   
        
        push = new BA_Push_Notification_Log__c();
        push.BA_Configuration__c = bac.id;
        push.IsNotificationRead__c = true;
        push.Push_Notification_Receiver__c = user1.id;
        insert push;
        
        btm1 = new BAC_Team_Member__c();
        btm1.Active__c = true;
        btm1.BA_Configuration__c = bac.id;
        btm1.Team_Member_Name__c = user1.id;   
        insert btm1;  
        String rdId1 = [Select Id From RecordType Where SobjectType = 'Body_Armor_Solution__c' and  Name = 'SAP Solution'].Id;
        
        bas = new Body_Armor_Solution__c();
        bas.BA_Configuration__c = bac.id;
        bas.name='hap solution1';
        bas.Body_Armor_Solution_ID_iOS__c = 'test123';
        bas.RecordTypeId=rdId1;
        bas.Comments__c = 'dfasdfa';
        insert bas; 
        mm = new Material_Master__c();
        mm.Material_Type__c = 'Dupont';
        mm.Material_Orign__c = 'Dupont';
        insert mm;
        mtype = new Material_Type__c();
        mtype.name = 'test';
        mtype.SAP_Material__c = mm.Id;
        mtype.Number_of_Layers__c = '2';
        mtype.Body_Armor_SAP_Solution__c = bas.id;
        mtype.Material_used__c = 'Dupont';
        mtype.GSM__c = 2;
        mtype.Comments__c= 'xxxxxxx';
        insert mtype;
        String rdIdsp = [Select Id From RecordType Where SobjectType = 'Solution_Pricing__c' and Name = 'SAP Solution Pricing'].Id; 
        
        sp = new Solution_Pricing__c();
        sp.name= 'sp price1';
        sp.Active__c= true;
        sp.RecordTypeId=rdIdsp;
        sp.BA_Configuration__c = bac.id;
        sp.Select_SAP_Solution__c = bas.id;
        sp.Total_cost_of_Body_Armour_for_size_XXL__c = 2;
        sp.Total_cost_of_Body_Armour_for_size_XL__c = 2;
        sp.Total_cost_of_Body_Armour_for_size_L__c = 2;
        sp.Total_cost_of_Body_Armour_for_size_XS__c = 2;
        sp.Total_cost_of_Body_Armour_for_size_S__c = 2;
        sp.Total_cost_of_Body_Armour_for_size_M__c = 2;
        sp.Material_Wastage_Comment__c = 'xxxxxx';
        sp.Cost_Of_Outer_Carrier__c = 2;
        sp.Cost_Of_SAP_Pouches__c = 3;
        sp.SAP_Material_Wastage__c = 2;
        sp.BAM_Margin__c = 3;
        sp.Cost_Comment__c = 'xxxx';
        insert sp; 
    }
    
}