DuPont DevSB/src/objects/BA_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>BAC_Progress__c</fullName>
        <label>BAC Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Campaigns</fullName>
                </value>
                <value>
                    <fullName>Requirements Commenced</fullName>
                </value>
                <value>
                    <fullName>Specifications Generated</fullName>
                </value>
                <value>
                    <fullName>Solutioning Started</fullName>
                </value>
                <value>
                    <fullName>Solutions Created</fullName>
                </value>
                <value>
                    <fullName>Pricing Completed</fullName>
                </value>
                <value>
                    <fullName>Commercials Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BA Configuration</label>
    <nameField>
        <label>BA Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/CtrlBACProgressDropdownService.cls
/*******************************************************************************
(C)2015
Author: pallavi sharma
Email: pallavi.sharma3@tcs.com
Description:  This class returns the my BAC/Campaign Progress dropdown.
 ********************************************************************************/
 
 @RestResource(urlMapping='/BACProgress/*')
 global class CtrlBACProgressDropdownService{
 
 @HttpPost
 global static CtrlKevlarSvcHelper.ReturnDropDownClass doPost()
 {
 
 CtrlKevlarSvcHelper h = new CtrlKevlarSvcHelper();
 RestRequest req = RestContext.request;
 try{
    system.debug('req.requestBody : ' + req.requestBody.toString()); 
    List<String> progressList = new List<String>();    
    Schema.DescribeFieldResult progress = BA_Configuration__c.BAC_Progress__c.getDescribe();    
    List<Schema.PicklistEntry> c = progress.getPicklistValues();
    for(Integer i=0;i<c.size();i++)
        {
             progressList.add(c[i].getvalue());   
        }  
    //system.debug('@@@@@BACProgressDropdown ' + progressList);      
    if(!progressList.isEmpty()){
        return new CtrlKevlarSvcHelper.ReturnDropDownClass (h.dataSent, h.getMessage('200'),h.getResponseMessage('507'),'507', progressList, null, 'No Error');
    }
    else{
        return new CtrlKevlarSvcHelper.ReturnDropDownClass (h.dataNotSent, h.getMessage('201'),null,null, null, null, '201');
    }        
 }
  catch(Exception e){
        System.debug('Error----------'+e.getMessage());
        //return e.getMessage();
         return new CtrlKevlarSvcHelper.ReturnDropDownClass (h.dataNotSent, h.getMessage('203'),'Data loading failed!',null, null,null, '203');
    }
 }
 
 }