DuPont DevSB/src/objects/BA_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BAC_Progress__c</fullName>
        <label>BAC Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Campaigns</fullName>
                </value>
                <value>
                    <fullName>Requirements Commenced</fullName>
                </value>
                <value>
                    <fullName>Specifications Generated</fullName>
                </value>
                <value>
                    <fullName>Solutioning Started</fullName>
                </value>
                <value>
                    <fullName>Solutions Created</fullName>
                </value>
                <value>
                    <fullName>Pricing Completed</fullName>
                </value>
                <value>
                    <fullName>Commercials Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Body_Armor_Configuration_ID__c</fullName>
        <externalId>true</externalId>
        <label>Body Armor Configuration ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sensitive_Destination_Committee_Approv__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sensitive Destination Committee Approv.</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre- Tender Solicitation</fullName>
                </value>
                <value>
                    <fullName>Tender in progress</fullName>
                </value>
                <value>
                    <fullName>Tender Bid Submissions</fullName>
                </value>
                <value>
                    <fullName>Solutions Evaluation</fullName>
                </value>
                <value>
                    <fullName>Tender Contract Award</fullName>
                </value>
                <value>
                    <fullName>Campaign Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BA Configuration</label>
    <nameField>
        <label>BA Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/BA_Push_Notification_Log__c.object
<CustomObject>
    <description>Stores push notifications mapping for each campaign corresponding to every user related to that campaign</description>
    <fields>
        <fullName>BA_Configuration__c</fullName>
        <label>BA Configuration</label>
        <referenceTo>BA_Configuration__c</referenceTo>
        <relationshipLabel>BA Push Notification Logs</relationshipLabel>
        <relationshipName>BA_Push_Notification_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsNotificationRead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>indicates whether notification was read by the receiver or not</description>
        <label>Is Notification Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Push_Notification_Receiver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>indicates the user for which we have to show the notification bell on campaign list</description>
        <label>Push Notification Receiver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BA_Push_Notification_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA Push Notification Log</label>
    <nameField>
        <displayFormat>PushNotification-{000000}</displayFormat>
        <label>Push Notification Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BA Push Notification Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/BAC_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BA_Configuration__c</fullName>
        <label>BA Configuration</label>
        <referenceTo>BA_Configuration__c</referenceTo>
        <relationshipName>BAC_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BAC_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA Team Member</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/CtrlBAConfigTriggerHandler_UT.cls
/*******************************************************************************
(C)2016
Author: krishnaveni duggaraju
Email: krishnaveni.duggaraju@tcs.com
Description:  This class tests the CtrlBAConfigTriggerHandler
 ********************************************************************************/
@isTest
private class CtrlBAConfigTriggerHandler_UT {
    public static Profile p;
    public static User user1,user2;
    public static BA_Configuration__c  bac;
    public static List<BA_Configuration__c> updateBacList= new List<BA_Configuration__c>();
    public static BA_Push_Notification_Log__c push;
    public static List<BAC_Team_Member__c> listBTM = new List<BAC_Team_Member__c>();
    public static BAC_Team_Member__c btm1;
    static testMethod void testDoPost() {
    
    p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
    List<User> userList = new List<User>();
    user1 = new User();     
    user1.Username = 'testName1@abc.com';
    user1.LastName = 'name';
    user1.Alias = 'tn';
    user1.CommunityNickname = 'test';
    user1.TimeZoneSidKey = 'America/Chicago';
    user1.LocaleSidKey = 'en_US';
    user1.EmailEncodingKey = 'UTF-8';
    user1.ProfileId = p.id;
    user1.LanguageLocaleKey = 'en_US';
    user1.email = 'testName1@abc.com';
    user1.isActive = true;
    userList.add(user1);
    
    user2 = new User();
    user2.Username = 'testName2@abc.com';
    user2.LastName = 'name2';
    user2.Alias = 'tn2';
    user2.CommunityNickname = 'test2';
    user2.TimeZoneSidKey = 'America/Chicago';
    user2.LocaleSidKey = 'en_US';
    user2.EmailEncodingKey = 'UTF-8';
    user2.ProfileId = p.id;
    user2.LanguageLocaleKey = 'en_US';
    user2.email = 'testName2@abc.com';
    user2.isActive = true;
    
    userList.add(user2);
    insert userList;
    bac= new BA_Configuration__c();
    bac.name='test';     
    bac.Body_Armor_Configuration_ID__c='ABCD123456';
    bac.Active__c = true; 
    bac.Status__c = 'Tender in progress';
    bac.BAC_Progress__c = 'New Campaigns';
    bac.Sensitive_Destination_Committee_Approv__c = true;
    bac.ownerid = user1.id;
    insert bac;
    bac.Status__c = 'Tender Bid Submissions';
    bac.BAC_Progress__c = 'Specifications Generated';
    update bac;
    bac.Status__c = 'Solutions Evaluation';
    bac.BAC_Progress__c = 'Solutioning Started';
    update bac;
    bac.Status__c = 'Tender Contract Award';
    bac.BAC_Progress__c = 'Solutions Created';
    update bac;
    bac.Status__c = 'Campaign Closed';
    bac.BAC_Progress__c = 'Commercials Generated';
    update bac;
    
    push = new BA_Push_Notification_Log__c();
    push.BA_Configuration__c = bac.id;
    push.IsNotificationRead__c = true;
    push.Push_Notification_Receiver__c = user1.id;
    insert push;
    
    btm1 = new BAC_Team_Member__c();
    btm1.Active__c = true;
    btm1.BA_Configuration__c = bac.id;
    btm1.Team_Member_Name__c = user1.id;
    listBTM.add(btm1);
    BAC_Team_Member__c btm2 = new BAC_Team_Member__c();
    btm2.Active__c = true;
    btm2.BA_Configuration__c = bac.id;
    btm2.Team_Member_Name__c = user2.id;
    listBTM.add(btm2);    
    insert listBTM;       
    }
    
}