DuPont DevSB/src/objects/BA_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BAC_Progress__c</fullName>
        <label>BAC Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Campaigns</fullName>
                </value>
                <value>
                    <fullName>Requirements Commenced</fullName>
                </value>
                <value>
                    <fullName>Specifications Generated</fullName>
                </value>
                <value>
                    <fullName>Solutioning Started</fullName>
                </value>
                <value>
                    <fullName>Solutions Created</fullName>
                </value>
                <value>
                    <fullName>Pricing Completed</fullName>
                </value>
                <value>
                    <fullName>Commercials Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Body_Armor_Configuration_ID__c</fullName>
        <externalId>true</externalId>
        <label>Body Armor Configuration ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sensitive_Destination_Committee_Approv__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sensitive Destination Committee Approv.</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre- Tender Solicitation</fullName>
                </value>
                <value>
                    <fullName>Tender in progress</fullName>
                </value>
                <value>
                    <fullName>Tender Bid Submissions</fullName>
                </value>
                <value>
                    <fullName>Solutions Evaluation</fullName>
                </value>
                <value>
                    <fullName>Tender Contract Award</fullName>
                </value>
                <value>
                    <fullName>Campaign Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BA Configuration</label>
    <nameField>
        <label>BA Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/BA_Push_Notification_Log__c.object
<CustomObject>
    <description>Stores push notifications mapping for each campaign corresponding to every user related to that campaign</description>
    <fields>
        <fullName>BA_Configuration__c</fullName>
        <label>BA Configuration</label>
        <referenceTo>BA_Configuration__c</referenceTo>
        <relationshipLabel>BA Push Notification Logs</relationshipLabel>
        <relationshipName>BA_Push_Notification_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsNotificationRead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>indicates whether notification was read by the receiver or not</description>
        <label>Is Notification Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Push_Notification_Receiver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>indicates the user for which we have to show the notification bell on campaign list</description>
        <label>Push Notification Receiver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BA_Push_Notification_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA Push Notification Log</label>
    <nameField>
        <displayFormat>PushNotification-{000000}</displayFormat>
        <label>Push Notification Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BA Push Notification Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/BAC_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BA_Configuration__c</fullName>
        <label>BA Configuration</label>
        <referenceTo>BA_Configuration__c</referenceTo>
        <relationshipName>BAC_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BAC_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA Team Member</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Functional_Design_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BA_Configuration__c</fullName>
        <label>BA Configuration</label>
        <referenceTo>BA_Configuration__c</referenceTo>
        <relationshipName>Functional_Design_Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Flammability_Protection_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flammability Protection Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Keep_BP_dimensions_same_for_all_the_size__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Keep BP dimensions same for all the size</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Keep_FP_dimensions_same_for_all_the_size__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Keep FP dimensions same for all the size</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Keep_SP_dimensions_same_for_all_the_size__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Keep SP dimensions same for all the size</label>
        <type>Checkbox</type>
    </fields>
    <label>BA Functional Design Requirement</label>
    <nameField>
        <label>Body Armor Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Functional Design Requirements</pluralLabel>
    <recordTypes>
        <fullName>Body_Armor_Functional_Design</fullName>
        <active>true</active>
        <label>Body Armor Functional Design</label>
    </recordTypes>
    <recordTypes>
        <fullName>HAP_Functional_Design</fullName>
        <active>true</active>
        <label>HAP Functional Design</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other_Requirement</fullName>
        <active>true</active>
        <label>Other Requirement</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/CtrlFDRTriggerHandler_UT.cls
/*******************************************************************************
(C)2016
Author: krishnaveni duggaraju
Email: krishnaveni.duggaraju@tcs.com
Description:  This class tests the CtrlFDRTriggerHandler
 ********************************************************************************/
@isTest
private class CtrlFDRTriggerHandler_UT {
    public static Profile p;
    public static User user1;
    public static BA_Configuration__c  bac;
    public static BA_Push_Notification_Log__c push;
    public static BAC_Team_Member__c btm1;
    public static Functional_Design_Requirement__c fdr1,fdr2,fdr3;
    public static Map<String,Id> rTNameToIDMap;
    static testMethod void testDoPost() {
    
    p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
    List<User> userList = new List<User>();
    user1 = new User();     
    user1.Username = 'testName1@abc.com';
    user1.LastName = 'name';
    user1.Alias = 'tn';
    user1.CommunityNickname = 'test';
    user1.TimeZoneSidKey = 'America/Chicago';
    user1.LocaleSidKey = 'en_US';
    user1.EmailEncodingKey = 'UTF-8';
    user1.ProfileId = p.id;
    user1.LanguageLocaleKey = 'en_US';
    user1.email = 'testName1@abc.com';
    user1.isActive = true;    
    insert user1;
    
    bac= new BA_Configuration__c();
    bac.name='test';     
    bac.Body_Armor_Configuration_ID__c='ABCD123456';
    bac.Active__c = true; 
    bac.Status__c = 'Tender in progress';
    bac.BAC_Progress__c = 'New Campaigns';
    bac.Sensitive_Destination_Committee_Approv__c = true;
    bac.ownerid = user1.id;
    insert bac;
    
    push = new BA_Push_Notification_Log__c();
    push.BA_Configuration__c = bac.id;
    push.IsNotificationRead__c = true;
    push.Push_Notification_Receiver__c = user1.id;
    insert push;
    
    btm1 = new BAC_Team_Member__c();
    btm1.Active__c = true;
    btm1.BA_Configuration__c = bac.id;
    btm1.Team_Member_Name__c = user1.id;   
    insert btm1;  
    
     List<RecordType> fdrRTList=new List<RecordType>();
    List<Functional_Design_Requirement__c> fdrList = new List<Functional_Design_Requirement__c>();
    rTNameToIDMap=new Map<String,Id>();
    
    fdrRTList=[Select Id,developerName From RecordType Where SobjectType = 'Functional_Design_Requirement__c' AND (developerName = 'Body_Armor_Functional_Design' OR 
              developerName='HAP_Functional_Design' OR developerName='Other_Requirement')];
    for(RecordType rt :fdrRTList){
        rTNameToIDMap.put(rt.developerName,rt.id);
    }
        
    fdr1= new Functional_Design_Requirement__c();
    fdr2= new Functional_Design_Requirement__c();
    fdr3= new Functional_Design_Requirement__c();
    
    fdr1.name='FDR123';
    fdr1.RecordTypeId=rTNameToIDMap.get('HAP_Functional_Design');
    fdr1.Active__c=true;
    fdr1.BA_Configuration__c=bac.id;
    fdr1.Keep_FP_dimensions_same_for_all_the_size__c=false;
    fdr1.Keep_BP_dimensions_same_for_all_the_size__c=false;
    fdr1.Keep_SP_dimensions_same_for_all_the_size__c=false;
    fdrList.add(fdr1);
    fdr2.name='FDR456';
    fdr2.RecordTypeId=rTNameToIDMap.get('Other_Requirement');
    fdr2.Active__c=true;
    fdr2.BA_Configuration__c=bac.id;
    fdr2.Flammability_Protection_Needed__c=false;
    fdrList.add(fdr2);
    fdr3.name='FDR789';
    fdr3.RecordTypeId=rTNameToIDMap.get('Body_Armor_Functional_Design');
    fdr3.Active__c=true;
    fdr3.BA_Configuration__c=bac.id;
    fdrList.add(fdr3);
    
    insert fdrList;     
    }
    
}