DuPont DevSB/src/objects/BINASFDCToSFDC__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Filter Criteria for Opportunities to be selected for BI NA MHC SFDC To SFDC Transfer</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BI NA SFDCToSFDC</label>
</CustomObject>

DuPont DevSB/src/objects/External_Initiative__c.object
<CustomObject>
    <description>Detailed information from an external data source provided in an automated feed (project, lead, or opportunity data).</description>
    <fields>
        <fullName>Segment_L2__c</fullName>
        <description>External initiative subsegment.</description>
        <label>Segment L2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment_L3__c</fullName>
        <description>Captures further external initiative detail.</description>
        <label>Segment L3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Announced</fullName>
                </value>
                <value>
                    <fullName>Study</fullName>
                </value>
                <value>
                    <fullName>Pre-Planning</fullName>
                </value>
                <value>
                    <fullName>Request for Proposals</fullName>
                </value>
                <value>
                    <fullName>Request for Qualifications</fullName>
                </value>
                <value>
                    <fullName>Pre-Design</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Planning Schematics</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Design Development</fullName>
                </value>
                <value>
                    <fullName>Final Planning</fullName>
                </value>
                <value>
                    <fullName>Construction Documents</fullName>
                </value>
                <value>
                    <fullName>Pre-tender</fullName>
                </value>
                <value>
                    <fullName>Pre-qualification</fullName>
                </value>
                <value>
                    <fullName>Tender</fullName>
                </value>
                <value>
                    <fullName>Bid</fullName>
                </value>
                <value>
                    <fullName>Bidding</fullName>
                </value>
                <value>
                    <fullName>GC Bidding</fullName>
                </value>
                <value>
                    <fullName>GC Bidding-Invitation</fullName>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Sub-bidding</fullName>
                </value>
                <value>
                    <fullName>Sub bidding</fullName>
                </value>
                <value>
                    <fullName>Bid result</fullName>
                </value>
                <value>
                    <fullName>Bid Results</fullName>
                </value>
                <value>
                    <fullName>Epc award</fullName>
                </value>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Execution</fullName>
                </value>
                <value>
                    <fullName>Sub-Award</fullName>
                </value>
                <value>
                    <fullName>Subcontract Award</fullName>
                </value>
                <value>
                    <fullName>Construct</fullName>
                </value>
                <value>
                    <fullName>Occupancy</fullName>
                </value>
                <value>
                    <fullName>Notice of Completion</fullName>
                </value>
                <value>
                    <fullName>Leasing</fullName>
                </value>
                <value>
                    <fullName>Retrofit</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Delayed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Total value of external initiative.</description>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>External Initiative</label>
    <nameField>
        <label>External Initiative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Initiatives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CLT-Fluid</fullName>
                </value>
                <value>
                    <fullName>CLT-Surfaces</fullName>
                </value>
                <value>
                    <fullName>CLT-Tyvek</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Initiative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>External Initiative (or project managed by a partner or other 3rd party) related to this opportunity</description>
        <label>External Initiative</label>
        <referenceTo>External_Initiative__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fId18__c</fullName>
        <description>18 digit unique id for record. Same Id used for dataloader and other API tools.</description>
        <formula>Id
&amp; MID(&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;,(
IF(FIND(MID(Id,1,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,1,0)
+IF(FIND(MID(Id,2,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,2,0)
+IF(FIND(MID(Id,3,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,4,0)
+IF(FIND(MID(Id,4,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,8,0)
+IF(FIND(MID(Id,5,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,16,0)
)+1,1)
&amp; MID(&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;,(
IF(FIND(MID(Id,6,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,1,0)
+IF(FIND(MID(Id,7,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,2,0)
+IF(FIND(MID(Id,8,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,4,0)
+IF(FIND(MID(Id,9,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,8,0)
+IF(FIND(MID(Id,10,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,16,0)
)+1,1)
&amp; MID(&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;,(
IF(FIND(MID(Id,11,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,1,0)
+IF(FIND(MID(Id,12,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,2,0)
+IF(FIND(MID(Id,13,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,4,0)
+IF(FIND(MID(Id,14,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,8,0)
+IF(FIND(MID(Id,15,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,16,0)
)+1,1)</formula>
        <inlineHelpText>18 digit unique id for record. Same Id used for dataloader and other API tools.</inlineHelpText>
        <label>Id18</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/batchOppSFDCToSFDC.cls
/******************************************************************************* 
Copyright © 2014 DuPont. All rights reserved. 
Author: Abhinav Bhatnagar
Email: abhinav.bhatnagar@dupont.com
Description:  Batch Class for Salesforce To Salesforce Functionality. The
primary funtionality of the batch class is to-
1. Fetch the custom settings or Load Defaults if custom settings are not available
2. Query and get valid Opportunities are not sent already to Parksite
3. Call ctrlOppSFDCToSFDC helper class and pass list of valid 1000 opportunties at a time

Updated
<AB20141111> updated End – Lost with End - Lost changed long hyphen with short hyphen
<AB20141111> updated End – Won with End - Won changed long hyphen with short hyphen

<AS20160919>
Modified By: Arjun Sharma
Modification Date: 19-Sept-2016
Modification: As per new requirement of CP for SF picklist values have changed for Stage, Segment L2 and Segment L3 
added new picklist values in the code. Old values are not removed.
********************************************************************************/
global class batchOppSFDCToSFDC implements Database.Batchable<sObject> {
    /* Global Private Constants used through out the class */
    private static final String CUSTOMSETTINGFORFILTER = 'BINASFDCToSFDC'; //Name of the custom settings from where filters needs to be fetched
    private static final String BLANK = '';
    private static final Integer NONE = 0;
    private static final Date STARTINGDATE = Date.newInstance(2013, 1, 1);
    private static final String BATCH = 'Batch';
    
    /*Global Variables*/
    private String AccountNameCustomSettings = BLANK;
    private String RecordTypeNameCustomSettings = BLANK;
    private String ApplicationTypeCustomSettings = BLANK;
    private Integer ValueCustomSettings = NONE; 
    private Date   StartingDateCustomSettings = STARTINGDATE;
    
    SET<String> EISegmentL2CustomSettings = new SET<String>();
    SET<String> EISegmentL3CustomSettings = new SET<String>();
    SET<String> EIStageCustomSettings = new SET<String>();
    SET<String> OppStageCustomSettings = new SET<String>();
    
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        try{
            boolean fetchingSuccessfull = getCustomSettingsSetFilters();//Get the custom settings and set them as filters for query
            
            If(!fetchingSuccessfull || Test.isRunningTest()){//If fetching of custom settings is unsuccessfull then load default settings.
                loadDefaultSettings(); 
            }
            Account acc = getAccount();
            RecordType rt = getRecordType();
            
            return Database.getQueryLocator([SELECT fId18__c, Name, External_Initiative__c, AccountId FROM Opportunity where AccountId = : acc.id AND RecordTypeId = : rt.id AND  Application_Type__c = : ApplicationTypeCustomSettings AND StageName not in : OppStageCustomSettings AND CloseDate > : StartingDateCustomSettings AND External_Initiative__r.Segment_L2__c not in : EISegmentL2CustomSettings AND External_Initiative__r.Value__c >= : ValueCustomSettings AND External_Initiative__r.Segment_L3__c in : EISegmentL3CustomSettings AND External_Initiative__r.Stage__c not in : EIStageCustomSettings AND id not in (SELECT LocalRecordId FROM PartnerNetworkRecordConnection) ORDER BY id LIMIT 1000 ]);
        
        }catch(Exception e){
            system.debug('Exception Occured '+e.getStackTraceString());
            return  Database.getQueryLocator([SELECT ID FROM Opportunity where name = 'This is not an existing Opportunity']);
        }
    }
    
    global void execute(Database.BatchableContext BC, List<Opportunity> oppList) {
        ctrlOppSFDCToSFDC costsObject = new ctrloppSFDCToSFDC(oppList);
        costsObject.callSFDCToSFDC(BATCH,BLANK);           
        
    }   
    
    global void finish(Database.BatchableContext BC) {
    }
    
    /*Filter Criteria -
Account  is Parksite (IL) Tyvek - HQ 
Opportunity Record Type is ‘BI-NA MHC Opportunity’
Other Validation Criteria -
Value greater or equal to "2,500,000"
AND Segment L2 does not contain Animal/Plant,Bath/Beach,Bowling,Communications,Custom House,Factories,oFlood Dam,
Other Terminal, Parks/Playground, Prisons, Spec Houses, Special, Swim Pools, Warehouse Other, Warehouse Refrigerated, Water Treatment
AND Stage not equal to any of the Pre-Planning, Occupancy, Abandoned, Deferred
AND Segment L3 equal to Building Additions, New Construction
AND Application Type equal to  CLT-Tyvek
AND Stage not equal to End - Lost OR End - Won . 
AND Close Date greater OR equal 1/1/2013
Method to compare values between each opportunity Metadata and fetched custom settings value to validate it */
    
    private boolean getCustomSettingsSetFilters(){
        try{
            Map<String, BINASFDCToSFDC__C> mapOfCustomSettings = BINASFDCToSFDC__C.getAll(); 
            Set<String> EISegmentL2 = new Set<String>();
            Set<String> EISegmentL3 = new Set<String>();
            Set<String> EIStage = new Set<String>();
            for(String key:mapOfCustomSettings.keySet()){
                if(key.contains('EI Segment L2')){
                    EISegmentL2CustomSettings.add(mapOfCustomSettings.get(key).Value__c);
                }else if(key.contains('EI Segment L3')){
                    EISegmentL3CustomSettings.add(mapOfCustomSettings.get(key).Value__c);
                }else if(key.contains('EI Stage')){
                    EIStageCustomSettings.add(mapOfCustomSettings.get(key).Value__c);
                }else if(key.contains('Stage End ')){
                    OppStageCustomSettings.add(mapOfCustomSettings.get(key).Value__c);
                }
            }
            AccountNameCustomSettings = mapOfCustomSettings.get('Account').value__c;  
            system.debug('AccountNameCustomSettings '+AccountNameCustomSettings);
            RecordTypeNameCustomSettings = mapOfCustomSettings.get('Opportunity Record Type').value__c; 
            system.debug('RecordTypeNameCustomSettings '+RecordTypeNameCustomSettings);
            ApplicationTypeCustomSettings =  mapOfCustomSettings.get('Application Type').value__c;
            StartingDateCustomSettings = Date.parse(mapOfCustomSettings.get('Close Date').value__c);
            ValueCustomSettings = Integer.valueOf(mapOfCustomSettings.get('Value').value__c);
            return true;
        }Catch(Exception e){
            
            return false;
        }
    }
    
    private void loadDefaultSettings(){
        
        AccountNameCustomSettings = 'Parksite (IL) Tyvek - HQ';
        RecordTypeNameCustomSettings = 'BI-NA MHC Opportunity';
        StartingDateCustomSettings = STARTINGDATE;
        
        EISegmentL2CustomSettings.add('Animal/Plant');
        EISegmentL2CustomSettings.add('Bath/Beach');
        EISegmentL2CustomSettings.add('Bowling');
        EISegmentL2CustomSettings.add('Communications');
        EISegmentL2CustomSettings.add('Custom House');
        EISegmentL2CustomSettings.add('Factories');
        EISegmentL2CustomSettings.add('Flood Dam');
        EISegmentL2CustomSettings.add('Other Terminal');
        EISegmentL2CustomSettings.add('Parks/Playground'); 
        EISegmentL2CustomSettings.add('Prisons');
        EISegmentL2CustomSettings.add('Spec Houses');
        EISegmentL2CustomSettings.add('Special');
        EISegmentL2CustomSettings.add('Swim Pools'); 
        EISegmentL2CustomSettings.add('Warehouse Other');
        EISegmentL2CustomSettings.add('Warehouse Refrigerated');
        EISegmentL2CustomSettings.add('Water Treatment');
        /*<AS20160919> Start*/
        EISegmentL2CustomSettings.add('Animal/Plant/Fish Facility');
        EISegmentL2CustomSettings.add('Beach/Marina Facility');
        EISegmentL2CustomSettings.add('Bowling Alley');
        EISegmentL2CustomSettings.add('Communication Building');
        EISegmentL2CustomSettings.add('Custom Homes');
        EISegmentL2CustomSettings.add('Manufacturing Building');
        EISegmentL2CustomSettings.add('Flood Control');
        EISegmentL2CustomSettings.add('Passenger Terminal (Other)');
        EISegmentL2CustomSettings.add('Park/Playground');
        EISegmentL2CustomSettings.add('Site Development');
        EISegmentL2CustomSettings.add('Prison/Jail');
        EISegmentL2CustomSettings.add('Sale/Spec Homes');
        EISegmentL2CustomSettings.add('Miscellaneous Education Building');
        EISegmentL2CustomSettings.add('Pre-School');
        EISegmentL2CustomSettings.add('Swimming Pool');
        EISegmentL2CustomSettings.add('Warehouse');
        EISegmentL2CustomSettings.add('Warehouse (Refrigerated)');
        EISegmentL2CustomSettings.add('Water Treatment Plant');
        /*<AS20160919> End*/
        
        EISegmentL3CustomSettings.add('Building Additions');
        EISegmentL3CustomSettings.add('New Construction');
        /*<AS20160919> Start*/
        EISegmentL3CustomSettings.add('Additions');
        EISegmentL3CustomSettings.add('New Porject');
        /*<AS20160919> End*/
        
        EIStageCustomSettings.add('Pre-Planning');
        EIStageCustomSettings.add('Occupancy');
        EIStageCustomSettings.add('Abandoned');
        EIStageCustomSettings.add('Deferred');
        /*<AS20160919> Start*/
        EIStageCustomSettings.add('Request for Proposals');
        EIStageCustomSettings.add('Request for Qualifications');
        EIStageCustomSettings.add('Pre-Design');
        EIStageCustomSettings.add('Notice of Completion');
        EIStageCustomSettings.add('Leasing');
        EIStageCustomSettings.add('Service Bidding');
        EIStageCustomSettings.add('Retrofit');
        EIStageCustomSettings.add('Delayed');
        /*<AS20160919> End*/
        
        ValueCustomSettings = 2500000;
        
        ApplicationTypeCustomSettings = 'CLT-Tyvek';
        
        OppStageCustomSettings.add('End - Lost');//<AB20141111> updated End – Lost with End - Lost changed long hyphen with short hyphen
        OppStageCustomSettings.add('End - Won');//<AB20141111> updated End – Won with End - Won changed long hyphen with short hyphen
        
    }
    
    private Account getAccount(){
        return  [Select id, name from Account where name= : AccountNameCustomSettings LIMIT 1];
    }
    
    private RecordType getRecordType(){
        return [Select id, name from RecordType where name = : RecordTypeNameCustomSettings LIMIT 1];
    }
}