DuPont DevSB/src/objects/BPD_Sample_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Abbreviation__c</fullName>
        <label>Abbreviation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BPD Sample Settings</label>
</CustomObject>

DuPont DevSB/src/objects/Case_Details__c.object
<CustomObject>
    <description>Trademark Abuse Case Details object is used for storing information related to brand protection cases.</description>
    <fields>
        <fullName>Related_Case__c</fullName>
        <label>Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Case_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trademark Abuse Case Details</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Case Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trademark Abuse Case Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Trademark_Abuse_Sample__c.object
<CustomObject>
    <description>This object is used to store the details related to samples obtained for Brand protection cases.</description>
    <fields>
        <fullName>Active_Ingredients__c</fullName>
        <label>Active Ingredients</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Azimsulfuron (AZM)</fullName>
                </value>
                <value>
                    <fullName>Bensulfuron methyl (BSM)</fullName>
                </value>
                <value>
                    <fullName>Bromacil (BRO)</fullName>
                </value>
                <value>
                    <fullName>Carbendazim (CAR)</fullName>
                </value>
                <value>
                    <fullName>Chlorimuron Ethyl (CLE)</fullName>
                </value>
                <value>
                    <fullName>Chlorsulfuron (CLS)</fullName>
                </value>
                <value>
                    <fullName>Copper (COP)</fullName>
                </value>
                <value>
                    <fullName>Cyazypyr (CYA)</fullName>
                </value>
                <value>
                    <fullName>Cymoxanil (CYM)</fullName>
                </value>
                <value>
                    <fullName>Dicamba (DIC)</fullName>
                </value>
                <value>
                    <fullName>Diruon (DIU)</fullName>
                </value>
                <value>
                    <fullName>Ethametsulfuron methyl (ETH)</fullName>
                </value>
                <value>
                    <fullName>Famoxadone (FAM)</fullName>
                </value>
                <value>
                    <fullName>Flupysulfuron methyl (FLU)</fullName>
                </value>
                <value>
                    <fullName>Flusilazole (FLZ)</fullName>
                </value>
                <value>
                    <fullName>Hexazinone (HEX)</fullName>
                </value>
                <value>
                    <fullName>Indoxacarb (IND)</fullName>
                </value>
                <value>
                    <fullName>Lenacil (LEN)</fullName>
                </value>
                <value>
                    <fullName>Mancozeb (MAN)</fullName>
                </value>
                <value>
                    <fullName>Methomyl (MET)</fullName>
                </value>
                <value>
                    <fullName>Metsulfuron methyl (MSM)</fullName>
                </value>
                <value>
                    <fullName>NIcosulfuron (NIC)</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Oxamyl (OXA)</fullName>
                </value>
                <value>
                    <fullName>Picoxystrobin (PIC)</fullName>
                </value>
                <value>
                    <fullName>Proquinazid (PRO)</fullName>
                </value>
                <value>
                    <fullName>Pyraxalt (PYR)</fullName>
                </value>
                <value>
                    <fullName>Rimsulfuron (RIM)</fullName>
                </value>
                <value>
                    <fullName>Rynaxypyr (RYN)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Trademark_Abuse_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BORNEO</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Identification_Date__c</fullName>
        <description>Date of Identification</description>
        <label>Identification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sample_Name__c</fullName>
        <label>Sample Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trademark_Abuse_Case_Details__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Trademark Abuse Case Details related to this Sample</description>
        <inlineHelpText>Reporting requirement called for a relationship between trademark and sample data - hence this lookup was created. The field is populated using trigger - when the case related sample is created</inlineHelpText>
        <label>Trademark Abuse Case Details</label>
        <referenceTo>Case_Details__c</referenceTo>
        <relationshipLabel>Samples/Trap Purchases</relationshipLabel>
        <relationshipName>Samples_Trap_Purchases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sample/Trap Purchase</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Samples/Trap Purchases</pluralLabel>
    <recordTypes>
        <fullName>Crop_Sample</fullName>
        <active>false</active>
        <label>Crop Sample</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/SampleHandler.cls
/*******************************************************************************
Copyright © 2015 DuPont. All rights reserved. 
Author: Pranitha S
Email: Pranitha_S@infosys.com
Description: Handler class for Trigger trigSample
Modifications:  <TJ20151123> Added code to populate the Case Detail in the 
                sample record based on the case related to the sample record.
                <PMA20151215> Corrected lookup field set from type string to NULL to ensure type match
                <Ankit 20160513 5:29 PM IST> added break condition for populating Trademark abuse case details on Sample/Trap purchase object<Issue IS ID-00069049> <IS ID-00071007>
                <Ankit 20160829 3:26 PM IST> added condition for populating Sample Name when active Ingredient is used for the first time as per Issue IS ID-00073074> code coverage 96% <AK 20160829 03:35 PM IST>
 *****************************************************************************/
public without sharing class SampleHandler extends TriggerHandlerBase{

public static final Id CropSample=Rtype.getIdByDevName('Trademark_Abuse_Sample__c', 'Crop_Sample');
public static final Id BPDCase=Rtype.getIdByDevName('Case', 'Brand_Protection_Legal_Case');
public String twoLetterCode;
public Integer length = 5;
public Integer counterVar = 0;
List <Trademark_Abuse_Sample__c> SampleName = new List<Trademark_Abuse_Sample__c>();
public String SampleName1;
public String SampleName2;
public Integer SeqNumber;


    public override void bulkBefore(){
        if(Trigger.IsBefore && Trigger.IsInsert){
            createSampleName();
            }
        //<TJ20151123> Calling the addCase method in case of an update or insert operation.
        if(Trigger.IsBefore && (Trigger.IsInsert || Trigger.IsUpdate)){
            addCase();
      }
    }
    
      /*  Method used to create the sample name for BPD cases  */ 
    public  void createSampleName(){

      for(Sobject record : Trigger.new){
      Trademark_Abuse_Sample__c sample =(Trademark_Abuse_Sample__c )record ;
           if(sample.RecordTypeId==CropSample){
            try{
                        
                String  activeIngredients = BPD_Sample_Settings__c.getInstance(sample.Active_Ingredients__c).Abbreviation__c; 
                 String  country = BPD_Sample_Settings__c.getInstance(sample.Country__c).Abbreviation__c;
                twoLetterCode = 'CP'; 
                string month;
                if(sample.Identification_Date__c.month()>=1 && sample.Identification_Date__c.month()<=9){
                month='0'+String.valueof(sample.Identification_Date__c.month());
                }
                else{
                month=string.valueof(sample.Identification_Date__c.month());
                }
                
                
                
                //Integer SeqNumber = [SELECT COUNT() FROM Trademark_Abuse_Sample__c WHERE RecordTypeId =: CropSample and 
              //  Active_Ingredients__c =: sample.Active_Ingredients__c]+1;
                SampleName=[SELECT Sample_Name__c FROM Trademark_Abuse_Sample__c WHERE RecordTypeId =: CropSample and 
                Active_Ingredients__c =: sample.Active_Ingredients__c order by CreatedDate desc Limit:1];
                
                 // <Ankit 20160829 3:26 PM IST> added condition for populating Sample Name when active Ingredient is used for the first time as per Issue IS ID-00073074> code coverage 96% <AK 20160829 03:35 PM IST>
                if(SampleName.size()==Null || SampleName.size() ==0)
                { 
                    sample.Sample_Name__c = twoLetterCode + '-'+ country + '-' + activeIngredients +
                    '-' + String.valueOf(sample.Identification_Date__c.year()).substring(2) + '-' + month + '-'  + '00001';
                } 
                
                else{
                
               // Trademark_Abuse_Sample__c SampleNm=new Trademark_Abuse_Sample__c();               
                For(Trademark_Abuse_Sample__c s:SampleName)
                {               
                    SampleNAme1=s.Sample_Name__c;
                    SampleNAme2 = SampleNAme1.substring(SampleNAme1.length() - 5);
                    SeqNumber=Integer.valueOf(SampleNAme2);
                    Integer Num= SeqNumber+1;
                    String formattedSeqNumber=  String.valueOf(Num).leftPad(length).replace(' ','0');    
                    sample.Sample_Name__c = twoLetterCode + '-'+ country + '-' + activeIngredients +
                    '-' + String.valueOf(sample.Identification_Date__c.year()).substring(2) + '-' + month + '-'  + formattedSeqNumber;              //update sample;
                }
                   }
                   //<Ankit 20160829 3:26 PM IST> Active ingredient change end
          }
          catch (Exception e){
          system.debug('There was a problem updating the sample name'+e.getMessage()+ counterVar );
     }
        } 
         
       } 
      
    }
    //<TJ20151123> Added code to populate the Case Detail in the sample record based on the case related to the sample record.
    public void addCase(){
        List<Trademark_Abuse_Sample__c> trdAbuseSmpls = new List<Trademark_Abuse_Sample__c>();                
        List<Case_Details__c> trdAbuseList = new List<Case_Details__c>();
        List<Id> CaseList = new List<Id>();
        for(SObject record : Trigger.new) {
            Trademark_Abuse_Sample__c td =(Trademark_Abuse_Sample__c )record ;
            trdAbuseSmpls.add(td);
            if(td.Case__c!=null)
                CaseList.add(td.Case__c);
        }
        //system.debug('case Id:  ' + CaseList.SIZE());
        //system.debug('case Id:  ' + CaseList);
        if(CaseList.size()!=0){
            //system.debug('case Id:  ' + CaseList);
            trdAbuseList=[Select Id,Related_Case__c from Case_Details__c where Related_Case__c IN:CaseList];            
            for(Trademark_Abuse_Sample__c tdrCase : trdAbuseSmpls){
                for(Case_Details__c cd : trdAbuseList){  
                    if(cd.Related_Case__c == tdrCase.Case__c){ 
                        //system.debug('trade Abuse Id ' + cd.Id); 
                        tdrCase.Trademark_Abuse_Case_Details__c =cd.Id;
                        break; // <Ankit 20160513 5:29 PM IST> added break condition for populating Trademark abuse case details on Sample/Trap purchase object<Issue IS ID-00069049> <IS ID-00071007> code coverage: 96% <AK 20160617 5:29 PM IST>   
                    }
                    else{
                        //system.debug('trade Abuse Id ' + cd.Id); 
                        tdrCase.Trademark_Abuse_Case_Details__c =NULL; //<PMA20151215>
                    }                    
                }
            }             
        }
        else{
            //system.debug('case Id23 ');
            for(Trademark_Abuse_Sample__c tdrCase : trdAbuseSmpls){
                tdrCase.Trademark_Abuse_Case_Details__c =NULL;                
            }            
        }
    }
    //<TJ20151123> END
 }