DuPont DevSB/src/objects/BPD_Sample_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Owning_Org__c</fullName>
        <label>Owning Org</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>BPD Sample Settings</label>
</CustomObject>

DuPont DevSB/src/objects/Brand__c.object
<CustomObject>
    <description>This Object stores informations on Brands used in Accounts or in Qualifications</description>
    <label>Brand</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Case_Details__c.object
<CustomObject>
    <description>Trademark Abuse Case Details object is used for storing information related to brand protection cases.</description>
    <fields>
        <fullName>Related_Case__c</fullName>
        <label>Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Case_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trademark Abuse Case Details</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Case Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trademark Abuse Case Details</pluralLabel>
    <recordTypes>
        <fullName>BPD_Case_Details</fullName>
        <active>true</active>
        <label>BPD Case Details</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EPass_ID__c</fullName>
        <description>Positive identification of individuals accessing DuPont computer systems.</description>
        <label>E-Pass ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Grouping__c</fullName>
        <description>DuPont Business</description>
        <inlineHelpText>DuPont Business (abbrev)</inlineHelpText>
        <label>User Grouping</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>DC&amp;F</fullName>
                </value>
                <value>
                    <fullName>DPM</fullName>
                </value>
                <value>
                    <fullName>DPS</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Owning_Org__c</fullName>
        <description>Primary &quot;Owning Organisation&quot; this user belongs to</description>
        <label>User Owning Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-Env</fullName>
                </value>
                <value>
                    <fullName>BI-Surf</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>CORP-CS</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-ES</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PM</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PS</fullName>
                </value>
                <value>
                    <fullName>DPT-Aramids</fullName>
                </value>
                <value>
                    <fullName>DPT-Automotive</fullName>
                </value>
                <value>
                    <fullName>DPT-Car Protection</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP</fullName>
                </value>
                <value>
                    <fullName>DPT-NOW</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IAL</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>LEGL</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Corp Marketing</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Customer Care</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-IT</fullName>
                </value>
                <value>
                    <fullName>DPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Region__c</fullName>
        <label>User Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlBPDBrandEdit_UT.cls
/*******************************************************************************
Copyright © 2015 DuPont. All rights reserved. 
Author :Kavya Kunam<kavya_kunam@infosys.com>, Pranitha S<Pranitha_S@infosys.com>
Description: This class is Unit Test class for class ctrlBPDBrandEdit
***************************************************************************************/

@isTest
private class ctrlBPDBrandEdit_UT{
        static testMethod void test() {
       Final Id CaseRecordType=Rtype.getIdByDevName('Case','Brand_Protection_Legal_Case');
      Final Id CaseDetailsRecordType=Rtype.getIdByDevName('Case_Details__c','BPD_Case_Details');
//[12232016] Called Utility class to create Custom setting data
        Profile p1 = [select id from profile where Name='System Administrator' limit 1];
        UserRole r1= [Select id from UserRole where Name='PS CRM' limit 1];
        
        User user1 = new User(LastName='abc',UserRoleId=r1.Id,ProfileId=p1.Id,Alias='kav123',EmailEncodingKey='UTF-8',TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',LanguageLocaleKey='en_US',Email='kavya_kunam@infosys.com',UserName='kavya@infosys.com.t12', EPass_ID__c='NA0000',User_Owning_Org__c='AGCP-CPC',User_Country__c='India',User_Grouping__c='CPC',User_Region__c='Latin America');
        insert user1;
        System.runas(user1){ 
         Test.startTest();
        //PKH Svmx_TestData_Util_UT.createCustomSettingData();    
        geoValidation.validateInTestMode=false;
        
         BPD_Sample_Settings__c bp = new  BPD_Sample_Settings__c();
         bp.Owning_Org__c='Crop Protection';
         bp.name='Acanto';
         insert bp;  
         
         BPD_Sample_Settings__c bp1 = new  BPD_Sample_Settings__c();
         bp1.Owning_Org__c='Crop Protection';
         bp1.name='Acend';
         insert bp1; 
        
        Date d = Date.newinstance(2014, 12, 27);
              
        Case cas1 = new Case();
        cas1.Owning_SBU__c='Building Innovations';
        cas1.Priority='Low';
        cas1.RecordTypeId = CaseRecordType;
        insert cas1;
        
        cas1=[select id from Case where id=:cas1.id];
        system.debug('aaaa'+cas1);
            
        Case_Details__c  c1= new Case_Details__c();
        c1=[select id from Case_Details__c where Related_Case__c =:cas1.Id];
        c1.Owning_SBU__c='Titanium Technologies;Crop Protection';
        c1.brand__c='Acanto;Acend';
        c1.RecordTypeId = CaseDetailsRecordType;
        update c1;
      
              
        PageReference pageref=Page.BPDBrandEdit;
        Test.setCurrentPage(pageRef);
        
        
        ApexPages.currentPage().getParameters().put('id',cas1.id);
        ApexPages.StandardController controller = new ApexPages.StandardController(cas1);
       
        ctrlBPDBrandEdit  cb = new ctrlBPDBrandEdit(controller);
        cb.brandselect();
        cb.SaveBrand();
        Test.stopTest();
        }
        }
        }