DuPont DevSB/src/objects/Brand__c.object
<CustomObject>
    <description>This Object stores informations on Brands used in Accounts or in Qualifications</description>
    <label>Brand</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Business_Partner__c.object
<CustomObject>
    <description>Business Partners are DuPont sites or contracted companies who are supply-chain partners with DuPont.   Business Partners can be a DuPont location or Customer manufacturing site, a Distributor, a warehouse, a carrier or a combination.    
This object is used corporately as a look-up for company sites related to a Case 
(i.e. Ship-point, Carrier, Manufacturing site).</description>
    <label>Business Partner</label>
    <nameField>
        <label>Business Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Partners</pluralLabel>
    <recordTypes>
        <fullName>ComplaintManager</fullName>
        <active>true</active>
        <description>Business Partners for Complaint Handling - Carriers - DuPont Sites - Partner Sites</description>
        <label>Complaint Manager</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order_Number__c</fullName>
        <inlineHelpText>Complete this field when the case is in regards an Order.</inlineHelpText>
        <label>Order Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Case_Details__c.object
<CustomObject>
    <description>Trademark Abuse Case Details object is used for storing information related to brand protection cases.</description>
    <fields>
        <fullName>Related_Case__c</fullName>
        <label>Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Case_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trademark Abuse Case Details</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Case Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trademark Abuse Case Details</pluralLabel>
    <recordTypes>
        <fullName>BPD_Case_Details</fullName>
        <active>true</active>
        <label>BPD Case Details</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Trademark_Abuse_Sample__c.object
<CustomObject>
    <description>This object is used to store the details related to samples obtained for Brand protection cases.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Trademark_Abuse_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Sample_Collector__c</fullName>
        <label>External Sample Collector</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formulation__c</fullName>
        <label>Formulation (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Internal_Sample_Collector2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Sample Collector</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Samples_Trap_Purchases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Collection_Method__c</fullName>
        <label>Product Collection Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Purchased</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Seized</fullName>
                </value>
                <value>
                    <fullName>Exchanged</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Quantity_Collected__c</fullName>
        <description>This is a number field.  Should be integer</description>
        <label>Product Quantity Collected</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sample_Packaging_Analysis__c</fullName>
        <label>Sample Packaging Analysis</label>
        <type>TextArea</type>
    </fields>
    <label>Sample/Trap Purchase</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Samples/Trap Purchases</pluralLabel>
    <recordTypes>
        <fullName>Brand_Protection_Abuse_Sample</fullName>
        <active>true</active>
        <label>Brand Protection Abuse Sample</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Trademark_Abuse_Sample_Analysis__c.object
<CustomObject>
    <description>This object is used to store the details related to sample analysis for samples gathered for brand protection cases.</description>
    <fields>
        <fullName>Case__c</fullName>
        <formula>Trademark_Abuse_Sample__r.Case__r.fId18__c</formula>
        <label>Case</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lab_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Lab Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Business_Partner__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Complaint Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Business_Partner__c</referenceTo>
        <relationshipLabel>Sample Analysis</relationshipLabel>
        <relationshipName>Trademark_Abuse_Sample_Analysis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lab_Type__c</fullName>
        <label>Lab Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Tertiary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trademark_Abuse_Sample__c</fullName>
        <label>Sample ID</label>
        <referenceTo>Trademark_Abuse_Sample__c</referenceTo>
        <relationshipLabel>Sample Analysis</relationshipLabel>
        <relationshipName>Trademark_Abuse_Sample_Analysis</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sample Analysis</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Trademark Abuse Sample Analysis Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Analysis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EPass_ID__c</fullName>
        <description>Positive identification of individuals accessing DuPont computer systems.</description>
        <label>E-Pass ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Grouping__c</fullName>
        <description>DuPont Business</description>
        <inlineHelpText>DuPont Business (abbrev)</inlineHelpText>
        <label>User Grouping</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>DC&amp;F</fullName>
                </value>
                <value>
                    <fullName>DPM</fullName>
                </value>
                <value>
                    <fullName>DPS</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Owning_Org__c</fullName>
        <description>Primary &quot;Owning Organisation&quot; this user belongs to</description>
        <label>User Owning Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-Env</fullName>
                </value>
                <value>
                    <fullName>BI-Surf</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>CORP-CS</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-ES</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PM</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PS</fullName>
                </value>
                <value>
                    <fullName>DPT-Aramids</fullName>
                </value>
                <value>
                    <fullName>DPT-Automotive</fullName>
                </value>
                <value>
                    <fullName>DPT-Car Protection</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP</fullName>
                </value>
                <value>
                    <fullName>DPT-NOW</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IAL</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>LEGL</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Corp Marketing</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Customer Care</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-IT</fullName>
                </value>
                <value>
                    <fullName>DPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Region__c</fullName>
        <label>User Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlBPDExcelDownload_UT.cls
/*******************************************************************************
Copyright © 2015 DuPont. All rights reserved. 
Author :Kavya Kunam<kavya_kunam@infosys.com>, Pranitha S<Pranitha_S@infosys.com>
Description: This class is Unit Test class for class ctrlBPDExcelDownload
***************************************************************************************/

@isTest
private class ctrlBPDExcelDownload_UT{
        static testMethod void test() {        
                   
        Final Id CPCSample=Rtype.getIdByDevName('Business_Partner__c','ComplaintManager');
        Final Id CaseRecordType=Rtype.getIdByDevName('Case','Brand_Protection_Legal_Case');
        Final Id CaseDetailsRecordType=Rtype.getIdByDevName('Case_Details__c','BPD_Case_Details');
        Final Id CropSample=Rtype.getIdByDevName('Trademark_Abuse_Sample__c','Brand_Protection_Abuse_Sample');
        Profile p1 = [select id from profile where Name='System Administrator' limit 1];
        UserRole r1= [Select id from UserRole where Name='PS CRM' limit 1];
        User user1 = new User(LastName='abc',UserRoleId=r1.Id,ProfileId=p1.Id,Alias='kav123',EmailEncodingKey='UTF-8',TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',LanguageLocaleKey='en_US',Email='kavya_kunam@infosys.com',UserName='kavya@infosys.com.t12', EPass_ID__c='NA0000',User_Owning_Org__c='AGCP-CPC',User_Country__c='India',User_Grouping__c='CPC',User_Region__c='Latin America',Phone='9912818460');
        insert user1;
        System.runas(user1){  
        
        //[12262016] Merge&Spin: Called Utility Test class for custom setting data
        //PKH Svmx_TestData_Util_UT.createCustomSettingData();   
        
        geoValidation.validateInTestMode=false;
        
        Business_Partner__c bp = new Business_Partner__c();
        bp.Name ='Barra Mansa';
        bp.RecordTypeId=CPCSample;
        insert bp;
        
             
         Date d = Date.newinstance(2014, 12, 27);
        Case cas =new Case();
        cas.Order_Number__c = '123abc';
        cas.Sample_Received_Date__c = d;
        cas.RecordTypeId = CaseRecordType;
        insert cas;
        
        Case_Details__c caseDetails = new Case_Details__c();
        caseDetails.Brand__c ='kevlar';
        caseDetails.Company__c='Infosys';
        caseDetails.Related_Case__c=cas.id;
        caseDetails.RecordTypeId = CaseDetailsRecordType;
        insert caseDetails;
        
        Trademark_Abuse_Sample__c sample = new Trademark_Abuse_Sample__c();
        sample.Product_Collection_Method__c='Purchased';
        sample.External_Sample_Collector__c='mary';
        sample.Formulation__c=10;
        sample.Sample_Packaging_Analysis__c='123';
        sample.Product_Quantity_Collected__c=12;
        sample.Internal_Sample_Collector2__c=user1.id;
        sample.Case__c=cas.id;
        sample.RecordTypeId = CropSample;
        insert sample;
       
        Trademark_Abuse_Sample_Analysis__c sampleAnalysis = new Trademark_Abuse_Sample_Analysis__c();
        sampleAnalysis.Lab_Name__c=bp.id;
        sampleAnalysis.Lab_Type__c='Primary';
        sampleAnalysis.Trademark_Abuse_Sample__c=sample.id;
        insert sampleAnalysis;
        
          PageReference pageRef = Page.BPDExcelDownload;
          Test.setCurrentPage(pageRef);
        
        Test.startTest();
        ApexPages.currentPage().getParameters().put('id',sampleAnalysis.id);
        ApexPages.StandardController controller = new ApexPages.StandardController(sample);
        
        ctrlBPDExcelDownload ad = new ctrlBPDExcelDownload(controller);
        
        
        Test.stopTest();
       }
     }
   }