DuPont DevSB/src/objects/Call_Report__c.object
<CustomObject>
    <description>Sales Team Members&apos; Call Report documentation.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Reports</relationshipLabel>
        <relationshipName>R00N30000001Uzc5EAC</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Activity_Description__c</fullName>
        <label>Activity Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Competitor Insight</fullName>
                </value>
                <value>
                    <fullName>Customer Interaction</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>New Business Development</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Technical-Follow up Visit</fullName>
                </value>
                <value>
                    <fullName>Technical-Support</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Face To Face</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Phone-Inbound</fullName>
                </value>
                <value>
                    <fullName>Phone-Outbound</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A key contact for this call report</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Report</relationshipLabel>
        <relationshipName>CallReportContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Initiative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Main Initiative related to this Call Report</description>
        <label>Related Initiative</label>
        <referenceTo>Initiative__c</referenceTo>
        <relationshipName>Call_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Overall status of this Call</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Behind Schedule</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Completed &amp; Reviewed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Call Report</label>
    <nameField>
        <label>Call Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Initiative__c.object
<CustomObject>
    <description>Sell-side Project or Initiative</description>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Main communication channel this initiative is using</description>
        <inlineHelpText>Main communication channel this initiative is using</inlineHelpText>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct Mail Campaign</fullName>
                </value>
                <value>
                    <fullName>eMail</fullName>
                </value>
                <value>
                    <fullName>Face to Face</fullName>
                </value>
                <value>
                    <fullName>Multiple</fullName>
                </value>
                <value>
                    <fullName>Paper Mail</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Press</fullName>
                </value>
                <value>
                    <fullName>Press-Advertisement</fullName>
                </value>
                <value>
                    <fullName>Seminar</fullName>
                </value>
                <value>
                    <fullName>Trade Show</fullName>
                </value>
                <value>
                    <fullName>Web-Advertising</fullName>
                </value>
                <value>
                    <fullName>Web-eLearning</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this Initiative</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <color>#F3D904</color>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Behind Schedule</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <color>#33CC00</color>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                    <color>#CC0000</color>
                    <label>Abandoned</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
                <value>
                    <fullName>Preparation</fullName>
                </value>
                <value>
                    <fullName>Rep Estimation</fullName>
                </value>
                <value>
                    <fullName>District Review</fullName>
                </value>
                <value>
                    <fullName>Area Review</fullName>
                </value>
                <value>
                    <fullName>DP BU Meeting</fullName>
                </value>
                <value>
                    <fullName>DP Supply Meeting</fullName>
                </value>
                <value>
                    <fullName>BU Allocations</fullName>
                </value>
                <value>
                    <fullName>District Allocations</fullName>
                </value>
                <value>
                    <fullName>Rep Allocations</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Initiative</label>
    <nameField>
        <label>Initiative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlEventToCallReport.cls
/*******************************************************************************
Copyright © 2009 DuPont. All rights reserved. 
Author: Thomas Snyder
Email: thomas.snyder@usa.dupont.com, tom@3ddd.com
Description:  Controller for page: EventToCallReport

TES20131023:  fix to unhandled exceptions:  Added try/catch around insert/update and
 truncate event.subject to 80chars when coverting to call report
********************************************************************************/
public with sharing class ctrlEventToCallReport {
    
    public static final string INITIATIVE_PREFIX    = Initiative__c.sObjectType.getDescribe().getKeyPrefix();
    public static final string CALLREPORT_PREFIX    = Call_Report__c.sObjectType.getDescribe().getKeyPrefix();

    public string               errMsg                  { get; set;}    
    public Event                event                   { get; set;} 
    public Contact              contact                 { get; private set;} 
    public Call_Report__c       callReport              { get; private set;} 
    
    public PageReference init() {
        string Id = ApexPages.currentPage().getParameters().get('id');
        
        try {
            event = [
                SELECT Id, AccountId, WhoId, WhatId, Subject, Direction__c, Description, Level_Of_Effort__c,
                Channel__c, Activity_Type__c, ActivityDate, Status__c, StartDateTime, EndDateTime, location
                FROM Event 
                WHERE id=:Id 
                LIMIT 1][0];
            system.debug('EVENT: --------->'+event);
        }
        catch (Exception ex) {
            errMsg='Unable to determine event. '+ex;
            return null;
        }

        if (event==null) {  
                errMsg='Unable to determine event. ';
                return null;
        }
        else {  
            
            if (event.WhatId!=null && String.valueOf(event.WhatId).startsWith(CALLREPORT_PREFIX)) {
                errMsg='Call Report already exists.';
                return null;
            }
            //Event must link to a contact or Account
            if ( ! (    ( event.WhoId!=null && String.valueOf(event.WhoId).startsWith('003')) || 
                        ( event.WhatId!=null && String.valueOf(event.WhatId).startsWith('001'))
                    )) {
                errMsg='The event must Relate to an Account or Contact. ';
                return null;
            }
            
    
            Call_Report__c callReport = new Call_Report__c();
            callReport.Account__c               = event.AccountId;
            callReport.Contact__c               = event.WhoId;
            callReport.Name                     = (event.subject.length()>80) ? event.subject.substring(0,80) : event.subject;
            //KT [11072017]: To remove Direction__c reference
            //callReport.Direction__c             = event.Direction__c;
            callReport.Status__c                = event.Status__c;
            callReport.Channel__c               = event.Channel__c;
            callReport.Activity_Type__c         = event.Activity_Type__c;
            callReport.Activity_Date__c         = event.ActivityDate;
            //KT [11082017]: To remove Level_of_Effort_hours__c reference
            //callReport.Level_of_Effort_hours__c = event.Level_Of_Effort__c;
            //KT [11072017]: To remove Origin_Channel_Type__c reference
            //callReport.Origin_Channel_Type__c   = 'Event';
    
            //description
            string descr='';
            if (event.StartDateTime != null)        descr+='StartTime: '    + event.StartDateTime.format()+'\n';
            if (event.EndDateTime   != null)        descr+='EndTime: '      + event.EndDateTime.format()+'\n';
            if (event.location      != null)        descr+='Location: '     + event.Location+'\n';
            if (event.Description   != null)        descr+='Description: '  + event.Description;
            callReport.Activity_Description__c=descr;
                
            if (event.WhatId!=null) {
                if ( String.valueOf(event.WhatId).startsWith(INITIATIVE_PREFIX)) {
                    callReport.Related_Initiative__c=event.WhatId;
                }
                else if (String.valueOf(event.WhatId).startsWith('001')) {
                    //do nothing,  just allow
                }
                else {
                    errMsg='The event RelatedTo can only be of type: Initiative or Account';
                    return null;
                }
            } //WhatId!=null
        
            system.debug('callReport: --------->'+callReport);
            //TES20131023 Added try/catch around insert/update
            try {
                insert callReport;
                system.debug('callReportId: --------->'+callReport.id);
                update new Event(id=event.id, WhatId=callReport.id);
            }catch(Exception ex) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Error: '+ex));
            }
        
            //Redirect to CallSCript in Edit mode....
            string url = '/'+callReport.id+'/e?retURL=/'+callReport.id;
            PageReference p = new PageReference(url);
            p.setRedirect(true);
            return p;   
            
        }  //event!=null
        
        return null;
    }



////////////////////////////////////////////////////////////////////////////////////
//      Test script(s)
////////////////////////////////////////////////////////////////////////////////////



    //public class EventToCallReportException extends Exception {}

}