DuPont DevSB/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>IsPublic__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>TRUE if this Campaign can be publicly displayed externally</inlineHelpText>
        <label>IsPublic</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PublicName__c</fullName>
        <description>Name of this campaign shown to public  (IE web sites, printed material, etc...)</description>
        <inlineHelpText>Name visible to external audience</inlineHelpText>
        <label>Public Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Owning_Organization__c</fullName>
        <description>SBU(Strategic Business Unit)-BU(Business Unit)-SubBU(Business or Product Line)</description>
        <inlineHelpText>Relevant sub-business for the Owning Business</inlineHelpText>
        <label>Owning Organization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>DSS-Clean Technologies</fullName>
                </value>
                <value>
                    <fullName>DSS-Consulting</fullName>
                </value>
                <value>
                    <fullName>DSS-L&amp;D</fullName>
                </value>
                <value>
                    <fullName>IB-Biomaterials-BioIsoprene</fullName>
                </value>
                <value>
                    <fullName>SHE</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Owning_SBU__c</fullName>
        <label>Owning SBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Building Innovations</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Industrial Biosciences</fullName>
                </value>
                <value>
                    <fullName>Marketing &amp; Sales</fullName>
                </value>
                <value>
                    <fullName>Performance Polymers</fullName>
                </value>
                <value>
                    <fullName>Protection Technologies</fullName>
                </value>
                <value>
                    <fullName>Safety Health &amp; Environment</fullName>
                </value>
                <value>
                    <fullName>Science &amp; Technology</fullName>
                </value>
                <value>
                    <fullName>Sustainable Solutions</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Geo Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Categorization of inquiry or lead used to determine process for handling and used for metrics.</description>
        <inlineHelpText>Type or category of an inquiry or sales lead.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alleged Incident</fullName>
                </value>
                <value>
                    <fullName>Call Request</fullName>
                </value>
                <value>
                    <fullName>Call Request - Face to Face</fullName>
                </value>
                <value>
                    <fullName>Career Opportunities</fullName>
                </value>
                <value>
                    <fullName>Certifications and Specifications</fullName>
                </value>
                <value>
                    <fullName>Code Compliance</fullName>
                </value>
                <value>
                    <fullName>Color Tools</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Contest</fullName>
                </value>
                <value>
                    <fullName>Contributions</fullName>
                </value>
                <value>
                    <fullName>Counterfeit Report</fullName>
                </value>
                <value>
                    <fullName>Data Sheet</fullName>
                </value>
                <value>
                    <fullName>Demo Request</fullName>
                </value>
                <value>
                    <fullName>Design &amp; Product Selection</fullName>
                </value>
                <value>
                    <fullName>Directory Assistance</fullName>
                </value>
                <value>
                    <fullName>Environmental Information</fullName>
                </value>
                <value>
                    <fullName>Export Procedures</fullName>
                </value>
                <value>
                    <fullName>Fabrication Assistance</fullName>
                </value>
                <value>
                    <fullName>General Company Info</fullName>
                </value>
                <value>
                    <fullName>General Feedback</fullName>
                </value>
                <value>
                    <fullName>Government Relations</fullName>
                </value>
                <value>
                    <fullName>Human Resources</fullName>
                </value>
                <value>
                    <fullName>Installation Assistance</fullName>
                </value>
                <value>
                    <fullName>Intellectual Assets &amp; Licensing</fullName>
                </value>
                <value>
                    <fullName>Investor Relations</fullName>
                </value>
                <value>
                    <fullName>Issue - Public Affairs</fullName>
                </value>
                <value>
                    <fullName>Lead Nurturing</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Literature</fullName>
                </value>
                <value>
                    <fullName>M/SDS &amp; Regulatory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>W2L_ExtendedData__c</fullName>
        <description>the field contain extendend data passed from Web-to-lead that can be decoded back into sfdc to enhance the Web-to-lead functionality</description>
        <label>W2L_ExtendedData</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>dummy</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/SiteObject__c.object
<CustomObject>
    <description>This abstract object is a site element that could be one of many types (i.e. subscription center, subscription list, form, subform, formfield, call script)</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to a campaign</description>
        <inlineHelpText>Campaign related to this site object</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Site Objects</relationshipLabel>
        <relationshipName>Site_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>for subscription List the ExternalId = (OrgId+CampaignId)</description>
        <externalId>true</externalId>
        <inlineHelpText>System Unique identifier for OrgId+CampaignId</inlineHelpText>
        <label>ExternalId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsPublic__c</fullName>
        <defaultValue>true</defaultValue>
        <description>TRUE if this Site Object can be publicly displayed externally (e.g. a Subscription Center)</description>
        <inlineHelpText>TRUE if this Site Object can be publicly displayed externally (e.g. a Subscription Center)</inlineHelpText>
        <label>IsPublic</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Owning_Organization__c</fullName>
        <label>Owning Organization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AGCP-CPC</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-Env</fullName>
                </value>
                <value>
                    <fullName>BI-Landscape Systems</fullName>
                </value>
                <value>
                    <fullName>BI-Surf</fullName>
                </value>
                <value>
                    <fullName>DEC-Packaging Graphics</fullName>
                </value>
                <value>
                    <fullName>DPP-Parts</fullName>
                </value>
                <value>
                    <fullName>DPP-Polymers</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
                <value>
                    <fullName>DPT-A&amp;HF</fullName>
                </value>
                <value>
                    <fullName>DPT-Agriculture</fullName>
                </value>
                <value>
                    <fullName>DPT-Air and Filtration</fullName>
                </value>
                <value>
                    <fullName>DPT-Aramids</fullName>
                </value>
                <value>
                    <fullName>DPT-ASPS</fullName>
                </value>
                <value>
                    <fullName>DPT-Chemical Industrial</fullName>
                </value>
                <value>
                    <fullName>DPT-Cleanroom/Pharma</fullName>
                </value>
                <value>
                    <fullName>DPT-Critical Clean</fullName>
                </value>
                <value>
                    <fullName>DPT-Envelopes</fullName>
                </value>
                <value>
                    <fullName>DPT-Graphics</fullName>
                </value>
                <value>
                    <fullName>DPT - IPP</fullName>
                </value>
                <value>
                    <fullName>DPT-Mechanical Industrial</fullName>
                </value>
                <value>
                    <fullName>DPT-Medical Fabrics</fullName>
                </value>
                <value>
                    <fullName>DPT-Medical Packaging</fullName>
                </value>
                <value>
                    <fullName>DPT-Medical Specialties</fullName>
                </value>
                <value>
                    <fullName>DPT-NOW</fullName>
                </value>
                <value>
                    <fullName>DPT-Optical</fullName>
                </value>
                <value>
                    <fullName>DPT-PM</fullName>
                </value>
                <value>
                    <fullName>DPT-Public Sector-ER</fullName>
                </value>
                <value>
                    <fullName>DPT-Public Sector-LE</fullName>
                </value>
                <value>
                    <fullName>DPT-Public Sector-MIL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PublicName__c</fullName>
        <description>Default Public name for this Site Object</description>
        <inlineHelpText>Default Public name for this Site Object</inlineHelpText>
        <label>Public Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReturnUrl__c</fullName>
        <description>used for Subscription centers and is used as the redirect when after center update is submitted</description>
        <inlineHelpText>URL displayed after the successful completion of a Site Submit in this Site Object</inlineHelpText>
        <label>ReturnUrl</label>
        <type>Url</type>
    </fields>
    <label>Site Object</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Objects</pluralLabel>
    <recordTypes>
        <fullName>MemberPortal</fullName>
        <active>true</active>
        <description>Member Portal a single function portal that uses a simple key for authentication</description>
        <label>Member Portal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/trigLeadParseW2LExtendedData_UT.cls
/*******************************************************************************
Copyright Â© 2012 DuPont. All rights reserved. 
Author: Vijay Laxmi
Email: vijay.laxmi1@tcs.com
Description:  Unit testclass for trigLeadParseW2LExtendedData on 20170428
   
********************************************************************************/

@isTest
public class trigLeadParseW2LExtendedData_UT{
    public static testMethod void testtrigLeadParseW2LExtendedData(){

        Campaign camp = new Campaign(name='Test MemberPortal Campaign ');
        insert camp;        

        SiteObject__c so = new SiteObject__c(Name='Test MP', PublicName__c='Test MP',
             RecordTypeId=MemberPortal.RTYPE_SO_MEMBERPORTAL,
             IsPublic__c=true, ExternalId__c='00Dundefined',campaign__c=camp.id, ReturnUrl__c='apex/somepage');
        insert so;

        Lead l=new Lead();
        l.Owning_SBU__c='Chemicals & Fluoroproducts';
        l.Owning_Organization__c='DCF-ChemSol';
        l.Country='India';
        l.Region__c='Acia Pacific';
        l.FirstName='From';
        l.LastName='TestClass';
        l.Company='Dupont';
        l.W2L_ExtendedData__c = '00Dundefined:yes';
        l.Type__c='Literature';
        l.status='Qualify';
        l.email = 'test@test.com';
        insert l;   
    }
}