DuPont DevSB/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>PublicName__c</fullName>
        <description>Name of this campaign shown to public  (IE web sites, printed material, etc...)</description>
        <inlineHelpText>Name visible to external audience</inlineHelpText>
        <label>Public Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>LastUpdatedLocation__c</fullName>
        <inlineHelpText>The tag of the traffic source which triggered the Last Membership change (e.g. name of website, email Campaign, etc)</inlineHelpText>
        <label>Last Update Source Tag</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fEmail__c</fullName>
        <formula>If(Contact.Email!=null,Contact.Email, 
if(Lead.Email!=null, Lead.Email, null))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
</CustomObject>

DuPont DevSB/src/objects/Email__c.object
<CustomObject>
    <description>Each record represents a unique email in the system, user for:
-Privacy Notification</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email Address (External Id Unique)</description>
        <externalId>true</externalId>
        <inlineHelpText>Email Address</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>Email</label>
    <nameField>
        <label>EM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/SiteObject__c.object
<CustomObject>
    <description>This abstract object is a site element that could be one of many types (i.e. subscription center, subscription list, form, subform, formfield, call script)</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>for subscription List the ExternalId = (OrgId+CampaignId)</description>
        <externalId>true</externalId>
        <inlineHelpText>System Unique identifier for OrgId+CampaignId</inlineHelpText>
        <label>ExternalId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PublicName__c</fullName>
        <description>Default Public name for this Site Object</description>
        <inlineHelpText>Default Public name for this Site Object</inlineHelpText>
        <label>Public Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Site Object</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Objects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/SiteObjectValue__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>unique id for subscription center =:  ORGID+CampaignId+email</description>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LastUpdatedLocation__c</fullName>
        <label>LastUpdatedLocation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SiteObject__c</fullName>
        <label>Site Object</label>
        <referenceTo>SiteObject__c</referenceTo>
        <relationshipLabel>Site Object Values</relationshipLabel>
        <relationshipName>Site_Object_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Site Object Value</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Object Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlMySubscriptions.cls
public class ctrlMySubscriptions {

    public LIST<SiteObjectValue__c> sovs    {set; get;}
    public LIST<CampaignMember>     members {set; get;}
    public string                   email   {set; get;}
    
//////////////////////////////////////////////////////////////////////////////////////
    public pageReference init() {
        
        email = ApexPages.currentPage().getParameters().get('em');

        sovs = [
            SELECT Id, Value__c,  SiteObject__c, SiteObject__r.Id, SiteObject__r.Name, Name, LastUpdatedLocation__c, 
            LastModifiedDate, LastModifiedById, 
            ExternalId__c, Email__c,  ConnectionSentId, ConnectionReceivedId From SiteObjectValue__c s
            Where Email__c = : email
            ORDER BY SiteObject__r.Name
            ];
        
        
        
        members = [
            SELECT CampaignId, campaign.PublicName__c, Status, LeadId, ContactId,
             HasResponded, FirstRespondedDate
            From CampaignMember
            Where fEmail__c = : email and campaign.recordType.name='Subscriber List'
            ORDER BY campaign.PublicName__c Limit 1000
            
        ];
        
        
        
        return null;
    }
    
    
////////////////////////////////////////////////////////////////////////////////////
//      Test script(s)
////////////////////////////////////////////////////////////////////////////////////

public static testMethod void test_ctrlMySubscriptions() {

        Test.startTest();
        PageReference pageRef = Page.MySubscriptions;
        Test.setCurrentPage(pageRef);
        ctrlMySubscriptions controller = new ctrlMySubscriptions();
        controller.init();
        Test.stopTest();
    
    } 

}