DuPont DevSB/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>List_Type__c</fullName>
        <inlineHelpText>Master: For Opted-In
Campaign: For a specific Campaign
Test Group: For a test group
Segment: For a segment of Contacts to be used for reporting purposes only</inlineHelpText>
        <label>List Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Campaign Test</fullName>
                </value>
                <value>
                    <fullName>Grouping</fullName>
                </value>
                <value>
                    <fullName>Master</fullName>
                </value>
                <value>
                    <fullName>Subscriber</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin_Tracking_Code__c</fullName>
        <description>A Reference code associated with the Campaign, such as Omniture Tracking Code</description>
        <inlineHelpText>A Reference code associated with the Campaign, such as Omniture Tracking Code</inlineHelpText>
        <label>Origin Tracking Code</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Organizational_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizational Group</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Origin_Name__c</fullName>
        <description>Specific Origin channel name for :
CALLS : phone number (800# or description on phone display)     
WEBSITE INQUIRIES: select name of CONTACT US FORM or common website URL 
 Note: Use Campaigns or First Referrer name field for Trade Show name or other origin details</description>
        <inlineHelpText>select phone number (display) for calls 
select webform name or URL for web inquiries</inlineHelpText>
        <label>Origin Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2013 FGF Energy Whitepaper Download</fullName>
                </value>
                <value>
                    <fullName>2013 FGF Protection Whitepaper Download</fullName>
                </value>
                <value>
                    <fullName>4-1000</fullName>
                </value>
                <value>
                    <fullName>Account statement</fullName>
                </value>
                <value>
                    <fullName>Brasil 800</fullName>
                </value>
                <value>
                    <fullName>DDF 800-441-0575</fullName>
                </value>
                <value>
                    <fullName>DIMC-Local-Corp Phone</fullName>
                </value>
                <value>
                    <fullName>DIMC-Local-SBU Phone</fullName>
                </value>
                <value>
                    <fullName>DIMC-Regional-Corp Phone</fullName>
                </value>
                <value>
                    <fullName>eCommerce - State Available</fullName>
                </value>
                <value>
                    <fullName>Follow The Truck</fullName>
                </value>
                <value>
                    <fullName>food.dupont.cn</fullName>
                </value>
                <value>
                    <fullName>http://www2.dupont.com/DuPont_Safety_Resources/zh_CN/</fullName>
                </value>
                <value>
                    <fullName>Inbound Other</fullName>
                </value>
                <value>
                    <fullName>info.mexico@mex.dupont.com</fullName>
                </value>
                <value>
                    <fullName>Inquiry Center</fullName>
                </value>
                <value>
                    <fullName>Mexico Local</fullName>
                </value>
                <value>
                    <fullName>Mioge</fullName>
                </value>
                <value>
                    <fullName>National Safety Congress</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
                <value>
                    <fullName>Partner Form</fullName>
                </value>
                <value>
                    <fullName>PI/General</fullName>
                </value>
                <value>
                    <fullName>Privacy Breach</fullName>
                </value>
                <value>
                    <fullName>Social Login</fullName>
                </value>
                <value>
                    <fullName>www.coastaltraining.cn</fullName>
                </value>
                <value>
                    <fullName>www.dupont.ca</fullName>
                </value>
                <value>
                    <fullName>www.dupont.co.in/Shunya_Download</fullName>
                </value>
                <value>
                    <fullName>www.dupont.com</fullName>
                </value>
                <value>
                    <fullName>www.dupont.com/40_40/en_GB</fullName>
                </value>
                <value>
                    <fullName>www.dupont.com/ANZ short form</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin_Tracking_Code__c</fullName>
        <description>Use this field to pass detailed web tracking codes or information for better metrics reporting</description>
        <inlineHelpText>Use this field to pass detailed web tracking codes or information for better metrics reporting</inlineHelpText>
        <label>Origin Tracking Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFRIKAANS</fullName>
                </value>
                <value>
                    <fullName>ALBANIAN</fullName>
                </value>
                <value>
                    <fullName>ARABIC</fullName>
                </value>
                <value>
                    <fullName>ARMENIAN</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJANI</fullName>
                </value>
                <value>
                    <fullName>BASQUE</fullName>
                </value>
                <value>
                    <fullName>BULGARIAN</fullName>
                </value>
                <value>
                    <fullName>BURMESE</fullName>
                </value>
                <value>
                    <fullName>BYELORUSSIAN</fullName>
                </value>
                <value>
                    <fullName>CHINESE</fullName>
                </value>
                <value>
                    <fullName>CHINESE (Traditional)</fullName>
                </value>
                <value>
                    <fullName>CROATIAN</fullName>
                </value>
                <value>
                    <fullName>CZECH</fullName>
                </value>
                <value>
                    <fullName>DANISH</fullName>
                </value>
                <value>
                    <fullName>DUTCH</fullName>
                </value>
                <value>
                    <fullName>ENGLISH</fullName>
                </value>
                <value>
                    <fullName>ESTONIAN</fullName>
                </value>
                <value>
                    <fullName>FINNISH</fullName>
                </value>
                <value>
                    <fullName>FRENCH</fullName>
                </value>
                <value>
                    <fullName>GERMAN</fullName>
                </value>
                <value>
                    <fullName>GREEK</fullName>
                </value>
                <value>
                    <fullName>HEBREW</fullName>
                </value>
                <value>
                    <fullName>HINDI</fullName>
                </value>
                <value>
                    <fullName>HUNGARIAN</fullName>
                </value>
                <value>
                    <fullName>ICELANDIC</fullName>
                </value>
                <value>
                    <fullName>INDONESIAN</fullName>
                </value>
                <value>
                    <fullName>ITALIAN</fullName>
                </value>
                <value>
                    <fullName>JAPANESE</fullName>
                </value>
                <value>
                    <fullName>KOREAN</fullName>
                </value>
                <value>
                    <fullName>LATIN</fullName>
                </value>
                <value>
                    <fullName>PORTUGUESE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/LeadHandler.cls
/*******************************************************************************
Copyright © 2012 DuPont. All rights reserved. 
Author: Thomas Snyder
Email: thomas.snyder@usa.dupont.com, tom@3ddd.com
Description:  Lead trigger handler

TES20131104 - Added logic for dealing with trigger sub-batching (this.hasFired)
NS20160303 - For PopulatePreferredLanguage in Lead Object
MR20160518 - Assign Regions for N&H using Organizational_Group__c (duplicate account and contact process)
    
********************************************************************************/
public class LeadHandler extends TriggerHandlerBase {

    static final string CAMPAIGN_PREFIX = Campaign.sObjectType.getDescribe().getKeyPrefix();

    static boolean InProcess = false;   //avoid recursion
  
    public override void bulkAfter(){
        if (!this.hasFired) //new sub-batch
            InProcess=false;
        if (!InProcess) {
            InProcess=true;
            if (Trigger.IsInsert) {
                EmailBase.leads_onAfter();
                originTrackingCodeToMembers(System.Trigger.new);
            }
            if (Trigger.IsUpdate) { 
                EmailBase.leads_onAfter();
            }
        }
    }    
    /* NS20160303
    START LOGIC
     Issue # :IS ID-00066047
    Description:  Once in field Origin Name is selected Brasil 800 in Lead Object,
             After Saving automatically into the field PREFERRED LANGUAGE should be filled with PORTUGUESE.*/
    
    public static void  PopulatePreferredLanguage(List<Lead> Leadlist){
        if(Trigger.IsBEFORE){
            if(Trigger.IsINSERT ||Trigger.IsUpdate){
                for(Lead leadobj:Leadlist){
                    if(leadobj.Origin_Name__c =='Brasil 800'){
                        leadobj.Preferred_Language__c ='PORTUGUESE'; 
                    } 
                }
            }
        }
        
    }
    /*END LOGIC */
  public override void bulkBefore(){
    if (Trigger.IsInsert) {
        LeadContactMapping.Lead_OnBeforeInsert(Trigger.new);
    }
    LeadScoring.scoreLeads(Trigger.new,this.getRulesEngineResults());
    
    // TES20131114:  Attenpt to fix Autoresponse issue
    for  (Lead l : (LIST<Lead>) Trigger.new) {
        Database.DMLOptions dmlo = new Database.DMLOptions();
        dmlo.EmailHeader.triggerAutoResponseEmail = true;
        //dmlo.AssignmentRuleHeader.UseDefaultRule=true;
        //dmlo.EmailHeader.triggerUserEmail = true; 
        l.setOptions(dmlo);
    } 
    //<MR20160518> Assign Regions for N&H using Organizational_Group__c
    //NH_Lead_Helper.AssignRegion(this);
  }   


  private static void originTrackingCodeToMembers(LIST<Lead> leads){
    //group leads (potential members) by campaign id
    MAP<Id, LIST<Lead>> leadsByCamp = new MAP<Id, LIST<Lead>>();  //MAP<campId,LIST<Lead>>
    for(Lead objLead: leads){
      string campid=tCodeToCampId(objLead.Origin_Tracking_Code__c);
      if (campid!=null) {
        if (!leadsByCamp.containsKey(campid))
          leadsByCamp.put(campid, new LIST<Lead>());
        leadsByCamp.get(campid).add(objLead);
      }
    }
    //validate campaign existence
    LIST<string> exemptListTypes = new LIST<string>{'Subscriber','Master'};
    Map<Id,Campaign> campaignMap = new Map<Id,Campaign>([
       SELECT Id FROM Campaign WHERE Id IN :leadsByCamp.keySet() 
      AND List_Type__c not in :exemptListTypes]);
    
    //insert members
    LIST<CampaignMember> newMembers = new LIST<CampaignMember>();  
    for(Id campId : leadsByCamp.keySet()) {
      if (campaignMap.containskey(campId)) {
        for (Lead l : leadsByCamp.get(campid))
          newMembers.add(new CampaignMember(campaignid=campid,leadid=l.id));
      }
    }
    database.insert(newMembers,false);
  }


  private static string tCodeToCampId(string tcode) {
    if (tcode!=null && tcode.contains(CAMPAIGN_PREFIX)){
      integer  campaignIdIndex=tcode.indexOf(CAMPAIGN_PREFIX, 0);
      if  (campaignIdIndex+15<=tcode.Length())
        return tcode.substring(campaignIdIndex, campaignIdIndex+15);
    }
    return null;
  }

}