DuPont DevSB/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DPT-Aramids</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP</fullName>
                </value>
                <value>
                    <fullName>DPT-NOW</fullName>
                </value>
                <value>
                    <fullName>DTT</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Queue__c</fullName>
        <label>Lead Queue</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin_Name__c</fullName>
        <description>Specific Origin channel name for :
CALLS : phone number (800# or description on phone display)     
WEBSITE INQUIRIES: select name of CONTACT US FORM or common website URL 
 Note: Use Campaigns or First Referrer name field for Trade Show name or other origin details</description>
        <inlineHelpText>select phone number (display) for calls 
select webform name or URL for web inquiries</inlineHelpText>
        <label>Origin Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2013 FGF Energy Whitepaper Download</fullName>
                </value>
                <value>
                    <fullName>2013 FGF Protection Whitepaper Download</fullName>
                </value>
                <value>
                    <fullName>4-1000</fullName>
                </value>
                <value>
                    <fullName>Account statement</fullName>
                </value>
                <value>
                    <fullName>Brasil 800</fullName>
                </value>
                <value>
                    <fullName>DDF 800-441-0575</fullName>
                </value>
                <value>
                    <fullName>DIMC-Local-Corp Phone</fullName>
                </value>
                <value>
                    <fullName>DIMC-Local-SBU Phone</fullName>
                </value>
                <value>
                    <fullName>DIMC-Regional-Corp Phone</fullName>
                </value>
                <value>
                    <fullName>eCommerce - State Available</fullName>
                </value>
                <value>
                    <fullName>Follow The Truck</fullName>
                </value>
                <value>
                    <fullName>food.dupont.cn</fullName>
                </value>
                <value>
                    <fullName>http://www2.dupont.com/DuPont_Safety_Resources/zh_CN/</fullName>
                </value>
                <value>
                    <fullName>Inbound Other</fullName>
                </value>
                <value>
                    <fullName>info.mexico@mex.dupont.com</fullName>
                </value>
                <value>
                    <fullName>Inquiry Center</fullName>
                </value>
                <value>
                    <fullName>Mexico Local</fullName>
                </value>
                <value>
                    <fullName>Mioge</fullName>
                </value>
                <value>
                    <fullName>National Safety Congress</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
                <value>
                    <fullName>Partner Form</fullName>
                </value>
                <value>
                    <fullName>PI/General</fullName>
                </value>
                <value>
                    <fullName>Privacy Breach</fullName>
                </value>
                <value>
                    <fullName>Social Login</fullName>
                </value>
                <value>
                    <fullName>www.coastaltraining.cn</fullName>
                </value>
                <value>
                    <fullName>www.dupont.ca</fullName>
                </value>
                <value>
                    <fullName>www.dupont.co.in/Shunya_Download</fullName>
                </value>
                <value>
                    <fullName>www.dupont.com</fullName>
                </value>
                <value>
                    <fullName>www.dupont.com/40_40/en_GB</fullName>
                </value>
                <value>
                    <fullName>www.dupont.com/ANZ short form</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>This is the Salesforce.com program associated with this Lead.</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>QUAL</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Geo Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Contact_Status__c</fullName>
        <description>To identify if Lead is matched to a Contact</description>
        <label>Related Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed-Single Contact</fullName>
                </value>
                <value>
                    <fullName>In Progress-Multiple Contacts</fullName>
                </value>
                <value>
                    <fullName>In Progress-No Contact</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Main Contact related to this record (e.g. Common Mailing Contact address in Refinish)</inlineHelpText>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Lead_Contact_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting used to link the incoming Lead to an existing contact based on the email Id</description>
    <fields>
        <fullName>Campaign_Id__c</fullName>
        <inlineHelpText>Example format : Campaign ID = 701Q00000006h2r.  
(Maximum 5 Campaign ID&apos;s in Comma separated format)</inlineHelpText>
        <label>Campaign Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Geo_Region__c</fullName>
        <label>Contact Geo Region</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Program__c</fullName>
        <label>Contact Program</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Record_Type__c</fullName>
        <description>Contacts&apos; Record Type</description>
        <label>Contact Record Type</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Origin_Name__c</fullName>
        <description>Lead&apos;s Origin Name</description>
        <label>Lead Origin Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Lead Contact Mapping</label>
</CustomObject>

DuPont DevSB/src/classes/LeadContactMapping.cls
/*******************************************************************************
Copyright © 2011 DuPont. All rights reserved. 
Author: Smita Kadian
Email: Smita.Kadian@usa.dupont.com
Date: 28 July 2011
Description: Class called from the trigger 'trigLeadContactMapping' to associate
			 incoming lead to a contact and set the flag.
********************************************************************************/
public without sharing class LeadContactMapping{
	public static final Id RecordTypeIdLead	=Rtype.getIdByDevName('Lead','Level 2 DPP EMEA');
	public static void Lead_OnBeforeInsert(List<Lead> leadsList){
		for(Lead l:leadsList){
			if(l.LeadSource=='Website' && l.RecordTypeId==RecordTypeIdLead && l.Lead_Queue__c=='DPP Level 2 EMEA'){
				//Variable Declaration
				String leadOrigin=l.Origin_Name__c;
				String leadEmail=l.Email;
				List<Lead_Contact_Mapping__c> leadContactList = new List<Lead_Contact_Mapping__c>();
				List<Contact> contactList=new List<Contact>();
				Set<Id> campContactSet=new Set<Id>();
				List<String> campIDList=new List<String>();
				List<Contact> campMembContactList=new List<Contact>();
				List<String> contactRecordTypeList=new List<String>();
				List<String> contactProgramList=new List<String>();
				List<String> contactRegionList=new List<String>();
				//Searching for lead origin name in custom setting object
				leadContactList = [select Contact_Geo_Region__c,Contact_Program__c,Campaign_Id__c,Contact_Record_Type__c,Lead_Origin_Name__c from Lead_Contact_Mapping__c where Lead_Origin_Name__c=:leadOrigin limit 1];
				if(leadContactList.size()!=0){
					String query='Select RecordType.Name,Program__c,Region__c,email from contact';
					String andWhere=' where ';
					//Splitting the comma seperated campaign Id text into list of strings
					if(leadContactList[0].Campaign_Id__c!=null){
						campIDList=leadContactList[0].Campaign_Id__c.trim().split(',');
						for(Integer i=0;i<campIDList.size();i++)campIDList[i]=campIDList[i].trim();
					}
					//Search for campaign members(Type:Contact)under the specified campaign ID with the same email id as that of the lead's
					campMembContactList=[select id from contact where email=:leadEmail and id IN (Select contactId from campaignMember where CampaignId IN :campIDList and contact.email=:leadEmail)];
					for(Contact con:campMembContactList)
					campContactSet.add(con.id);
					if(campMembContactList.size()==1){
						//if single contact found then assign it as the 'Related Contact' for the Lead and set the flag 'Related Contact Status'
						l.Related_Contact_Status__c='Completed-Single Contact';
						l.Related_Contact__c=campMembContactList[0].Id;
					}
					else if(campMembContactList.size()>1 || campMembContactList.size()==0 ){
						//In case of multiple contacts filter further on the corresponding fields for Contact in the custom setting
						if(leadContactList[0].Contact_Geo_Region__c!=null){
							contactRegionList=leadContactList[0].Contact_Geo_Region__c.trim().split(',');
							for(Integer i=0;i<contactRegionList.size();i++)contactRegionList[i]=contactRegionList[i].trim();
							query=query+andWhere+' Region__c IN  :contactRegionList  ';
							andWhere=' and ';
						}
						if(leadContactList[0].Contact_Program__c!=null){
							contactProgramList=leadContactList[0].Contact_Program__c.trim().split(',');
							for(Integer i=0;i<contactProgramList.size();i++)contactProgramList[i]=contactProgramList[i].trim();
							query=query+andWhere+' Program__c IN  :contactProgramList  ';
							andWhere=' and ';
						}
						if(leadContactList[0].Contact_Record_Type__c!=null){
							contactRecordTypeList=leadContactList[0].Contact_Record_Type__c.trim().split(',');
							for(Integer i=0;i<contactRecordTypeList.size();i++)contactRecordTypeList[i]=contactRecordTypeList[i].trim();
							query=query+andWhere+' RecordType.Name IN :contactRecordTypeList  ';
							andWhere=' and ';
						}
						if(campMembContactList.size()==0){
							//If no campaign members found, query the database irrespective of the campaign ID
							query=query+' and email=:leadEmail  limit 2  ';
							contactList=database.query(query);
						}
						else{
							contactList=database.query(query+' and email=:leadEmail and id IN :campContactSet  limit 2  ');
							if(contactList.size()==0){
								query=query+' and email=:leadEmail  limit 2  ';
								contactList=database.query(query);
							}
						}
						//Based on the no. of contacts found with same email id set the flag 'Related Contact Status' and field 'Related Contact'
						if(contactList.size()==1){
							l.Related_Contact_Status__c='Completed-Single Contact';
							l.Related_Contact__c=contactList[0].Id;
						}
						else if(contactList.size()>1 || contactList.size()==0){
							l.Related_Contact__c=null;
							l.Related_Contact_Status__c=null;
							if(contactList.size()>1)
								l.Related_Contact_Status__c='In Progress-Multiple Contacts';
							else if(contactList.size()==0)
								l.Related_Contact_Status__c='In Progress-No Contact';
						}
					}
				}
			}
		}
	}
}