DuPont DevSB/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Origin_Tracking_Code__c</fullName>
        <description>A Reference code associated with the Campaign, such as Omniture Tracking Code</description>
        <inlineHelpText>A Reference code associated with the Campaign, such as Omniture Tracking Code</inlineHelpText>
        <label>Origin Tracking Code</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Country__c</fullName>
        <label>Lead Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Åland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin_Tracking_Code__c</fullName>
        <description>Use this field to pass detailed web tracking codes or information for better metrics reporting</description>
        <inlineHelpText>Use this field to pass detailed web tracking codes or information for better metrics reporting</inlineHelpText>
        <label>Origin Tracking Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>StateName__c</fullName>
        <label>State Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/trigLeadGeoValidation_UT.cls
@isTest(seeAllData=true)
private class trigLeadGeoValidation_UT{

   static testMethod void leadTestMethod() {
        List<Lead> objLeadList = new List<Lead>();
        Campaign objCampaign = new Campaign(Name='Test');
        Insert objCampaign;
        objCampaign.Origin_Tracking_Code__c =objCampaign.Id;
        Update objCampaign;
        for(Integer i=0;i<25;i++){
            Lead objLead = new Lead(lastname='Test', Origin_Tracking_Code__c=objCampaign.Id, Company='Test Company');
            objLeadList.add(objLead);
        }
        Insert objLeadList;
        
        Update([select Id from Lead where Id =:objLeadList[0].Id]);
    }
    static testMethod void leadTestMethod2() {
        List<Lead> objLeadList = new List<Lead>();
        Campaign objCampaign = new Campaign(Name='Test');
        Insert objCampaign;
        objCampaign.Origin_Tracking_Code__c =objCampaign.Id;
        Update objCampaign;
        for(Integer i=0;i<25;i++){
            Lead objLead = new Lead(lastname='Test', Origin_Tracking_Code__c=objCampaign.Id, Company='Test Company', Lead_Country__c ='USA',StateName__c = 'New York');
            objLeadList.add(objLead);
        }
        geoValidation gvld = new geoValidation();
        geoValidation.validateInTestMode = true;
        geoValidation.GeoValidationDisabled();
        Insert objLeadList;
        geoValidation gvld2 = new geoValidation();
        geoValidation.validateInTestMode = true;
        geoValidation.GeoValidationDisabled();
        Update([select Id from Lead where Id =:objLeadList[0].Id]);
    }
    
}