DuPont DevSB/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SAP Order Number or the Document Number</description>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Entitlement.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for this entitlement, likely the contact that activated this entitlement.</description>
        <inlineHelpText>Primary contact for this entitlement, likely the contact that activated this entitlement.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Document Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Qualification__c.object
<CustomObject>
    <description>List of current or past Qualifications and Certifications of this Partner or Account</description>
    <label>Qualification</label>
    <nameField>
        <displayFormat>QL{YY}{MM}-{0000}</displayFormat>
        <label>Qualification Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/SFDC_Answer__c.object
<CustomObject>
    <description>The range of possible answers for a given question. Each answer has a score, and caller coaching, and determines the follow on question to ask.</description>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order the answer appears in the list of answers</description>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <description>The question object that the answer applies to.</description>
        <label>Question</label>
        <referenceTo>SFDC_Questions__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>The relative weight assigned to this answer.  Note: This is relative weight, not absolute weight.</description>
        <label>Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>AN-{000000}</displayFormat>
        <label>Answer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/SFDC_FollowOnQuestion__c.object
<CustomObject>
    <description>Junction object representing a list of follow on questions to ask for a given answer.</description>
    <fields>
        <fullName>Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The answer ID field in the junction object.</description>
        <label>Answer</label>
        <referenceTo>SFDC_Answer__c</referenceTo>
        <relationshipLabel>Follow On Questions</relationshipLabel>
        <relationshipName>R00N30000001GaNBEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionOrder__c</fullName>
        <label>QuestionOrder</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The question field on the junction object.</description>
        <label>Question</label>
        <referenceTo>SFDC_Questions__c</referenceTo>
        <relationshipLabel>Follow On Questions</relationshipLabel>
        <relationshipName>FollowOnQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Script</label>
        <referenceTo>SFDC_Script__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>FollowOnQuestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FollowOnQuestion</label>
    <nameField>
        <label>Follow On Question ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FollowOnQuestions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/SFDC_Questions__c.object
<CustomObject>
    <fields>
        <fullName>AllowChange__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allow change of a script result.   Only Applicable if Script.AllowContinuation is true</description>
        <inlineHelpText>Allow edit of a script result.   Only Applicable if Script.AllowContinuation is true</inlineHelpText>
        <label>Allow Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Answer_Format__c</fullName>
        <description>Only includes Radio Button today, as that is what the scoring supports.  When multiple answers can be chosen a multi select option can be added.</description>
        <label>Answer Format</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Radio Button</fullName>
                    <default>true</default>
                    <label>Radio Button</label>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DataType__c</fullName>
        <label>DataType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                    <label>Text</label>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Radiolist</fullName>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Decimal</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>MultiSelect Checkboxes</fullName>
                </value>
                <value>
                    <fullName>MultiSelect Picklist</fullName>
                </value>
                <value>
                    <fullName>Section - TextBlock</fullName>
                </value>
                <value>
                    <fullName>Section - Header</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DefaultAnswer__c</fullName>
        <description>Default Answer</description>
        <label>DefaultAnswer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Where the field Is Required.</description>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsVisible__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If the field is visible on the SiteScript page.  This can be used for hide bindings for static information to a record (recordtype, ownerid) , or for softly removing obsolete fields</description>
        <label>IsVisible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_Coach__c</fullName>
        <description>Coaching advice for the person asking the question.</description>
        <label>Question Coach</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SaveResult__c</fullName>
        <defaultValue>true</defaultValue>
        <description>uncheck this if you do not want it to be added to the script header.</description>
        <label>Save Result</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This relationship serves no programatic purpose. It may be useful to note the intended script when creating the questions, especially as the number of questions increase.</description>
        <label>Script</label>
        <referenceTo>SFDC_Script__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>Code/name used to Identify Question when selecting using the SiteScript class.  This allow you to select a question wo/ the need bound to the id or the name which has a tenancy to change.</description>
        <externalId>true</externalId>
        <inlineHelpText>Code/name used to Identify Question when selecting using the SiteScript class.  This allow you to select a question wo/ the need bound to the id or the name which has a tenancy to change.</inlineHelpText>
        <label>ShortName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WriteToField__c</fullName>
        <description>The API name of the field to populate on the WriteToObject</description>
        <inlineHelpText>The API name of the field to populate on the WriteToObject</inlineHelpText>
        <label>WriteToField</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/SFDC_Script__c.object
<CustomObject>
    <fields>
        <fullName>AllowContinuation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows you to continue/edit a script.   To Allow for Continuation, you must have an Avail With Object specified otherwise no script header/results are created</description>
        <inlineHelpText>To Allow for Continuation, you must have an Avail With Object specified.</inlineHelpText>
        <label>AllowContinuation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Available_With__c</fullName>
        <label>Available With</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Leads</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Cases</fullName>
                </value>
                <value>
                    <fullName>Opportunities</fullName>
                </value>
                <value>
                    <fullName>Accounts</fullName>
                </value>
                <value>
                    <fullName>Qualification__cs</fullName>
                </value>
                <value>
                    <fullName>Request__cs</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
                <value>
                    <fullName>Entitlements</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReturnToType__c</fullName>
        <label>ReturnToType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ReturnURL</fullName>
                </value>
                <value>
                    <fullName>Available_With Object</fullName>
                </value>
                <value>
                    <fullName>WriteTo Object</fullName>
                </value>
                <value>
                    <fullName>Script Header</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReturnToValue__c</fullName>
        <description>Determine where to redirect on save,  Value is dependant on ReturnToType
ReturnUrl: Expects a valid url
AvalibleWith Object: Object Name
Header, WriteTo Object:  no value required</description>
        <inlineHelpText>Determine where to redirect on save,  Value is dependant on ReturnToType
ReturnUrl: Expects a valid url
AvalibleWith Object: Object Name
Header, WriteTo Object:  no value required</inlineHelpText>
        <label>ReturnToValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use_Scoring__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Use Scoring</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WriteToObject__c</fullName>
        <description>SiteScript: API name of Object to write to.  use with Save_To_Field.</description>
        <inlineHelpText>SiteScript: API name of Object to write to.  use with Save_To_Field.</inlineHelpText>
        <label>Write To Object</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Script</label>
    <nameField>
        <label>Script Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Script</pluralLabel>
    <recordTypes>
        <fullName>SiteScript</fullName>
        <active>true</active>
        <description>SiteScript</description>
        <label>SiteScript</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlBINA_InvestionReports_UT.cls
/////////////////////////////////////////////////////////////////////////////////////////////////////////
//Copyright © 2014 DuPont. All rights reserved. 
//Name :ctrlBINA_InvestionReports_UT
//Author :Rajiv Kumar Bhatter<Rajiv_Bhatter@infosys.com>, Sanjay Nandi<Sanjay_Nandi@infosys.com>
//Description: This  UT class for controller  ctrlBINA_InvestionReports
//************************************<MG-20140827>***************************************************//
@isTest(SeeAllData=true)
public class ctrlBINA_InvestionReports_UT{

 static testMethod void testctrlBINA_InvestionReports() {
    Final Id SITERECTYPEID = Rtype.getIdByDevName('SFDC_Script__c','SiteScript');
    Profile p=[SELECT id,name from Profile where Name=:'System Administrator' LIMIT 1];
    User user1=[SELECT id,name from User where IsActive=: true and ProfileId =: p.Id LIMIT 1];
     System.runAs(user1){

  SFDC_Script__c ss = new SFDC_Script__c(
    name='Project Information',
    Available_With__c ='Account;Contact;Lead;Case;Qualification__c;Entitlements',
    WriteToObject__c='Entitlement',
    ReturnToType__c='WriteToObject',
    AllowContinuation__c=true,
    Use_Scoring__c=true,
    ReturnToValue__c=null 
 
    );

   insert ss;  
        
   SFDC_Questions__c Ques1=new SFDC_Questions__c(Name='RegistrationID',Script__c=ss.Id,Answer_Format__c='Checkbox',ShortName__c='id',DefaultAnswer__c='@param.var',
                     WriteToField__c='id',AllowChange__c=True, SaveResult__c=True,IsRequired__C= true,IsVisible__c=True,DataType__c='Text', Question_Coach__c='BINA TYVEK');
   SFDC_Questions__c Ques2=new SFDC_Questions__c(Name='Sheathing Type',Script__c=ss.Id,Answer_Format__c='Checkbox',ShortName__c='Sheathing Type',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true,IsVisible__c=True,DataType__c='MultiSelect Picklist', Question_Coach__c='BINA TYVEK');
   SFDC_Questions__c Ques3=new SFDC_Questions__c(Name='Wall Cladding Type',Script__c=ss.Id,Answer_Format__c='Checkbox',ShortName__c='Wall Cladding Type',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true, IsVisible__c=True,DataType__c='MultiSelect Picklist', Question_Coach__c='BINA TYVEK');
   SFDC_Questions__c Ques4=new SFDC_Questions__c(Name='Framing Type',Script__c=ss.Id,Answer_Format__c='Checkbox',ShortName__c='Framing Type',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true,IsVisible__c=True,DataType__c='MultiSelect Picklist', Question_Coach__c='BINA TYVEK');
     
   insert new LIST<SFDC_Questions__c> {Ques1,Ques2,Ques3,Ques4};
   
    SFDC_FollowOnQuestion__c fq1 = new SFDC_FollowOnQuestion__c(Script__c=ss.id, Question__c=Ques1.id, QuestionOrder__c=1);
    SFDC_FollowOnQuestion__c fq2 = new SFDC_FollowOnQuestion__c(Script__c=ss.id, Question__c=Ques2.id, QuestionOrder__c=2);
    SFDC_FollowOnQuestion__c fq3 = new SFDC_FollowOnQuestion__c(Script__c=ss.id, Question__c=Ques3.id, QuestionOrder__c=3);
    SFDC_FollowOnQuestion__c fq4 = new SFDC_FollowOnQuestion__c(Script__c=ss.id, Question__c=Ques4.id, QuestionOrder__c=4);
    insert new LIST<SFDC_FollowOnQuestion__c> {fq1,fq2,fq3,fq4};
    
     
    SFDC_Answer__c an4 = new SFDC_Answer__c(Score__c=0, Order__c=1, Answer__c='Sheathing - Plywood', Questions__c=Ques2.id);
    SFDC_Answer__c an5 = new SFDC_Answer__c(Score__c=0, Order__c=2, Answer__c='Sheathing - OSB', Questions__c=Ques2.id);
    SFDC_Answer__c an6 = new SFDC_Answer__c(Score__c=0, Order__c=3, Answer__c='Sheathing - Exterior Insulation', Questions__c=Ques2.id);
    insert new LIST<SFDC_Answer__c> {an4,an5,an6};
    
    SFDC_Answer__c an1 = new SFDC_Answer__c(Score__c=0, Order__c=1, Answer__c='Wall Cladding - Brick Mason', Questions__c=Ques3.id);
    SFDC_Answer__c an2 = new SFDC_Answer__c(Score__c=0, Order__c=2, Answer__c='Wall Cladding - Stone Venn', Questions__c=Ques3.id);
    SFDC_Answer__c an3 = new SFDC_Answer__c(Score__c=0, Order__c=3, Answer__c='Wall Cladding - Stucco', Questions__c=Ques3.id);
    insert new LIST<SFDC_Answer__c> {an1,an2,an3};
    
    SFDC_Answer__c an7 = new SFDC_Answer__c(Score__c=0, Order__c=1, Answer__c='Framing - 2X4 Wood', Questions__c=Ques4.id);
    SFDC_Answer__c an8 = new SFDC_Answer__c(Score__c=0, Order__c=2, Answer__c='Framing - 2X6 Wood', Questions__c=Ques4.id);
    SFDC_Answer__c an9 = new SFDC_Answer__c(Score__c=0, Order__c=3, Answer__c='Framing - 2X8 Wood', Questions__c=Ques4.id);
    insert new LIST<SFDC_Answer__c> {an7,an8,an9}; 
    
    SiteScript scriptTest = new SiteScript(ss.id);
       system.debug('the Scriptnamed is.......'+scriptTest);       
        Account acc= new Account(name='testacc');
        insert acc;
        Contact con=new contact(Firstname='Sanjay', LastName='Nandi',Email='sanjay31nandi@infosys.com',MailingStreet='Abc',MailingCity='Abc',MobilePhone='0000000000',Phone='12345',MailingState='XYZ',MailingPostalCode='12345',MailingCountry='United States', AccountId=acc.id);
        insert con;
        Entitlement ent= new Entitlement(name='TestEntit',primary_contact__c=con.id, Accountid=acc.id);
        insert ent;
        DateTime dT = System.now();
        Case cas=new case(
            EntitlementId=ent.id,
            Submitted_By_First_Name_Last_Name__c='sanjay',
            Case_Shipping_Address__c='Abc',
            Alt_Phone__c='00000000',
            Problem_Description__c='Test',
            Description='test',
            Date_Entered__c=date.newinstance(dT.year(), dT.month(), dT.day()),
            status='new',  ownerId=user1.Id);
        insert cas;
       
        scriptTest.getQuestion('Wall Cladding Type').answer=an1.answer__c;
        scriptTest.getQuestion('Sheathing Type').answer=an1.answer__c;
        system.debug('this is sanjay');
        scriptTest.getQuestion('Framing Type').answer=an7.answer__c;
        scriptTest.getQuestion('id').answer=ent.id;
        scriptTest.save();
       

   
        ApexPages.currentPage().getParameters().put('id', cas.id);
        ApexPAges.StandardController sc = new ApexPages.StandardController(cas);
        ctrlBINA_InvestionReports c = new ctrlBINA_InvestionReports (sc);
        
      }
  }
}