DuPont DevSB/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SubType__c</fullName>
        <description>Select a Subtype that most closely relates to the Type.</description>
        <label>SubType</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Late</fullName>
                </value>
                <value>
                    <fullName>Missing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlEmailTaskDetails.cls
public class ctrlEmailTaskDetails{
    public string XactivityId;
    public Task task{get;set;}
    public Case casedetails{get;set;}
    public String fullRecordURL{get;set;}
    public string activityId{
       get{return XactivityId;}
       set{
            XactivityId = value;
            task = [Select subject,Id,Status,SubType__c,ActivityDate,Completion_Date__c,whatId,Owner.Name from task where Id = :XactivityId];
            casedetails = [select CaseNumber from Case where Id =:task.WhatId];
            fullRecordURL = URL.getSalesforceBaseUrl().toExternalForm() + '/';
          }
      }
}