DuPont DevSB/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SAP Order Number or the Document Number</description>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/SFDC_Answer__c.object
<CustomObject>
    <description>The range of possible answers for a given question. Each answer has a score, and caller coaching, and determines the follow on question to ask.</description>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order the answer appears in the list of answers</description>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <description>The question object that the answer applies to.</description>
        <label>Question</label>
        <referenceTo>SFDC_Questions__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>AN-{000000}</displayFormat>
        <label>Answer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/SFDC_FollowOnQuestion__c.object
<CustomObject>
    <description>Junction object representing a list of follow on questions to ask for a given answer.</description>
    <fields>
        <fullName>Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The answer ID field in the junction object.</description>
        <label>Answer</label>
        <referenceTo>SFDC_Answer__c</referenceTo>
        <relationshipLabel>Follow On Questions</relationshipLabel>
        <relationshipName>R00N30000001GaNBEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionOrder__c</fullName>
        <label>QuestionOrder</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The question field on the junction object.</description>
        <label>Question</label>
        <referenceTo>SFDC_Questions__c</referenceTo>
        <relationshipLabel>Follow On Questions</relationshipLabel>
        <relationshipName>FollowOnQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Script</label>
        <referenceTo>SFDC_Script__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>FollowOnQuestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FollowOnQuestion</label>
    <nameField>
        <label>Follow On Question ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FollowOnQuestions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/SFDC_Questions__c.object
<CustomObject>
    <fields>
        <fullName>AllowChange__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allow change of a script result.   Only Applicable if Script.AllowContinuation is true</description>
        <inlineHelpText>Allow edit of a script result.   Only Applicable if Script.AllowContinuation is true</inlineHelpText>
        <label>Allow Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Answer_Format__c</fullName>
        <description>Only includes Radio Button today, as that is what the scoring supports.  When multiple answers can be chosen a multi select option can be added.</description>
        <label>Answer Format</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Radio Button</fullName>
                    <default>true</default>
                    <label>Radio Button</label>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DataType__c</fullName>
        <label>DataType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                    <label>Text</label>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Radiolist</fullName>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Decimal</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>MultiSelect Checkboxes</fullName>
                </value>
                <value>
                    <fullName>MultiSelect Picklist</fullName>
                </value>
                <value>
                    <fullName>Section - TextBlock</fullName>
                </value>
                <value>
                    <fullName>Section - Header</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DefaultAnswer__c</fullName>
        <description>Default Answer</description>
        <label>DefaultAnswer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <description>Text entry field that allows to assign a question to a group.This can be used to group questions and scoring in Reports or dashboards.</description>
        <label>Group</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Where the field Is Required.</description>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsVisible__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If the field is visible on the SiteScript page.  This can be used for hide bindings for static information to a record (recordtype, ownerid) , or for softly removing obsolete fields</description>
        <label>IsVisible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_Coach__c</fullName>
        <description>Coaching advice for the person asking the question.</description>
        <label>Question Coach</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SaveResult__c</fullName>
        <defaultValue>true</defaultValue>
        <description>uncheck this if you do not want it to be added to the script header.</description>
        <label>Save Result</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This relationship serves no programatic purpose. It may be useful to note the intended script when creating the questions, especially as the number of questions increase.</description>
        <label>Script</label>
        <referenceTo>SFDC_Script__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>Code/name used to Identify Question when selecting using the SiteScript class.  This allow you to select a question wo/ the need bound to the id or the name which has a tenancy to change.</description>
        <externalId>true</externalId>
        <inlineHelpText>Code/name used to Identify Question when selecting using the SiteScript class.  This allow you to select a question wo/ the need bound to the id or the name which has a tenancy to change.</inlineHelpText>
        <label>ShortName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WriteToField__c</fullName>
        <description>The API name of the field to populate on the WriteToObject</description>
        <inlineHelpText>The API name of the field to populate on the WriteToObject</inlineHelpText>
        <label>WriteToField</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/SFDC_Script__c.object
<CustomObject>
    <fields>
        <fullName>AllowContinuation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows you to continue/edit a script.   To Allow for Continuation, you must have an Avail With Object specified otherwise no script header/results are created</description>
        <inlineHelpText>To Allow for Continuation, you must have an Avail With Object specified.</inlineHelpText>
        <label>AllowContinuation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Available_With__c</fullName>
        <label>Available With</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Leads</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Cases</fullName>
                </value>
                <value>
                    <fullName>Opportunities</fullName>
                </value>
                <value>
                    <fullName>Accounts</fullName>
                </value>
                <value>
                    <fullName>Qualification__cs</fullName>
                </value>
                <value>
                    <fullName>Request__cs</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
                <value>
                    <fullName>Entitlements</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReturnToType__c</fullName>
        <label>ReturnToType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ReturnURL</fullName>
                </value>
                <value>
                    <fullName>Available_With Object</fullName>
                </value>
                <value>
                    <fullName>WriteTo Object</fullName>
                </value>
                <value>
                    <fullName>Script Header</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReturnToValue__c</fullName>
        <description>Determine where to redirect on save,  Value is dependant on ReturnToType
ReturnUrl: Expects a valid url
AvalibleWith Object: Object Name
Header, WriteTo Object:  no value required</description>
        <inlineHelpText>Determine where to redirect on save,  Value is dependant on ReturnToType
ReturnUrl: Expects a valid url
AvalibleWith Object: Object Name
Header, WriteTo Object:  no value required</inlineHelpText>
        <label>ReturnToValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use_Scoring__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Use Scoring</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WriteToObject__c</fullName>
        <description>SiteScript: API name of Object to write to.  use with Save_To_Field.</description>
        <inlineHelpText>SiteScript: API name of Object to write to.  use with Save_To_Field.</inlineHelpText>
        <label>Write To Object</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Script</label>
    <nameField>
        <label>Script Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Script</pluralLabel>
    <recordTypes>
        <fullName>SiteScript</fullName>
        <active>true</active>
        <description>SiteScript</description>
        <label>SiteScript</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlBINA_EnvelopesRegistration_WB_UT.cls
/////////////////////////////////////////////////////////////////////////////////////////////////////////
//Copyright © 2017 DuPont. All rights reserved. 
//Name :ctrlBINA_EnvelopesRegistration_WB_UT
//Author : Sairam Kumar
//Description: This  UT class for controller ctrlBINA_EnvelopesRegistration_WB 

//***************************************************************************************//

@isTest
public class ctrlBINA_EnvelopesRegistration_WB_UT{

  static testMethod  void testctrlBINA_EnvelopesRegistration_WB_UT() {
     
    Final Id SITERECTYPEID = Rtype.getIdByDevName('SFDC_Script__c','SiteScript');
    Profile p=[SELECT id,name from Profile where Name=:'System Administrator' LIMIT 1];
    User user1=[SELECT id,name from User where IsActive=: true and ProfileId =: p.Id LIMIT 1];
    Final Id PRODUCT_ONLY_FLUID_WB_REG_RTYPE = Rtype.getIdByDevName('Entitlement','BI_NA_Env_Product_Only_Fluid_Applied_WB');
    Final Id PRODUCTlABOUR_FLUID_WB_EIFS_REG_RTYPE = Rtype.getIdByDevName('Entitlement','BI_NA_Env_Product_Labor_Fluid_Applied_WB_w_EIFS');
    

     System.runAs(user1){
       
  SFDC_Script__c ss1 = new SFDC_Script__c(
    name='Project Information WB+',
    Available_With__c ='Account;Contact;Lead;Case;Qualification__c;Entitlements',
    WriteToObject__c='Entitlement',
    ReturnToType__c='WriteToObject',
    AllowContinuation__c=true,
    Use_Scoring__c=true,
    ReturnToValue__c=null 
 
    );
    
   
  SFDC_Script__c ss2 = new SFDC_Script__c(
    name='Certified Installer Information',
    Available_With__c ='Account;Contact;Lead;Case;Qualification__c;Entitlements',
    WriteToObject__c='Entitlement',
    ReturnToType__c='WriteToObject',
    AllowContinuation__c=true,
    Use_Scoring__c=true,
    ReturnToValue__c=null 
 
    );
   
   
  SFDC_Script__c ss3 = new SFDC_Script__c(
    name='Related Contact Information',
    Available_With__c ='Account;Contact;Lead;Case;Qualification__c;Entitlements',
    WriteToObject__c='Entitlement',
    ReturnToType__c='WriteToObject',
    AllowContinuation__c=true,
    Use_Scoring__c=true,
    ReturnToValue__c=null 
 
    );
   
   
  SFDC_Script__c ss4 = new SFDC_Script__c(
    name='Estimated Product Exposure Time(in Days)',
    Available_With__c ='Account;Contact;Lead;Case;Qualification__c;Entitlements',
    WriteToObject__c='Entitlement',
    ReturnToType__c='WriteToObject',
    AllowContinuation__c=true,
    Use_Scoring__c=true,
    ReturnToValue__c=null 
 
    );
   
   // Added 
  SFDC_Script__c ss5 = new SFDC_Script__c(
    name='Certified Installer Information WB',
    Available_With__c ='Account;Contact;Lead;Case;Qualification__c;Entitlements',
    WriteToObject__c='Entitlement',
    ReturnToType__c='WriteToObject',
    AllowContinuation__c=true,
    Use_Scoring__c=true,
    ReturnToValue__c=null 
 
    );
     
        
 SFDC_Script__c ss6 = new SFDC_Script__c(
    name='Warranty Dates',
    Available_With__c ='Account;Contact;Lead;Case;Qualification__c;Entitlements',
    WriteToObject__c='Entitlement',
    ReturnToType__c='WriteToObject',
    AllowContinuation__c=true,
    Use_Scoring__c=true,
    ReturnToValue__c=null 
 
    );
         
    SFDC_Script__c ss7 = new SFDC_Script__c(
    name='Project Information WB+ w/EIFS',
    Available_With__c ='Account;Contact;Lead;Case;Qualification__c;Entitlements',
    WriteToObject__c='Entitlement',
    ReturnToType__c='WriteToObject',
    AllowContinuation__c=true,
    Use_Scoring__c=true,
    ReturnToValue__c=null 
 
    );

   insert new LIST<SFDC_Script__c> {ss1,ss2,ss3,ss5,ss4,ss6,ss7};
   
   
   SFDC_Questions__c Ques1=new SFDC_Questions__c(Name='RegistrationID',Script__c=ss1.Id,Answer_Format__c='Checkbox',ShortName__c='id',DefaultAnswer__c='@param.var',
                     WriteToField__c='id',AllowChange__c=True, SaveResult__c=True,IsRequired__C= false,IsVisible__c=True,DataType__c='Text', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
   SFDC_Questions__c Ques2=new SFDC_Questions__c(Name='Building Height (number of stories)',Script__c=ss1.Id,Answer_Format__c='Checkbox',ShortName__c='Building Height (number of stories)',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true,IsVisible__c=True,DataType__c='Integer', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
   SFDC_Questions__c Ques3=new SFDC_Questions__c(Name='Building Size (sq. ft.)',Script__c=ss1.Id,Answer_Format__c='Checkbox',ShortName__c='Building Size',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true,IsVisible__c=True,DataType__c='Integer', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
   SFDC_Questions__c Ques4=new SFDC_Questions__c(Name='Sheathing Type',Script__c=ss1.Id,Answer_Format__c='Checkbox',ShortName__c='Sheathing Type',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true,IsVisible__c=True,DataType__c='MultiSelect Picklist', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
   SFDC_Questions__c Ques5=new SFDC_Questions__c(Name='Wall Cladding Type',Script__c=ss1.Id,Answer_Format__c='Checkbox',ShortName__c='Wall Cladding Type',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true, IsVisible__c=True,DataType__c='MultiSelect Picklist', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
   SFDC_Questions__c Ques6=new SFDC_Questions__c(Name='Framing Type',Script__c=ss1.Id,Answer_Format__c='Checkbox',ShortName__c='Framing Type',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true,IsVisible__c=True,DataType__c='MultiSelect Picklist', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
   SFDC_Questions__c Ques7=new SFDC_Questions__c(Name='Certified Installer Name',Script__c=ss2.Id,Answer_Format__c='Checkbox',ShortName__c='Certified Installer Name',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= false,IsVisible__c=True,DataType__c='Text', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
   SFDC_Questions__c Ques8=new SFDC_Questions__c(Name='Certified Installer #',Script__c=ss2.Id,Answer_Format__c='Checkbox',ShortName__c='Certified Installer',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= false,IsVisible__c=True,DataType__c='Text', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
   SFDC_Questions__c Ques9=new SFDC_Questions__c(Name='Related Account',Script__c=ss3.Id,Answer_Format__c='Checkbox',ShortName__c='Related Account',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= false,IsVisible__c=True,DataType__c='Text', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
    SFDC_Questions__c Ques10=new SFDC_Questions__c(Name='Related Account Sub Type',Script__c=ss3.Id,Answer_Format__c='Checkbox',ShortName__c='Related Account Sub Type',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= false,IsVisible__c=True,DataType__c='Text', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
    SFDC_Questions__c Ques11=new SFDC_Questions__c(Name='Related Contact Name',Script__c=ss3.Id,Answer_Format__c='Checkbox',ShortName__c='Related Contact Name',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= false,IsVisible__c=True,DataType__c='Text', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
    SFDC_Questions__c Ques12=new SFDC_Questions__c(Name='Related Contact Email',Script__c=ss3.Id,Answer_Format__c='Checkbox',ShortName__c='Related Contact Email',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= false,IsVisible__c=True,DataType__c='Text', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
    SFDC_Questions__c Ques13=new SFDC_Questions__c(Name='Related Contact Phone Number',Script__c=ss3.Id,Answer_Format__c='Checkbox',ShortName__c='Related Contact Phone Number',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= false,IsVisible__c=True,DataType__c='Text', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');

    SFDC_Questions__c Ques14=new SFDC_Questions__c(Name='Estimated Product Exposure Time(In Days)',Script__c=ss4.Id,Answer_Format__c='text',ShortName__c='Estimated Product Exposure Time(In Days)',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true,IsVisible__c=True,DataType__c='Integer', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
         
    SFDC_Questions__c Ques15=new SFDC_Questions__c(Name='RegistrationID',Script__c=ss7.Id,Answer_Format__c='Checkbox',ShortName__c='id',DefaultAnswer__c='@param.var',
                     WriteToField__c='id',AllowChange__c=True, SaveResult__c=True,IsRequired__C= false,IsVisible__c=True,DataType__c='Text', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
   SFDC_Questions__c Ques16=new SFDC_Questions__c(Name='Building Height (number of stories)',Script__c=ss7.Id,Answer_Format__c='Checkbox',ShortName__c='Building Height (number of stories)',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true,IsVisible__c=True,DataType__c='Integer', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
   SFDC_Questions__c Ques17=new SFDC_Questions__c(Name='Building Size (sq. ft.)',Script__c=ss7.Id,Answer_Format__c='Checkbox',ShortName__c='Building Size',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true,IsVisible__c=True,DataType__c='Integer', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
   SFDC_Questions__c Ques18=new SFDC_Questions__c(Name='Sheathing Type',Script__c=ss7.Id,Answer_Format__c='Checkbox',ShortName__c='Sheathing Type',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true,IsVisible__c=True,DataType__c='MultiSelect Picklist', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
  
  SFDC_Questions__c Ques19=new SFDC_Questions__c(Name='EIFS System',Script__c=ss7.Id,Answer_Format__c='Checkbox',ShortName__c='EIFS System',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true,IsVisible__c=True,DataType__c='Text', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
  SFDC_Questions__c Ques20=new SFDC_Questions__c(Name='EIFS Manufacturer',Script__c=ss7.Id,Answer_Format__c='Checkbox',ShortName__c='EIFS Manufacturer',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true,IsVisible__c=True,DataType__c='Text', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
  
  SFDC_Questions__c Ques21=new SFDC_Questions__c(Name='Framing Type',Script__c=ss7.Id,Answer_Format__c='Checkbox',ShortName__c='Framing Type',
                      AllowChange__c=True, SaveResult__c=True,IsRequired__C= true,IsVisible__c=True,DataType__c='MultiSelect Picklist', Question_Coach__c='BINA TYVEK',Group__c='BINA TYVEK');
        
      
   
   insert new LIST<SFDC_Questions__c> {Ques1,Ques2,Ques3,Ques4,Ques5,Ques6,Ques7,Ques8,Ques9,Ques10,Ques11,Ques12,Ques13,Ques14,Ques15,Ques16,Ques17,Ques18,Ques19,Ques20,Ques21};
   
    SFDC_FollowOnQuestion__c fq1 = new SFDC_FollowOnQuestion__c(Script__c=ss1.id, Question__c=Ques1.id, QuestionOrder__c=1);
    SFDC_FollowOnQuestion__c fq2 = new SFDC_FollowOnQuestion__c(Script__c=ss1.id, Question__c=Ques2.id, QuestionOrder__c=2);
    SFDC_FollowOnQuestion__c fq3 = new SFDC_FollowOnQuestion__c(Script__c=ss1.id, Question__c=Ques3.id, QuestionOrder__c=3);
    SFDC_FollowOnQuestion__c fq4 = new SFDC_FollowOnQuestion__c(Script__c=ss1.id, Question__c=Ques4.id, QuestionOrder__c=4);
    SFDC_FollowOnQuestion__c fq5 = new SFDC_FollowOnQuestion__c(Script__c=ss1.id, Question__c=Ques5.id, QuestionOrder__c=5);
    SFDC_FollowOnQuestion__c fq6 = new SFDC_FollowOnQuestion__c(Script__c=ss1.id, Question__c=Ques6.id, QuestionOrder__c=6);
         
    SFDC_FollowOnQuestion__c fq7 = new SFDC_FollowOnQuestion__c(Script__c=ss2.id, Question__c=Ques1.id, QuestionOrder__c=1);
    SFDC_FollowOnQuestion__c fq8 = new SFDC_FollowOnQuestion__c(Script__c=ss2.id, Question__c=Ques7.id, QuestionOrder__c=2);
    
    SFDC_FollowOnQuestion__c fq9 = new SFDC_FollowOnQuestion__c(Script__c=ss5.id, Question__c=Ques1.id, QuestionOrder__c=1);
    SFDC_FollowOnQuestion__c fq19 = new SFDC_FollowOnQuestion__c(Script__c=ss5.id, Question__c=Ques7.id, QuestionOrder__c=2);   
    SFDC_FollowOnQuestion__c fq20 = new SFDC_FollowOnQuestion__c(Script__c=ss5.id, Question__c=Ques8.id, QuestionOrder__c=3);
         
    SFDC_FollowOnQuestion__c fq10 = new SFDC_FollowOnQuestion__c(Script__c=ss3.id, Question__c=Ques1.id, QuestionOrder__c=1);
    SFDC_FollowOnQuestion__c fq11 = new SFDC_FollowOnQuestion__c(Script__c=ss3.id, Question__c=Ques9.id, QuestionOrder__c=2);
    SFDC_FollowOnQuestion__c fq12 = new SFDC_FollowOnQuestion__c(Script__c=ss3.id, Question__c=Ques10.id, QuestionOrder__c=3);
    SFDC_FollowOnQuestion__c fq13 = new SFDC_FollowOnQuestion__c(Script__c=ss3.id, Question__c=Ques11.id, QuestionOrder__c=4);
    SFDC_FollowOnQuestion__c fq14 = new SFDC_FollowOnQuestion__c(Script__c=ss3.id, Question__c=Ques12.id, QuestionOrder__c=5);
    SFDC_FollowOnQuestion__c fq15 = new SFDC_FollowOnQuestion__c(Script__c=ss3.id, Question__c=Ques13.id, QuestionOrder__c=6);
    SFDC_FollowOnQuestion__c fq16 = new SFDC_FollowOnQuestion__c(Script__c=ss4.id, Question__c=Ques1.id, QuestionOrder__c=1);
    SFDC_FollowOnQuestion__c fq17 = new SFDC_FollowOnQuestion__c(Script__c=ss4.id, Question__c=Ques14.id, QuestionOrder__c=2);
    
    SFDC_FollowOnQuestion__c fq18 = new SFDC_FollowOnQuestion__c(Script__c=ss6.id, Question__c=Ques1.id, QuestionOrder__c=1);
     
    SFDC_FollowOnQuestion__c fq21 = new SFDC_FollowOnQuestion__c(Script__c=ss7.id, Question__c=Ques15.id, QuestionOrder__c=1);
    SFDC_FollowOnQuestion__c fq22 = new SFDC_FollowOnQuestion__c(Script__c=ss7.id, Question__c=Ques16.id, QuestionOrder__c=2);
    SFDC_FollowOnQuestion__c fq23 = new SFDC_FollowOnQuestion__c(Script__c=ss7.id, Question__c=Ques17.id, QuestionOrder__c=3);
    SFDC_FollowOnQuestion__c fq24 = new SFDC_FollowOnQuestion__c(Script__c=ss7.id, Question__c=Ques18.id, QuestionOrder__c=4);
    SFDC_FollowOnQuestion__c fq25 = new SFDC_FollowOnQuestion__c(Script__c=ss7.id, Question__c=Ques19.id, QuestionOrder__c=5);
    SFDC_FollowOnQuestion__c fq26 = new SFDC_FollowOnQuestion__c(Script__c=ss7.id, Question__c=Ques20.id, QuestionOrder__c=6);
    SFDC_FollowOnQuestion__c fq27 = new SFDC_FollowOnQuestion__c(Script__c=ss7.id, Question__c=Ques21.id, QuestionOrder__c=7);
    
    insert new LIST<SFDC_FollowOnQuestion__c> {fq1,fq2,fq3,fq4,fq5,fq6,fq7,fq8,fq9,fq10,fq11,fq12,fq13,fq14,fq15,fq16,fq17,fq18,fq19,fq20,fq21,fq22,fq23,fq24,fq25,fq26,fq27};
         
    SFDC_Answer__c an4 = new SFDC_Answer__c(Score__c=0, Order__c=1, Answer__c='Sheathing - Exterior Gypsum', Questions__c=Ques4.id);
    SFDC_Answer__c an5 = new SFDC_Answer__c(Score__c=0, Order__c=2, Answer__c='Sheathing - Exterior Insulation', Questions__c=Ques4.id);
    SFDC_Answer__c an6 = new SFDC_Answer__c(Score__c=0, Order__c=3, Answer__c='Sheathing - Glass Faced Gypsum', Questions__c=Ques4.id);
    SFDC_Answer__c an10 = new SFDC_Answer__c(Score__c=0, Order__c=3, Answer__c='	Sheathing - None', Questions__c=Ques4.id);
    SFDC_Answer__c an11 = new SFDC_Answer__c(Score__c=0, Order__c=3, Answer__c='	Sheathing - OSB', Questions__c=Ques4.id);
         
    insert new LIST<SFDC_Answer__c> {an4,an5,an6,an10,an11};
    
    SFDC_Answer__c an1 = new SFDC_Answer__c(Score__c=0, Order__c=1, Answer__c='Wall Cladding - Brick Mason', Questions__c=Ques5.id);
    SFDC_Answer__c an2 = new SFDC_Answer__c(Score__c=0, Order__c=2, Answer__c='Wall Cladding - Stone Venn', Questions__c=Ques5.id);
    SFDC_Answer__c an3 = new SFDC_Answer__c(Score__c=0, Order__c=3, Answer__c='Wall Cladding - Stucco', Questions__c=Ques5.id);
    insert new LIST<SFDC_Answer__c> {an1,an2,an3};
    
    SFDC_Answer__c an7 = new SFDC_Answer__c(Score__c=0, Order__c=1, Answer__c='Framing - 2X4 Wood', Questions__c=Ques6.id);
    SFDC_Answer__c an8 = new SFDC_Answer__c(Score__c=0, Order__c=2, Answer__c='Framing - 2X6 Wood', Questions__c=Ques6.id);
    SFDC_Answer__c an9 = new SFDC_Answer__c(Score__c=0, Order__c=3, Answer__c='Framing - 2X8 Wood', Questions__c=Ques6.id);
    insert new LIST<SFDC_Answer__c> {an7,an8,an9}; 
    
    geoValidation.validateInTestMode=false;
    Account acc= new Account(name='testacc');
    insert acc;
        
    Entitlement ent= new Entitlement();
    Entitlement ent1= new Entitlement();     
           
    DateTime dT = System.now();
      
    Entitlement__C e1=new Entitlement__C(Name='5_Tyvek® Fluid Applied WB+™',Record_Type__c='Product Only WB+',Products__C='Tyvek® Fluid Applied WB+™', Application__c='< 5 Stories');
    Entitlement__C e2=new Entitlement__C(Name='5_Tyvek® Fluid Applied Flashing',Record_Type__c='Product Only WB+',Products__C='Tyvek® Fluid Applied Flashing & Joint Compound+',Application__c='< 5 Stories');
    Entitlement__C e3=new Entitlement__C(Name='5_DuPont™ Sealant for Tyvek®',Record_Type__c='Product Only WB+',Products__C='DuPont™ Sealant for Tyvek® Fluid Applied',Application__c='< 5 Stories');
    insert new LIST<Entitlement__C> {e1,e2,e3};
            
    test.StartTest();
         
    System.debug('recordtype id is'+PRODUCTlABOUR_FLUID_WB_EIFS_REG_RTYPE);
    
   
    
   // Product and labour Fluid Applied WB EIFS
  
    ApexPages.currentPage().getParameters().put('RecordType',PRODUCTlABOUR_FLUID_WB_EIFS_REG_RTYPE);
    ApexPages.currentPage().getParameters().put('def_account_id',acc.id);
    ApexPages.currentPage().getParameters().put('ent','Entitlement');
    ApexPages.currentPage().getParameters().put('retURL','abc');
    ApexPAges.StandardController sc = new ApexPages.StandardController(ent);
    ctrlBINA_EnvelopesRegistration_WB c2 = new ctrlBINA_EnvelopesRegistration_WB (sc);
        
    ent.name='test';
    ent.Registration_Address__c='somnething';
    ent.Registration_City__c='xyz';
    ent.Registration_State_Province__c='AK';
    ent.Registration_Postal_Code__c='560188';
    ent.Registration_Country1__c='United States';
    ent.Lot_Nb__c='abc';
    ent.startdate=date.newinstance(2017,12,31);
    ent.Building_Type__c='Multi-Family';
    ent.Application_Type__c='Commercial';
    ent.Product_Answer1__c='';
  
    
    c2.initScript();
    c2.cancel();
    c2.productAnswer();
    c2.validationScript();
    c2.checkBox1=false;
    c2.checkBox2=false;
    c2.checkBox3=false;     
    c2.productSelection();
    c2.entit.Product_Answer1__c='';
    c2.saveEnt();
    
    ent.Lot_Nb__c='12';
    ent.Registration_Postal_Code__c='56010';
    
    c2.checkBox1=true;
    c2.checkBox2=true;
    c2.checkBox3=true;     
    c2.saveEnt();
    
   
    c2.script1.getQuestion('Building Height (number of stories)').answer='1';
    System.debug('Script1 is' +c2.script1);
    c2.script1.getQuestion('Building Size').answer= '2';
    c2.script2.getQuestion('Certified Installer Name').answer='shub';
    c2.script3.getQuestion('Related Account').answer='sairam';
    c2.script4.getQuestion('Estimated Product Exposure Time(In Days)').answer='12';

    c2.saveEnt();
    c2.selectedMaterials.clear();
    c2.saveEnt();
    ent.startdate=date.newinstance(2014,02, 29);
    c2.saveEnt();        
   
    /// Product Only Fluid Applied WB+
    //
   
    ApexPages.currentPage().getParameters().put('RecordType',PRODUCT_ONLY_FLUID_WB_REG_RTYPE);
    ApexPages.currentPage().getParameters().put('def_account_id',acc.id);
    ApexPages.currentPage().getParameters().put('ent','Entitlement');
    ApexPages.currentPage().getParameters().put('retURL','abc');  
    ApexPAges.StandardController sc1 = new ApexPages.StandardController(ent1);
    ctrlBINA_EnvelopesRegistration_WB c3 = new ctrlBINA_EnvelopesRegistration_WB (sc1);
        
    ent1.name='test';
    ent1.Registration_Address__c='somnething';
    ent1.Registration_City__c='xyz';
    ent1.Registration_State_Province__c='AK';
    ent1.Registration_Postal_Code__c='56018';
    ent1.Registration_Country1__c='United States';
    ent1.Lot_Nb__c='12';
    ent1.startdate=date.newinstance(2016,01,01);
    ent1.Building_Type__c='Multi-Family';
    ent1.Application__c='< 5 Stories';
    ent1.Application_Type__c='Commercial';
    
    
    c3.initScript();
    c3.cancel();
    c3.productAnswer();
    c3.validationScript();
    c3.checkBox1=true;
    c3.checkBox2=true;
    c3.checkBox3=true; 
     c3.productSelection();
  //  c3.saveEnt();
    
    ent1.Lot_Nb__c='12';
    ent1.Registration_Postal_Code__c='56010';
    
    
    c3.checkBox1=true;
    c3.checkBox2=true;
    c3.checkBox3=true;     
 
    
    c3.AllMaterials.add(new SelectOption('DuPont™ Sealant for Tyvek® Fluid Applied', 'DuPont™ Sealant for Tyvek® Fluid Applied'));
    c3.SelectedMaterials.add(new SelectOption('DuPont™ Sealant for Tyvek® Fluid Applied', 'DuPont™ Sealant for Tyvek® Fluid Applied'));
    c3.saveEnt();
         
  
   
    c3.Script1=new SiteScript(ss7.id);
    c3.script4=new SiteScript(ss4.id);   
         
    c3.script1.getQuestion('Building Height (number of stories)').answer='1';
    c3.script1.getQuestion('Building Size').answer= '2';
    c3.script1.getQuestion('Framing Type').answer='Framing - 2X6 Wood';
    c3.script1.getQuestion('Sheathing Type').answer='Sheathing - OSB';
    c3.script1.getQuestion('EIFS System').answer='sairam';
    c3.script1.getQuestion('EIFS Manufacturer').answer='pqr';  
    c3.script4.getQuestion('Estimated Product Exposure Time(In Days)').answer='12';  
    c3.Script2=new SiteScript(ss5.id);
    c3.Script3=new SiteScript(ss3.id);
    c3.saveEnt();
    c3.selectedMaterials.clear();
   
    c3.productSelection();
    

       Test.StopTest();
      }
  }
    
}