DuPont DevSB/src/objects/Catalog_Item__c.object
<CustomObject>
    <description>Catalog Items are the individual Sales Aids contained in a Catalog to be selected for fulfillment of a Request and Catalog Item Subscriptions</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Catalog Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Request__c.object
<CustomObject>
    <description>Multiple purpose Object where various Requests and Transaction Types can be created and tracked throughout the system</description>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Instructions__c</fullName>
        <description>Instructions to successfully perform this Request</description>
        <label>Instructions</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority of Request</description>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                </value>
                <value>
                    <fullName>Rush</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Shipping_City__c</fullName>
        <description>Request shipping city mapped from Contact or Lead Mailing Address by sControl</description>
        <label>Shipping City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Shipping_Country__c</fullName>
        <description>Request Shipping Country mapped from Contact or Lead Country by sControl</description>
        <label>Shipping Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Shipping_Postal_Code__c</fullName>
        <description>Request Shipping Postal code mapped from Contact or Lead Mailing address by sControl</description>
        <label>Shipping Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Shipping_State__c</fullName>
        <description>Request Shipping State mapped from Contact or Lead mailing address by sControl</description>
        <label>Shipping State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Shipping_Street__c</fullName>
        <description>Request Shipping Street mapped from Contact or Lead mailing address by sControl</description>
        <label>Shipping Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Company__c</fullName>
        <description>The Company to which the labels are delivered/shipped.</description>
        <label>Send to Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Contact__c</fullName>
        <description>The Contact person who receives the labels.</description>
        <label>Send to Contact</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Reason__c</fullName>
        <description>Reason why this request is in a specific Stage</description>
        <inlineHelpText>Reason why this request is in a specific Stage</inlineHelpText>
        <label>Stage Reason</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Request</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Behind Schedule</fullName>
                </value>
                <value>
                    <fullName>In Approval</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
                <value>
                    <fullName>Error: Rejected by Supplier</fullName>
                </value>
                <value>
                    <fullName>Sent to Supplier</fullName>
                </value>
                <value>
                    <fullName>Accepted by Supplier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>RQ-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Request_Item__c.object
<CustomObject>
    <description>Line items on a Request</description>
    <fields>
        <fullName>Catalog_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Catalog Item which relates to this Request Item.  (i.e Sales Aid Fulfillment)</description>
        <label>Catalog Item</label>
        <referenceTo>Catalog_Item__c</referenceTo>
        <relationshipLabel>Request Items</relationshipLabel>
        <relationshipName>R00N30000001uwx6EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Used to identify the quantity of Request Items (i.e. Sales Aids) in a specific line item on a Request</description>
        <label>Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>The Request to which this Request Item is related</description>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Request Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The Supplier&apos;s acknowledgment of the Request Item</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Capture</fullName>
                    <default>true</default>
                    <label>Capture</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request Item</label>
    <nameField>
        <displayFormat>ITM-{YY}{MM}{DD}-{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/SampleRequestWSInfo__mdt.object
<CustomObject>
    <description>Parameters for test and prod Donelly web service</description>
    <fields>
        <fullName>Debug__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Debug</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SampleRequestWSInfo</label>
    <pluralLabel>SampleRequestWSInfos</pluralLabel>
</CustomObject>

DuPont DevSB/src/classes/SampleRequestWS.cls
public class SampleRequestWS {
    @InvocableMethod(label='Call WS' description='Call Donelly Web Service')
    public static void callWS(List<Id> reqIds) {
        for (Id reqId : reqIds) {
            System.debug('Call with ' + reqId);
            wsCallout(reqId);
        }
    }
    
    @future(callout=true)
    public static void wsCallout(string recordId){
        Organization org = [SELECT InstanceName, IsSandbox FROM Organization];
        String instanceName;
        if(org.IsSandbox){
            instanceName = 'Test';
        }else{
            instanceName = 'Prod';
        }
        SampleRequestWSInfo__mdt wsInfo = [SELECT URL__c, UserName__c, Password__c, Debug__c
                       FROM SampleRequestWSInfo__mdt 
                       WHERE Label = :instanceName];

        Request__c request = [select Name,Comments__c,CreatedBy.FirstName,CreatedBy.LastName,CreatedBy.Street,CreatedBy.City,
                              CreatedBy.State,CreatedBy.PostalCode,CreatedBy.Country,CreatedBy.Phone,CreatedBy.Email,
                              Priority__c,Instructions__c,Send_to_Contact__c,Send_to_Company__c,Request_Shipping_Street__c,
                              Request_Shipping_City__c,Request_Shipping_State__c,Request_Shipping_Postal_Code__c,
                              Request_Shipping_Country__c,Phone__c,Status__c,Stage_Reason__c,
                              (select Catalog_Item__r.Name,Quantity__c from Items__r)  
                              from Request__c where id=:recordId ];
        String body;
        body  = '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://sma-promail/">';
        body += '   <soap:Header>';
        body += '       <AuthenticationHeader>';
        body += '           <Username>' + wsInfo.UserName__c + '</Username>';
        body += '           <Password>' + wsInfo.Password__c + '</Password>';
        /*body += '         <Username>DDFNOW</Username>';
        body += '           <Password>WonfdD</Password>';*/
        body += '       </AuthenticationHeader>';
        body += '       <DebugHeader>';
        if (wsInfo.debug__c)
            body += '           <Debug>true</Debug>';
        else
            body += '           <Debug>false</Debug>';
        body += '       </DebugHeader>';
        body += '   </soap:Header>';
        body += '   <soap:Body>';
        body += '       <AddOrder>';
        body += '           <order>';
        body += '               <Header>';
        body += '                   <ID>' + Request.Name + '</ID>';
        body += '                   <EntryDate>' + system.now().format('yyyy-MM-dd\'T\'HH:mm:ss') + '</EntryDate>';
        body += '                   <Comments>' + Request.Comments__c + '</Comments>';
        body += '                   <ReferenceNumber>' + Request.Name + '</ReferenceNumber>';
        body += '               </Header>';
        body += '               <Classification/>';
        body += '                   <OrderedBy>';
        body += '                       <CompanyName>DuPont</CompanyName>';
        body += '                       <FirstName>' + Request.CreatedBy.FirstName +'</FirstName>';
        body += '                       <LastName>' + Request.CreatedBy.LastName + '</LastName>';
        body += '                       <Address1>' + Request.CreatedBy.Street + '</Address1>';
        body += '                       <Address2/>';
        body += '                       <City>' + Request.CreatedBy.City + '</City>';
        body += '                       <State>' + Request.CreatedBy.State + '</State>';
        body += '                       <PostalCode>' + Request.CreatedBy.PostalCode + '</PostalCode>';
        body += '                       <Country>' + Request.CreatedBy.Country + '</Country>';
        body += '                       <Phone>' + Request.CreatedBy.Phone + '</Phone>';
        body += '                       <Email>' + Request.CreatedBy.Email + '</Email>';
        body += '                   </OrderedBy>';
        body += '                   <ShipTo>';
        body += '                       <OrderShipTo>';
        body += '                           <CompanyName>' + Request.Send_to_Company__c + '</CompanyName>';
        string[] splitted = Request.Send_to_Contact__c.split(' ');
        if(splitted.size()==2){
        body += '                           <FirstName>' + splitted[0] + '</FirstName>';
        body += '                           <LastName>' + splitted[1] + '</LastName>';
        } else {
        body += '                           <FirstName></FirstName>';
        body += '                           <LastName>' + splitted[0] + '</LastName>';
        }
        body += '                           <Address1>' + Request.Request_Shipping_Street__c + '</Address1>';
        body += '                           <Address2/>';
        body += '                           <City>' + Request.Request_Shipping_City__c + '</City>';
        body += '                           <State>' + Request.Request_Shipping_State__c + '</State>';
        body += '                           <PostalCode>' + Request.Request_Shipping_Postal_Code__c + '</PostalCode>';
        body += '                           <Country>' + Request.Request_Shipping_Country__c + '</Country>';
        body += '                           <Phone>' + Request.Phone__c + '</Phone>';
        body += '                           <TaxExempt>false</TaxExempt>';
        body += '                           <TaxExemptApproved>false</TaxExemptApproved>';
        body += '                           <Commercial>false</Commercial>';
        body += '                           <Flag>Other</Flag>';
        if (Request.Priority__c == 'Rush') {
        body += '                           <Rush>true</Rush>';
        }
        body += '                           <Comments>' + Request.Instructions__c + '</Comments>';
        body += '                           <Key>0</Key>';
        body += '                           <FreightCode/>';
        body += '                       </OrderShipTo>';
        body += '                   </ShipTo>';
        body += '                   <BillTo>';
        body += '                       <TaxExempt>false</TaxExempt>';
        body += '                       <TaxExemptApproved>false</TaxExemptApproved>';
        body += '                       <Commercial>false</Commercial>';
        body += '                       <Flag>OrderedBy</Flag>';
        body += '                   </BillTo>';
        body += '                   <Offers>';
        for(Request_Item__c ri: request.Items__r){
        body += '                       <OfferOrdered>';
        body += '                           <Offer>';
        body += '                               <Header>';
        body += '                                   <ID>' + ri.Catalog_Item__r.Name + '</ID>';
        body += '                               </Header>';
        body += '                           </Offer>';
        body += '                           <Quantity>' + ri.Quantity__c + '</Quantity>';
        body += '                           <OrderShipToKey>';
        body += '                               <Key>0</Key>';
        body += '                           </OrderShipToKey>';
        body += '                       </OfferOrdered>';
        }
        body += '                   </Offers>';
        body += '           </order>';
        body += '       </AddOrder>';
        body += '   </soap:Body>';
        body += '</soap:Envelope>';
        HttpRequest req = new HttpRequest();
        req.setEndpoint(wsInfo.URL__c);
        System.debug('Endpoint ' + req.getEndpoint());
        req.setMethod('GET');
        req.setBody(body);
        req.setHeader('Content-Type', 'text/xml');
        Http http = new Http();
        HttpResponse res = http.send(req);
        if (res.getStatusCode() != 200) {
            request.Status__c = 'Error: Rejected by Supplier';
            request.Stage_Reason__c = res.getBody();
        }
        else {
            request.Status__c = 'Accepted by Supplier';
        }
        update request;
        System.debug('Request response code:'+res.getStatusCode());        
        System.debug('Request response body:'+res.getBody());        
    }
}