DuPont DevSB/src/objects/Catalog_Item__c.object
<CustomObject>
    <description>Catalog Items are the individual Sales Aids contained in a Catalog to be selected for fulfillment of a Request and Catalog Item Subscriptions</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Catalog Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Request__c.object
<CustomObject>
    <description>Multiple purpose Object where various Requests and Transaction Types can be created and tracked throughout the system</description>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Instructions__c</fullName>
        <description>Instructions to successfully perform this Request</description>
        <label>Instructions</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority of Request</description>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                </value>
                <value>
                    <fullName>Rush</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Shipping_City__c</fullName>
        <description>Request shipping city mapped from Contact or Lead Mailing Address by sControl</description>
        <label>Shipping City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Shipping_Country__c</fullName>
        <description>Request Shipping Country mapped from Contact or Lead Country by sControl</description>
        <label>Shipping Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Shipping_Postal_Code__c</fullName>
        <description>Request Shipping Postal code mapped from Contact or Lead Mailing address by sControl</description>
        <label>Shipping Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Shipping_State__c</fullName>
        <description>Request Shipping State mapped from Contact or Lead mailing address by sControl</description>
        <label>Shipping State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Shipping_Street__c</fullName>
        <description>Request Shipping Street mapped from Contact or Lead mailing address by sControl</description>
        <label>Shipping Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Company__c</fullName>
        <description>The Company to which the labels are delivered/shipped.</description>
        <label>Send to Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Contact__c</fullName>
        <description>The Contact person who receives the labels.</description>
        <label>Send to Contact</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>RQ-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Request_Item__c.object
<CustomObject>
    <description>Line items on a Request</description>
    <fields>
        <fullName>Catalog_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Catalog Item which relates to this Request Item.  (i.e Sales Aid Fulfillment)</description>
        <label>Catalog Item</label>
        <referenceTo>Catalog_Item__c</referenceTo>
        <relationshipLabel>Request Items</relationshipLabel>
        <relationshipName>R00N30000001uwx6EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Used to identify the quantity of Request Items (i.e. Sales Aids) in a specific line item on a Request</description>
        <label>Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>The Request to which this Request Item is related</description>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Request Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Request Item</label>
    <nameField>
        <displayFormat>ITM-{YY}{MM}{DD}-{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/orderMapping.cls
public class orderMapping {
    public void orderMap(){
        SendOrder.Order order = new SendOrder.Order();
        order.Header = new SendOrder.Header();
        order.OrderedBy = new SendOrder.OrderedBy();
        order.ShipTo= new SendOrder.ShipTo();
        order.ShipTo.OrderShipTo = new SendOrder.OrderShipTo();
        order.Offers = new SendOrder.Offers();
        order.Offers.OfferOrdered = new SendOrder.OfferOrdered();
        order.Offers.OfferOrdered.Offer = new SendOrder.Offer();
        order.Offers.OfferOrdered.Offer.Header = new SendOrder.OfferHeader();
        
        order.Offers.OfferOrdered.OrderShipToKey = new SendOrder.OrderShipToKey();
        Request__c Request = new Request__c();
        Request_Item__c RequestItem = new Request_Item__c();
        
        order.Header.ID = Request.Name;
        order.Header.EntryDate = system.today();
        order.Header.ReferenceNumber = Request.Name;
        order.Header.Comments = Request.Comments__c;
        order.Header.InsertDate = system.today();
        
        
        
        order.OrderedBy.FirstName = Request.CreatedBy.FirstName;  
        
        order.OrderedBy.LastName = Request.CreatedBy.LastName; 
        
         
         
        order.OrderedBy.CompanyName = 'Dupont';
        order.OrderedBy.Address1 = Request.CreatedBy.Street;
        order.OrderedBy.Address2 = Request.CreatedBy.Street;
        order.OrderedBy.Address3 = Request.CreatedBy.Street;
        order.OrderedBy.City = Request.CreatedBy.City;
        order.OrderedBy.State = Request.CreatedBy.State;
        order.OrderedBy.PostalCode = Request.CreatedBy.PostalCode;
        order.OrderedBy.Country = Request.CreatedBy.Country;
        order.OrderedBy.Phone = Request.CreatedBy.Phone;
        order.OrderedBy.Email = Request.CreatedBy.Email;
        order.OrderedBy.UID = Request.CreatedBy.FirstName;
        order.OrderedBy.TaxExempt = false;
        order.OrderedBy.TaxExemptApproved = false;
        order.OrderedBy.TaxExemptApproved = false;
        order.OrderedBy.Commercial = false;
        
        order.ShipTo.OrderShipTo.TaxExempt = false;
        order.ShipTo.OrderShipTo.TaxExempt = false;
        order.ShipTo.OrderShipTo.TaxExemptApproved = false;
        order.ShipTo.OrderShipTo.Commercial = false;
        order.ShipTo.OrderShipTo.Flag = 'Other'; 
        order.ShipTo.OrderShipTo.Key = 0;
        if(Request.Priority__c == 'Rush'){
            order.ShipTo.OrderShipTo.Rush = True ;
        }else{
            order.ShipTo.OrderShipTo.Rush = false ;
        }
        order.ShipTo.OrderShipTo.Comments = Request.Instructions__c;
        order.ShipTo.OrderShipTo.FreightCode = null; 
        string[] splitted1 = Request.Send_to_Contact__c.split(' ');
        order.BillTo.FirstName = splitted1[0];  
        if(splitted1[1]!=null){
        	order.BillTo.LastName = splitted1[1]; 
        }
        order.BillTo.CompanyName = Request.Send_to_Company__c;
        order.BillTo.Address1 = Request.Request_Shipping_Street__c;
        order.BillTo.Address2 = Request.Request_Shipping_Street__c;
        order.BillTo.Address3 = Request.Request_Shipping_Street__c;
        order.BillTo.City = Request.Request_Shipping_City__c;
        order.BillTo.State = Request.Request_Shipping_State__c;
        order.BillTo.PostalCode = Request.Request_Shipping_Postal_Code__c;
        order.BillTo.Country = Request.Request_Shipping_Country__c;
        order.BillTo.Phone = Request.Phone__c;
        order.BillTo.TaxExempt = false;
        order.BillTo.TaxExemptApproved = false;
        order.BillTo.Commercial = false;
        
        order.Offers.OfferOrdered.Offer.Header.ID = RequestItem.Catalog_Item__r.Name;
        order.Offers.OfferOrdered.Quantity = RequestItem.Quantity__c;
        order.Offers.OfferOrdered.OrderShipToKey.Key = 0;
    }   
}