DuPont DevSB/src/objects/Catalog__c.object
<CustomObject>
    <description>Catalog of Sales Aids used for Fulfillment Requests</description>
    <label>Catalog</label>
    <nameField>
        <label>Catalog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Catalog_Item__c.object
<CustomObject>
    <description>Catalog Items are the individual Sales Aids contained in a Catalog to be selected for fulfillment of a Request and Catalog Item Subscriptions</description>
    <fields>
        <fullName>Catalog_Item_Name__c</fullName>
        <description>Name or desciption of item</description>
        <label>Catalog Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Catalog__c</fullName>
        <description>Name of catalog which contains these fulfillment items</description>
        <label>Catalog</label>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Catalog Items</relationshipLabel>
        <relationshipName>R00N30000001usfKEAQ</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Status__c</fullName>
        <description>Status of Item in Catalog</description>
        <label>Item Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quantity_Limit_Max__c</fullName>
        <description>Maximum quantity of this item allowable for request without approval</description>
        <inlineHelpText>Maximum quantity of this item allowable for request without approval</inlineHelpText>
        <label>Quantity Limit Maximum</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Limit_Min__c</fullName>
        <description>Minimum Quantity of this time available for a request</description>
        <label>Quantity Limit Minimum</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reference_Keywords__c</fullName>
        <description>Keywords to used for searching catalog (use to identify items by segment, product, or market, etc)</description>
        <label>Reference Keywords</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Special_Handling__c</fullName>
        <description>Special Handling instructions to supplier regarding catalog item</description>
        <label>Special Handling</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <description>Min or Max UOM</description>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Box</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Container</fullName>
                </value>
                <value>
                    <fullName>Dozen</fullName>
                </value>
                <value>
                    <fullName>Each</fullName>
                </value>
                <value>
                    <fullName>Gallon</fullName>
                </value>
                <value>
                    <fullName>Gram</fullName>
                </value>
                <value>
                    <fullName>Kilogram</fullName>
                    <default>true</default>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>Liter</fullName>
                </value>
                <value>
                    <fullName>Meter</fullName>
                </value>
                <value>
                    <fullName>Ounce</fullName>
                </value>
                <value>
                    <fullName>Packet</fullName>
                </value>
                <value>
                    <fullName>Pound</fullName>
                </value>
                <value>
                    <fullName>Square Foot</fullName>
                </value>
                <value>
                    <fullName>Square Meter</fullName>
                </value>
                <value>
                    <fullName>Swatch</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Catalog Item</label>
    <nameField>
        <label>Catalog Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Request__c.object
<CustomObject>
    <description>Multiple purpose Object where various Requests and Transaction Types can be created and tracked throughout the system</description>
    <fields>
        <fullName>Sample_Request_Catalog__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sample Request Catalog</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalog__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Particular phase or period in the life-cycle of this request</description>
        <inlineHelpText>Particular phase or period in the life-cycle of this request</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Capture</fullName>
                    <default>true</default>
                    <label>Capture</label>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Lab Approved</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Complete In ERP</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Abandonded</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Letter Sent</fullName>
                </value>
                <value>
                    <fullName>Printed</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_Datetime__c</fullName>
        <label>Submitted Datetime</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <description>Unit of Measure of product ordered</description>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>gram</fullName>
                </value>
                <value>
                    <fullName>ml</fullName>
                </value>
                <value>
                    <fullName>square foot</fullName>
                </value>
                <value>
                    <fullName>kg</fullName>
                </value>
                <value>
                    <fullName>each</fullName>
                </value>
                <value>
                    <fullName>hour</fullName>
                </value>
                <value>
                    <fullName>lb</fullName>
                </value>
                <value>
                    <fullName>square meter</fullName>
                </value>
                <value>
                    <fullName>ton, metric</fullName>
                </value>
                <value>
                    <fullName>day</fullName>
                </value>
                <value>
                    <fullName>cubic meter</fullName>
                </value>
                <value>
                    <fullName>liter</fullName>
                </value>
                <value>
                    <fullName>Milliliter</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>RQ-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <recordTypes>
        <fullName>SalesAidCapture</fullName>
        <active>true</active>
        <description>Sales Aid Requests record type for Capture or Not Started Stage</description>
        <label>Sales Aid - Capture</label>
    </recordTypes>
    <recordTypes>
        <fullName>SalesAidSubmitted</fullName>
        <active>true</active>
        <label>Sales Aid - Submitted</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Request_Item__c.object
<CustomObject>
    <description>Line items on a Request</description>
    <fields>
        <fullName>Catalog_Item_Name__c</fullName>
        <formula>Catalog_Item__r.Catalog_Item_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Catalog Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Catalog_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Catalog Item which relates to this Request Item.  (i.e Sales Aid Fulfillment)</description>
        <label>Catalog Item</label>
        <referenceTo>Catalog_Item__c</referenceTo>
        <relationshipLabel>Request Items</relationshipLabel>
        <relationshipName>R00N30000001uwx6EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Used to identify the quantity of Request Items (i.e. Sales Aids) in a specific line item on a Request</description>
        <label>Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>The Request to which this Request Item is related</description>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Request Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Special_Handling__c</fullName>
        <label>Special Handling</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Current Stage this is readonly for the user and is controlled by the Backend Process or system admin.</description>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Capture</fullName>
                    <default>true</default>
                    <label>Capture</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <description>The Unit of Measure of the Item Requested. This is mapped from the Sales Aid Solution.</description>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cubic Meter</fullName>
                </value>
                <value>
                    <fullName>Day</fullName>
                </value>
                <value>
                    <fullName>Each</fullName>
                </value>
                <value>
                    <fullName>Foot</fullName>
                </value>
                <value>
                    <fullName>Gallon</fullName>
                </value>
                <value>
                    <fullName>Gram</fullName>
                </value>
                <value>
                    <fullName>Hour</fullName>
                </value>
                <value>
                    <fullName>Kilogram</fullName>
                </value>
                <value>
                    <fullName>Liter</fullName>
                </value>
                <value>
                    <fullName>Meter</fullName>
                </value>
                <value>
                    <fullName>Pound</fullName>
                </value>
                <value>
                    <fullName>Square Foot</fullName>
                </value>
                <value>
                    <fullName>Square Meter</fullName>
                </value>
                <value>
                    <fullName>Ton, Metric</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request Item</label>
    <nameField>
        <displayFormat>ITM-{YY}{MM}{DD}-{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Items</pluralLabel>
    <recordTypes>
        <fullName>SalesAidItemCapture</fullName>
        <active>true</active>
        <description>Sales Aid Item Record Type for Capture or Not Started Stage</description>
        <label>Sales Aid Item - Capture</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlSalesAideItems.cls
public with sharing class ctrlSalesAideItems {
    public Request__c request {get;set;}
    public Request_Item__c[] shoppingCart {get;set;}
    public Boolean canEdit {get; set;}
    public String searchString {get;set;}
    public Catalog_Item__c[] searchResults {get;set;}
    public Boolean overLimit {get;set;}
    public Boolean noRecords {get;set;}
    public String idToAdd {get; set;}
    public String idToRemove {get; set;}
    private Request_Item__c[] forDeletion = new Request_Item__c[]{};
    private static final Id SARI_CAPTURE_RTYPE   =   utilRT.getRT('Request_Item__c','SalesAidItemCapture').Id;
    private static final Id SAR_CAPTURE_RTYPE    =   utilRT.getRT('Request__c','SalesAidCapture').Id;
    private static final Id SAR_SUBMITTED_RTYPE    =   utilRT.getRT('Request__c','SalesAidSubmitted').Id;

    public ctrlSalesAideItems(ApexPages.StandardController controller) {
        request = [select Id, Name, Sample_Request_Catalog__c, RecordTypeId, Stage__c, Submitted_Datetime__c from Request__c where Id = :controller.getRecord().Id limit 1];
        if (request.Sample_Request_Catalog__c == null) {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.FATAL, 'You must add a catalog to the request before adding items');
            ApexPages.addMessage(msg);
        }
        else {
            shoppingCart = [SELECT Id, Catalog_Item__c, Catalog_Item__r.Name, Catalog_Item__r.Catalog_Item_Name__c, Quantity__c, Catalog_Item__r.Unit_of_Measure__c, 
                        Catalog_Item__r.Quantity_Limit_Max__c, Special_Handling__c
                        FROM Request_Item__c where Request__c=:request.Id];
            canEdit = request.Stage__c == 'Capture';
            execSearch();
        }
    }
    
    public PageReference addToShoppingCart() {
        for(Catalog_Item__c ci : searchResults){
            if((String)ci.Id==idToAdd){
                Request_Item__c ri = new Request_Item__c(Request__c=request.Id, Catalog_Item__c=ci.Id, RecordTypeId=SARI_CAPTURE_RTYPE, Special_Handling__c = ci.Special_Handling__c);
                ri.Catalog_Item__r = ci;
                shoppingCart.add(ri);
                break;
            }
        }
        
        execSearch(); 
        return null;
     }
    
     public PageReference removeFromShoppingCart() {
        Integer row = 0;

         for(Request_Item__c ri : shoppingCart){
            if((String)ri.Catalog_Item__c==idToRemove){
                if(ri.Id!=null)
                    forDeletion.add(ri);
                shoppingCart.remove(row);
                break;
            }
            row++;
        }
        system.debug('Remove from cart:' +shoppingCart.size());        
        execSearch();
        return null;
     }
    
    public void execSearch() {
        String qString = 'select Id, Name, Catalog_Item_Name__c, Quantity_Limit_Max__c, Quantity_Limit_Min__c, Unit_of_Measure__c, Special_Handling__c from Catalog_Item__c where Item_Status__c=\'Active\' and Catalog__c =\'' + request.Sample_Request_Catalog__c + '\'';
        if(searchString!=null && searchString != ''){
            qString+= ' AND (Name Like \'%' + searchString + '%\' OR Catalog_Item_Name__c Like  \'%' + searchString + '%\' OR Reference_Keywords__c Like \'%' + searchString + '%\') ';
        }
        // Add filter for removing selected catalog items
        Set<Id> selectedEntries = new Set<Id>();
        for(Request_Item__c ri:shoppingCart){
            selectedEntries.add(ri.Catalog_Item__c);
        }
        if(selectedEntries.size()>0){
            String tempFilter = ' and Id not in (';
            for(Id i : selectedEntries){
                tempFilter+= '\'' + (String)i + '\',';
            }
            String extraFilter = tempFilter.substring(0,tempFilter.length()-1);
            extraFilter+= ')';
            
            qString+= extraFilter;
        }
                
        qString+= ' order by Catalog_Item_Name__c';
        qString+= ' limit 51';
        
        system.debug('qString:' +qString);        
        searchResults = database.query(qString);
        overLimit = searchResults.size()==51;
        noRecords = searchResults.size()==0;
        if(overLimit){
            searchResults.remove(50);
        }
    }
    
    public PageReference onSubmit() {
        try{
            if(forDeletion.size()>0)
                delete(forDeletion);
            if(shoppingCart.size()>0)
                upsert(shoppingCart);
            request.RecordTypeId = SAR_SUBMITTED_RTYPE;
            request.Stage__c = 'Submitted';
            request.Submitted_Datetime__c = string.valueOfGmt(System.now());
            update request;
        }
        catch(Exception e){
            ApexPages.addMessages(e);
            return null;
        }          
        return new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
    }
    
    public PageReference onSave() {
        try{
            if(forDeletion.size()>0)
                delete(forDeletion);
            if(shoppingCart.size()>0)
                upsert(shoppingCart);
        }
        catch(Exception e){
            ApexPages.addMessages(e);
            return null;
        }  
        return new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
     }
    
    public PageReference onCancel() {
        return new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
    }    
}