DuPont DevSB/src/objects/ConstructionPts__CP_Project__c.object
<CustomObject>
    <fields>
        <fullName>ConstructionPts__Address__c</fullName>
        <label>Address</label>
        <length>101</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Bid_Date__c</fullName>
        <label>Bid Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__County__c</fullName>
        <label>County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Features_Info__c</fullName>
        <label>Features Info</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Market_Segment_Name__c</fullName>
        <label>Market Segment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Ownership__c</fullName>
        <label>Ownership</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Project_Report_URL__c</fullName>
        <label>Project Report URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Project_Type__c</fullName>
        <label>Project Type</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Report_Number__c</fullName>
        <label>Dodge Report Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Report_Version__c</fullName>
        <label>Report Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__SFDC_Upload_Time__c</fullName>
        <label>SFDC Upload Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Search_Names__c</fullName>
        <label>Search Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Spec_Alerts__c</fullName>
        <label>Spec Alerts</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Stage255__c</fullName>
        <description>This one is a text field to be used for formula fields</description>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Status__c</fullName>
        <label>Status</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Stories_above__c</fullName>
        <label>Stories above</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Stories_below__c</fullName>
        <label>Stories below</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Structural__c</fullName>
        <label>Structural</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Total_Sq_Ft__c</fullName>
        <label>Total Sq. Ft.</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Type_Of_Work__c</fullName>
        <label>Type Of Work</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>CP Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/batchBICPProject.cls
/*************************************************************************************************
Copyright © 2016 DuPont. All rights reserved. 
Authors:        Arjun Sharma
Email:          arjun.sharma2@tcs.com
Description:    Create and update External Initiative based on newly inserted CP Project

<AS20161220>
Modified By: Arjun Sharma
Modification Date: 20-Dec-2016
Modification: Change filter criteria for query


<AS20170428>
Modified By: Arjun Sharma
Modification Date: 28-Apr-2017
Modification: Changes the Batch size of Lead creation

***************************************************************************************************/
global class batchBICPProject implements Database.Batchable<sObject>{
    //<AS20170428>start
    //public static final Integer batchJobSize = Integer.valueOf(Label.
    public static final Integer batchJobSize = Integer.valueOf(Label.CPSF_Dodge_Role_Batch_Size);
     //<AS20170428>End
    public static Integer batchFilter = Integer.valueOf(Label.CIC_CPSF_Batch_Filter);
    public static datetime Lastmodifiedfilter = system.today().adddays(batchFilter);
    public Database.QueryLocator start(Database.BatchableContext BC){       
        String query = 'SELECT Name,ConstructionPts__Bid_Date__c,ConstructionPts__City__c,ConstructionPts__Country__c,ConstructionPts__County__c,ConstructionPts__Address__c,ConstructionPts__Stage255__c,ConstructionPts__Features_Info__c,ConstructionPts__Search_Names__c,ConstructionPts__Report_Number__c,ConstructionPts__Report_Version__c,ConstructionPts__Project_Type__c,ConstructionPts__Project_Report_URL__c,ConstructionPts__Stories_above__c,ConstructionPts__Stories_below__c,ConstructionPts__Total_Sq_Ft__c,LastModifiedDate,ConstructionPts__Market_Segment_Name__c,ConstructionPts__Type_Of_Work__c,ConstructionPts__Ownership__c,ConstructionPts__Spec_Alerts__c,ConstructionPts__Structural__c,ConstructionPts__State__c,ConstructionPts__Value__c,ConstructionPts__Zipcode__c,ConstructionPts__Status__c FROM ConstructionPts__CP_Project__c where ConstructionPts__SFDC_Upload_Time__c >=:Lastmodifiedfilter';//<AS20161220>
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext info, List<ConstructionPts__CP_Project__c> scope){
        BI_CPProjectHandler cpProjectHandler = new BI_CPProjectHandler();
        cpProjectHandler.onAfterInsertUpdateCPProject(scope);
    }
    // execute consecutive batch
    public void finish(Database.BatchableContext info){
       Database.executeBatch(new batchBICPRoleHandler(),batchJobSize);
    }

}