DuPont DevSB/src/objects/ConstructionPts__CP_Project__c.object
<CustomObject>
    <fields>
        <fullName>ConstructionPts__Address__c</fullName>
        <label>Address</label>
        <length>101</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Bid_Date__c</fullName>
        <label>Bid Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__County__c</fullName>
        <label>County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Features_Info__c</fullName>
        <label>Features Info</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Market_Segment_Name__c</fullName>
        <label>Market Segment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Ownership__c</fullName>
        <label>Ownership</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Project_Report_URL__c</fullName>
        <label>Project Report URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Project_Type__c</fullName>
        <label>Project Type</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Report_Number__c</fullName>
        <label>Dodge Report Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Report_Version__c</fullName>
        <label>Report Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Search_Names__c</fullName>
        <label>Search Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Spec_Alerts__c</fullName>
        <label>Spec Alerts</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Stage255__c</fullName>
        <description>This one is a text field to be used for formula fields</description>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Stories_above__c</fullName>
        <label>Stories above</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Stories_below__c</fullName>
        <label>Stories below</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Structural__c</fullName>
        <label>Structural</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Total_Sq_Ft__c</fullName>
        <label>Total Sq. Ft.</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPts__Type_Of_Work__c</fullName>
        <label>Type Of Work</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>CP Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/External_Initiative__c.object
<CustomObject>
    <description>Detailed information from an external data source provided in an automated feed (project, lead, or opportunity data).</description>
    <fields>
        <fullName>Bid_Due_Date__c</fullName>
        <description>The date the bid for this project is due</description>
        <inlineHelpText>The date the bid for this project is due</inlineHelpText>
        <label>Bid Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Overage__c</fullName>
        <label>Data Overage</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Data_Source__c</fullName>
        <description>Identifies external data source.</description>
        <inlineHelpText>Identifies external data source.</inlineHelpText>
        <label>Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>McGraw Hill Construction</fullName>
                </value>
                <value>
                    <fullName>Dodge</fullName>
                    <default>true</default>
                    <label>Dodge</label>
                </value>
                <value>
                    <fullName>CIC - Construction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Additional information about this external initiative</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique identifier from external system.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_Search_Name__c</fullName>
        <description>External search name used by external system.</description>
        <label>External Search Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_URL__c</fullName>
        <description>Link to external initiative in external system.</description>
        <label>External URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>External_Version__c</fullName>
        <description>Identifies version of external initiative, can be used to ensure the data is synchronized.</description>
        <label>External Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Floors_Above_Ground__c</fullName>
        <description>Used to classify projects.</description>
        <label>Floors Above Ground</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Floors_Below_Ground__c</fullName>
        <description>Used to classify projects.</description>
        <label>Floors Below Ground</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Initiative_Size__c</fullName>
        <description>Total size of project.</description>
        <label>Initiative Size</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Import_Date__c</fullName>
        <description>Captures date of most recent external update to project.</description>
        <label>Last Import Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Owning_Organization__c</fullName>
        <label>Owning Organization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-Env</fullName>
                </value>
                <value>
                    <fullName>BI-Landscape Systems</fullName>
                </value>
                <value>
                    <fullName>BI-Surf</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
                <value>
                    <fullName>DPT-A&amp;HF</fullName>
                </value>
                <value>
                    <fullName>DPT-Agriculture</fullName>
                </value>
                <value>
                    <fullName>DPT-Air and Filtration</fullName>
                </value>
                <value>
                    <fullName>DPT-Aramids</fullName>
                </value>
                <value>
                    <fullName>DPT-ASPS</fullName>
                </value>
                <value>
                    <fullName>DPT-Automotive</fullName>
                </value>
                <value>
                    <fullName>DPT-Chemical Industrial</fullName>
                </value>
                <value>
                    <fullName>DPT-Cleanroom/Pharma</fullName>
                </value>
                <value>
                    <fullName>DPT-Covers</fullName>
                </value>
                <value>
                    <fullName>DPT-Critical Clean</fullName>
                </value>
                <value>
                    <fullName>DPT-Envelopes</fullName>
                </value>
                <value>
                    <fullName>DPT-ES</fullName>
                </value>
                <value>
                    <fullName>DPT-Graphics</fullName>
                </value>
                <value>
                    <fullName>DPT-Ind Pkg &amp; Protection</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP</fullName>
                </value>
                <value>
                    <fullName>DPT-Mechanical Industrial</fullName>
                </value>
                <value>
                    <fullName>DPT-Medical Fabrics</fullName>
                </value>
                <value>
                    <fullName>DPT-Medical Packaging</fullName>
                </value>
                <value>
                    <fullName>DPT-Medical Specialties</fullName>
                </value>
                <value>
                    <fullName>DPT-NOW</fullName>
                </value>
                <value>
                    <fullName>DPT-Optical</fullName>
                </value>
                <value>
                    <fullName>DPT-PM</fullName>
                </value>
                <value>
                    <fullName>DPT-Public Sector-ER</fullName>
                </value>
                <value>
                    <fullName>DPT-Public Sector-LE</fullName>
                </value>
                <value>
                    <fullName>DPT-Public Sector-MIL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment_L1__c</fullName>
        <description>Highest level External initiative segment.</description>
        <label>Segment L1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment_L2__c</fullName>
        <description>External initiative subsegment.</description>
        <label>Segment L2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment_L3__c</fullName>
        <description>Captures further external initiative detail.</description>
        <label>Segment L3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment_L4__c</fullName>
        <description>Captures further external initiative detail.</description>
        <label>Segment L4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Specification_L1__c</fullName>
        <description>External initiative specification primary specification.</description>
        <label>Specification L1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Specification_L2__c</fullName>
        <description>External initiative specification secondary specification.</description>
        <label>Specification L2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Construction-Commercial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>External Initiative</label>
    <nameField>
        <label>External Initiative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Initiatives</pluralLabel>
    <recordTypes>
        <fullName>BI_NA_External_Initiative</fullName>
        <active>true</active>
        <label>BI-NA External Initiative</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/BI_CPProjectHandler.cls
/*************************************************************************************************
Copyright © 2016 DuPont. All rights reserved. 
Authors:        Arjun Sharma
Email:          arjun.sharma2@tcs.com
Description:    Trigger handler for CP Project
Event:          After Insert : 
                Create new External Initiative based on newly inserted CP Project,
                After Update : 
                Update External Initiative based on updated CP Project,
                by Dodge Report Number which is related to External Id of External Initiative

<AS20161015>
Modified By: Arjun Sharma
Modification Date: 15-Oct-2016
Modification: Added field mapping of Specification L1 and Data ovarage field for stage, Segment L2 and Specification L1

<AS20161017>
Modification: To avoid the SOQL query 101, map owner direct with its ID.
<AS20161109>
Modification: Create exception record to log data and technical issue.
*************************************************************************************************/

public class BI_CPProjectHandler extends TriggerHandlerBase {
    List<External_Initiative__c> extInitUpsert = new List<External_Initiative__c>();
    //Map the all record type of External Initiative
    Map<String,RecordType> mapExternalInitiativeRT = RType.getDevNameMapBySObjectType('External_Initiative__c');
    // fetch the record type id for BI NA External Initiative of External Initiative
    String extInitRtypeId = mapExternalInitiativeRT.containsKey('BI_NA_External_Initiative')?mapExternalInitiativeRT.get('BI_NA_External_Initiative').Id:null;
    //String owner = Label.External_Initiative_Owner_Name;//<AS20161017>
	Schema.SObjectField externalIdField = null;
    static final String appName = 'CPSF';
    static final String objectName = 'External_Initiative';
    
    //Create/Update External Initiative after insertion or update of CP Project    
    public void onAfterInsertUpdateCPProject(List<ConstructionPts__CP_Project__c> cpProjectList){
        try{
            list<string> LstExternalId = new list<string>(); 
            externalIdField = External_Initiative__c.Fields.External_ID__c;
            String errString = '';
            String errStringTxt = '';
            if(extInitRtypeId != null && cpProjectList != null){
                for(ConstructionPts__CP_Project__c cpProject : cpProjectList){
                    External_Initiative__c objEI = new External_Initiative__c(); 
                    objEI = createExtInit(cpProject);
                    if(objEI != null){
                        extInitUpsert.add(objEI);
                        LstExternalId.add(Label.CPSF+cpProject.ConstructionPts__Report_Number__c);
                    }
                }
            }
       
            if(extInitUpsert != null && extInitUpsert.size()>0){
            	List<Database.UpsertResult> urList = database.upsert(extInitUpsert, externalIdField, false);
				ExceptionHandlingClass_CIC_CP.MthdFetchErrors(LstExternalId,urList,objectName,appName);//<AS20161109>
        	}
       }catch(Exception e){
            ExceptionHandlingClass_CIC_CP.autoCreatedpsException(e,objectName,appName);//<AS20161109>
       }
    }
    
/*************************************************************************************************
Function description 
Name:           createExtInit
Return type:    External_Initiative__c
Description:    Method used to map the value of CP Project to External Initiative
*************************************************************************************************/

    public External_Initiative__c createExtInit(ConstructionPts__CP_Project__c objCPProject){
        String formattedReportNo = BI_CPUtil.mhcFormatted(objCPProject.ConstructionPts__Report_Number__c);
        Integer extVersion = null;
        String projectType = '';
        String projectStage = '';
        String specAlerts = '';
        String overage = '';
        if(objCPProject.ConstructionPts__Report_Version__c != null){
            extVersion = Integer.valueof(objCPProject.ConstructionPts__Report_Version__c.trim());
        }
        
        if(objCPProject.ConstructionPts__Stage255__c != null){
            String eiStage = objCPProject.ConstructionPts__Stage255__c;
            if(eiStage.indexOf(',')>-1){
                projectStage = eiStage.substring(0,eiStage.indexOf(','));
                overage = 'Stage: '+eiStage.substring(eiStage.indexOf(',')+1)+';';//<AS20161015>
            }else{
                projectStage = eiStage;
            }            
        }
        
        if(objCPProject.ConstructionPts__Project_Type__c != null){
        	if(objCPProject.ConstructionPts__Project_Type__c.length()>255){
        		projectType = objCPProject.ConstructionPts__Project_Type__c.substring(0,255);
                Integer index = projectType.lastIndexOf(',');//<AS20161015> Start
                if(index > -1){
                    projectType = projectType.substring(0,index);
                    overage = overage+' SegmentL2: '+objCPProject.ConstructionPts__Project_Type__c.substring(index+1)+';';
                }
        	}else{
            	projectType = objCPProject.ConstructionPts__Project_Type__c;
        	}    
        }
        
        if(objCPProject.ConstructionPts__Spec_Alerts__c != null){
        	if(objCPProject.ConstructionPts__Spec_Alerts__c.length()>255){
        		specAlerts = objCPProject.ConstructionPts__Spec_Alerts__c.substring(0,255);
                Integer index = specAlerts.lastIndexOf(' ');
                if(index > -1){
                    specAlerts = specAlerts.substring(0,index);
                    overage = overage+' SpecificationL1: '+objCPProject.ConstructionPts__Spec_Alerts__c.substring(index+1)+';';
                }
        	}else{
            	specAlerts = objCPProject.ConstructionPts__Spec_Alerts__c;
        	}    
        }//<AS20161015> End
        
		External_Initiative__c extInit = new External_Initiative__c(Name=objCPProject.Name,Owning_Organization__c=Label.External_Initiative_Owning_Organization,Type__c=Label.External_Initiative_Type,
											 Bid_Due_Date__c=objCPProject.ConstructionPts__Bid_Date__c,City__c=objCPProject.ConstructionPts__City__c,
                                             Country__c=objCPProject.ConstructionPts__Country__c,County__c=objCPProject.ConstructionPts__County__c,
                                             Street__c=objCPProject.ConstructionPts__Address__c,Data_Source__c=Label.External_Initiative_Data_Source,
                                             Description__c=objCPProject.ConstructionPts__Features_Info__c,External_ID__c=formattedReportNo,
                                             External_Search_Name__c =objCPProject.ConstructionPts__Search_Names__c,
                                             External_URL__c=objCPProject.ConstructionPts__Project_Report_URL__c,External_Version__c=extVersion,
                                             Floors_Above_Ground__c=objCPProject.ConstructionPts__Stories_above__c,Floors_Below_Ground__c=objCPProject.ConstructionPts__Stories_below__c,
                                             Initiative_Size__c=BI_CPUtil.initiativeSize(objCPProject.ConstructionPts__Total_Sq_Ft__c),Last_Import_Date__c=objCPProject.LastModifiedDate.date(),
                                             Segment_L1__c=objCPProject.ConstructionPts__Market_Segment_Name__c,Segment_L2__c=projectType,
                                             Segment_L3__c=objCPProject.ConstructionPts__Type_Of_Work__c,Segment_L4__c=objCPProject.ConstructionPts__Ownership__c,
                                             Specification_L1__c=specAlerts,Data_Overage__c=overage,//<AS20161015>
                                             Specification_L2__c=objCPProject.ConstructionPts__Structural__c,Stage__c=projectStage,
                                             State__c=objCPProject.ConstructionPts__State__c,UOM__c=BI_CPUtil.uom(objCPProject.ConstructionPts__Total_Sq_Ft__c),
                                             Value__c=objCPProject.ConstructionPts__Value__c,PostalCode__c=objCPProject.ConstructionPts__Zipcode__c,
                                             Project_Status__c=objCPProject.ConstructionPts__Status__c,RecordTypeId=extInitRtypeId);
        return extInit;
    }
}