DuPont DevSB/src/objects/copado__Deployment__c.object
<CustomObject>
    <fields>
        <fullName>copado__From_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>copado__Org__c.CreatedById</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Deployments (From Org)</relationshipLabel>
        <relationshipName>Deployments_From_Org</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/copado__Org__c.object
<CustomObject>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Corporate_Package__c.object
<CustomObject>
    <description>Corporate Packages Object to track all Corp package deployments being done as part of org Split</description>
    <fields>
        <fullName>Copado_Deployment__c</fullName>
        <description>URL For the Copado Deployment Record</description>
        <label>Copado Deployment</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Corporate Package</label>
    <nameField>
        <label>Corporate Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporate Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/SFDC_CorpPackage_SyncLines_Test.cls
@isTest (SeeALLData=True)
public class SFDC_CorpPackage_SyncLines_Test {
    
    // Test Sync Method
    static testMethod void testNewSyncPositive(){
        
        //Create Org Credential
        copado__Org__c sourceOrg = new copado__Org__c();
        sourceOrg.name = 'TestDest';
        insert sourceOrg;
        
        // Create Copado Deploy
        copado__Deployment__c deploymentRecord = new copado__Deployment__c();
        deploymentRecord.copado__From_Org__c = sourceOrg.Id;
        insert deploymentRecord;
         
        // Create Copado Deploy Step
        copado__Step__c step1 = new copado__Step__c();
        step1.copado__Deployment__c = deploymentRecord.Id;
        insert step1;
        
        // Create Attachment related to Step
        Attachment att = new Attachment();
        att.Name = 'TestAttachment';
        att.Body = BLOB.valueOf('[{"t":"CustomField","n":"WorkOrderLineItem.ServiceAppointmentCount","s":true},{"t":"CustomField","n":"WorkOrderLineItem.Priority","s":true}]');
        att.ParentId = step1.id;
        insert att;
        
        
        // Create Corporate Package
        Corporate_Package__c packageRecord = new Corporate_Package__c();
        packageRecord.Name = 'Test';
        packageRecord.Description__c = 'Test';
        packageRecord.Copado_Deployment__c = 'https://url..?id='+deploymentRecord.Id+'?oas=2323423432432';
        insert packageRecord;
        
        // Test the constructor
        ApexPages.currentPage().getParameters().put('id',packageRecord.id);
        ApexPages.StandardController stdCont = new ApexPages.StandardController(packageRecord);
        SFDC_CorpPackage_SyncLines_Controller objController = new SFDC_CorpPackage_SyncLines_Controller(stdCont);

        
        // Test the Sync
        objController.syncLines();
        
        // Test the Cancel
        objController.cancel();
        
    }
}