DuPont DevSB/src/objects/copado__Deployment__c.object
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Corporate_Metadata_Components__c.object
<CustomObject>
    <fields>
        <fullName>Corporate_Package__c</fullName>
        <label>Corporate Package</label>
        <referenceTo>Corporate_Package__c</referenceTo>
        <relationshipLabel>Metadata Components</relationshipLabel>
        <relationshipName>Corporate_Metadata_Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Metdata_Mapping_One_Dupont__c</fullName>
        <label>MetaData Mapping (One DuPont)</label>
        <referenceTo>OneDuPontMetaData__c</referenceTo>
        <relationshipLabel>Corporate Package Associations</relationshipLabel>
        <relationshipName>Corporate_Metadata_Components</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Corporate Metadata Components</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Corp Component #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corporate Metadata Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Corporate_Package__c.object
<CustomObject>
    <description>Corporate Packages Object to track all Corp package deployments being done as part of org Split</description>
    <fields>
        <fullName>Copado_Deployment__c</fullName>
        <description>URL For the Copado Deployment Record</description>
        <label>Copado Deployment</label>
        <type>Url</type>
    </fields>
    <label>Corporate Package</label>
    <nameField>
        <label>Corporate Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporate Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/OneDuPontMetaData__c.object
<CustomObject>
    <fields>
        <fullName>MetaDataName__c</fullName>
        <externalId>true</externalId>
        <label>MetaData Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MetaData Mapping (One DuPont)</label>
    <nameField>
        <displayFormat>MD-{000000000}</displayFormat>
        <label>MetaData Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Mappings (One DuPont)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/SFDC_CorpPackage_SyncLines_Controller.cls
public class SFDC_CorpPackage_SyncLines_Controller {
    
    public Corporate_Package__c corpPackage;
    public final ApexPages.StandardController controller = null;
    public list<copado__Step__c> stepList;
    public List<Attachment> attachmentList;
    public copado__Deployment__c deployRecord;
    public Set<Id> attachmentIdSet;
    public List<Corporate_Metadata_Components__c> deleteList;
    public List<Corporate_Metadata_Components__c> upsertList;
    public Set<String> metadataKeySet;
    public SFDC_CorpPackage_SyncLines_Controller.metadataList corpLines;


    public SFDC_CorpPackage_SyncLines_Controller(ApexPages.StandardController stdController){
        this.corpPackage = (Corporate_Package__c)stdController.getRecord();
        this.corpPackage = [SELECT Id,Copado_Deployment__c FROM Corporate_Package__c WHERE Id=:corpPackage.id];
        this.controller = stdController;
    }
    
    public PageReference syncLines(){
        
        // Initiation
        attachmentIdSet = new Set<Id>();
        upsertList = new List<Corporate_Metadata_Components__c>();
        deleteList = new List<Corporate_Metadata_Components__c>();
        metadataKeySet = new Set<String>();
        String deployId;
          
        // Get the Deploy record
        try{
            deployId = corpPackage.Copado_Deployment__c;
        	deployId = deployId.mid(deployId.indexOf('?id=')+4,15);
        	deployRecord = [SELECT ID FROM copado__Deployment__c WHERE ID=:deployID LIMIT 1];
        }catch (Exception E){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,+'Cannot Query the Deployment Record using the id '+deployID+'.  Error: '+E));return null;
        }	
        
        // Get the related steps
        for (copado__Step__c stepList : [SELECT Id,copado__Attachment_Id__c FROM copado__Step__c WHERE copado__Deployment__c=:deployRecord.Id AND copado__Type__c='Metadata']){
            attachmentIdSet.add(stepList.Id);
        }		
        
        // Parse the Attachments JSON to internal object 
        try{    
            attachmentList = [SELECT Id,Body FROM Attachment WHERE ParentId IN:attachmentIdSet]; 
            for (Attachment a : attachmentList){
                String s='{"itemList":'+a.Body.toString()+'}';
                corplines = (SFDC_CorpPackage_SyncLines_Controller.metadataList) System.JSON.deserializeStrict(s, SFDC_CorpPackage_SyncLines_Controller.metadataList.class);
            	
                // Inner Loop through the corp lines
                for (SFDC_CorpPackage_SyncLines_Controller.metadataItem line: corplines.itemList){
                	metadataKeySet.add(line.t+'.'+line.n);
            	}
            }   
        }catch (Exception E){ 
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Cannot Parse the Attachments.  Error: '+E));
            return null;
        }
        
        // Build lists for deletion
        deleteList = new List<Corporate_Metadata_Components__c>();
        try{
        	deleteList = [SELECT ID FROM Corporate_Metadata_Components__c WHERE Corporate_Package__c=:corpPackage.Id];
        }catch (Exception E){} 
        
        // Build List for upsert
        for (OneDuPontMetadata__c metaMapping : [SELECT ID FROM OneDuPontMetadata__c WHERE MetaDataName__c IN:metadataKeySet]){
            Corporate_Metadata_Components__c newC = new Corporate_Metadata_Components__c();
            newC.Corporate_Package__c = corpPackage.Id;
            newC.Metdata_Mapping_One_Dupont__c = metaMapping.Id;
            upsertList.add(newC);
        } 
        
        // Insert and delete the Corp Lines
        try{
            delete deleteList;
            upsert upsertList;
        }catch (Exception E){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Error Inserting Component Records  Error: '+E));return null;
        }

        // SUCCESS
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Successfully Synced the Metadata Lines'));
        return null;
    }
    
    public PageReference cancel(){return controller.cancel();}
    
    // Inner class for JSON Deserialize
    // 
    public class metadataList{
        public List<metadataItem> itemList;
    }
    
    public class metadataItem{
        public String t;
        public String n;
        public Boolean s;
    }
}