DuPont DevSB/src/objects/CRM_IT_Project__c.object
<CustomObject>
    <label>CRM IT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM IT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Project_Member__c.object
<CustomObject>
    <description>Name of member of the Project Team</description>
    <fields>
        <fullName>Access__c</fullName>
        <label>Access</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read/Write</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CRM_IT_Project__c</fullName>
        <description>Persons accountable IT Controls related to Project Management, Execution, Testing and Deployment of this CRM Project.</description>
        <label>CRM-IT Project</label>
        <referenceTo>CRM_IT_Project__c</referenceTo>
        <relationshipName>CRM_Project_Member</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC Users who are members of the project team for this CRM-IT Project</description>
        <label>Project Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRM_IT_Project_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRM IT Project Member</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Project Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRM IT Project Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EPass_ID__c</fullName>
        <description>Positive identification of individuals accessing DuPont computer systems.</description>
        <label>E-Pass ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Grouping__c</fullName>
        <description>DuPont Business</description>
        <inlineHelpText>DuPont Business (abbrev)</inlineHelpText>
        <label>User Grouping</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>DC&amp;F</fullName>
                </value>
                <value>
                    <fullName>DPM</fullName>
                </value>
                <value>
                    <fullName>DPS</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Owning_Org__c</fullName>
        <description>Primary &quot;Owning Organisation&quot; this user belongs to</description>
        <label>User Owning Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-Env</fullName>
                </value>
                <value>
                    <fullName>BI-Surf</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>CORP-CS</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-ES</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PM</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PS</fullName>
                </value>
                <value>
                    <fullName>DPT-Aramids</fullName>
                </value>
                <value>
                    <fullName>DPT-Automotive</fullName>
                </value>
                <value>
                    <fullName>DPT-Car Protection</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP</fullName>
                </value>
                <value>
                    <fullName>DPT-NOW</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IAL</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>LEGL</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Corp Marketing</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Customer Care</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-IT</fullName>
                </value>
                <value>
                    <fullName>DPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Region__c</fullName>
        <label>User Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/trigProjectMemberApexSharing_UT.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
 /*******************************************************************************
Copyright © 2011 DuPont. All rights reserved. 
Author: Sreedhar Jagannath
Email: sreedhar.jagannath@ind.dupont.com
Date : 26th Dec 2011
Description : Test class for trigProjectmember

* Modification Log 
* ============================================================================= 
* Ver   Date        Author                 Modification 
* ---   ---------   ----------- ----------------------------------------------- 
* 1.0   26-Dec-11   Sreedhar Jagannath     Initial Code
* 1.1   10-jan-16   Priya                  Usernames in the testCreateUsers() method
**************************************************************************************************************/

@isTest
private class trigProjectMemberApexSharing_UT{
    
    public static User sysUser;
    public static User user2;
    public static User user3;
    
    static testmethod void testCreateUsers() {
        Profile p1 = [select id from profile where Name='System Administrator' limit 1];
        UserRole r1= [Select id from UserRole where Name='PS CRM' limit 1];
        //<Priya20160216> Modified usernames
        sysUser = new User(LastName='XYZ',UserRoleId=r1.Id,ProfileId=p1.Id,Alias='ain123',EmailEncodingKey='UTF-8',TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',LanguageLocaleKey='en_US',Email='XYZ@infosys.com',UserName='XYZ_DPtest@infosys.com', EPass_ID__c='NA0000',User_Owning_Org__c='AGCP-CPC',User_Country__c='India',User_Grouping__c='CPC',User_Region__c='Latin America');
        user2 = new User(LastName='XYZ1',UserRoleId=r1.Id,ProfileId=p1.Id,Alias='ain1234',EmailEncodingKey='UTF-8',TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',LanguageLocaleKey='en_US',Email='XYZ1@infosys.com',UserName='XYZ1_DPtest@infosys.com', EPass_ID__c='NA0000',User_Owning_Org__c='AGCP-CPC',User_Country__c='India',User_Grouping__c='CPC',User_Region__c='Latin America');
        user3 = new User(LastName='XYZ2',UserRoleId=r1.Id,ProfileId=p1.Id,Alias='ain1235',EmailEncodingKey='UTF-8',TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',LanguageLocaleKey='en_US',Email='XYZ2@abc.com',UserName='XYZ2_DPtest@abc.com', EPass_ID__c='NA0000',User_Owning_Org__c='AGCP-CPC',User_Country__c='India',User_Grouping__c='CPC',User_Region__c='Latin America');
        User [] users=new User[]{sysUser,user2,user3};
        insert users;
        
    }

     static testMethod void testAddSharesforReadWrite() {
                testCreateUsers();  
                System.RunAs(sysUser){
                CRM_IT_Project__c proj1 = new CRM_IT_Project__c(Name = 'TEST',OwnerId = sysUser.Id);
                insert proj1;
                Project_Member__c pm1 = new Project_Member__c(Access__c ='Read/Write',CRM_IT_Project__c = proj1.Id,Project_Member__c = user2.Id);
                insert pm1;
                Project_Member__c pm2 = new Project_Member__c(Access__c ='Read/Write',CRM_IT_Project__c = proj1.Id,Project_Member__c = user3.Id);
                insert pm2;
                
                List<Project_Member__c> pms = new List<Project_Member__c>();
                pms.add(pm1);
                pms.add(pm2);
                
                // get a set of all new created ids
                Set<ID> ids = new Set<ID>();
                for (Project_Member__c pm : pms)
                ids.add(pm.CRM_IT_Project__c);

                List<CRM_IT_Project__Share> shares = [select id from CRM_IT_Project__Share where 
                   ParentId IN :ids and RowCause = 'Apex_Sharing_Access__c'];
                    //System.assertEquals(shares.size(),2);
                    
                    ProjectMemberHandler.refreshprojmembers(new SET<Id> {pm1.id});
                    delete pm1;
                }
                }
                
      static testMethod void testAddSharesforReadOnly() {
                
                testCreateUsers();
                System.RunAs(sysUser){
                CRM_IT_Project__c proj1 = new CRM_IT_Project__c(Name = 'TEST',OwnerId =sysUser.Id);
                insert proj1;
                Project_Member__c pm1 = new Project_Member__c(Access__c ='Read Only',CRM_IT_Project__c = proj1.Id,Project_Member__c = user2.Id);
                insert pm1;
                Project_Member__c pm2 = new Project_Member__c(Access__c ='Read Only',CRM_IT_Project__c = proj1.Id,Project_Member__c = user3.Id);
                insert pm2;
                
                List<Project_Member__c> pms = new List<Project_Member__c>();
                pms.add(pm1);
                pms.add(pm2);
                
                // get a set of all new created ids
                Set<ID> ids = new Set<ID>();
                for (Project_Member__c pm : pms)
                ids.add(pm.CRM_IT_Project__c);

                List<CRM_IT_Project__Share> shares = [select id from CRM_IT_Project__Share where 
                   ParentId IN :ids and RowCause = 'Apex_Sharing_Access__c'];
                    //System.assertEquals(shares.size(),2);
                }
                }
                
       static testMethod void testUpdateProjectMembers (){
                
                testCreateUsers();
                System.RunAs(sysUser){
                CRM_IT_Project__c proj1 = new CRM_IT_Project__c(Name = 'TEST',OwnerId =sysUser.Id);
                insert proj1;
                Project_Member__c pm1 = new Project_Member__c(Access__c ='Private',CRM_IT_Project__c = proj1.Id,Project_Member__c = user2.Id);
                insert pm1;
                Project_Member__c pm2 = new Project_Member__c(Access__c ='Private',CRM_IT_Project__c = proj1.Id,Project_Member__c = user3.Id);
                insert pm2;
     
                List<Project_Member__c> pms = new List<Project_Member__c>();
                pms.add(pm1);
                pms.add(pm2);
                
                // get a set of all new created ids
                Set<ID> ids = new Set<ID>();
                for (Project_Member__c pm : pms)
                ids.add(pm.CRM_IT_Project__c);
                
                update pms;
                 
                List<CRM_IT_Project__Share> shares = [select id from CRM_IT_Project__Share where 
                   ParentId IN :ids and RowCause = 'Apex_Sharing_Access__c'];
                    //System.assertEquals(shares.size(),0);
                
     
                for (Project_Member__c pm : pms)
                pm.Access__c = 'Read/Write';
                
                update pms;
                
                shares = [select id from CRM_IT_Project__Share where ParentId IN :ids and RowCause = 'Apex_Sharing_Access__c'];
                //System.assertEquals(shares.size(),2);
                
                for (Project_Member__c pm : pms)
                pm.Access__c = 'Read Only';
                
                update pms;
                
                shares = [select id from CRM_IT_Project__Share where ParentId IN :ids and RowCause = 'Apex_Sharing_Access__c'];
                //System.assertEquals(shares.size(),2);

                for (Project_Member__c pm : pms)
                pm.Access__c = 'Private';
                
                update pms;
                
                shares = [select id from CRM_IT_Project__Share where ParentId IN :ids and RowCause = 'Apex_Sharing_Access__c'];
                //System.assertEquals(shares.size(),0);
                }
             }
             
   }