DuPont DevSB/src/objects/CS_Account_Load_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used for storing all the used values in Accounts Batch processes.</description>
    <fields>
        <fullName>AccountGroup__c</fullName>
        <label>AccountGroup</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountOwnerUserName__c</fullName>
        <description>This field will hold the username.</description>
        <inlineHelpText>This field will hold the username of static user &quot;Customer Service&quot; created in application.</inlineHelpText>
        <label>Account Owner User Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountOwner__c</fullName>
        <label>Account Owner</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType_Name__c</fullName>
        <label>RecordType Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendErrorNotificationTo__c</fullName>
        <label>Send Error Notification To</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CS_AccountLoadSettings</label>
</CustomObject>

DuPont DevSB/src/objects/CS_YKPartnerMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will be used for mapping YK Partner types to their Service Centers</description>
    <fields>
        <fullName>Shared_Service_Center__c</fullName>
        <label>Shared Service Center</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>CS YK Partner Mapping</label>
</CustomObject>

DuPont DevSB/src/classes/scheduleCSAccountDailyUpdate_UT.cls
/*******************************************************************************
Copyright © 2015 DuPont. All rights reserved.
Author: Prerna Chandak
Email: prerna.chandak@accenture.com
Description: test Class to cover Batch Process scheduleCSAccountDailyUpdate. 
********************************************************************************/
@isTest
private class scheduleCSAccountDailyUpdate_UT{

static testMethod void testschedule() {

Test.StartTest();
CS_Account_Load_Settings__c s= new CS_Account_Load_Settings__c(Name='Batch Criteria',AccountGroup__c='Z001 ( Sold-to party )',AccountOwner__c='Customer Service',AccountOwnerUserName__c='customerservice@dupont.com',RecordType_Name__c='ERP Customer - Extended Data',
SendErrorNotificationTo__c='anup_kumar14@infosys.com');
insert s;
CS_YKPartnerMapping__c cs=new CS_YKPartnerMapping__c(Name='25590',Shared_Service_Center__c='CSCI');
insert cs;
scheduleCSAccountDailyUpdate shcheduledClass = new scheduleCSAccountDailyUpdate();

String sch = '0 0 0 15 3 ? 2022';
system.schedule('Test', sch, shcheduledClass); 
Test.stopTest(); 

}





}