DuPont DevSB/src/objects/Customer_Data_Request_Line_Item__c.object
<CustomObject>
    <description>Line Items to capture multiple Bill To, ship to, Pay to and Partner User Requests</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>This will capture country of the New Partner</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AD - Andorran</fullName>
                </value>
                <value>
                    <fullName>AE - Utd.Arab Emir.</fullName>
                </value>
                <value>
                    <fullName>AF - Afghanistan</fullName>
                </value>
                <value>
                    <fullName>AG - Antigua/Barbuda</fullName>
                </value>
                <value>
                    <fullName>AI - Anguilla</fullName>
                </value>
                <value>
                    <fullName>AL - Albania</fullName>
                </value>
                <value>
                    <fullName>AM - Armenia</fullName>
                </value>
                <value>
                    <fullName>AN</fullName>
                </value>
                <value>
                    <fullName>AO - Angola</fullName>
                </value>
                <value>
                    <fullName>AQ - Antarctica</fullName>
                </value>
                <value>
                    <fullName>AR - Argentina</fullName>
                </value>
                <value>
                    <fullName>AS - Samoa, America</fullName>
                </value>
                <value>
                    <fullName>AT - Austria</fullName>
                </value>
                <value>
                    <fullName>AU - Australia</fullName>
                </value>
                <value>
                    <fullName>AW - Aruba</fullName>
                </value>
                <value>
                    <fullName>AX - Aaland</fullName>
                </value>
                <value>
                    <fullName>AZ - Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>BA - Bosnia-Herz.</fullName>
                </value>
                <value>
                    <fullName>BB - Barbados</fullName>
                </value>
                <value>
                    <fullName>BD - Bangladesh</fullName>
                </value>
                <value>
                    <fullName>BE - Belgium</fullName>
                </value>
                <value>
                    <fullName>BF - Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>BG - Bulgaria</fullName>
                </value>
                <value>
                    <fullName>BH - Bahrain</fullName>
                </value>
                <value>
                    <fullName>BI - Burundi</fullName>
                </value>
                <value>
                    <fullName>BJ - Benin</fullName>
                </value>
                <value>
                    <fullName>BL - St. Barthélemy</fullName>
                </value>
                <value>
                    <fullName>BM - Bermuda</fullName>
                </value>
                <value>
                    <fullName>BN - Brunei Daruss.</fullName>
                </value>
                <value>
                    <fullName>BO - Bolivia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Data_Request__c</fullName>
        <description>The reference to the Customer Data Request to which this Line item belongs</description>
        <label>Customer Data Request</label>
        <referenceTo>Customer_Data_Request__c</referenceTo>
        <relationshipLabel>Customer Data Request Line Items</relationshipLabel>
        <relationshipName>Customer_Data_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Name_2__c</fullName>
        <description>Alternative name of the customer or an addition to the name of the customer</description>
        <label>Customer Name 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <description>Name of the Customer</description>
        <label>Customer Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Language_Country__c</fullName>
        <description>&quot;Name of the Country in local language

The approved list of ISO countries use by DuPont. Source reference ISO 3166-1: http://www.iso.org/iso/country_codes/iso_3166_code_lists/english_country_names_and_code_elements.htm&quot;</description>
        <label>Local Language Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AD - Andorran</fullName>
                </value>
                <value>
                    <fullName>AE - Utd.Arab Emir.</fullName>
                </value>
                <value>
                    <fullName>AF - Afghanistan</fullName>
                </value>
                <value>
                    <fullName>AG - Antigua/Barbuda</fullName>
                </value>
                <value>
                    <fullName>AI - Anguilla</fullName>
                </value>
                <value>
                    <fullName>AL - Albania</fullName>
                </value>
                <value>
                    <fullName>AM - Armenia</fullName>
                </value>
                <value>
                    <fullName>AN</fullName>
                </value>
                <value>
                    <fullName>AO - Angola</fullName>
                </value>
                <value>
                    <fullName>AQ - Antarctica</fullName>
                </value>
                <value>
                    <fullName>AR - Argentina</fullName>
                </value>
                <value>
                    <fullName>AS - Samoa, America</fullName>
                </value>
                <value>
                    <fullName>AT - Austria</fullName>
                </value>
                <value>
                    <fullName>AU - Australia</fullName>
                </value>
                <value>
                    <fullName>AW - Aruba</fullName>
                </value>
                <value>
                    <fullName>AX - Aaland</fullName>
                </value>
                <value>
                    <fullName>AZ - Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>BA - Bosnia-Herz.</fullName>
                </value>
                <value>
                    <fullName>BB - Barbados</fullName>
                </value>
                <value>
                    <fullName>BD - Bangladesh</fullName>
                </value>
                <value>
                    <fullName>BE - Belgium</fullName>
                </value>
                <value>
                    <fullName>BF - Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>BG - Bulgaria</fullName>
                </value>
                <value>
                    <fullName>BH - Bahrain</fullName>
                </value>
                <value>
                    <fullName>BI - Burundi</fullName>
                </value>
                <value>
                    <fullName>BJ - Benin</fullName>
                </value>
                <value>
                    <fullName>BL - St. Barthélemy</fullName>
                </value>
                <value>
                    <fullName>BM - Bermuda</fullName>
                </value>
                <value>
                    <fullName>BN - Brunei Daruss.</fullName>
                </value>
                <value>
                    <fullName>BO - Bolivia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Local_Version__c</fullName>
        <description>The local language to be selected by the user entering the address(Bill To/Ship To/PayTo)</description>
        <label>Local Version</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese Trad.</fullName>
                </value>
                <value>
                    <fullName>Cyrillic</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hangul</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Kanji</fullName>
                </value>
                <value>
                    <fullName>Katakana</fullName>
                </value>
                <value>
                    <fullName>Thai</fullName>
                </value>
                <value>
                    <fullName>Ukranian_Cyril</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Data Request Line Item</label>
    <nameField>
        <displayFormat>CDRITM-{YY}{MM}{DD}-{000000000}</displayFormat>
        <label>Customer Data Request Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Data Request Line Items</pluralLabel>
    <recordTypes>
        <fullName>Create_new_bill_to_ship_to_payer</fullName>
        <active>true</active>
        <description>Create a request to add additional bill to, ship to and payer account groups to an existing customer</description>
        <label>Create new bill to, ship to, payer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Create_new_partner_function</fullName>
        <active>true</active>
        <description>Create a request to add a create partner user for example end user, CSR, sales, etc.</description>
        <label>Create new partner function</label>
    </recordTypes>
    <recordTypes>
        <fullName>Link_Contact</fullName>
        <active>true</active>
        <description>Create a request  to add/link additional contacts to an existing customer</description>
        <label>Link Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Link_Existing_Partner_Function</fullName>
        <active>true</active>
        <description>Create a request to link a existing partner user to an existing customer</description>
        <label>Link Existing Partner Function</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlCustMasterDataReqLineItemNewEdit_UT.cls
@isTest
public class ctrlCustMasterDataReqLineItemNewEdit_UT{

 public static final string CREATENEWBILLTOSHIPTOPAYTO_CDRLI_RTYPE = Rtype.getIdByDevName('Customer_Data_Request_Line_Item__c','Create_new_bill_to_ship_to_payer');
    public static final string LINKCONTACT_CDRLI_RTYPE = Rtype.getIdByDevName('Customer_Data_Request_Line_Item__c','Link_Contact');
    public static final string LINKEXISTINGPARTNER_CDRLI_RTYPE = Rtype.getIdByDevName('Customer_Data_Request_Line_Item__c','Link_Existing_Partner_Function');
    public static final string CREATENEWPARTNERFUNCTION_CDRLI_RTYPE = Rtype.getIdByDevName('Customer_Data_Request_Line_Item__c','Create_new_partner_function');



Public static testMethod void MasterDataReq(){
 Test.StartTest();
 
  Customer_Data_Request__c cdr = new Customer_Data_Request__c();
        cdr.Customer_Name__c='TestA';
        cdr.Customer_Name_2__c='TestB';
        cdr.Record_Locked__c=true;
        cdr.Sold_To_Office_House_Number__c = 'test';
        cdr.Sold_to_State_Province__c = 'test';
        insert cdr;       
 
   Customer_Data_Request_Line_Item__c cli=new Customer_Data_Request_Line_Item__c();
     cli.Customer_Name__c='TestA';
     cli.Customer_Name_2__c='TestB';
     cli.Customer_Data_Request__c=cdr.id;
     cli.Local_Version__c='Arabic';
     cli.Country__c='AD - Andorran';
     cli.Local_Language_Country__c='AF - Afghanistan';
     insert cli;
   
   Customer_Data_Request_Line_Item__c cdrli=new Customer_Data_Request_Line_Item__c();

  ApexPages.StandardController sd = new ApexPages.standardController(cdrli);
  ctrlCustMasterDataReqLineItemNewEdit con1 = new ctrlCustMasterDataReqLineItemNewEdit(sd);
  con1.redirect();
  
  cdrli.recordtypeId=CREATENEWBILLTOSHIPTOPAYTO_CDRLI_RTYPE;
  con1.redirect();
  
  cdrli.recordtypeId=LINKCONTACT_CDRLI_RTYPE ;
  con1.redirect();
  
  cdrli.recordtypeId=LINKEXISTINGPARTNER_CDRLI_RTYPE;
  con1.redirect();
  
  cdrli.recordtypeId=CREATENEWPARTNERFUNCTION_CDRLI_RTYPE;
  con1.redirect();
  
  ApexPages.StandardController sc = new ApexPages.standardController(cli);
  ctrlCustMasterDataReqLineItemNewEdit con = new ctrlCustMasterDataReqLineItemNewEdit(sc);
  con.redirect();

  cli.recordtypeId=CREATENEWBILLTOSHIPTOPAYTO_CDRLI_RTYPE;
  update cli;
  con.redirect();
  
  cli.recordtypeId=LINKCONTACT_CDRLI_RTYPE ;
  update cli;
  con.redirect();
  
  cli.recordtypeId=LINKEXISTINGPARTNER_CDRLI_RTYPE;
  update cli;
  con.redirect();
  
  cli.recordtypeId=CREATENEWPARTNERFUNCTION_CDRLI_RTYPE;
  update cli;
  con.redirect();
  
  //ApexPages.hasMessages.put(ApexPages.SEVERITY.ERROR,'Error');
  con.redirect();

test.stopTest();
}
}