DuPont DevSB/src/objects/Demand__c.object
<CustomObject>
    <description>Main Object for storing Demand Signals for each Demand Item (Product, Market Segment, etc)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to an account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Demand</relationshipLabel>
        <relationshipName>Demand</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offset__c</fullName>
        <description>Number of months to go back for UI display</description>
        <label>Offset</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SnapShotDay__c</fullName>
        <description>Day of the month to run the Snapshot.  0 or null to ignore.</description>
        <label>SnapShot Day</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Demand View Type (Inventory, Production, Purchases, Sales etc..)</description>
        <label>Demand View Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Purchases</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Demand</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demand</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/DemandItem__c.object
<CustomObject>
    <description>Demand Item can represent a Product, Material, Market Segment to record demand signals.</description>
    <fields>
        <fullName>Demand__c</fullName>
        <description>M/D to Demand</description>
        <label>Demand</label>
        <referenceTo>Demand__c</referenceTo>
        <relationshipLabel>Demand Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Demand Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demand Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/DemandItemSchedule__c.object
<CustomObject>
    <description>Schedule for a given demand Item.  One record represents the demand for a given month</description>
    <fields>
        <fullName>BaseDate__c</fullName>
        <description>Date that indicates the month this record represents.  Typically beginning of month.</description>
        <inlineHelpText>Date that indicates the month this record represents. Typically beginning of month.</inlineHelpText>
        <label>Base Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DemandItem__c</fullName>
        <description>M/D to Demand Item</description>
        <label>Demand Item</label>
        <referenceTo>DemandItem__c</referenceTo>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Last_Snapshot_Date__c</fullName>
        <description>Field to capture the date when the last snapshot was taken</description>
        <inlineHelpText>Read Only field for when the last snapshot was taken</inlineHelpText>
        <label>Last Snapshot Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Snapshot_Taken_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the name of the user executed the snapshot functionality</description>
        <inlineHelpText>Last Snapshot Taken By User</inlineHelpText>
        <label>Last Snapshot Taken By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Demand_Item_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QtyFcst1__c</fullName>
        <description>Forecast Qty Snapshot - 1 Months ago</description>
        <label>Forecast Qty Snapshot - 1 Months ago</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QtyFcst2__c</fullName>
        <description>Forecast Qty Snapshot - 2 Months ago</description>
        <inlineHelpText>Forecast Qty Snapshot - 2 Months ago</inlineHelpText>
        <label>Forecast Qty Snapshot - 2 Months ago</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QtyFcst__c</fullName>
        <label>Forecast Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RevFcst1__c</fullName>
        <label>Forecast Rev Snapshot  - 1 Months ago</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RevFcst2__c</fullName>
        <label>Forecast Rev Snapshot - 2 Months ago</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RevFcst__c</fullName>
        <label>Forecast Revenue</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Demand Item Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demand Item Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/DemandSnapshotManual.cls
/*******************************************************************************
Copyright © 2014 DuPont. All rights reserved. 
Author: Abhinav Bhatnagar
Email: abhinav.bhatnagar@dupont.com

Description: Class to traverse each BI account, check for snapshot date and take snapshot 

**********************************************************************************/

public class DemandSnapshotManual{
    public List<DemandItem__c> di{get;set;}
    public List<DemandItemSchedule__c> dis{get;set;} 
    
    private final ApexPages.StandardController controller;
    
    public DemandSnapshotManual(ApexPages.StandardController stdController) {
        controller = stdController;
        
    }
    
    public DemandSnapshotManual(){
        
    }
    public void takeSnapshot(){
        DemandItems objDemandItem = new DemandItems(controller.getRecord().id);
        di = objDemandItem.di;
        DemandItemSchedules objDemandItemSchedules = new DemandItemSchedules(di);
        dis = objDemandItemSchedules.dis;
        
        updateDemandItemSchedule();
        
    }
    
    public void updateDemandItemSchedule(){
        
        List<DemandItemSchedule__c> disUpdated = new List<DemandItemSchedule__c>();
        for(DemandItemSchedule__c s:dis){
            Integer monthDiff = Date.today().monthsBetween(s.BaseDate__c);
            System.debug('monthDiff pre -->'+monthDiff+' Date.today()'+Date.today()+'s.BaseDate__c '+s.BaseDate__c);
            
            if (Date.today().day() < s.BaseDate__c.day()) monthDiff--;
            System.debug('monthDiff post -->'+monthDiff);
            if(monthDiff==1){
                s.QtyFcst1__c = s.QtyFcst__c;
                s.RevFcst1__c = s.RevFcst__c;
                disUpdated.add(s);
            }else  if(monthDiff==2){
                s.QtyFcst2__c = s.QtyFcst__c;
                s.RevFcst2__c = s.RevFcst__c;
                disUpdated.add(s);
            }
            s.Last_Snapshot_Date__c = Date.today();
            s.Last_Snapshot_Taken_By__c = UserInfo.getUserId();
        }
        
        
        upsert disUpdated;
    }
    /////////////////////////////////////////////////////////////////////////////////////////////////
    public class DemandItemSchedules{
        public List<DemandItemSchedule__c> dis{get;set;}
        
        public DemandItemSchedules(List<DemandItem__c> di){
            dis = getDemandItemSchedules(di);            
            
        }
        
        public List<DemandItemSchedule__c> getDemandItemSchedules(List<DemandItem__c> di){            
            List<DemandItemSchedule__c> demandItemsSch = new List<DemandItemSchedule__c>();
            Set<Id> DemandItemIds = new Set<Id>();
            for(DemandItem__c d: di){
                DemanditemIds.add(d.id);
            }
            ///
            List<DemandItem__c> d1 =  Database.query(getDemandItemScheduleQuery(DemanditemIds));
            for(DemandItem__c d: d1){
                for(DemandItemSchedule__c dis: d.Schedules__r){	
                    demandItemsSch.add(dis);
                }
            }
            ///
            
            return demandItemsSch;
        }
        
        public String getDemandItemScheduleQuery(Set<Id> DemandItemIds){
            Date currentDate = Date.today();
            Date startDate =  currentDate.toStartOfMonth();
            Date nextToNextMonth = startDate.addMonths(2);
            Date endDate = Date.newInstance(nextToNextMonth.year(), nextToNextMonth.month(), Date.daysInMonth(nextToNextMonth.year(), nextToNextMonth.month()));
            //System.debug('currentDate --> '+currentDate+'currentDate.year() '+currentDate.year()+'currentDate.month() '+currentDate.month()+'startDate '+startDate+' nextToNextMonth '+nextToNextMonth);
            String strQuery = 'SELECT Name, (SELECT BaseDate__c,QtyFcst1__c,QtyFcst2__c,RevFcst1__c,RevFcst2__c,QtyFcst__c,RevFcst__c,Last_Snapshot_Date__c,Last_Snapshot_Taken_By__c FROM Schedules__r where BaseDate__c>='+String.valueOf(startDate).substring(0,10)+' AND BaseDate__c<='+String.valueOf(endDate).substring(0,10)+') FROM DemandItem__c where id IN :DemandItemIds';
            //System.debug('getDemandItemScheduleQuery ---- > '+strQuery);
            return strQuery;
        }
        
        
        
        
    }
    /////////////////////////////////////////////////////////////////////////////////////////////////
    public class DemandItems{
        public List<DemandItem__c> di{get;set;}
        
        
        public DemandItems(Id demandId){
            di = getDemandItems(demandId);            
            
        }
        
        public List<DemandItem__c> getDemandItems(Id demandId){            
            
            List<DemandItem__c> demandItems = new List<DemandItem__c>();
            List<Demand__c> d1 = Database.query(getDemandItemsQuery(demandId));
            for(Demand__c de: d1){           
                for(DemandItem__c di: de.Items__r){
                    demandItems.add(di);
                }
            }
            
            ///
            return demandItems;
        }
        
        public String getDemandItemsQuery(Id DemandId){
            String strQuery = 'SELECT Name, (SELECT Demand__c,Name,Id FROM Items__r) FROM Demand__c where id =\''+DemandId+'\'';
            System.debug('getDemandItemsQuery ---- > '+strQuery);
            return strQuery;
        }
        
        
    }
    
    /////////////////////////////////////////////////////////////////////////////////////////////////
    public class Demands{
        
        public List<Demand__c> getDemand(Id demandId){            
            List<Demand__c> Demand = Database.query(getDemandsQuery(demandId));
            return  Demand;
        }
        
        public String getDemandsQuery(Id demandId){
            String strQuery = 'SELECT Account__c,Offset__c,Id,SnapShotDay__c,Type__c FROM Demand__r where  id=\''+demandId+'\'';
            System.debug('getDemandsQuery ---- > '+strQuery);
            return strQuery;
        }
    }
}