DuPont DevSB/src/objects/Demand__c.object
<CustomObject>
    <description>Main Object for storing Demand Signals for each Demand Item (Product, Market Segment, etc)</description>
    <label>Demand</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demand</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/DemandItem__c.object
<CustomObject>
    <description>Demand Item can represent a Product, Material, Market Segment to record demand signals.</description>
    <fields>
        <fullName>Demand__c</fullName>
        <description>M/D to Demand</description>
        <label>Demand</label>
        <referenceTo>Demand__c</referenceTo>
        <relationshipLabel>Demand Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Demand Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demand Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/DemandItemSchedule__c.object
<CustomObject>
    <description>Schedule for a given demand Item.  One record represents the demand for a given month</description>
    <fields>
        <fullName>BaseDate__c</fullName>
        <description>Date that indicates the month this record represents.  Typically beginning of month.</description>
        <inlineHelpText>Date that indicates the month this record represents. Typically beginning of month.</inlineHelpText>
        <label>Base Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DemandItem__c</fullName>
        <description>M/D to Demand Item</description>
        <label>Demand Item</label>
        <referenceTo>DemandItem__c</referenceTo>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Last_Snapshot_Date__c</fullName>
        <description>Field to capture the date when the last snapshot was taken</description>
        <inlineHelpText>Read Only field for when the last snapshot was taken</inlineHelpText>
        <label>Last Snapshot Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Snapshot_Taken_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the name of the user executed the snapshot functionality</description>
        <inlineHelpText>Last Snapshot Taken By User</inlineHelpText>
        <label>Last Snapshot Taken By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Demand_Item_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QtyFcst__c</fullName>
        <label>Forecast Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RevFcst__c</fullName>
        <label>Forecast Revenue</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Demand Item Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demand Item Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/batchDemandSnapshot.cls
/*******************************************************************************
Copyright © 2013 DuPont. All rights reserved. 
Author: Thomas Snyder
Email: thomas.snyder@usa.dupont.com, tom@3ddd.com
Description:  batch class to DoSomething
Database.executeBatch(new batchDemandSnapshot(),200);
<AB20140911> - Updated for updating fields Last Snapshot Taken and Last Snapshot Taken By
<20170908:Shubham Agarwal> : Commented to restrict email notification on batch Job completion, however batch failures will be captured as issues by Batch Job monitoring Process.
********************************************************************************/
global class batchDemandSnapshot implements Database.Batchable<Sobject>, Database.Stateful {

    global DmlResults unsuccessfuls;
    
    
    global batchDemandSnapshot() {
        unsuccessfuls= new DmlResults();
    }
        
    global Database.QueryLocator start(Database.BatchableContext BC){
        if (Test.IsRunningTest()) {
        return Database.getQueryLocator([
            SELECT Id FROM DemandItemSchedule__c WHERE DemandItem__r.Demand__r.SnapShotDay__c =: Date.Today().day() 
                AND BaseDate__c >= :Date.Today().addMonths(-1) LIMIT 200]);
        }
        return Database.getQueryLocator([
            SELECT Id FROM DemandItemSchedule__c WHERE DemandItem__r.Demand__r.SnapShotDay__c =: Date.Today().day()
                AND BaseDate__c >= :Date.Today().addMonths(-1) ]);
        }
        
    global void execute(Database.BatchableContext BC, LIST<SObject> scope) {
            Util.Describe descrDIS = new Util.Describe('DemandItemSchedule__c');
            LIST<DemandItemSchedule__c> diss =  (LIST<DemandItemSchedule__c>) descrDIS.getObjects(scope);
            for (DemandItemSchedule__c dis : diss) {
                integer offset = Date.Today().monthsBetween(dis.BaseDate__c);
                if (offset>=0) {
                    string qtySSField = 'QtyFcst'+offset+'__c'; 
                    string revSSField = 'RevFcst'+offset+'__c';
                    if (descrDIS.FieldExist(qtySSField))
                        dis.put(qtySSField,dis.QtyFcst__c);
                    if (descrDIS.FieldExist(revSSField))
                        dis.put(revSSField,dis.RevFcst__c);     
                     //   <AB20140911> Starts
                     dis.Last_Snapshot_Date__c = Date.today();
                     dis.Last_Snapshot_Taken_By__c = UserInfo.getUserId();
                    //<AB20140911> Ends
                }
            }
            unsuccessfuls.add(new DmlResults(database.update(diss,false),diss));
    } 
    
    global void finish(Database.BatchableContext BC) {
     //<20170908:Shubham Agarwal> : Commented to restrict email notification on batch Job completion, however batch failures will be captured as issues by Batch Job monitoring Process.
       // utilEmail.batchOnFinish(BC.getJobId(), unsuccessfuls, false);  
       //<20170908:Shubham Agarwal> : End  
    }

}