DuPont DevSB/src/objects/Entitlement.object
<CustomObject>
    <recordTypes>
        <fullName>BI_EMEA_Entitlement</fullName>
        <active>true</active>
        <description>BI-EMEA Entitlement Record Type</description>
        <label>BI-EMEA Entitlement</label>
    </recordTypes>
    <recordTypes>
        <fullName>BI_NA_Env_Product_Labor</fullName>
        <active>true</active>
        <description>BI-NA Envelopes Entitlements/Registrations Product and Labor Record type</description>
        <label>BI-NA Env Product &amp; Labor</label>
    </recordTypes>
    <recordTypes>
        <fullName>BI_NA_Env_Product_Only</fullName>
        <active>true</active>
        <description>BI-NA Envelopes Entitlements/Registrations Product Only Record type</description>
        <label>BI-NA Env Product Only</label>
    </recordTypes>
    <recordTypes>
        <fullName>BI_NA_Env_Product_Only_Fluid_Applied</fullName>
        <active>true</active>
        <description>BI-NA Envelopes Entitlements/Registrations Product Only - Fluid Applied Record type</description>
        <label>BI-NA Env Product Only – Fluid Applied</label>
    </recordTypes>
    <recordTypes>
        <fullName>BI_NA_Surface_Entitlement</fullName>
        <active>true</active>
        <description>BI-NA Surfaces Entitlements/Registrations Record type</description>
        <label>BI-NA Surfaces Entitlement</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EPass_ID__c</fullName>
        <description>Positive identification of individuals accessing DuPont computer systems.</description>
        <label>E-Pass ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Grouping__c</fullName>
        <description>DuPont Business</description>
        <inlineHelpText>DuPont Business (abbrev)</inlineHelpText>
        <label>User Grouping</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>DC&amp;F</fullName>
                </value>
                <value>
                    <fullName>DPM</fullName>
                </value>
                <value>
                    <fullName>DPS</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Owning_Org__c</fullName>
        <description>Primary &quot;Owning Organisation&quot; this user belongs to</description>
        <label>User Owning Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-Env</fullName>
                </value>
                <value>
                    <fullName>BI-Surf</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>CORP-CS</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-ES</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PM</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PS</fullName>
                </value>
                <value>
                    <fullName>DPT-Aramids</fullName>
                </value>
                <value>
                    <fullName>DPT-Automotive</fullName>
                </value>
                <value>
                    <fullName>DPT-Car Protection</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP</fullName>
                </value>
                <value>
                    <fullName>DPT-NOW</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IAL</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>LEGL</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Corp Marketing</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Customer Care</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-IT</fullName>
                </value>
                <value>
                    <fullName>DPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Region__c</fullName>
        <label>User Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlOverideCase_UT.cls
/////////////////////////////////////////////////////////////////////////////////////////////////////////
//Copyright © 2014 DuPont. All rights reserved. 
//Name :ctrlOverideEntitlement_UT
//Author :Rajiv Kumar Bhatter<Rajiv_Bhatter@infosys.com>, Sanjay Nandi<Sanjay_Nandi@infosys.com>
//Description: This class is Unit Test class for class ctrlOverideEntitlement
//***************************************************************************************//
@isTest(Seealldata=true)
private class ctrlOverideCase_UT{
        static testMethod void testctrlOverideCase_UT() {
        Profile p1 = [select id from profile where Name='System Administrator' limit 1];
        UserRole r1= [Select id from UserRole where Name='PS CRM' limit 1];
        User user1 = new User(LastName='XYZ',UserRoleId=r1.Id,ProfileId=p1.Id,Alias='ain123',EmailEncodingKey='UTF-8',TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',LanguageLocaleKey='en_US',Email='sanjay_nandi@infosys.com',UserName='sanjay@infosys.com.t12', EPass_ID__c='NA0000',User_Owning_Org__c='AGCP-CPC',User_Country__c='India',User_Grouping__c='CPC',User_Region__c='Latin America');
        insert user1;
        System.runas(user1){
        
        Final string BISURFACEAcc_RTYPE= Rtype.getIdByDevName('Account','BI_Tyvek');
        Final string BITYVEKAcc_RTYPE = Rtype.getIdByDevName('Account','BI_Surfaces');
        Final string BISURFACE_RTYPE= Rtype.getIdByDevName('Case','BI_NA_Surfaces_Case');
        Final string BITYVEK_RTYPE = Rtype.getIdByDevName('Case','BI_NA_Envelopes_Case');
        Final string OTHERCASE = Rtype.getIdByDevName('Case','BI_Case');
        Final string PRODUCTANDLABOUT_COB_RTYPE = Rtype.getIdByDevName('Entitlement','BI_NA_Env_Product_Labor');
        Final string PRODUCTONLY_COB_RTYPE = Rtype.getIdByDevName('Entitlement','BI_NA_Env_Product_Only');
        Final string PRODUCTFLUIDAPPLIED_COB_RTYPE = Rtype.getIdByDevName('Entitlement','BI_NA_Env_Product_Only_Fluid_Applied');
        Final string SurfaceEntitlement=Rtype.getIdByDevName('Entitlement','BI_NA_Surface_Entitlement');
        Final string OTHERENTIT=Rtype.getIdByDevName('Entitlement','BI_EMEA_Entitlement');
        geoValidation.validateInTestMode=false;
        
        Date d2=date.newinstance(2014, 10, 22);
        Date d3=date.newinstance(2014, 9, 22);
        Account accTyvek= new Account(name='SanjayTdfgdfvek',BI_Account_SubType__c='Fabricator',RecordtypeId=BISURFACEAcc_RTYPE);
        insert accTyvek;
        Account accSurf= new Account(name='sanjayfdgfdSurface',BI_Account_SubType__c='Fabricator',Recordtypeid=BITYVEKAcc_RTYPE);
        insert accSurf;
        Entitlement entTyvek= new Entitlement(name='SanjayTvek',RecordtypeId=PRODUCTANDLABOUT_COB_RTYPE,startdate=d2,AccountId=accTyvek.Id);
        insert entTyvek;
        Entitlement entSurf= new Entitlement(name='sanjaySurface',Recordtypeid=SurfaceEntitlement,startdate=d2,AccountId=accSurf.Id);
        insert entSurf;
        Entitlement entother= new Entitlement(name='sanjaySurface',Recordtypeid=OTHERENTIT,startdate=d2,AccountId=accSurf.Id);
        insert entother;
        Entitlement entTyvek1= new Entitlement(name='SanjayTvek',RecordtypeId=PRODUCTANDLABOUT_COB_RTYPE,startdate=d3,AccountId=accTyvek.Id);
        insert entTyvek1;
        Entitlement entSurf1= new Entitlement(name='sanjaySurface',Recordtypeid=SurfaceEntitlement,startdate=d3,AccountId=accSurf.Id);
        insert entSurf1;
        Entitlement entother1= new Entitlement(name='sanjaySurface',Recordtypeid=OTHERENTIT,startdate=d3,AccountId=accSurf.Id);
        insert entother1;
        Test.startTest();
        Case cas=new Case();
        
        ApexPAges.StandardController controller = new ApexPages.StandardController(cas);
        ctrlOverideNewCase c1 = new ctrlOverideNewCase (controller);
        cas.recordtypeid=BITYVEK_RTYPE;
        c1.retPage();
        c1.redirectToPage();
        
        ApexPAges.StandardController controller2 = new ApexPages.StandardController(cas);
        cas.recordtypeid=BITYVEK_RTYPE;
        ctrlOverideNewCase c2 = new ctrlOverideNewCase (controller2);
        c2.redirectToPage();
        
        ApexPAges.StandardController controller4 = new ApexPages.StandardController(cas);    
        cas.recordtypeid=BITYVEK_RTYPE; 
        ApexPages.currentPage().getParameters().put('def_entitlement_id',entSurf.id);
        ctrlOverideNewCase c4 = new ctrlOverideNewCase (controller4);
        c4.redirectToPage();
        
        ApexPAges.StandardController controller5 = new ApexPages.StandardController(cas);     
        ApexPages.currentPage().getParameters().put('def_entitlement_id',entSurf1.id);
        ctrlOverideNewCase c5 = new ctrlOverideNewCase (controller5);
        cas.recordtypeid=BITYVEK_RTYPE;
        c5.redirectToPage();
        
        ApexPAges.StandardController controller6= new ApexPages.StandardController(cas);  
        ApexPages.currentPage().getParameters().put('def_entitlement_id',entTyvek1.id);   
        cas.recordtypeid=BITYVEK_RTYPE;
        ctrlOverideNewCase c6 = new ctrlOverideNewCase (controller6);
        c6.redirectToPage();
        
        ApexPAges.StandardController controller7= new ApexPages.StandardController(cas);     
        ApexPages.currentPage().getParameters().put('def_entitlement_id',NULL);
        cas.recordtypeid=BISURFACE_RTYPE;
        ctrlOverideNewCase c7 = new ctrlOverideNewCase (controller7);
        c7.redirectToPage();
       
        ApexPAges.StandardController controller8= new ApexPages.StandardController(cas);     
        ApexPages.currentPage().getParameters().put('def_entitlement_id',entSurf.id);
        cas.recordtypeid=BISURFACE_RTYPE;
        ctrlOverideNewCase c8 = new ctrlOverideNewCase (controller8);
        c8.redirectToPage();
        
        ApexPAges.StandardController controller9 = new ApexPages.StandardController(cas);
        ApexPages.currentPage().getParameters().put('def_entitlement_id',entTyvek1.id);
        cas.recordtypeid=BISURFACE_RTYPE;
        ctrlOverideNewCase c9 = new ctrlOverideNewCase (controller9);
        c9.redirectToPage();
        
        ApexPAges.StandardController controller10 = new ApexPages.StandardController(cas);
        ApexPages.currentPage().getParameters().put('def_entitlement_id',entSurf1.id);
        cas.recordtypeid=BISURFACE_RTYPE;
        ctrlOverideNewCase c10 = new ctrlOverideNewCase (controller10);
        c10.redirectToPage();
        
        ApexPAges.StandardController controller11 = new ApexPages.StandardController(cas);
        ApexPages.currentPage().getParameters().put('def_entitlement_id',entSurf.id);
        cas.recordtypeid=OTHERCASE;
        ctrlOverideNewCase c11 = new ctrlOverideNewCase (controller11);
        c11.redirectToPage();
        
        ApexPAges.StandardController controller12 = new ApexPages.StandardController(cas);
        ApexPages.currentPage().getParameters().put('def_entitlement_id',entSurf1.id);
        cas.recordtypeid=OTHERCASE;
        ctrlOverideNewCase c12 = new ctrlOverideNewCase (controller12);
        c12.redirectToPage();
        
        ApexPAges.StandardController controller13 = new ApexPages.StandardController(cas);
        ApexPages.currentPage().getParameters().put('def_entitlement_id',entTyvek1.id);
        cas.recordtypeid=OTHERCASE;
        ctrlOverideNewCase c13 = new ctrlOverideNewCase (controller13);
        c13.redirectToPage();
        
        ApexPAges.StandardController controller14 = new ApexPages.StandardController(cas);
        ApexPages.currentPage().getParameters().put('def_entitlement_id',entother1.id);
        cas.recordtypeid=OTHERCASE;
        ctrlOverideNewCase c14 = new ctrlOverideNewCase (controller14);
        c14.redirectToPage();
        
        Test.stopTest();
        
       
       }
    }
 }