DuPont DevSB/src/objects/Entitlement.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Used to indicate the Stage of the Entitlement i.e. whether its in progress or has been completed</description>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Registration In-Progress</fullName>
                </value>
                <value>
                    <fullName>Registration Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>BI_NA_Env_Product_Labor</fullName>
        <active>true</active>
        <description>BI-NA Envelopes Entitlements/Registrations Product and Labor Record type</description>
        <label>BI-NA Env Product &amp; Labor</label>
    </recordTypes>
    <recordTypes>
        <fullName>BI_NA_Env_Product_Only</fullName>
        <active>true</active>
        <description>BI-NA Envelopes Entitlements/Registrations Product Only Record type</description>
        <label>BI-NA Env Product Only</label>
    </recordTypes>
    <recordTypes>
        <fullName>BI_NA_Env_Product_Only_Fluid_Applied</fullName>
        <active>true</active>
        <description>BI-NA Envelopes Entitlements/Registrations Product Only - Fluid Applied Record type</description>
        <label>BI-NA Env Product Only – Fluid Applied</label>
    </recordTypes>
    <recordTypes>
        <fullName>BI_NA_Surface_Entitlement</fullName>
        <active>true</active>
        <description>BI-NA Surfaces Entitlements/Registrations Record type</description>
        <label>BI-NA Surfaces Entitlement</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EPass_ID__c</fullName>
        <description>Positive identification of individuals accessing DuPont computer systems.</description>
        <label>E-Pass ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Grouping__c</fullName>
        <description>DuPont Business</description>
        <inlineHelpText>DuPont Business (abbrev)</inlineHelpText>
        <label>User Grouping</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>DC&amp;F</fullName>
                </value>
                <value>
                    <fullName>DPM</fullName>
                </value>
                <value>
                    <fullName>DPS</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Owning_Org__c</fullName>
        <description>Primary &quot;Owning Organisation&quot; this user belongs to</description>
        <label>User Owning Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-Env</fullName>
                </value>
                <value>
                    <fullName>BI-Surf</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>CORP-CS</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-ES</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PM</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PS</fullName>
                </value>
                <value>
                    <fullName>DPT-Aramids</fullName>
                </value>
                <value>
                    <fullName>DPT-Automotive</fullName>
                </value>
                <value>
                    <fullName>DPT-Car Protection</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP</fullName>
                </value>
                <value>
                    <fullName>DPT-NOW</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IAL</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>LEGL</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Corp Marketing</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Customer Care</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-IT</fullName>
                </value>
                <value>
                    <fullName>DPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Region__c</fullName>
        <label>User Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlOverideEntitlementEdit_UT.cls
@isTest
private class ctrlOverideEntitlementEdit_UT{
        static testMethod void testctrlOverideEntitlementEdit_UT() {
        Profile p1 = [select id from profile where Name='System Administrator' limit 1];
        UserRole r1= [Select id from UserRole where Name='PS CRM' limit 1];
        User user1 = new User(LastName='XYZ',UserRoleId=r1.Id,ProfileId=p1.Id,Alias='ain123',EmailEncodingKey='UTF-8',TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',LanguageLocaleKey='en_US',Email='sanjay_nandi@infosys.com',UserName='sanjay@infosys.com.t12', EPass_ID__c='NA0000',User_Owning_Org__c='AGCP-CPC',User_Country__c='India',User_Grouping__c='CPC',User_Region__c='Latin America');
        insert user1;
        System.runas(user1){
        
        Final string BITYVEKAcc_RTYPE= Rtype.getIdByDevName('Account','BI_Tyvek');
        Final string BISURFACEAcc_RTYPE = Rtype.getIdByDevName('Account','BI_Surfaces');
        Final string PRODUCTANDLABOUT_COB_RTYPE = Rtype.getIdByDevName('Entitlement','BI_NA_Env_Product_Labor');
        Final string PRODUCTONLY_COB_RTYPE = Rtype.getIdByDevName('Entitlement','BI_NA_Env_Product_Only');
        Final string PRODUCTFLUIDAPPLIED_COB_RTYPE = Rtype.getIdByDevName('Entitlement','BI_NA_Env_Product_Only_Fluid_Applied');
        Final string SurfaceEntitlement=Rtype.getIdByDevName('Entitlement','BI_NA_Surface_Entitlement');
        geoValidation.validateInTestMode=false;
        
        Account accTyvek= new Account(name='Rajiv',BI_Account_SubType__c='Fabricator',RecordtypeId=BITYVEKAcc_RTYPE);
        insert accTyvek;
        Account accSurf= new Account(name='Rajiv1',BI_Account_SubType__c='Fabricator',Recordtypeid=BISURFACEAcc_RTYPE);
        insert accSurf;
        Entitlement entTyvek1= new Entitlement(name='Rajiv',RecordtypeId=PRODUCTANDLABOUT_COB_RTYPE, stage__c='Registration In Progress',AccountId=accTyvek.Id);
        insert entTyvek1;
        Entitlement entSurf1= new Entitlement(name='Rajiv1',Recordtypeid=SurfaceEntitlement,AccountId=accSurf.Id);
        insert entSurf1;
        
        Test.startTest();
         
         ApexPages.StandardController controller2 = new ApexPages.StandardController(entTyvek1);
        ctrlOverideEntitlementEdit c3 = new ctrlOverideEntitlementEdit(controller2);
        c3.redirect();
         
        ApexPages.StandardController controller = new ApexPages.StandardController(entTyvek1);
        ApexPages.currentPage().getParameters().put('id',entTyvek1.id);
        ctrlOverideEntitlementEdit c1 = new ctrlOverideEntitlementEdit(controller);
        c1.redirect();
        
        ApexPages.StandardController controller1 = new ApexPages.StandardController(entSurf1);
        ApexPages.currentPage().getParameters().put('id',entSurf1.id);
        ctrlOverideEntitlementEdit c2 = new ctrlOverideEntitlementEdit(controller1);
        c2.redirect();
            
            
        
               
        Test.stopTest();
        
       
       }
    }
    }