DuPont DevSB/src/objects/Entitlement.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for this entitlement, likely the contact that activated this entitlement.</description>
        <inlineHelpText>Primary contact for this entitlement, likely the contact that activated this entitlement.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>BI_NA_Surface_Entitlement</fullName>
        <active>true</active>
        <description>BI-NA Surfaces Entitlements/Registrations Record type</description>
        <label>BI-NA Surfaces Entitlement</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EPass_ID__c</fullName>
        <description>Positive identification of individuals accessing DuPont computer systems.</description>
        <label>E-Pass ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Grouping__c</fullName>
        <description>DuPont Business</description>
        <inlineHelpText>DuPont Business (abbrev)</inlineHelpText>
        <label>User Grouping</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>DC&amp;F</fullName>
                </value>
                <value>
                    <fullName>DPM</fullName>
                </value>
                <value>
                    <fullName>DPS</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Owning_Org__c</fullName>
        <description>Primary &quot;Owning Organisation&quot; this user belongs to</description>
        <label>User Owning Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-Env</fullName>
                </value>
                <value>
                    <fullName>BI-Surf</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>CORP-CS</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-ES</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PM</fullName>
                </value>
                <value>
                    <fullName>DPT-AFS-PS</fullName>
                </value>
                <value>
                    <fullName>DPT-Aramids</fullName>
                </value>
                <value>
                    <fullName>DPT-Automotive</fullName>
                </value>
                <value>
                    <fullName>DPT-Car Protection</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP</fullName>
                </value>
                <value>
                    <fullName>DPT-NOW</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IAL</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>LEGL</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Corp Marketing</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-Customer Care</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-IT</fullName>
                </value>
                <value>
                    <fullName>DPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Region__c</fullName>
        <label>User Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlBINA_SurfaceVFPanel_UT.cls
/////////////////////////////////////////////////////////////////////////////////////////////////////////
//Copyright © 2014 DuPont. All rights reserved. 
//Name :ctrlBINA_SurfaceVFPanel_UT
//Author :Rajiv Kumar Bhatter<Rajiv_Bhatter@infosys.com>, Sanjay Nandi<Sanjay_Nandi@infosys.com>
//Description: This  UT class for controller  ctrlBINA_SurfaceVFPanel
//************************************<MG-20140827>***************************************************//
@isTest(SeeAllData=true)
private class ctrlBINA_SurfaceVFPanel_UT{
    static testMethod void testctrlBINA_SurfaceVFPanel_UT() {
/*PKH        
        final Id CASERECORDTYPEID=Rtype.getIdByDevName('Case','BI_NA_Surfaces_Case');
        final Id ENTITLEMENTRECORDTYPEID=Rtype.getIdByDevName('Entitlement','BI_NA_Surface_Entitlement');
        Profile p1 = [select id from profile where Name='System Administrator' limit 1];
        UserRole r1= [Select id from UserRole where Name='PS CRM' limit 1];
        User user1 = new User(LastName='XYZ',UserRoleId=r1.Id,ProfileId=p1.Id,Alias='ain123',EmailEncodingKey='UTF-8',TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',LanguageLocaleKey='en_US',Email='sanjay_nandi@infosys.com',UserName='sanjay@infosys.com.t12', EPass_ID__c='NA0000',User_Owning_Org__c='AGCP-CPC',User_Country__c='India',User_Grouping__c='CPC',User_Region__c='Latin America');
        insert user1;
        System.runas(user1){   
        geoValidation.validateInTestMode=true;
        
        Account acc= new Account(name='testacc',BillingCountry='CA', BillingState='British Columbia',ShippingCountry='United States', ShippingState='British Columbia');
        insert acc;
        Contact con=new contact(Firstname='Sanjay', LastName='Nandi',Email='sanjay31nandi@infosys.com',MailingStreet='Abc',MailingCity='Abc',MobilePhone='0000000000',Phone='12345',MailingState='XYZ',MailingPostalCode='12345',MailingCountry='United States', AccountId=acc.id);
        insert con;
        Entitlement ent= new Entitlement(name='TestEntit',primary_contact__c=con.id, Accountid=acc.id);
        insert ent;
        Case cas=new case(product_selected__c='Materail1;Material2',status='new', recordtypeid=CASERECORDTYPEID, ownerId=user1.Id, Entitlementid=ent.id);
        insert cas;
        case cas1 = [SELECT id,product_selected__c From case LIMIT 1];
        
        Test.startTest();
        
        ApexPages.currentPage().getParameters().put('id', cas.id);
        ApexPAges.StandardController sc = new ApexPages.StandardController(cas1);
        ctrlBINA_SurfaceVFPanel c = new ctrlBINA_SurfaceVFPanel (sc);
        ApexPages.currentPage().getParameters().put('id', ent.id);
        ApexPAges.StandardController sc1 = new ApexPages.StandardController(ent);
        ctrlBINA_SurfaceVFPanel c1 = new ctrlBINA_SurfaceVFPanel (sc1);
        
        Test.stopTest();
      }  
*/        
     }
     
    }