DuPont DevSB/src/objects/ERP_Relationship__c.object
<CustomObject>
    <description>Used to manage the types of relationships an ERP customer might have (Sold-To, Ship-To, End User, etc.)</description>
    <fields>
        <fullName>Deletion_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates Partner record is deleted or not at SAP,and will be deleted in SFDC through batch jobs.This deletion applies for a specified Customer only.</description>
        <label>Deletion Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>ERP Relationship</label>
    <nameField>
        <displayFormat>ERP-R{000000000}</displayFormat>
        <label>ERP Relationship  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/batchDeletionOfSalesRep.cls
/*
 * Name      :   batchDeletionOfSalesRep
 * Description  :   
 * Author      :   Infosys Limited <DW20150106>
 * Created Date :   06Jan2015
 *
 * Version   Modified Date     Modified By                Modification
 *
 * ---------------------------------------------------------------------------------------------------- 
 */

 global class batchDeletionOfSalesRep implements Database.Batchable<sObject>,Schedulable 
{
    global Database.QueryLocator start(Database.BatchableContext BC)
    { 
        return Database.getQueryLocator([SELect id FROM ERP_Relationship__c WHERE Deletion_Flag__c=True]);  
    }
    global void execute(Database.BatchableContext BC, List<sObject> returnedRequestsFromQuery)
    {
        if(returnedRequestsFromQuery.size()>0)
        {   
            delete returnedRequestsFromQuery;
        }   
    }
    global void finish(Database.BatchableContext BC)
    {
    } 
    
    
    global void execute(SchedulableContext SC) {
        batchDeletionOfSalesRep batch = new batchDeletionOfSalesRep();
        database.executebatch(batch);
    }
}