DuPont DevSB/src/objects/External_Initiative__c.object
<CustomObject>
    <description>Detailed information from an external data source provided in an automated feed (project, lead, or opportunity data).</description>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Source__c</fullName>
        <description>Identifies external data source.</description>
        <inlineHelpText>Identifies external data source.</inlineHelpText>
        <label>Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>McGraw Hill Construction</fullName>
                </value>
                <value>
                    <fullName>Dodge</fullName>
                    <default>true</default>
                    <label>Dodge</label>
                </value>
                <value>
                    <fullName>CIC - Construction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique identifier from external system.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_Search_Name__c</fullName>
        <description>External search name used by external system.</description>
        <label>External Search Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Version__c</fullName>
        <description>Identifies version of external initiative, can be used to ensure the data is synchronized.</description>
        <label>External Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owning_Organization__c</fullName>
        <label>Owning Organization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-Env</fullName>
                </value>
                <value>
                    <fullName>BI-Landscape Systems</fullName>
                </value>
                <value>
                    <fullName>BI-Surf</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
                <value>
                    <fullName>DPT-A&amp;HF</fullName>
                </value>
                <value>
                    <fullName>DPT-Agriculture</fullName>
                </value>
                <value>
                    <fullName>DPT-Air and Filtration</fullName>
                </value>
                <value>
                    <fullName>DPT-Aramids</fullName>
                </value>
                <value>
                    <fullName>DPT-ASPS</fullName>
                </value>
                <value>
                    <fullName>DPT-Automotive</fullName>
                </value>
                <value>
                    <fullName>DPT-Chemical Industrial</fullName>
                </value>
                <value>
                    <fullName>DPT-Cleanroom/Pharma</fullName>
                </value>
                <value>
                    <fullName>DPT-Covers</fullName>
                </value>
                <value>
                    <fullName>DPT-Critical Clean</fullName>
                </value>
                <value>
                    <fullName>DPT-Envelopes</fullName>
                </value>
                <value>
                    <fullName>DPT-ES</fullName>
                </value>
                <value>
                    <fullName>DPT-Graphics</fullName>
                </value>
                <value>
                    <fullName>DPT-Ind Pkg &amp; Protection</fullName>
                </value>
                <value>
                    <fullName>DPT-IPP</fullName>
                </value>
                <value>
                    <fullName>DPT-Mechanical Industrial</fullName>
                </value>
                <value>
                    <fullName>DPT-Medical Fabrics</fullName>
                </value>
                <value>
                    <fullName>DPT-Medical Packaging</fullName>
                </value>
                <value>
                    <fullName>DPT-Medical Specialties</fullName>
                </value>
                <value>
                    <fullName>DPT-NOW</fullName>
                </value>
                <value>
                    <fullName>DPT-Optical</fullName>
                </value>
                <value>
                    <fullName>DPT-PM</fullName>
                </value>
                <value>
                    <fullName>DPT-Public Sector-ER</fullName>
                </value>
                <value>
                    <fullName>DPT-Public Sector-LE</fullName>
                </value>
                <value>
                    <fullName>DPT-Public Sector-MIL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment_L1__c</fullName>
        <description>Highest level External initiative segment.</description>
        <label>Segment L1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment_L2__c</fullName>
        <description>External initiative subsegment.</description>
        <label>Segment L2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment_L3__c</fullName>
        <description>Captures further external initiative detail.</description>
        <label>Segment L3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment_L4__c</fullName>
        <description>Captures further external initiative detail.</description>
        <label>Segment L4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Specification_L1__c</fullName>
        <description>External initiative specification primary specification.</description>
        <label>Specification L1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Specification_L2__c</fullName>
        <description>External initiative specification secondary specification.</description>
        <label>Specification L2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Announced</fullName>
                </value>
                <value>
                    <fullName>Study</fullName>
                </value>
                <value>
                    <fullName>Pre-Planning</fullName>
                </value>
                <value>
                    <fullName>Request for Proposals</fullName>
                </value>
                <value>
                    <fullName>Request for Qualifications</fullName>
                </value>
                <value>
                    <fullName>Pre-Design</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Planning Schematics</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Design Development</fullName>
                </value>
                <value>
                    <fullName>Final Planning</fullName>
                </value>
                <value>
                    <fullName>Construction Documents</fullName>
                </value>
                <value>
                    <fullName>Pre-tender</fullName>
                </value>
                <value>
                    <fullName>Pre-qualification</fullName>
                </value>
                <value>
                    <fullName>Tender</fullName>
                </value>
                <value>
                    <fullName>Bid</fullName>
                </value>
                <value>
                    <fullName>Bidding</fullName>
                </value>
                <value>
                    <fullName>GC Bidding</fullName>
                </value>
                <value>
                    <fullName>GC Bidding-Invitation</fullName>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Sub-bidding</fullName>
                </value>
                <value>
                    <fullName>Sub bidding</fullName>
                </value>
                <value>
                    <fullName>Bid result</fullName>
                </value>
                <value>
                    <fullName>Bid Results</fullName>
                </value>
                <value>
                    <fullName>Epc award</fullName>
                </value>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Execution</fullName>
                </value>
                <value>
                    <fullName>Sub-Award</fullName>
                </value>
                <value>
                    <fullName>Subcontract Award</fullName>
                </value>
                <value>
                    <fullName>Construct</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State/Province</description>
        <label>State/Province</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Total value of external initiative.</description>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>External Initiative</label>
    <nameField>
        <label>External Initiative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Initiatives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ExternalInitiativeHandler_UT.cls
/*******************************************************************************
Copyright © 2016 DuPont. All rights reserved. 
Author: Abhinav Bhatnagar
Email: abhinav.bhatnagar@dupont.com
Description:  Test Class for ExternalInitiativeHandler Handler class
15-March-2016 : Created to increase code coverage of ExternalInitiativeHandler Class

<AS20160919>
Modified By: Arjun Sharma
Modification Date: 19-Sept-2016
Modification: Record type name 'BI-NA External Initiative' changed to 'BI External Initiative' and
Data Source 'Dodge' is added to create External Initiative for CPSF

<AS20161015>
Modification: Record type name is reverted as per business requirement.
********************************************************************************/
@isTest(seeAllData=false)
public class ExternalInitiativeHandler_UT {
    static testMethod void testEIH() {
        try{
            Test.startTest();
            String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'External_Initiative__c' and Name = 'BI-NA External Initiative'].Id;//<AS20161015>
            List<External_Initiative__c> cps = new List<External_Initiative__c>();
            cps.add(new External_Initiative__c(name='S2S Test EI QA Tyvek - 01',State__c='DE', County__c='New Castle',External_ID__c='01TEST15032016', External_Version__c=1, External_Search_Name__c='Tyvek,Surfaces',Stage__c='Bid',Owning_Organization__c='BI',RecordTypeId=strRecordTypeId,Segment_L1__c='Test',Segment_L2__c='Warehouse Other1',Segment_L3__c='Building Additions',Segment_L4__c='Test',Specification_L1__c='Test',Specification_L2__c='Test',Value__c=20000000,Data_Source__c='Dodge'));//<AS20160919>
           
            insert cps;
            External_Initiative__c ei = [Select name,State__c,County__c,External_ID__c,External_Version__c,External_Search_Name__c,Stage__c,Owning_Organization__c,RecordTypeId,Segment_L1__c,Segment_L2__c,Segment_L3__c,Segment_L4__c,Specification_L1__c,Specification_L2__c,Value__c from External_Initiative__c where External_ID__c='01TEST15032016'];
            ei.Specification_L2__c='Test Update';
            upsert ei;
            Test.stopTest();
            
        }catch(Exception e){
            system.debug('--->>>Exception Occured '+e.getStackTraceString());
        }
    }
}