DuPont DevSB/src/objects/External_Initiative__c.object
<CustomObject>
    <description>Detailed information from an external data source provided in an automated feed (project, lead, or opportunity data).</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Source__c</fullName>
        <description>Identifies external data source.</description>
        <inlineHelpText>Identifies external data source.</inlineHelpText>
        <label>Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>McGraw Hill Construction</fullName>
                </value>
                <value>
                    <fullName>Dodge</fullName>
                    <default>true</default>
                    <label>Dodge</label>
                </value>
                <value>
                    <fullName>CIC - Construction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Additional information about this external initiative</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EI_Region__c</fullName>
        <label>EI_Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique identifier from external system.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_Search_Name__c</fullName>
        <description>External search name used by external system.</description>
        <label>External Search Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_External_Initiative_Name__c</fullName>
        <description>For CIC Project External Initiative name is more than 80 char to store full name . We have created a field</description>
        <label>Full External Initiative Name</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_Level__c</fullName>
        <label>Project Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Sub</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>External Initiative</label>
    <nameField>
        <label>External Initiative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Initiatives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_Initiative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>External Initiative (or project managed by a partner or other 3rd party) related to this opportunity</description>
        <label>External Initiative</label>
        <referenceTo>External_Initiative__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/batch_CIC_Oppty.cls
/*************************************************************************************************
Copyright © 2013 DuPont. All rights reserved. 
Authors:        Vijay Laxmi
Email:          vijay.laxmi1@tcs.com
Date:           10/10/2016
Description:    Class to create opportunity if not present on ExternalInitiative for Project Level "Parent" only

***************************************************************************************************/

global class batch_CIC_Oppty  implements Database.Batchable<sObject> 
{
    public static final Integer batchJobSize = Integer.valueOf(Label.CIC_Batch_Size);
    public static Integer batchFilter = Integer.valueOf(Label.CIC_LastModified_Date_Filter);
    public static datetime Lastmodifiedfilter = system.today().adddays(batchFilter);
    public static String EIdatasoce = system.Label.CIC_External_Initiative_Data_Source;
    public static String EI_ProjectLevel ='Parent';
    
    public Database.QueryLocator start(Database.BatchableContext BC)
    {
        // Fetching the External Initiative for CIC Project
        String query  ='select id,External_ID__c,Country__c,EI_Region__c,Full_External_Initiative_Name__c,Description__c,External_Search_Name__c,Name,City__c from External_Initiative__c where ((Data_Source__c=:EIdatasoce) and (lastmodifieddate>=:lastmodifiedFilter) and Project_Level__c=:EI_ProjectLevel)';
        return Database.getQueryLocator(query);          
    }
    public void execute(Database.BatchableContext info, List<External_Initiative__c> ei)
    {
        set<id> setEIID = new  set<id>();
        for(External_Initiative__c EId : ei)
        {
            setEIID.add(EId.id);
        }
        // Fetching the Opportunity for which External Initiative ids is already present
        list<opportunity> lstopp =  [
                                    select id,External_Initiative__c,owner.id,owner.name,owner.DefaultCurrencyIsoCode
                                    from Opportunity 
                                    where External_Initiative__c in:setEIID
                                    ];
        map<id,opportunity>  mapEIIDOpp = new map<id,opportunity>();
        for(opportunity opp : lstopp)
        {
            mapEIIDOpp.put(opp.External_Initiative__c,Opp); 
        }
        List<External_Initiative__c> lstExternal = new   List<External_Initiative__c>();
        // External Initiative is not containing oppty we are adding in List "lstExternal" and calling the "Addopportunities_CIC" method from BI_MHC class to create new  Opportunity
        for(External_Initiative__c Ext :ei)
        {
            if(!mapEIIDOpp.containskey(Ext.id))         
                lstExternal.add(Ext);
        }
        BI_MHC.Addopportunities_CIC(lstExternal);
    }
    public void finish(Database.BatchableContext info) {}
}