DuPont DevSB/src/objects/External_Initiative__c.object
<CustomObject>
    <description>Detailed information from an external data source provided in an automated feed (project, lead, or opportunity data).</description>
    <fields>
        <fullName>Data_Source__c</fullName>
        <description>Identifies external data source.</description>
        <inlineHelpText>Identifies external data source.</inlineHelpText>
        <label>Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>McGraw Hill Construction</fullName>
                </value>
                <value>
                    <fullName>Dodge</fullName>
                    <default>true</default>
                    <label>Dodge</label>
                </value>
                <value>
                    <fullName>CIC - Construction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Version__c</fullName>
        <description>Identifies version of external initiative, can be used to ensure the data is synchronized.</description>
        <label>External Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Announced</fullName>
                </value>
                <value>
                    <fullName>Study</fullName>
                </value>
                <value>
                    <fullName>Pre-Planning</fullName>
                </value>
                <value>
                    <fullName>Request for Proposals</fullName>
                </value>
                <value>
                    <fullName>Request for Qualifications</fullName>
                </value>
                <value>
                    <fullName>Pre-Design</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Planning Schematics</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Design Development</fullName>
                </value>
                <value>
                    <fullName>Final Planning</fullName>
                </value>
                <value>
                    <fullName>Construction Documents</fullName>
                </value>
                <value>
                    <fullName>Pre-tender</fullName>
                </value>
                <value>
                    <fullName>Pre-qualification</fullName>
                </value>
                <value>
                    <fullName>Tender</fullName>
                </value>
                <value>
                    <fullName>Bid</fullName>
                </value>
                <value>
                    <fullName>Bidding</fullName>
                </value>
                <value>
                    <fullName>GC Bidding</fullName>
                </value>
                <value>
                    <fullName>GC Bidding-Invitation</fullName>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Sub-bidding</fullName>
                </value>
                <value>
                    <fullName>Sub bidding</fullName>
                </value>
                <value>
                    <fullName>Bid result</fullName>
                </value>
                <value>
                    <fullName>Bid Results</fullName>
                </value>
                <value>
                    <fullName>Epc award</fullName>
                </value>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Execution</fullName>
                </value>
                <value>
                    <fullName>Sub-Award</fullName>
                </value>
                <value>
                    <fullName>Subcontract Award</fullName>
                </value>
                <value>
                    <fullName>Construct</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Delayed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>External Initiative</label>
    <nameField>
        <label>External Initiative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Initiatives</pluralLabel>
    <recordTypes>
        <fullName>BI_NA_External_Initiative</fullName>
        <active>true</active>
        <label>BI-NA External Initiative</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_Initiative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>External Initiative (or project managed by a partner or other 3rd party) related to this opportunity</description>
        <label>External Initiative</label>
        <referenceTo>External_Initiative__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ExternalInitiativeHandler.cls
/*************************************************************************************************
Copyright © 2013 DuPont. All rights reserved. 
Authors:        Divya Ramakrishnaiah, Thomas Snyder
Email:          divya.ramakrishnaiah@usa.dupont.com, thomas.snyder@usa.dupont.com/ tom@3ddd.com
Description:    Trigger handler for External Initiative
Event:          After Insert : 
                Create new Opportunities based on newly inserted External Initiative,
                of record type - 'BI_NA_External_Initiative'. Assignment is based on Project county.
                Before Update : 
                Create Opportunities related to External Initiative,
                of record type - 'BI_NA_External_Initiative', if not already present.  
Notes:          Best practice for bulk inserts of ExternalInitiative would be to sort the 
                the data to import by the state prior to upload. This is because all counties 
                are Mapped by each unique state per batch (typically 200 rows)
<KK20130828>
Modified By: Kusuma Kumar
Modification Date: 28-Aug-2013
Modification: Added a new method updateOpportunityOwner2 to update the Opportunity Owner2 field with the Contact based 
			  on the External Initiative parameters and Opportunity Rating,Net Amount and Application Type
<AB20160307>
Modified By: Abhinav Bhatnagar
Modification Date: 07-Mar-2016
Modification: Updated each method to avoid creating/updating any associated opportunities with External Intiative which have Stage set 
			   as 'Abandoned' OR 'Deferred'. This is done to accomodate the changes made at the side of Ingenium, third party partner which
				send payload to DuPont SQL Server. Earlier Ingenium used to send EI whose stage are not 'Abandoned' OR 'Deferred' OR 'Construct'
				However, for stage 'Construct' Every thing is to remain same.
<AB20160613>
Modified By: Abhinav Bhatnagar
Modification Date: 13-Jun-2016
Modification: Commented updateOpportunityOwner2() method in bulkAfter method to avoid updates on manully done owner2 changes.

<AS20160919>
Modified By: Arjun Sharma
Modification Date: 19-Sept-2016
Modification: Updated each method with new picklist value of Stage for Dodge data


***************************************************************************************************/
public without sharing class ExternalInitiativeHandler extends TriggerHandlerBase{
    public override void bulkAfter(){
        if(Trigger.IsInsert){
            addOpportunityOnInsert();
            /*<KK20130828>*/
            updateOpportunityOwner2();
        }
        /*<KK20130828>*/
       /*AB20160613 if(Trigger.IsUpdate){
        	updateOpportunityOwner2();
        } AB20160613*/
    }
    public override void bulkbefore(){
        if(Trigger.IsUpdate){
            updateExtInitWithOpps();
        }
    }
        
    /***************************************************
    For Record type : 'BI_NA_External_Initiative'
    Add Opportunities to External Initiative, based on 'External Search Name' field value
    ***************************************************/
    public void addOpportunityOnInsert(){
        List<External_Initiative__c> MHCExtInitList = new List<External_Initiative__c>();
        for (Sobject so  : this.getRecordsByRT('BI_NA_External_Initiative').values()){
            External_Initiative__c  extInitRec = (External_Initiative__c)so;
            //<AB20160307>
            if ( (extInitRec.Data_Source__c == Label.External_Initiative_Data_Source )  && ( extInitRec.stage__c!='Abandoned' && (extInitRec.stage__c!='Deferred' && extInitRec.stage__c!='Delayed'))) //<AS20160919>
            	MHCExtInitList.add(extInitRec);
        }
        BI_MHC.AddOpportunities(MHCExtInitList);
    }
    /***************************************************
    For Record type : 'BI_NA_External_Initiative'
    Before Update - Dont allow import of an older version of External Initiative
    Add Opportunities if not added earlier
    ****************************************************/
    public void updateExtInitWithOpps(){
        List<External_Initiative__c> MHCExtInitList = new List<External_Initiative__c>();
        External_Initiative__c  extInitRec;
        External_Initiative__c oldExtInitRec;
        for (Sobject so : this.getRecordsByRT('BI_NA_External_Initiative').values()){
            extInitRec = (External_Initiative__c)so;
            oldExtInitRec = (External_Initiative__c)Trigger.oldMap.get(extInitRec.Id);
            if(extInitRec.External_Version__c < oldExtInitRec.External_Version__c)
                extInitRec.External_Version__c.addError('Cannot update Commercial Project to a prior version.');
            //<AB20160307>
            if ( (extInitRec.Data_Source__c == Label.External_Initiative_Data_Source )  && ( extInitRec.stage__c!='Abandoned' && (extInitRec.stage__c!='Deferred' && extInitRec.stage__c!='Delayed'))) //<AS20160919>
            MHCExtInitList.add(extInitRec);
        }
        BI_MHC.AddOpportunities(MHCExtInitList);
    }
    
    /*<KK20130828>*/
    /***********************************************************
    For Record type : 'BI_NA_External_Initiative'
    After Update and After Insert - Updates the Opportunity Owner2 
    of the Opportunity records related to External Initiative.
    ************************************************************/
    public void updateOpportunityOwner2(){
        List<External_Initiative__c> MHCExtInitList = new List<External_Initiative__c>();
        for (Sobject so  : this.getRecordsByRT('BI_NA_External_Initiative').values()){
            External_Initiative__c  extInitRec = (External_Initiative__c)so;
            //<AB20160307>
            if ( (extInitRec.Data_Source__c == Label.External_Initiative_Data_Source || extInitRec.Data_Source__c == Label.CIC_External_Initiative_Data_Source)  && ( extInitRec.stage__c!='Abandoned' && (extInitRec.stage__c!='Deferred' && extInitRec.stage__c!='Delayed'))) //<AS20160919>
            MHCExtInitList.add(extInitRec);
        }
        BI_MHC.UpdateOpportunities(MHCExtInitList);
    }
}