DuPont DevSB/src/objects/FieldDefaults__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>These Custom Settings are used to pre-populate the form field values when creating new records using the standard edit pages.</description>
    <fields>
        <fullName>DF00N30000002jgSW__c</fullName>
        <description>Farm_Detail__c.Country__c</description>
        <label>Farm_Detail__c.Country__c</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FieldDefaults</label>
</CustomObject>

DuPont DevSB/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlOverrideNew_UT.cls
@isTest
public class ctrlOverrideNew_UT {
    public static testMethod void test_PageInit() { 
        test.startTest();
            FieldDefaults__c settings = FieldDefaults__c.getOrgDefaults();
            
            settings.DF00N4100000SIpR5__c = '@User.User_Country__c';
            settings.DF00N30000002jgSW__c = '@User.User_Country__c';
            settings.DF00N4100000SIq95__c = '@User.User_Country__c';
            insert settings;
            
            ctrlOverrideNew ctrl = new ctrlOverrideNew(new ApexPages.StandardController(new Lead()));
            system.debug(ctrl.init());
            ctrlOverrideNew ctrl1 = new ctrlOverrideNew();
            
            
            DefaultFields objDf = new DefaultFields ();
            
            DefaultFields.FieldDefaults dfd = new DefaultFields.FieldDefaults(new FieldDefaults__c());
            DefaultFields.FieldDefaults dfd2 = new DefaultFields.FieldDefaults('FieldDefaults__c');
            dfd2.defaultFor('test');
            String urlparam = dfd2.UrlParams ;
        test.stopTest();
    }
    
}