DuPont DevSB/src/objects/Functional_Design_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Flammability_Tests__c</fullName>
        <label>Flammability Tests</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ASTM D6413</fullName>
                </value>
                <value>
                    <fullName>ASTM D6413 13b</fullName>
                </value>
                <value>
                    <fullName>NFPA 2112 -2002</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Names_of_Labs__c</fullName>
        <label>Names of Labs</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HP White</fullName>
                </value>
                <value>
                    <fullName>TNO</fullName>
                </value>
                <value>
                    <fullName>Banc Saint-Etienne Test Facility</fullName>
                </value>
                <value>
                    <fullName>Chesapeake</fullName>
                </value>
                <value>
                    <fullName>CFSL</fullName>
                </value>
                <value>
                    <fullName>TBRL</fullName>
                </value>
                <value>
                    <fullName>Kolas, Samyang</fullName>
                </value>
                <value>
                    <fullName>Beschussamt Mellrichstadt (Germany)</fullName>
                </value>
                <value>
                    <fullName>Banco Nazionale di Prova in Gardone Val Trompia (Italy)</fullName>
                </value>
                <value>
                    <fullName>Ballistic and Mechanical Testing Pty Ltd (BMT-NATA Accr. 13310) Melbourne Australia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Panel_Flexibility_Reference__c</fullName>
        <label>Panel Flexibility Reference</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abrasion test –ASTM D4966 -12</fullName>
                </value>
                <value>
                    <fullName>Flexibility Test – CREL</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Third_party_testing_standards__c</fullName>
        <label>Third-party testing standards</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HP White</fullName>
                </value>
                <value>
                    <fullName>TNO</fullName>
                </value>
                <value>
                    <fullName>Banc Saint-Etienne Test Facility</fullName>
                </value>
                <value>
                    <fullName>Chesapeake</fullName>
                </value>
                <value>
                    <fullName>CFSL</fullName>
                </value>
                <value>
                    <fullName>TBRL</fullName>
                </value>
                <value>
                    <fullName>Kolas, Samyang</fullName>
                </value>
                <value>
                    <fullName>Beschussamt Mellrichstadt (Germany)</fullName>
                </value>
                <value>
                    <fullName>Banco Nazionale di Prova in Gardone Val Trompia (Italy)</fullName>
                </value>
                <value>
                    <fullName>Ballistic and Mechanical Testing Pty Ltd (BMT-NATA Accr. 13310) Melbourne Australia</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BA Functional Design Requirement</label>
    <nameField>
        <label>Body Armor Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Functional Design Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Kevlar_Response_Messages__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Kevlar_Response_Messages</label>
</CustomObject>

DuPont DevSB/src/classes/CtrlOthersDropdownsService_UT.cls
/*********************************************************************************************
(C)2016
Author: krishnaveni duggaraju
Email: krishnaveni.duggaraju@tcs.com
Description:  This class CtrlOthersDropdownsService_UT.
 ********************************************************************************************/

@isTest
private class CtrlOthersDropdownsService_UT {
    public static Kevlar_Response_Messages__c m1,m2,m3,m4;
    public static List<Kevlar_Response_Messages__c> respMsgList = new List<Kevlar_Response_Messages__c>();
    static{
            m1 = testData_Kevlar_UT.getMessage1(); 
            respMsgList.add(m1);       
            m4 = testData_Kevlar_UT.getMessage21();
            respMsgList.add(m4);  
            m2 = testData_Kevlar_UT.getMessage2(); 
            respMsgList.add(m2);
            m3 = testData_Kevlar_UT.getMessage3();     
            respMsgList.add(m3);     
            insert respMsgList;    
        } 
static testMethod void testDoPost() {
    String JsonMsg= '{}'; 
    Test.startTest();  
    RestRequest req = new RestRequest(); 
    RestResponse res = new RestResponse();
    req.requestURI = '/services/apexrest/OthersDropdowns';  
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueof(JsonMsg);
    RestContext.request = req;
    RestContext.response= res; 
    CtrlOthersDropdownsService testuserId=new CtrlOthersDropdownsService();
    CtrlOthersDropdownsService.doPost();  
    Test.stopTest();    
}   
static testMethod void testDoPost1() { 
    Functional_Design_Requirement__c f = new Functional_Design_Requirement__c();
    f.Flammability_Tests__c = ''; 
    f.Panel_Flexibility_Reference__c = '';   
    f.Third_party_testing_standards__c = ''; 
   // f.Names_of_Labs__c = '';           
    Test.startTest();
    CtrlOthersDropdownsService testuserId=new CtrlOthersDropdownsService();
    CtrlOthersDropdownsService.doPost();  
    Test.stopTest();
}
}