DuPont DevSB/src/objects/Kevlar_Response_Messages__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Kevlar_Response_Messages</label>
</CustomObject>

DuPont DevSB/src/objects/Threat_Master__c.object
<CustomObject>
    <fields>
        <fullName>Angle_NBT__c</fullName>
        <label>Angle_NBT</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Straight</fullName>
                </value>
                <value>
                    <fullName>Left</fullName>
                </value>
                <value>
                    <fullName>Right</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Angled_Shot__c</fullName>
        <label>Angled Shot</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>-60</fullName>
                </value>
                <value>
                    <fullName>-45</fullName>
                </value>
                <value>
                    <fullName>-30</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Energy_Level_Joule_NBT__c</fullName>
        <label>Energy Level Joule NBT</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>33</fullName>
                </value>
                <value>
                    <fullName>36</fullName>
                </value>
                <value>
                    <fullName>43</fullName>
                </value>
                <value>
                    <fullName>50</fullName>
                </value>
                <value>
                    <fullName>65</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Energy_Level_NBT__c</fullName>
        <label>Energy Level NBT</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>E1</fullName>
                </value>
                <value>
                    <fullName>E2</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_Of_Stabs__c</fullName>
        <label>No. Of Stabs</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_shots__c</fullName>
        <label>Number of shots</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Penetration_Allowed__c</fullName>
        <label>Penetration Allowed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shooting_Mechnism__c</fullName>
        <label>Shooting Mechnism</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Barrel</fullName>
                </value>
                <value>
                    <fullName>Weapon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shot_Locations__c</fullName>
        <label>Shot  Locations</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NIJ 0101.04</fullName>
                </value>
                <value>
                    <fullName>NIJ 0101.06</fullName>
                </value>
                <value>
                    <fullName>NIJ 0115.00</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stab_Location__c</fullName>
        <label>Stab Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NIJ 0101.04</fullName>
                </value>
                <value>
                    <fullName>NIJ 0101.06</fullName>
                </value>
                <value>
                    <fullName>NIJ 0115.00</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Standard__c</fullName>
        <label>Test Standard</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NIJ 0101.04</fullName>
                </value>
                <value>
                    <fullName>NIJ 0101.06</fullName>
                </value>
                <value>
                    <fullName>TR 03/2008: Rev 10/2008</fullName>
                </value>
                <value>
                    <fullName>German Schutzklasse Oct 2008</fullName>
                </value>
                <value>
                    <fullName>CEN prEN ISO 148763/74</fullName>
                </value>
                <value>
                    <fullName>HP White Protoco</fullName>
                </value>
                <value>
                    <fullName>HOSDB 2007</fullName>
                </value>
                <value>
                    <fullName>Russia GOST R 50744-95</fullName>
                </value>
                <value>
                    <fullName>China GA 68</fullName>
                </value>
                <value>
                    <fullName>China GA 141</fullName>
                </value>
                <value>
                    <fullName>China GA 293</fullName>
                </value>
                <value>
                    <fullName>US MIL Standard</fullName>
                </value>
                <value>
                    <fullName>NIJ 0115.00</fullName>
                </value>
                <value>
                    <fullName>STANG 2911</fullName>
                </value>
                <value>
                    <fullName>STANAG 4296</fullName>
                </value>
                <value>
                    <fullName>STANAG 2920</fullName>
                </value>
                <value>
                    <fullName>US MIL 662E</fullName>
                </value>
                <value>
                    <fullName>Impact Test – DIN 4840</fullName>
                </value>
                <value>
                    <fullName>Impact Test – EN 397</fullName>
                </value>
                <value>
                    <fullName>VAPM BSW &amp; VAPM APR 2006: Stand 14-05-2009</fullName>
                </value>
                <value>
                    <fullName>VAPM KDIW 04 &amp; APR 06: Stand 14-05-2009</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>V50__c</fullName>
        <label>V50</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Velocity_V50__c</fullName>
        <label>Velocity_V50</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1002</fullName>
                </value>
                <value>
                    <fullName>1023</fullName>
                </value>
                <value>
                    <fullName>1081</fullName>
                </value>
                <value>
                    <fullName>1095</fullName>
                </value>
                <value>
                    <fullName>1384</fullName>
                </value>
                <value>
                    <fullName>325</fullName>
                </value>
                <value>
                    <fullName>347</fullName>
                </value>
                <value>
                    <fullName>350</fullName>
                </value>
                <value>
                    <fullName>354</fullName>
                </value>
                <value>
                    <fullName>375</fullName>
                </value>
                <value>
                    <fullName>387</fullName>
                </value>
                <value>
                    <fullName>396</fullName>
                </value>
                <value>
                    <fullName>402</fullName>
                </value>
                <value>
                    <fullName>404</fullName>
                </value>
                <value>
                    <fullName>410</fullName>
                </value>
                <value>
                    <fullName>429</fullName>
                </value>
                <value>
                    <fullName>438</fullName>
                </value>
                <value>
                    <fullName>440</fullName>
                </value>
                <value>
                    <fullName>446</fullName>
                </value>
                <value>
                    <fullName>451</fullName>
                </value>
                <value>
                    <fullName>457</fullName>
                </value>
                <value>
                    <fullName>473</fullName>
                </value>
                <value>
                    <fullName>480</fullName>
                </value>
                <value>
                    <fullName>484</fullName>
                </value>
                <value>
                    <fullName>490</fullName>
                </value>
                <value>
                    <fullName>493</fullName>
                </value>
                <value>
                    <fullName>495</fullName>
                </value>
                <value>
                    <fullName>506</fullName>
                </value>
                <value>
                    <fullName>528</fullName>
                </value>
                <value>
                    <fullName>567</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BA Threat Master</label>
    <nameField>
        <label>Threat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Threats Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/CtrlThreatDropdownService_UT.cls
/*********************************************************************************************
(C)2016
Author: krishnaveni duggaraju
Email: krishnaveni.duggaraju@tcs.com
Description:  This class CtrlThreatDropdownService_UT.
 ********************************************************************************************/

@isTest
private class CtrlThreatDropdownService_UT {
    public static Kevlar_Response_Messages__c m1,m2,m3,m4;
    public static List<Kevlar_Response_Messages__c> respMsgList = new List<Kevlar_Response_Messages__c>(); 
    static{
            m1 = testData_Kevlar_UT.getMessage1(); 
            respMsgList.add(m1);       
            m4 = testData_Kevlar_UT.getMessage30();
            respMsgList.add(m4);  
            m2 = testData_Kevlar_UT.getMessage2(); 
            respMsgList.add(m2);
            m3 = testData_Kevlar_UT.getMessage3();     
            respMsgList.add(m3);     
            insert respMsgList;    
        }
 static testMethod void testDoPost() { 
         String JsonMsg= '{}';
 
        Test.startTest();  
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/ThreatDefaultDropdowns';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JsonMsg);
        RestContext.request = req;
        RestContext.response= res;   
        CtrlThreatDropdownService testuserId=new CtrlThreatDropdownService();
        CtrlThreatDropdownService.doPost();  
        Test.stopTest();    
    }   
    static testMethod void testDoPost1() {
        Threat_Master__c f = new Threat_Master__c();
        f.Test_Standard__c = '';
        f.V50__c= null; 
        f.Velocity_V50__c= '';   
        f.Angle_NBT__c= ''; 
        f.Stab_Location__c = '';  
        f.No_Of_Stabs__c= ''; 
        f.Penetration_Allowed__c= '';   
        f.Energy_Level_Joule_NBT__c= ''; 
        f.Energy_Level_NBT__c= '';
        f.Angled_Shot__c= ''; 
        f.Number_of_shots__c= '';
        f.Shooting_Mechnism__c= ''; 
        f.Shot_Locations__c= '';
                 
        Test.startTest();
        CtrlThreatDropdownService testuserId=new CtrlThreatDropdownService();
        CtrlThreatDropdownService.doPost();  
        Test.stopTest();
    }
}