DuPont DevSB/src/objects/Kevlar_Response_Messages__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Message__c</fullName>
        <label>Response Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Kevlar_Response_Messages</label>
</CustomObject>

DuPont DevSB/src/classes/TestData_Kevlar_UT.cls
/*******************************************************************************
(C)2015
Author: krishnaveni duggaraju
Email: krishnaveni.duggaraju@tcs.com
Description:  This class creates the data for the test classes

 ********************************************************************************/
@isTest
public class TestData_Kevlar_UT{
    public static Kevlar_Response_Messages__c getMessage1(){
        Kevlar_Response_Messages__c m1=new Kevlar_Response_Messages__c();
        m1.name='200';
        m1.Message__c='Data sent successfully';
        return m1;
    }
    public static Kevlar_Response_Messages__c getMessage2(){
        Kevlar_Response_Messages__c m2=new Kevlar_Response_Messages__c();
        m2.name='201';
        m2.Message__c='No Application found';
        return m2;
    }
    public static Kevlar_Response_Messages__c getMessage3(){
        Kevlar_Response_Messages__c m3=new Kevlar_Response_Messages__c();
        m3.name='203';
        m3.Message__c='Exception';
        return m3;
    }
    public static Kevlar_Response_Messages__c getMessage4(){
        Kevlar_Response_Messages__c m4=new Kevlar_Response_Messages__c();
        m4.name='501';
        m4.Response_Message__c='Populate Status Values';
        return m4;
    }
    public static Kevlar_Response_Messages__c getMessage5(){
        Kevlar_Response_Messages__c m5=new Kevlar_Response_Messages__c();
        m5.name='502';
        m5.Response_Message__c='Kevlar Users Populated';
        return m5;
    }
    public static Kevlar_Response_Messages__c getMessage6(){
        Kevlar_Response_Messages__c m6=new Kevlar_Response_Messages__c();
        m6.name='503';
        m6.Response_Message__c='Populate color of BA dropdown values';
        return m6;
    }
    public static Kevlar_Response_Messages__c getMessage7(){
        Kevlar_Response_Messages__c m7=new Kevlar_Response_Messages__c();
        m7.name='506';
        m7.Response_Message__c='Populate currency values';
        return m7;
    }
    public static Kevlar_Response_Messages__c getMessage8(){
        Kevlar_Response_Messages__c m8=new Kevlar_Response_Messages__c();
        m8.name='505';
        m8.Response_Message__c='Populate region and countries dropdown values';
        return m8;
    }
    public static Kevlar_Response_Messages__c getMessage9(){
        Kevlar_Response_Messages__c m9=new Kevlar_Response_Messages__c();
        m9.name='504';
        m9.Response_Message__c='Closure Reason Dropdown Populated';
        return m9;
    }
    public static Kevlar_Response_Messages__c getMessage10(){
        Kevlar_Response_Messages__c m10=new Kevlar_Response_Messages__c();
        m10.name='507';
        m10.Response_Message__c='Campaign progress Dropdown Populated';
        return m10;
    }
    public static Kevlar_Response_Messages__c getMessage11(){
        Kevlar_Response_Messages__c m11=new Kevlar_Response_Messages__c();
        m11.name='508';
        m11.Response_Message__c='BAC inserted successfully';
        return m11;
    }
    public static Kevlar_Response_Messages__c getMessage12(){
        Kevlar_Response_Messages__c m12=new Kevlar_Response_Messages__c();
        m12.name='516';
        m12.Response_Message__c='Plate Design Populated';
        return m12;
    }
    public static Kevlar_Response_Messages__c getMessage13(){
        Kevlar_Response_Messages__c m13=new Kevlar_Response_Messages__c();
        m13.name='509';
        m13.Response_Message__c='Campaign Updated Successfully';
        return m13;
    }
    public static Kevlar_Response_Messages__c getMessage14(){
        Kevlar_Response_Messages__c m14=new Kevlar_Response_Messages__c();
        m14.name='510';
        m14.Response_Message__c='Campaigns Populated';
        return m14;
    }
    
    public static Kevlar_Response_Messages__c getMessage15(){
        Kevlar_Response_Messages__c m15=new Kevlar_Response_Messages__c();
        m15.name='204';
        m15.Message__c='Exception';
        return m15;
    }
    public static Kevlar_Response_Messages__c getMessage16(){
        Kevlar_Response_Messages__c m16=new Kevlar_Response_Messages__c();
        m16.name='513';
        m16.Response_Message__c='FDR Inserted successfully';
        return m16;
    }
    public static Kevlar_Response_Messages__c getMessage517(){
        Kevlar_Response_Messages__c m517=new Kevlar_Response_Messages__c();
        m517.name='517';
        m517.Response_Message__c='HAP Inserted successfully';
        return m517;
    }
     public static Kevlar_Response_Messages__c getMessage545(){
        Kevlar_Response_Messages__c m545=new Kevlar_Response_Messages__c();
        m545.name='545';
        m545.Response_Message__c='Other requirements saved';
        return m545;
    }
     public static Kevlar_Response_Messages__c getMessage546(){
        Kevlar_Response_Messages__c m546=new Kevlar_Response_Messages__c();
        m546.name='546';
        m546.Response_Message__c='Custom Bullet Saved';
        return m546;
    }
    public static Kevlar_Response_Messages__c getMessage17(){
        Kevlar_Response_Messages__c m17=new Kevlar_Response_Messages__c();
        m17.name='518';
        m17.Response_Message__c='Updated FDR record';
        return m17;
    }
    public static Kevlar_Response_Messages__c getMessage18(){
        Kevlar_Response_Messages__c m18=new Kevlar_Response_Messages__c();
        m18.name='522';
        m18.Response_Message__c='Default Dimensions Populated';
        return m18;
    }
    public static Kevlar_Response_Messages__c getMessage19(){
        Kevlar_Response_Messages__c m19=new Kevlar_Response_Messages__c();
        m19.name='521';
        m19.Response_Message__c='Populated Design Successfully';
        return m19;
    }
    public static Kevlar_Response_Messages__c getMessage20(){
        Kevlar_Response_Messages__c m20=new Kevlar_Response_Messages__c();
        m20.name='511';
        m20.Response_Message__c='Populates threat master data';
        return m20;
    }
    public static Kevlar_Response_Messages__c getMessage21(){
        Kevlar_Response_Messages__c m21=new Kevlar_Response_Messages__c();
        m21.name='523';
        m21.Response_Message__c='Other Default Dropdowns Populated';
        return m21;
    }
    public static Kevlar_Response_Messages__c getMessage22(){
        Kevlar_Response_Messages__c m22=new Kevlar_Response_Messages__c();
        m22.name='527';
        m22.Response_Message__c='Get Attachment successfully';
        return m22;
    }
    public static Kevlar_Response_Messages__c getMessage23(){
        Kevlar_Response_Messages__c m23=new Kevlar_Response_Messages__c();
        m23.name='526';
        m23.Response_Message__c='Attachment saved successfully';
        return m23;
    }
    public static Kevlar_Response_Messages__c getMessage24(){
        Kevlar_Response_Messages__c m24=new Kevlar_Response_Messages__c();
        m24.name='530';
        m24.Response_Message__c='Record Deleted Successfully';
        return m24;
    }
    public static Kevlar_Response_Messages__c getMessage25(){
        Kevlar_Response_Messages__c m25=new Kevlar_Response_Messages__c();
        m25.name='514';
        m25.Response_Message__c='Populates BAS records values for particular campaign';  
        return m25;
    }
    public static Kevlar_Response_Messages__c getMessage26(){
        Kevlar_Response_Messages__c m26=new Kevlar_Response_Messages__c();
        m26.name='515';
        m26.Response_Message__c='Populate Material details';  
        return m26;
    }
    public static Kevlar_Response_Messages__c getMessage27(){
        Kevlar_Response_Messages__c m27=new Kevlar_Response_Messages__c();
        m27.name='533';
        m27.Response_Message__c='Solution pricing saved successfully';  
        return m27;
    }
    public static Kevlar_Response_Messages__c getMessage28(){
        Kevlar_Response_Messages__c m28=new Kevlar_Response_Messages__c();
        m28.name='534';
        m28.Response_Message__c='Solution pricing updated successfully';  
        return m28;
    }
    public static Kevlar_Response_Messages__c getMessage29(){
        Kevlar_Response_Messages__c m29=new Kevlar_Response_Messages__c();
        m29.name='520';
        m29.Response_Message__c='Threats Updated';  
        return m29;
    }
    public static Kevlar_Response_Messages__c getMessage30(){
        Kevlar_Response_Messages__c m30=new Kevlar_Response_Messages__c();
        m30.name='541';
        m30.Response_Message__c='ThreatDropdown Values Populated';  
        return m30;
    }
    public static Kevlar_Response_Messages__c getMessage31(){
        Kevlar_Response_Messages__c m31=new Kevlar_Response_Messages__c();
        m31.name='528';
        m31.Response_Message__c='SAP Solution Updated';  
        return m31;
    }
    public static Kevlar_Response_Messages__c getMessage32(){
        Kevlar_Response_Messages__c m32=new Kevlar_Response_Messages__c();
        m32.name='531';
        m32.Response_Message__c='Pricing Master populated successfully  d';  
        return m32;
    }
    public static Kevlar_Response_Messages__c getMessage33(){
        Kevlar_Response_Messages__c m33=new Kevlar_Response_Messages__c();
        m33.name='532';
        m33.Response_Message__c='Updated Pricing Master data already sent   ';  
        return m33;
    }
    public static Kevlar_Response_Messages__c getMessage34(){
        Kevlar_Response_Messages__c m34=new Kevlar_Response_Messages__c();
        m34.name='529';
        m34.Response_Message__c='SAP Solution Updated';  
        return m34;
    }
    public static Kevlar_Response_Messages__c getMessage35(){
        Kevlar_Response_Messages__c m35=new Kevlar_Response_Messages__c();
        m35.name='520';
        m35.Response_Message__c='HAP Design Created';  
        return m35;
    }
    public static Kevlar_Response_Messages__c getMessage36(){
        Kevlar_Response_Messages__c m36=new Kevlar_Response_Messages__c();
        m36.name='542';
        m36.Response_Message__c='sourceOfIT Updated';  
        return m36;
    }
    public static Kevlar_Response_Messages__c getMessage37(){
        Kevlar_Response_Messages__c m37=new Kevlar_Response_Messages__c();
        m37.name='543';
        m37.Response_Message__c='Attachment Deleted';  
        return m37;
    }
    public static Kevlar_Response_Messages__c getMessage38(){
        Kevlar_Response_Messages__c m38=new Kevlar_Response_Messages__c();
        m38.name='544';
        m38.Response_Message__c='Solution Package Saved';  
        return m38;
    }
    public static Kevlar_Response_Messages__c getMessage39(){
        Kevlar_Response_Messages__c m39=new Kevlar_Response_Messages__c();
        m39.name='205';
        m39.Response_Message__c='No update needed!';  
        return m39;
    }
    public static Kevlar_Response_Messages__c getMessage40(){
        Kevlar_Response_Messages__c m40=new Kevlar_Response_Messages__c();
        m40.name='204';
        m40.Message__c='Data is already updated!';  
        return m40;
    }
}