DuPont DevSB/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Country__c</fullName>
        <label>Lead Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Åland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opt In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin_Channel_Type__c</fullName>
        <inlineHelpText>Channel Type of the DuPont touch point where this lead was collected. This can be different from the channel where the customer heard from us (use Lead Source for this purpose)</inlineHelpText>
        <label>Origin Channel Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Data File</fullName>
                </value>
                <value>
                    <fullName>eMail</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Face to Face</fullName>
                </value>
                <value>
                    <fullName>Paper Mail</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Website-Secure</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin_Name__c</fullName>
        <description>Specific Origin channel name for :
CALLS : phone number (800# or description on phone display)     
WEBSITE INQUIRIES: select name of CONTACT US FORM or common website URL 
 Note: Use Campaigns or First Referrer name field for Trade Show name or other origin details</description>
        <inlineHelpText>select phone number (display) for calls 
select webform name or URL for web inquiries</inlineHelpText>
        <label>Origin Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2013 FGF Energy Whitepaper Download</fullName>
                </value>
                <value>
                    <fullName>2013 FGF Protection Whitepaper Download</fullName>
                </value>
                <value>
                    <fullName>4-1000</fullName>
                </value>
                <value>
                    <fullName>Account statement</fullName>
                </value>
                <value>
                    <fullName>Brasil 800</fullName>
                </value>
                <value>
                    <fullName>DDF 800-441-0575</fullName>
                </value>
                <value>
                    <fullName>DIMC-Local-Corp Phone</fullName>
                </value>
                <value>
                    <fullName>DIMC-Local-SBU Phone</fullName>
                </value>
                <value>
                    <fullName>DIMC-Regional-Corp Phone</fullName>
                </value>
                <value>
                    <fullName>eCommerce - State Available</fullName>
                </value>
                <value>
                    <fullName>Follow The Truck</fullName>
                </value>
                <value>
                    <fullName>food.dupont.cn</fullName>
                </value>
                <value>
                    <fullName>http://www2.dupont.com/DuPont_Safety_Resources/zh_CN/</fullName>
                </value>
                <value>
                    <fullName>Inbound Other</fullName>
                </value>
                <value>
                    <fullName>info.mexico@mex.dupont.com</fullName>
                </value>
                <value>
                    <fullName>Inquiry Center</fullName>
                </value>
                <value>
                    <fullName>Mexico Local</fullName>
                </value>
                <value>
                    <fullName>Mioge</fullName>
                </value>
                <value>
                    <fullName>National Safety Congress</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
                <value>
                    <fullName>Partner Form</fullName>
                </value>
                <value>
                    <fullName>PI/General</fullName>
                </value>
                <value>
                    <fullName>Privacy Breach</fullName>
                </value>
                <value>
                    <fullName>Social Login</fullName>
                </value>
                <value>
                    <fullName>www.coastaltraining.cn</fullName>
                </value>
                <value>
                    <fullName>www.dupont.ca</fullName>
                </value>
                <value>
                    <fullName>www.dupont.co.in/Shunya_Download</fullName>
                </value>
                <value>
                    <fullName>www.dupont.com</fullName>
                </value>
                <value>
                    <fullName>www.dupont.com/40_40/en_GB</fullName>
                </value>
                <value>
                    <fullName>www.dupont.com/ANZ short form</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Owning_Organization__c</fullName>
        <description>SBU(Strategic Business Unit)-BU(Business Unit)-SubBU(Business or Product Line)</description>
        <inlineHelpText>Relevant sub-business for the Owning Business</inlineHelpText>
        <label>Owning Organization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>DSS-Clean Technologies</fullName>
                </value>
                <value>
                    <fullName>DSS-Consulting</fullName>
                </value>
                <value>
                    <fullName>DSS-L&amp;D</fullName>
                </value>
                <value>
                    <fullName>IB-Biomaterials-BioIsoprene</fullName>
                </value>
                <value>
                    <fullName>SHE</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Owning_SBU__c</fullName>
        <label>Owning SBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Building Innovations</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Industrial Biosciences</fullName>
                </value>
                <value>
                    <fullName>Marketing &amp; Sales</fullName>
                </value>
                <value>
                    <fullName>Performance Polymers</fullName>
                </value>
                <value>
                    <fullName>Protection Technologies</fullName>
                </value>
                <value>
                    <fullName>Safety Health &amp; Environment</fullName>
                </value>
                <value>
                    <fullName>Science &amp; Technology</fullName>
                </value>
                <value>
                    <fullName>Sustainable Solutions</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Categorization of inquiry or lead used to determine process for handling and used for metrics.</description>
        <inlineHelpText>Type or category of an inquiry or sales lead.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alleged Incident</fullName>
                </value>
                <value>
                    <fullName>Call Request</fullName>
                </value>
                <value>
                    <fullName>Call Request - Face to Face</fullName>
                </value>
                <value>
                    <fullName>Career Opportunities</fullName>
                </value>
                <value>
                    <fullName>Certifications and Specifications</fullName>
                </value>
                <value>
                    <fullName>Code Compliance</fullName>
                </value>
                <value>
                    <fullName>Color Tools</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Contest</fullName>
                </value>
                <value>
                    <fullName>Contributions</fullName>
                </value>
                <value>
                    <fullName>Counterfeit Report</fullName>
                </value>
                <value>
                    <fullName>Data Sheet</fullName>
                </value>
                <value>
                    <fullName>Demo Request</fullName>
                </value>
                <value>
                    <fullName>Design &amp; Product Selection</fullName>
                </value>
                <value>
                    <fullName>Directory Assistance</fullName>
                </value>
                <value>
                    <fullName>Environmental Information</fullName>
                </value>
                <value>
                    <fullName>Export Procedures</fullName>
                </value>
                <value>
                    <fullName>Fabrication Assistance</fullName>
                </value>
                <value>
                    <fullName>General Company Info</fullName>
                </value>
                <value>
                    <fullName>General Feedback</fullName>
                </value>
                <value>
                    <fullName>Government Relations</fullName>
                </value>
                <value>
                    <fullName>Human Resources</fullName>
                </value>
                <value>
                    <fullName>Installation Assistance</fullName>
                </value>
                <value>
                    <fullName>Intellectual Assets &amp; Licensing</fullName>
                </value>
                <value>
                    <fullName>Investor Relations</fullName>
                </value>
                <value>
                    <fullName>Issue - Public Affairs</fullName>
                </value>
                <value>
                    <fullName>Lead Nurturing</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Literature</fullName>
                </value>
                <value>
                    <fullName>M/SDS &amp; Regulatory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlDPSAskaQuestion.cls
/*******************************************************************************
Copyright © 2016 DuPont. All rights reserved.
Author: Tabrez Ansari
Email: tabrez.ansari@tcs.com
Description:  This controller is used for capturing the Lead created as query on Ask a Question tab.
Created Date: 10/6/2016
Version: 1.0
********************************************************************************/

public with sharing class ctrlDPSAskaQuestion {
    // Initialize Variables
    public Lead objLead { get; set; }
    public String txtfName { get; set; }
    public String txtlName { get; set; }
    public String txtCompany { get; set; }
    public String txtEmail { get; set; }
    public String txtPhone { get; set; }
    public String txtMobile { get; set; }
    public String txtLeadCountry { get; set; }
    public String txttype { get; set; }
    public String txtDescription { get; set; }
    public boolean bolCheckbox { get; set; }
    
    public String successMsg;
    public String errorMsg;
    public Id srchCritId { get; set; }
    
    /* Function Description
    Name : ctrlDPSAskaQuestion
    Return Type: void
    Description: It is the constructor method     
    */
    public ctrlDPSAskaQuestion(ApexPages.StandardController controller) {
        txtLeadCountry ='--- None ---';
        blankValues();
        objLead = new Lead();
        
        successMsg = Label.LeadSuccessMsg;
        errorMsg = Label.LeadErrorMsg;
        srchCritId = apexpages.currentpage().getparameters().get('strId');
    }
    
    /* Function Description
    Name : blankValues
    Return Type: void
    Description: This function is used for autopopulating the values from the contact & user information.
    */ 
    public void blankValues(){
        try{
            txtfName = UserInfo.getFirstName();
            txtlName = UserInfo.getLastName();
            txtEmail = UserInfo.getUserEmail();
            User usr = [select id, ContactId, name from User where id =: UserInfo.getUserId()];
            List<Contact> lsobjcon = new List<Contact>();
            Contact objcon = new Contact();
            lsobjcon = [select id, name, MailingCountry, Contact_Country__c, Account.Name, Phone, MobilePhone from Contact where id =: usr.ContactId limit 1];
            if(lsobjcon.size() > 0){
                System.debug(lsobjcon[0].Contact_Country__c);
                map<String,String> mapexisting=new Map<String,String>();
                
                mapexisting.put(lsobjcon[0].Contact_Country__c,'Contact_Country__c');
                Map<String,String> convertedmapFieldVal=new Map<String,String>();
                convertedmapFieldVal=convertCountry(mapexisting); 
                txtLeadCountry =convertedmapFieldVal.get('Contact_Country__c');
                txtCompany = lsobjcon[0].Account.Name;
                txtPhone = lsobjcon[0].Phone;
                txtMobile = lsobjcon[0].MobilePhone;
            }
            
            System.debug(txtLeadCountry );
            txttype = '';
            txtDescription = '';
            bolCheckbox = false;
        }
        catch(Exception e){
            System.debug(e);
        }
    }

    /* Function Description
    Name : createLead
    Return Type: void
    Description: This function is used for creating Lead with the values provided & with few default values.
    */ 
    public void createLead(){
        try{
            if((txtfName == null || txtfName == '') || (txtlName == null || txtlName =='') || (txtCompany == null || txtCompany == '') || (txtemail == null || txtemail == '') ||
                (txtLeadCountry == null || txtLeadCountry == '') || (txttype == null || txttype == '')){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,errorMsg));
            }
            else{
                objLead.FirstName = txtfName;
                objLead.LastName = txtlName;
                objLead.Company = txtCompany;
                objLead.Email = txtemail;
                objLead.Phone = txtPhone;
                objLead.MobilePhone = txtMobile;
                objLead.Lead_Country__c = txtLeadCountry;
                objLead.Type__c = txttype;
                objLead.Description = txtDescription;
                objLead.Opt_In__c = bolCheckbox;
                Id LeadRecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get(Label.DPS_Lead_Record_Type).getRecordTypeId();
                if(LeadRecordTypeId != null)
                    objLead.RecordTypeId = LeadRecordTypeId;
                objLead.Owning_Organization__c = Label.DPS_Owning_Organization;
                objLead.Owning_SBU__c = Label.DPS_Owning_SBU;
                objLead.KV_DPS_Segment__c = Label.DPS_Segment;
                objLead.KV_DPS_SubSegment__c = Label.DPS_Sub_Segment;
                objLead.Origin_Channel_Type__c = Label.DPS_Origin_Channel_Type;
                objLead.Origin_Name__c = Label.DPS_Origin_Name;
                if(srchCritId != null)
                    objLead.KV_Search_Criteria__c = srchCritId;
                
                Database.DMLOptions dmo = new Database.DMLOptions();
                dmo.assignmentRuleHeader.useDefaultRule = true;
                objLead.setOptions(dmo);
    
                insert objLead;
                
                if(objLead.Opt_In__c == true){
                    cls_AssignCampaignId.assignCampId(objLead.Id);
                }
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,successMsg));
                blankValues();
            }
        }
        catch(Exception e) {
            System.debug(e);
        }
    }

    /* Function Description
    Name : convertCountry
    Return Type: Map
    Description: This function is used for changing the country name from Capital to Camel Case.
    */ 
    public MAP<String,String> convertCountry(Map<String,String> mapFieldVal)
    {   Map<String,String> mapConvertedCountry=new Map<String,String>();
        String originalCountry='';
        for(String str: mapFieldVal.keyset()){
        String convertedStr='';
        String firstpart='';
        originalCountry=str;
        List<String> lsconverted=new List<String>();
        for(Integer i=0; i<str.length() ;i++){
                str=str.toLowercase();
                if(str.substring(i,i+1).isAlpha()){
                    if(i==0){
                        firstpart=str.substring(0,i+1).toUpperCase();
                        convertedStr=firstpart;
                    }
                    else if(!str.substring(i-1,i).isAlpha()){
                        firstpart=str.substring(i,i+1).toUpperCase();
                        convertedStr=convertedStr+firstpart;
                    }
                    else{
                        convertedStr=convertedStr +  str.substring(i,i+1);
                    }
                }
                else{
                    convertedStr=convertedStr +  str.substring(i,i+1);
                }
                
        }
        lsconverted.add(convertedStr);
        mapConvertedCountry.put(mapFieldVal.get(originalCountry),convertedStr);
        }
        return mapConvertedCountry;
    }
    
    /* Function Description
    Name : submitLead
    Return Type: PageReference
    Description: This function is used to redirect the ask a question page back on the same page.
    */ 
    public PageReference submitLead()
    {
        createLead();
        PageReference pg = new PageReference('/apex/panelDPSAskAQuestion');
        pg.setRedirect(true);
        objLead = new Lead();
        return null;
    }
    
    /* Function Description
    Name : getcountryOptions
    Return Type: List
    Description: This function is used to redirect the ask a question page back on the same page.
    */
    public List<SelectOption> getcountryOptions()    
    {   if(txtLeadCountry == null || txtLeadCountry == '')
            txtLeadCountry ='--- None ---';
        List<SelectOption> options =  new List<SelectOption>();    
        options.add(new selectOption(txtLeadCountry ,txtLeadCountry ));
        Schema.DescribeFieldResult fieldResult = Contact.Contact_Country__c.getDescribe();    
        List<Schema.picklistEntry> ple = fieldResult.getPicklistValues();  
        Map<String,String> mapFieldVal=new Map<String,String>();  
        Map<String,String> convertedmapFieldVal=new Map<String,String>();  
        for(Schema.picklistEntry f:ple)    
        {   
            mapFieldVal.put(f.getValue(),f.getLabel());
        } 
        convertedmapFieldVal=convertCountry(mapFieldVal); 
        for(String s: convertedmapFieldVal.keyset()){
            options.add(new selectOption(s,convertedmapFieldVal.get(s)));  
        }  
        return Options;    
    }      
}