DuPont DevSB/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Queue__c</fullName>
        <label>Lead Queue</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owning_Organization__c</fullName>
        <description>SBU(Strategic Business Unit)-BU(Business Unit)-SubBU(Business or Product Line)</description>
        <inlineHelpText>Relevant sub-business for the Owning Business</inlineHelpText>
        <label>Owning Organization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>DSS-Clean Technologies</fullName>
                </value>
                <value>
                    <fullName>DSS-Consulting</fullName>
                </value>
                <value>
                    <fullName>DSS-L&amp;D</fullName>
                </value>
                <value>
                    <fullName>IB-Biomaterials-BioIsoprene</fullName>
                </value>
                <value>
                    <fullName>SHE</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Owning_SBU__c</fullName>
        <label>Owning SBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Building Innovations</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Industrial Biosciences</fullName>
                </value>
                <value>
                    <fullName>Marketing &amp; Sales</fullName>
                </value>
                <value>
                    <fullName>Performance Polymers</fullName>
                </value>
                <value>
                    <fullName>Protection Technologies</fullName>
                </value>
                <value>
                    <fullName>Safety Health &amp; Environment</fullName>
                </value>
                <value>
                    <fullName>Science &amp; Technology</fullName>
                </value>
                <value>
                    <fullName>Sustainable Solutions</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Geo Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Categorization of inquiry or lead used to determine process for handling and used for metrics.</description>
        <inlineHelpText>Type or category of an inquiry or sales lead.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alleged Incident</fullName>
                </value>
                <value>
                    <fullName>Call Request</fullName>
                </value>
                <value>
                    <fullName>Call Request - Face to Face</fullName>
                </value>
                <value>
                    <fullName>Career Opportunities</fullName>
                </value>
                <value>
                    <fullName>Certifications and Specifications</fullName>
                </value>
                <value>
                    <fullName>Code Compliance</fullName>
                </value>
                <value>
                    <fullName>Color Tools</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Contest</fullName>
                </value>
                <value>
                    <fullName>Contributions</fullName>
                </value>
                <value>
                    <fullName>Counterfeit Report</fullName>
                </value>
                <value>
                    <fullName>Data Sheet</fullName>
                </value>
                <value>
                    <fullName>Demo Request</fullName>
                </value>
                <value>
                    <fullName>Design &amp; Product Selection</fullName>
                </value>
                <value>
                    <fullName>Directory Assistance</fullName>
                </value>
                <value>
                    <fullName>Environmental Information</fullName>
                </value>
                <value>
                    <fullName>Export Procedures</fullName>
                </value>
                <value>
                    <fullName>Fabrication Assistance</fullName>
                </value>
                <value>
                    <fullName>General Company Info</fullName>
                </value>
                <value>
                    <fullName>General Feedback</fullName>
                </value>
                <value>
                    <fullName>Government Relations</fullName>
                </value>
                <value>
                    <fullName>Human Resources</fullName>
                </value>
                <value>
                    <fullName>Installation Assistance</fullName>
                </value>
                <value>
                    <fullName>Intellectual Assets &amp; Licensing</fullName>
                </value>
                <value>
                    <fullName>Investor Relations</fullName>
                </value>
                <value>
                    <fullName>Issue - Public Affairs</fullName>
                </value>
                <value>
                    <fullName>Lead Nurturing</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Literature</fullName>
                </value>
                <value>
                    <fullName>M/SDS &amp; Regulatory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/trigInsertLeadIntoChemours_UT.cls
@isTest
public class trigInsertLeadIntoChemours_UT 
{
    @isTest static void shareLeadTest() 
    {
        Lead l=new Lead();
        l.Owning_SBU__c='Chemicals & Fluoroproducts';
        l.Owning_Organization__c='DCF-ChemSol';
        l.Country='India';
        l.Region__c='Acia Pacific';
        l.FirstName='From';
        l.LastName='TestClass';
        l.Company='Chemours';
        l.Type__c='Literature';
        l.status='Qualify';
        insert l;
        
        Lead testLead = [select Id, FirstName from Lead where Id = :l.Id];
        //System.assertEquals(testLead.FirstName, 'From');  
    }
    @isTest static void shareLeadTestMethod1() 
    {
        Lead l=new Lead();
        l.Owning_SBU__c='Chemicals & Fluoroproducts';
        l.Owning_Organization__c='DCF-ChemSol';
        l.Country='India';
        l.Region__c='Acia Pacific';
        l.FirstName='From';
        l.LastName='TestClass1';
        l.Company='Chemours';
        l.Type__c='Literature';
        l.status='Qualify';
        l.Lead_Queue__c='DCF-NA C&D-DWT Lead Queued';
        insert l;
        
        Lead testLead = [select Id, FirstName,LastName from Lead where Id = :l.Id];
       //System.assertEquals(testLead.FirstName, 'From'); 
        testLead.LastName='TestClass2';
        update testLead;
         
    }
}