DuPont DevSB/src/objects/List__c.object
<CustomObject>
    <description>List object that will enable workflows based on hierarchical properties.</description>
    <fields>
        <fullName>Code_1__c</fullName>
        <label>Code 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Equipment Model</fullName>
                </value>
                <value>
                    <fullName>Geography</fullName>
                </value>
                <value>
                    <fullName>Instruction URL</fullName>
                </value>
                <value>
                    <fullName>Quantity Matrix</fullName>
                </value>
                <value>
                    <fullName>Revenue Schedule Product</fullName>
                </value>
                <value>
                    <fullName>Segment</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>List</label>
    <nameField>
        <label>List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/InstructionsSet.cls
/*******************************************************************************
Copyright © 2010 DuPont. All rights reserved. 
Author: Suneil Chetlur
Email: suneil.chetlur@ind.dupont.com
Description: Constructor Class to select the right URL for the 
             onclick event of the button "Instruction" on the
             opportunity page layout.
********************************************************************************/

public class InstructionsSet{
opportunity oppo;
public InstructionsSet(ApexPages.StandardController controller) {
    oppo=[select id,recordtypeid from opportunity where id=:System.currentPageReference().getParameters().get('id')];
}

/*****************************************************
Function called from the page "InstructionReference"
for the onclick even of the Instruction button on 
opportunity page layout.
*****************************************************/

public pagereference CheckRecordType(){
    list__c []l;
    string recid;
    recid=oppo.recordtypeid;
    string recidtomap;
    recidtomap=recid.substring(0,15);
    l=[select id,Website__c,code_1__c,name,type__c from list__c where code_1__c=:recidtomap and type__c='Instruction URL'];
    if(l.size()!=null){
        PageReference customPage= new PageReference(l[0].website__c);
        customPage.setRedirect(true);
        return customPage;
    }
    if(l.size()==null){
        PageReference customPage= new PageReference('/'+oppo.id+'/');
        customPage.setRedirect(true);
        return customPage;
    }
    return null;
}




}