DuPont DevSB/src/objects/Loop__DDP__c.object
<CustomObject>
    <customHelpPage>Loop__aboutloop</customHelpPage>
    <description>Document Packages powered by Nintex</description>
    <fields>
        <fullName>Loop__Filter__c</fullName>
        <inlineHelpText>Use this value with the filter and filtertype querystring parameters on your custom button or link to filter which DDPs are listed. Filtertype options are equals, doesnotequal, startswith, endswith, contains, and doesnotcontain.</inlineHelpText>
        <label>Filter</label>
        <type>TextArea</type>
    </fields>
    <label>Document Package</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drawloop Document Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Loop__DDP_Integration_Option__c.object
<CustomObject>
    <description>Delivery Options for Document Packages</description>
    <fields>
        <fullName>Loop__DDP__c</fullName>
        <label>Document Package</label>
        <referenceTo>Loop__DDP__c</referenceTo>
        <relationshipName>Custom_Integration_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Delivery Option</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Qualification__c.object
<CustomObject>
    <description>List of current or past Qualifications and Certifications of this Partner or Account</description>
    <fields>
        <fullName>BI_Product_Changed_DDP_Name__c</fullName>
        <formula>(if(ISPICKVAL( Certified_In_Area__c , &quot;DWSRCI&quot;) ,&quot;DWSRCI&quot; &amp; &quot;-Schedule1A&quot; , 
(if (ISPICKVAL( Certified_In_Area__c , &quot;DWSCCI&quot;) ,&quot;DWSCCI&quot; &amp; &quot;-Schedule1A&quot; , 
(if(ISPICKVAL( Certified_In_Area__c , &quot;DWSCCIFA&quot;) ,&quot;DWSCCIFA&quot; &amp; &quot;-Schedule1A&quot; , null ))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BI-Product Changed DDP Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certified_In_Area__c</fullName>
        <inlineHelpText>CRCFI - Corian Residential
ZRAMI - Zodiaq Residential Manufacturer 
ZRAZI - Zodiaq Residential Installer 
DWSRCI - CAN - Weatherization Residential 
DWSCCI - Weatherization Commercial 
DWSCCIFA - Fluid Applied</inlineHelpText>
        <label>Certified In Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CRCFI</fullName>
                </value>
                <value>
                    <fullName>ZRAMI</fullName>
                </value>
                <value>
                    <fullName>ZRAZI</fullName>
                </value>
                <value>
                    <fullName>DWSRCI</fullName>
                </value>
                <value>
                    <fullName>DWSCCI</fullName>
                </value>
                <value>
                    <fullName>DWSCCIFA</fullName>
                </value>
                <value>
                    <fullName>DWSRCI - CAN</fullName>
                </value>
                <value>
                    <fullName>AIA Speaker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Drawloop_Next_Schedule_1A_Email__c</fullName>
        <label>Drawloop Next Schedule 1A-Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Products_Changed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Products Changed</label>
        <type>Checkbox</type>
    </fields>
    <label>Qualification</label>
    <nameField>
        <displayFormat>QL{YY}{MM}-{0000}</displayFormat>
        <label>Qualification Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ProductsChanged.cls
public class ProductsChanged {

   Qualification__c listQualification  = new Qualification__c(); 
    boolean isProductButtonDisabled = false;
    string urlForTriggeringDDPSchedule = '/apex/loop__looplus?eid={Qualification.id}';
    private final Qualification__c Qualification;
    String DDPName=null;
    Map<string,string> TypeID=new Map<string,string>();
    string DDPID=null;
    

    public ProductsChanged(ApexPages.StandardController controller) {
        Qualification=  (Qualification__c)Controller.getRecord();
        listQualification  = [select id, Products_Changed__c, BI_Product_Changed_DDP_Name__c, Certified_In_Area__c from Qualification__c where id = :Qualification.id  ];
        
        system.debug('id: '+ Qualification.Id);
        system.debug('Products_Changed: '+ listQualification  );
            if(listQualification.Products_Changed__c == true){
                isProductButtonDisabled = false;
                DDPName=listQualification.BI_Product_Changed_DDP_Name__c;
                for(Loop__DDP_Integration_Option__c  loopOption:[select id,RecordType.Name,RecordTypeId,Loop__DDP__r.ID from Loop__DDP_Integration_Option__c where Loop__DDP__r.Loop__Filter__c=:DDPName]){
                TypeID.put(loopOption.RecordType.Name,loopOption.id);
                 if(DDPID!=null){
                 DDPID=loopOption.Loop__DDP__r.ID;
                 }
                }
            }
            else 
                isProductButtonDisabled = true;
        }
  
    
    public boolean getisProductButtonDisabled () {
          return isProductButtonDisabled;  
    }

    public string geturlForTriggeringDDP () {
          return urlForTriggeringDDPSchedule;  
    }


    public PageReference urlForTriggeringDDP() {
        String OpenPageUrl = '/apex/loop__looplus?eid='+Qualification.id+'&filter='+DDPName+'&autorun=true';
        
        
        PageReference newPage = new PageReference(OpenPageUrl);
        newPage.setRedirect(true);
        
        string drawloopNextField = null;
        
        drawloopNextField='SFQualification__c:'+Qualification.id+';Deploy:'+TypeID.get('Email')+';DDPId:'+DDPID+';DeployType:autoemail';
        
        listQualification.Drawloop_Next_Schedule_1A_Email__c = drawloopNextField; 
        update listQualification;
        return newPage;
        
    }

}