DuPont DevSB/src/objects/OneDuPontMetaData__c.object
<CustomObject>
    <fields>
        <fullName>AgCo_CRM_Metadata_Remediation__c</fullName>
        <label>AgCo CRM - Metadata Remediation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>AgCo_CRM_Remediation_Reason_Note__c</fullName>
        <inlineHelpText>Required when remediation for the AGCo CRM is selected.  Enter either the reason for the remediation and/or any notes about the remediation</inlineHelpText>
        <label>AgCo CRM - Remediation Reason/Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>AgCo_Remediation_Level__c</fullName>
        <label>AgCo Remediation Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Destination_Org__c</fullName>
        <inlineHelpText>Enter all the orgs this metadata component will be migrated to</inlineHelpText>
        <label>Destination Org</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AgCo</fullName>
                </value>
                <value>
                    <fullName>MatCo</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>IB</fullName>
                </value>
                <value>
                    <fullName>DPS</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>Remedy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EC_CRM_Metadata_Remediation__c</fullName>
        <label>EC CRM - Metadata Remediation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EC_CRM_Remediation_Reason_Note__c</fullName>
        <inlineHelpText>Required when remediation for EC CRM is selected.  Enter either the reason for the remediation and/or any notes about the remediation</inlineHelpText>
        <label>EC CRM - Remediation Reason/Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EC_Remediation_Level__c</fullName>
        <label>EC Remediation Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>FMC_CRM_Metadata_Remediation__c</fullName>
        <label>FMC CRM - Metadata Remediation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Modify</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FMC_CRM_Remediation_Reason_Note__c</fullName>
        <label>FMC CRM - Remediation Reason/Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FMC_Remediation_Level__c</fullName>
        <label>FMC Remediation Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IB_CRM_Metadata_Remediation__c</fullName>
        <label>IB CRM - Metadata Remediation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IB_CRM_Remediation_Reason_Note__c</fullName>
        <inlineHelpText>Required when remediation for IB CRM is selected.  Enter either the reason for the remediation and/or any notes about the remediation</inlineHelpText>
        <label>IB CRM - Remediation Reason/Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IB_Remediation_Level__c</fullName>
        <label>IB Remediation Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MS_CRM_Metadata_Remediation__c</fullName>
        <label>MS CRM - Metadata Remediation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MS_CRM_Remediation_Reason_Note__c</fullName>
        <inlineHelpText>Required when remediation for MS CRM is selected.  Enter either the reason for the remediation and/or any notes about the remediation</inlineHelpText>
        <label>MS CRM - Remediation Reason/Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MS_Remediation_Level__c</fullName>
        <label>MS Remediation Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>NH_CRM_Metadata_Remediation__c</fullName>
        <label>NH CRM - Metadata Remediation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>NH_CRM_Remediation_Reason_Note__c</fullName>
        <inlineHelpText>Required when remediation for the NH is selected.  Enter either the reason for the remediation and/or any notes about the remediation</inlineHelpText>
        <label>NH CRM - Remediation Reason/Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NH_Remediation_Level__c</fullName>
        <label>NH Remediation Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PS_CRM_Remediation_Reason_Note__c</fullName>
        <inlineHelpText>Required when remediation for PS CRM is selected.  Enter either the reason for the remediation and/or any notes about the remediation</inlineHelpText>
        <label>PS CRM - Remediation Reason/Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PS_CRM_Remediation__c</fullName>
        <label>PS CRM Metadata Remediation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PS_Remediation_Level__c</fullName>
        <label>PS Remediation Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ParentMetaData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent MetaData</label>
        <referenceTo>OneDuPontMetaData__c</referenceTo>
        <relationshipName>ParentMetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SS_CRM_Metadata_Remediation__c</fullName>
        <label>SS CRM - Metadata Remediation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SS_CRM_Remediation_Reason_Note__c</fullName>
        <inlineHelpText>Required when remediation for SS CRM is selected.  Enter either the reason for the remediation and/or any notes about the remediation</inlineHelpText>
        <label>SS CRM - Remediation Reason/Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SS_Remediation_Levels__c</fullName>
        <label>SS Remediation Levels</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Remediation_Levels</valueSetName>
        </valueSet>
    </fields>
    <label>MetaData Mapping (One DuPont)</label>
    <nameField>
        <displayFormat>MD-{000000000}</displayFormat>
        <label>MetaData Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Mappings (One DuPont)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/globalValueSets/Remediation_Levels.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>L1</fullName>
    </customValue>
    <customValue>
        <fullName>L2</fullName>
    </customValue>
    <customValue>
        <fullName>L3</fullName>
    </customValue>
    <description>Remediation Levels</description>
    <masterLabel>Remediation Levels</masterLabel>
</GlobalValueSet>

DuPont DevSB/src/globalValueSets/Remediation_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Delete</fullName>
    </customValue>
    <customValue>
        <fullName>Modify</fullName>
        <label>Modify Metdata Component</label>
    </customValue>
    <description>Types of Remediation to be implemented</description>
    <masterLabel>Remediation Types</masterLabel>
</GlobalValueSet>

DuPont DevSB/src/classes/SFDC_ChildComponentSync_Controller.cls
public class SFDC_ChildComponentSync_Controller {

    public OneDuPontMetaData__c syncRecord{get;set;}
    public String buSelection{get;set;}
    public final ApexPages.StandardController controller = null;
    
     public SFDC_ChildComponentSync_Controller(ApexPages.StandardController stdController){
        this.syncRecord = (OneDuPontMetaData__c)stdController.getRecord();
        this.syncRecord = [SELECT Id, Name, AgCo_CRM_Metadata_Remediation__c,AgCo_CRM_Remediation_Reason_Note__c,
                           AgCo_Remediation_Level__c
                           FROM OneDuPontMetaData__c WHERE Id=:syncRecord.id];
        this.controller = stdController;
        
         
        // Clear the picklists 
        this.syncRecord.AgCo_Remediation_Level__c = null;
        this.syncRecord.AgCo_CRM_Remediation_Reason_Note__c = '*Child Component of a Custom Object being delete*';
        this.syncRecord.AgCo_CRM_Metadata_Remediation__c = null;
        this.buSelection = 'None';
    }
   


     // Sync the metadata 
    public PageReference updateLines(){
        
        if ((buSelection=='None') || (syncRecord.AgCo_Remediation_Level__c==null) ||
            (syncRecord.AgCo_CRM_Remediation_Reason_Note__c==null) ||(syncRecord.AgCo_CRM_Metadata_Remediation__c==null) )
        {
            // SUCCESS
        	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Missing Required Fields'));
        	return null;
        }
        
        List<OneDuPontMetadata__c> updateList = new List<OneDuPontMetadata__c>();
        for (OneDuPontMetadata__c c : [SELECT ID,
                                       IB_Remediation_Level__c,
                                       IB_CRM_Remediation_Reason_Note__c,
                                       IB_CRM_Metadata_Remediation__c,
                                       NH_Remediation_Level__c,
                                       NH_CRM_Remediation_Reason_Note__c,
                                       NH_CRM_Metadata_Remediation__c,
                                       SS_Remediation_Levels__c,
                                       SS_CRM_Remediation_Reason_Note__c,
                                       SS_CRM_Metadata_Remediation__c,
                                       PS_Remediation_Level__c,
                                       PS_CRM_Remediation_Reason_Note__c,
                                       PS_CRM_Remediation__c,
                                       FMC_Remediation_Level__c,
                                       FMC_CRM_Remediation_Reason_Note__c,
                                       FMC_CRM_Metadata_Remediation__c,
                                       AgCo_Remediation_Level__c,
                                       AgCo_CRM_Remediation_Reason_Note__c,
                                       AgCo_CRM_Metadata_Remediation__c,
                                       EC_Remediation_Level__c,
                                       EC_CRM_Remediation_Reason_Note__c,
                                       EC_CRM_Metadata_Remediation__c,
                                       MS_Remediation_Level__c,
                                       MS_CRM_Remediation_Reason_Note__c,
                                       MS_CRM_Metadata_Remediation__c,
                                       Destination_Org__c
                                       FROM OneDuPontMetadata__c WHERE ParentMetaData__c=:syncRecord.Id])
        {
            
            String destinationOrg = c.Destination_Org__c;
            if (c.Destination_Org__c==null){continue;}
            
            if (buSelection=='IB' && destinationOrg.contains('IB')){ 
                c.IB_CRM_Metadata_Remediation__c = syncRecord.AgCo_CRM_Metadata_Remediation__c;
                c.IB_Remediation_Level__c = syncRecord.AgCo_Remediation_Level__c;
                c.IB_CRM_Remediation_Reason_Note__c = syncRecord.AgCo_CRM_Remediation_Reason_Note__c;      
            }
            
            if (buSelection=='AgCo' && destinationOrg.contains('AgCo')){
                c.AgCo_CRM_Metadata_Remediation__c = syncRecord.AgCo_CRM_Metadata_Remediation__c;
                c.AgCo_Remediation_Level__c = syncRecord.AgCo_Remediation_Level__c;
                c.AgCo_CRM_Remediation_Reason_Note__c = syncRecord.AgCo_CRM_Remediation_Reason_Note__c;      
            }
            
            if (buSelection=='FMC' && destinationOrg.contains('Remedy')){
                c.FMC_CRM_Metadata_Remediation__c = syncRecord.AgCo_CRM_Metadata_Remediation__c;
                c.FMC_Remediation_Level__c = syncRecord.AgCo_Remediation_Level__c;
                c.FMC_CRM_Remediation_Reason_Note__c = syncRecord.AgCo_CRM_Remediation_Reason_Note__c;      
            }
            
            if (buSelection=='PS' && destinationOrg.contains('DPS')){
                c.PS_CRM_Remediation__c = syncRecord.AgCo_CRM_Metadata_Remediation__c;
                c.PS_Remediation_Level__c = syncRecord.AgCo_Remediation_Level__c;
                c.PS_CRM_Remediation_Reason_Note__c = syncRecord.AgCo_CRM_Remediation_Reason_Note__c;      
            }
            
            if (buSelection=='SS' && destinationOrg.contains('DSS')){
                c.SS_CRM_Metadata_Remediation__c = syncRecord.AgCo_CRM_Metadata_Remediation__c;
                c.SS_Remediation_Levels__c = syncRecord.AgCo_Remediation_Level__c;
                c.SS_CRM_Remediation_Reason_Note__c = syncRecord.AgCo_CRM_Remediation_Reason_Note__c;      
            }
            
            if (buSelection=='EC' && destinationOrg.contains('EC')){
                c.EC_CRM_Metadata_Remediation__c = syncRecord.AgCo_CRM_Metadata_Remediation__c;
                c.EC_Remediation_Level__c = syncRecord.AgCo_Remediation_Level__c;
                c.EC_CRM_Remediation_Reason_Note__c = syncRecord.AgCo_CRM_Remediation_Reason_Note__c;      
            }
            
            if (buSelection=='MS' && destinationOrg.contains('MatCo')){
                c.MS_CRM_Metadata_Remediation__c = syncRecord.AgCo_CRM_Metadata_Remediation__c;
                c.MS_Remediation_Level__c = syncRecord.AgCo_Remediation_Level__c;
                c.MS_CRM_Remediation_Reason_Note__c = syncRecord.AgCo_CRM_Remediation_Reason_Note__c;      
            }
            
            if (buSelection=='NH'&& destinationOrg.contains('NH')){
                c.NH_CRM_Metadata_Remediation__c = syncRecord.AgCo_CRM_Metadata_Remediation__c;
                c.NH_Remediation_Level__c = syncRecord.AgCo_Remediation_Level__c;
                c.NH_CRM_Remediation_Reason_Note__c = syncRecord.AgCo_CRM_Remediation_Reason_Note__c;      
            }
            
            updateList.add(c); 
        }
        
        update updateList;       
        
        // SUCCESS
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Successfully Updated the Children Metadata Components'));
        return null;
    }
    
    // Cancel and return
    public PageReference cancel(){
        return controller.cancel();
    }

}