DuPont DevSB/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_Duration__c</fullName>
        <description>Length of opportunity or contract in months, quarters, or years (see Amount Type).</description>
        <inlineHelpText>Length of opportunity or contract in months, quarters, or years (see Amount Type).</inlineHelpText>
        <label>Duration</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Opportunity_Company__c.object
<CustomObject>
    <description>Companies related to this opportunity</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company associated with this Opportunity</description>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunity_Company</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Oppoortunity this Company is related to</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Company</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity-Company</label>
    <nameField>
        <displayFormat>OPCO{YY}{MM}-{0000}</displayFormat>
        <label>OPCO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity-Companies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Opportunity_Products__c.object
<CustomObject>
    <description>List of Products relevent to a given opportunity</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Name of the opportunity this Product is applicable to</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductOfOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product applicable to this opportunity</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>R00N30000001Tv8nEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Price__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Opportunity-Product</label>
    <nameField>
        <displayFormat>OPPR{YY}{MM}-{0000}</displayFormat>
        <label>Opportunity-Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity-Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ctrlOpportunityDeepClone_UT.cls
/*******************************************************************************
Author: Martin Ryder
Email: martin.ryder@doextra.com
Description:  DPP Deep clone test class
//<MR20160614> remove generated schedules before cloning old ones
//********************************************************************************/
@isTest
public class ctrlOpportunityDeepClone_UT {
    static testMethod void test_ctrlOpportunityDeepClone() {
        Account a = new account (name='Test', ShippingCountry='US');
        insert a;
        //Opportunity o = new opportunity (AccountId=a.id, name='Onehundredandtwenty Onehundredandtwenty Onehundredandtwenty Onehundredandtwenty Onehundredandtwenty Onehundredandtwenty', stagename='Prospect', closeDate=Date.today(), Amount=1, Estimated_Max_Effort_hours__c=20, Type='Defense',Contract_Duration__c=2);
        Opportunity o = new opportunity (AccountId=a.id, name='Onehundredandtwenty Onehundredandtwenty Onehundredandtwenty Onehundredandtwenty Onehundredandtwenty Onehundredandtwenty', stagename='Prospect', closeDate=Date.today(), Amount=1, Type='Defense',Contract_Duration__c=2);
        insert o;
        
        OpportunityTeamMember OTM = new OpportunityTeamMember(OpportunityId=o.Id, UserId=userinfo.getuserId(), TeamMemberRole='Finance');
        insert OTM;
        
        Opportunity_Company__c newOC = new Opportunity_Company__c(Opportunity__c=o.Id, Company__c =a.Id);
        insert newOC;
        
        Product2 prod2 = new Product2(name='prod2', description='here is a long short', CanUseRevenueSchedule=true, CanUseQuantitySchedule=true, IsActive=true);        
        insert prod2;
        Opportunity_Products__c newOP = new Opportunity_Products__c (Opportunity__c=o.Id, ProductOfOpportunity__c =prod2.id, Quantity__c=1, Sales_Price__c=1);
        insert newOP;
        
        id pb = Test.getStandardPricebookId();
        pricebookentry pbe = new PricebookEntry( Pricebook2Id = pb, Product2Id = prod2.Id, UnitPrice = 10000, IsActive = true);
        insert pbe;
        OpportunityLineitem oli = new opportunityLineItem(opportunityId=o.Id, pricebookentryId=pbe.Id, quantity=2, TotalPrice=34);
        insert oli;
        //Krish: added startTest to avoid too many soql queries error
        Test.startTest();
        //<MR20160614> remove generated schedules before cloning old ones.
        system.debug('After Items');
        QuantitySchedulingController.oppDuration=5;
        list<opportunitylineitemschedule> testolis = [select id, quantity, ScheduleDate  from opportunitylineitemschedule where OpportunityLineItemId=:oli.id];
        system.debug(JSON.serializePretty(testolis));        
        opportunitylineitemschedule olis = new opportunitylineitemschedule(opportunitylineitemId=oli.Id, scheduledate=date.today(),quantity=1, type='Quantity');
        insert olis;

        //<MR20160614> remove generated schedules before cloning old ones.
        system.debug('After Items schedule');
        testolis = [select id, quantity, ScheduleDate  from opportunitylineitemschedule where OpportunityLineItemId=:oli.id];
        system.debug(JSON.serializePretty(testolis));

        PageReference pageRef = Page.OpportunityDeepClone;
        Test.setCurrentPage(pageRef);   
        ApexPages.StandardController sc = new ApexPages.StandardController(o);
        ctrlOpportunityDeepClone dc = new ctrlOpportunityDeepClone(sc);
        dc.deepclone();

        //<MR20160614> remove generated schedules before cloning old ones.
        system.debug('After Deep Clone');
        testolis = [select id, quantity, ScheduleDate  from opportunitylineitemschedule where OpportunityLineItemId=:oli.id];
        system.debug(JSON.serializePretty(testolis));

        
        o.name='Clone test';
        update o;
        
        sc = new ApexPages.StandardController(o);
        dc = new ctrlOpportunityDeepClone(sc);
        dc.deepclone();
        
        o.name='Clone(1) test';
        update o;
        //Krish: added startTest to avoid too many soql queries error
        Test.stopTest();
        sc = new ApexPages.StandardController(o);
        dc = new ctrlOpportunityDeepClone(sc);
        dc.deepclone();
        
        
        

    }


}