DuPont DevSB/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amount_Type__c</fullName>
        <description>Type of Revenue stream entered in the Amount field (e.g. Time period, type of schedule )</description>
        <inlineHelpText>Type of Revenue stream entered in the Amount field (e.g. Time period, type of schedule )</inlineHelpText>
        <label>Amount Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Annual - Auto - Monthly</fullName>
                </value>
                <value>
                    <fullName>Annual - Auto - Quarterly</fullName>
                </value>
                <value>
                    <fullName>Annual - Auto - Yearly</fullName>
                </value>
                <value>
                    <fullName>Annual - Manual - Monthly</fullName>
                </value>
                <value>
                    <fullName>Annual - Manual - Quarterly</fullName>
                </value>
                <value>
                    <fullName>Annual - Manual - Yearly</fullName>
                </value>
                <value>
                    <fullName>Multiple Years</fullName>
                </value>
                <value>
                    <fullName>One Time</fullName>
                </value>
                <value>
                    <fullName>One Time - Auto - Monthly</fullName>
                </value>
                <value>
                    <fullName>One Time - Auto - Quarterly</fullName>
                </value>
                <value>
                    <fullName>One Time - Auto - Yearly</fullName>
                </value>
                <value>
                    <fullName>One Time - Manual - Monthly</fullName>
                </value>
                <value>
                    <fullName>One Time - Manual - Quarterly</fullName>
                </value>
                <value>
                    <fullName>One Time - Manual - Yearly</fullName>
                </value>
                <value>
                    <fullName>One Time - Tender</fullName>
                </value>
                <value>
                    <fullName>Schedule-Months</fullName>
                </value>
                <value>
                    <fullName>Schedule-Quarters</fullName>
                </value>
                <value>
                    <fullName>Schedule-Years</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Commercial_Revenue_Date__c</fullName>
        <label>Commercial Revenue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Duration__c</fullName>
        <description>Duration Field used for the purpose of revenue schedulling.</description>
        <inlineHelpText>New Length of contract in months or quarters (see Amount Type)</inlineHelpText>
        <label>New Duration</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owning_Organisation__c</fullName>
        <description>DuPont organization owning/leading the execution of this opportunity</description>
        <label>Owning Organization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AGCP</fullName>
                </value>
                <value>
                    <fullName>AGCP-CPC</fullName>
                </value>
                <value>
                    <fullName>AGNH</fullName>
                </value>
                <value>
                    <fullName>AGNH-Qualicon</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-Env</fullName>
                </value>
                <value>
                    <fullName>BI-Landscape Systems</fullName>
                </value>
                <value>
                    <fullName>BI-Surf</fullName>
                </value>
                <value>
                    <fullName>BI-Typar</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>DCF</fullName>
                </value>
                <value>
                    <fullName>DCF-ChemSol</fullName>
                </value>
                <value>
                    <fullName>DCF-FLCH</fullName>
                </value>
                <value>
                    <fullName>DCF-FLCH Refrigerants </fullName>
                </value>
                <value>
                    <fullName>DCF-FLCH Vertrel </fullName>
                </value>
                <value>
                    <fullName>DCF-FPS</fullName>
                </value>
                <value>
                    <fullName>DCSE-Clean &amp; Disinfect</fullName>
                </value>
                <value>
                    <fullName>DEC</fullName>
                </value>
                <value>
                    <fullName>DEC-CPM</fullName>
                </value>
                <value>
                    <fullName>DEC-Digital Printing</fullName>
                </value>
                <value>
                    <fullName>DEC-Microcircuit Materials</fullName>
                </value>
                <value>
                    <fullName>DPE</fullName>
                </value>
                <value>
                    <fullName>DPP-Parts</fullName>
                </value>
                <value>
                    <fullName>DPP-Polymers</fullName>
                </value>
                <value>
                    <fullName>DPT-A&amp;HF</fullName>
                </value>
                <value>
                    <fullName>DPT-Air and Filtration</fullName>
                </value>
                <value>
                    <fullName>DPT-Aramids</fullName>
                </value>
                <value>
                    <fullName>DPT-ASPS</fullName>
                </value>
                <value>
                    <fullName>DPT-Automotive</fullName>
                </value>
                <value>
                    <fullName>DPT-Barrier &amp; Cleaning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>OneDuPont</fullName>
        <active>true</active>
        <businessProcess>I2C Sales Process</businessProcess>
        <description>Other Opportunities (e.g. in white spaces not covered by the Industry or SBU Types you have access to)</description>
        <label>OneDuPont</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/TestOpportunity.cls
public class TestOpportunity {

public static testMethod void mytest(){

    Test.startTest();

    Date da1 = Date.newInstance(2006,11,11);
     //[12302016] Merge&Spin; Removed Hard Coded Id of DSS Consulting Record type on opportunity
    //Commented for dps
    //string DSS_Consulting=RType.getIdByDevName('Opportunity','DSS_Consulting');
    string DSS_Consulting=RType.getIdByDevName('Opportunity','OneDuPont');
    
    Opportunity o2 = new Opportunity(Owning_Organisation__c='DSRB',RecordTypeId=DSS_Consulting,Amount=1000,Amount_Type__c='One Time - Manual - Monthly', CurrencyIsoCode='EUR', CloseDate= da1,Name='Test opp', StageName='Qualify',Commercial_Revenue_Date__c= da1);
    //Opportunity o3 = new Opportunity(Owning_Organisation__c='DSRB',RecordTypeId='012300000000hKS',Amount=1000,Amount_Type__c='One Time - Manual - Monthly', CurrencyIsoCode='USD', CloseDate= da1,Name='Test opp Manu', StageName='Qualify',Commercial_Revenue_Date__c= da1);   
    //Opportunity[] s = new Opportunity[2];
    //s[0] = o3;
    //s[1] = o2;
       insert o2;
    
    Opportunity[] testz = [select Name, New_Duration__c from Opportunity Where Name = 'Test opp'];
    //testz[0].New_Duration__c = 0;
    //update testz[0];
    /*
    Opportunity[] testz2 = [select Name, New_Duration__c from Opportunity Where Name = 'Test opp Manu'];
    testz2[0].New_Duration__c = 0;
    update testz2;

    Opportunity[] testz3 = [select Name, New_Duration__c from Opportunity Where Name = 'Test opp Manu'];
    testz2[0].New_Duration__c = 100;
    update testz3;
*/

    Test.stopTest();
}       
       
}