DuPont DevSB/src/objects/Opportunity_Products__c.object
<CustomObject>
    <description>List of Products relevent to a given opportunity</description>
    <fields>
        <fullName>ProductOfOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product applicable to this opportunity</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>R00N30000001Tv8nEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity-Product</label>
    <nameField>
        <displayFormat>OPPR{YY}{MM}-{0000}</displayFormat>
        <label>Opportunity-Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity-Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/lookupFieldTest.cls
public class lookupFieldTest {

    public lookupFieldTest(ApexPages.StandardController controller) {

    }


public opportunity_products__c getlookupFieldTest() 
{
Id id = System.currentPageReference().getParameters().get('id'); 
return id == null ? new opportunity_products__c() : [SELECT Id,productofopportunity__r.recordtype.name FROM opportunity_products__c WHERE productofopportunity__r.recordtype.name like'DPT%'];  

//String lookupParam = ApexPages.currentPage().getParameters().get('lookup');
//String Qry = 'select id from opportunity_products__c where' + lookupParam + '!=null';
//List<opportunity_products__c> P = Database.Query(Qry); 
  // return P;
    }
}