DuPont DevSB/src/objects/Opportunity_Products__c.object
<CustomObject>
    <description>List of Products relevent to a given opportunity</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Name of the opportunity this Product is applicable to</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductOfOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product applicable to this opportunity</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>R00N30000001Tv8nEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity-Product</label>
    <nameField>
        <displayFormat>OPPR{YY}{MM}-{0000}</displayFormat>
        <label>Opportunity-Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity-Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/MyControll.cls
public class MyControll {
//private final opportunity_products__c ops; //1-16-17 commented by OrgSplit project since the references were commented in the below code
opportunity opp;
public id nam{get;set;}
public MyControll() {
opp=[select id, name from opportunity where id =:ApexPages.currentPage().getParameters().get('id')];
//nam=name;
//ops = [select id,ProductOfOpportunity__c,opportunity__c,name from opportunity_products__c where opportunity__c =
//:opp.name];
}
public MyControll(id name)
{
nam=name;
system.debug(nam);
}
public mycontroll getmycontroll() 
{ 
id n;
//n=ops.ProductOfOpportunity__c;
n=opp.id;
return new mycontroll(n);
}
public PageReference save() {
update opp;
return null;
}
}