DuPont DevSB/src/objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Document Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/SiteObject__c.object
<CustomObject>
    <description>This abstract object is a site element that could be one of many types (i.e. subscription center, subscription list, form, subform, formfield, call script)</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>for subscription List the ExternalId = (OrgId+CampaignId)</description>
        <externalId>true</externalId>
        <inlineHelpText>System Unique identifier for OrgId+CampaignId</inlineHelpText>
        <label>ExternalId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsPublic__c</fullName>
        <defaultValue>true</defaultValue>
        <description>TRUE if this Site Object can be publicly displayed externally (e.g. a Subscription Center)</description>
        <inlineHelpText>TRUE if this Site Object can be publicly displayed externally (e.g. a Subscription Center)</inlineHelpText>
        <label>IsPublic</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NewRecordOwnerId__c</fullName>
        <description>User or Queue Id of Owner</description>
        <inlineHelpText>User or Queue Id of Owner</inlineHelpText>
        <label>New Record OwnerId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewRecordTypeId__c</fullName>
        <description>RecordType Id used for new records created from this SiteObject (e.g. New Leads in a Subscription Center)
Supported Site Object Types: Subscription Center&quot;</description>
        <inlineHelpText>RecordType Id used for new records created from this SiteObject (e.g. New Leads in a Subscription Center)</inlineHelpText>
        <label>New Record TypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PublicDescription__c</fullName>
        <description>Short description visible to external audience</description>
        <inlineHelpText>Short description visible to external audience</inlineHelpText>
        <label>Public Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PublicName__c</fullName>
        <description>Default Public name for this Site Object</description>
        <inlineHelpText>Default Public name for this Site Object</inlineHelpText>
        <label>Public Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReturnUrl__c</fullName>
        <description>used for Subscription centers and is used as the redirect when after center update is submitted</description>
        <inlineHelpText>URL displayed after the successful completion of a Site Submit in this Site Object</inlineHelpText>
        <label>ReturnUrl</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>SubForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used in the Center to indicate the Subform to use for both MyProfile and &apos;this is not my email&apos;</description>
        <inlineHelpText>Used in the Center to indicate the Subform to use for both MyProfile and &apos;this is not my email&apos;</inlineHelpText>
        <label>SubForm</label>
        <referenceTo>SiteObject__c</referenceTo>
        <relationshipLabel>Centers using this Subform</relationshipLabel>
        <relationshipName>Site_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Site Object</description>
        <inlineHelpText>Type of Site Object</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call Script</fullName>
                </value>
                <value>
                    <fullName>CLS Translation</fullName>
                </value>
                <value>
                    <fullName>Customer Portal</fullName>
                </value>
                <value>
                    <fullName>Form</fullName>
                </value>
                <value>
                    <fullName>Lead Field</fullName>
                </value>
                <value>
                    <fullName>Lead SubForm</fullName>
                </value>
                <value>
                    <fullName>Partner Portal</fullName>
                </value>
                <value>
                    <fullName>SiteScript</fullName>
                </value>
                <value>
                    <fullName>SiteScript with Attachment</fullName>
                </value>
                <value>
                    <fullName>Subscription Center</fullName>
                </value>
                <value>
                    <fullName>Subscription List</fullName>
                </value>
                <value>
                    <fullName>Translation Label</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Site Object</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Objects</pluralLabel>
    <recordTypes>
        <fullName>SubForm</fullName>
        <active>true</active>
        <label>SubForm</label>
    </recordTypes>
    <recordTypes>
        <fullName>Translation</fullName>
        <active>true</active>
        <description>Translation of the Public Name and Description</description>
        <label>Translation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/SiteObjectItem__c.object
<CustomObject>
    <description>Shows the relationship between SiteObjects and the ability to override the name and description based on language</description>
    <fields>
        <fullName>ChildSiteObject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related List</label>
        <referenceTo>SiteObject__c</referenceTo>
        <relationshipLabel>Centers</relationshipLabel>
        <relationshipName>Centers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DescriptionOverride__c</fullName>
        <label>Description Override</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FormField__c</fullName>
        <description>Form Field to use</description>
        <label>Form Field</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead.Salutation</fullName>
                </value>
                <value>
                    <fullName>Lead.FirstName</fullName>
                </value>
                <value>
                    <fullName>Lead.LastName</fullName>
                </value>
                <value>
                    <fullName>Lead.Email</fullName>
                </value>
                <value>
                    <fullName>Lead.Phone</fullName>
                </value>
                <value>
                    <fullName>Lead.Company</fullName>
                </value>
                <value>
                    <fullName>Lead.Lead_Country__c</fullName>
                </value>
                <value>
                    <fullName>SiteField__c.Country__c</fullName>
                </value>
                <value>
                    <fullName>SiteField__c.Role1__c</fullName>
                </value>
                <value>
                    <fullName>SiteField__c.Role2__c</fullName>
                </value>
                <value>
                    <fullName>SiteField__c.Role3__c</fullName>
                </value>
                <value>
                    <fullName>SiteField__c.Role4__c</fullName>
                </value>
                <value>
                    <fullName>SiteField__c.Role5__c</fullName>
                </value>
                <value>
                    <fullName>SiteField__c.Role6__c</fullName>
                </value>
                <value>
                    <fullName>SiteField__c.Role7__c</fullName>
                </value>
                <value>
                    <fullName>SiteField__c.Role8__c</fullName>
                </value>
                <value>
                    <fullName>SiteField__c.Role9__c</fullName>
                </value>
                <value>
                    <fullName>SiteField__c.Role10__c</fullName>
                </value>
                <value>
                    <fullName>SiteField__c.PrivacyInquiryType__c</fullName>
                </value>
                <value>
                    <fullName>Lead.Street</fullName>
                </value>
                <value>
                    <fullName>Lead.State</fullName>
                </value>
                <value>
                    <fullName>Lead.City</fullName>
                </value>
                <value>
                    <fullName>Lead.PostalCode</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>nl</fullName>
                </value>
                <value>
                    <fullName>es</fullName>
                </value>
                <value>
                    <fullName>it</fullName>
                </value>
                <value>
                    <fullName>bg</fullName>
                </value>
                <value>
                    <fullName>zh</fullName>
                </value>
                <value>
                    <fullName>cs</fullName>
                </value>
                <value>
                    <fullName>dk</fullName>
                </value>
                <value>
                    <fullName>fi</fullName>
                </value>
                <value>
                    <fullName>hu</fullName>
                </value>
                <value>
                    <fullName>ja</fullName>
                </value>
                <value>
                    <fullName>ko</fullName>
                </value>
                <value>
                    <fullName>no</fullName>
                </value>
                <value>
                    <fullName>pl</fullName>
                </value>
                <value>
                    <fullName>pt</fullName>
                </value>
                <value>
                    <fullName>ro</fullName>
                </value>
                <value>
                    <fullName>ru</fullName>
                </value>
                <value>
                    <fullName>sv</fullName>
                </value>
                <value>
                    <fullName>tr</fullName>
                </value>
                <value>
                    <fullName>uk</fullName>
                </value>
                <value>
                    <fullName>el</fullName>
                </value>
                <value>
                    <fullName>zh_TW</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NameOverride__c</fullName>
        <label>Name Override</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SiteObject__c</fullName>
        <label>Site Object</label>
        <referenceTo>SiteObject__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>order__c</fullName>
        <label>order</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Site Object Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteObjectItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/SiteBuilder.cls
/*******************************************************************************
Copyright © 2009 DuPont. All rights reserved. 
Author: Thomas Snyder
Email: thomas.snyder@usa.dupont.com, tom@3ddd.com
Description:  helper class for custom Site objects retrival and translation
********************************************************************************/


public class SiteBuilder {
    	
	public static final string RTYPE_SO_CENTER					= Rtype.getIdByName('SiteObject__c','Subscription Center');
	public static final string RTYPE_SO_SUBFORM					= Rtype.getIdByName('SiteObject__c','SubForm');	
	public static final string RTYPE_SO_LIST					= Rtype.getIdByName('SiteObject__c','Subscriber List');
	public static final string RTYPE_SOI_CENTERITEM				= Rtype.getIdByName('SiteObjectItem__c','Center Item');
	public static final string RTYPE_SOI_FORMFIELD				= Rtype.getIdByName('SiteObjectItem__c','Form Field');
	public static final string RTYPE_SOI_TRANSLATION			= Rtype.getIdByName('SiteObjectItem__c','Translation Item'); 

	//public static final string DEFAULT_SUBFORM 					= 'a1qQ000000000pb'; //TEST5 
	 public static final string DEFAULT_SUBFORM 					= 'a1q300000004DOD'; //PROD
/////////////////////////////////////////////////////////////////////////////////////////////////////////// 
    
    public static SiteObject__c getSiteObject(string ObjectId) {
        LIST<SiteObject__c> sos = [
            Select Id, Type__c, ReturnUrl__c, PublicName__c, PublicDescription__c, IsPublic__c, 
                Subform__c,  NewRecordOwnerId__c, NewRecordTypeId__c, ExternalId__c
            From SiteObject__c
            where id =: ObjectId
            LIMIT 1
            ];
        
        if (sos.size()>0 )
            return sos[0];
        else
            return null;
    }
/////////////////////////////////////////////////////////////////////////////////////////////////////////// 

    public static SiteObject__c getSiteObjectAndItems(string siteObjectId, string ObjRType, string ItemRType, string isolang) {
            /////////////////////////////////////////////////////////////////////////////////////////
            //  Get the SiteObject And Items
            /////////////////////////////////////////////////////////////////////////////////////////
            LIST<SiteObject__c> sos = [
                Select Id, Type__c, ReturnUrl__c, PublicName__c, PublicDescription__c, IsPublic__c, 
                    Subform__c,  NewRecordOwnerId__c, NewRecordTypeId__c,
                    (   Select Id, IsRequired__c, order__c, Language__c, FormField__c, 
                            ChildSiteObject__c, ChildSiteObject__r.ExternalId__c, ChildSiteObject__r.PublicName__c, 
                            ChildSiteObject__r.PublicDescription__c
                        from Items__r   
                        where recordtypeid =: ItemRType 
                            AND (ChildSiteObject__c = null OR ChildSiteObject__r.IsPublic__c=true)
                        order by order__c
                    )
                From SiteObject__c
                where id =: siteObjectId AND recordtypeid =:ObjRType
                LIMIT 1
                ];
            
            if (sos.size()>0 ) {
                SiteObject__c siteObject=sos[0];    
                translateSiteObjectAndItems(siteObject,isolang);
                return siteObject;
            }
            else
                return null;
            
    }
/////////////////////////////////////////////////////////////////////////////////////////////////////////// 
    public static void translateSiteObjectAndItems(SiteObject__c siteObject, string isolang) {

                MAP<id,SiteObject__c> mapSiteObjs = new MAP<id,SiteObject__c>();
                //add Parent Item
                mapSiteObjs.put(siteObject.id, siteObject);
                
                //add Child items (if any) 
                try {
	                for (SiteObjectItem__c soi : siteObject.Items__r ) {
	                    if (soi.ChildSiteObject__c != null)
	                        mapSiteObjs.put(soi.ChildSiteObject__c, soi.ChildSiteObject__r);
	                }
                }
                catch (exception ex) {
                	//TRAP  when siteObject.Items__r is not in the SOQL select 
                	// 	IF(siteObject.Items__r !=null) ... does not work for this.
                }
                
                if (mapSiteObjs.size()>0)
                    translateSiteObjects(mapSiteObjs, isolang);


    }
/////////////////////////////////////////////////////////////////////////////////////////////////////////// 
    public static void translateSiteObjects(MAP<id,SiteObject__c> mapSiteObjs, string isolang) {
                
                /////////////////////////////////////////////////////////////////////////////////////////
                //  Get the translations
                /////////////////////////////////////////////////////////////////////////////////////////           
                MAP<Id,SiteObjectItem__c> translation = new MAP<Id,SiteObjectItem__c>();
                for (SiteObjectItem__c soi : [
                        Select SiteObject__c, NameOverride__c, DescriptionOverride__c 
                        from SiteObjectItem__c
                        where ( SiteObject__c in : mapSiteObjs.keySet() )
                        AND recordtypeid =: RTYPE_SOI_TRANSLATION
                        AND language__c =:isolang
                        ]) 
                    translation.put(soi.SiteObject__c, soi);
                 
                 if (translation.size()>0) { 
                    system.debug('Translation: '+translation);
                
	                for ( SiteObject__c so : mapSiteObjs.values()) {
	                    if (so.id!=null && translation.containsKey(so.id)) {
	                    	SiteObjectItem__c soi_tran = translation.get(so.id);
	                    	if (soi_tran!=null) {
	                        	if (soi_tran.NameOverride__c      != null)        so.PublicName__c=soi_tran.NameOverride__c;
	                        	if (soi_tran.DescriptionOverride__c  != null)     so.PublicDescription__c=soi_tran.DescriptionOverride__c;
	                    	}
	                    }
	                }
                 }
        
    }

/////////////////////////////////////////////////////////////////////////////////////////////////////////// 
//	TEST SCripts and helpers

////////////////////////////////////////////////////////////////////////////////////////////////////

public static string testAddSubform() {
		SiteObject__c sf = new SiteObject__c(name='subform1', recordTypeid=RTYPE_SO_SUBFORM, publicname__c='subform1');	
		insert sf;
		LIST<SiteObjectItem__c> flds = new LIST<SiteObjectItem__c>();
		for (Schema.PicklistEntry plst : SiteObjectItem__c.FormField__c.getDescribe().getPicklistValues() )
			if (plst.IsActive()) 
				flds.add( new SiteObjectItem__c(SiteObject__c=sf.id, IsRequired__c=true, FormField__c=plst.getValue(), recordtypeid=RTYPE_SOI_FORMFIELD));
		insert flds;
		return sf.id;
}


////////////////////////////////////////////////////////////////////////////////////
//		Test script(s)
////////////////////////////////////////////////////////////////////////////////////

	public static testMethod void test_SiteBuilder() {
		SubscriptionCenter.TESTMODE=true;
		string formid=testAddSubform();
		//add translation
		insert new SiteObjectItem__c(SiteObject__c=formid, language__c='fr', recordtypeid=RTYPE_SOI_TRANSLATION, NameOverride__c='dfdasfsdf', DescriptionOverride__c='dfdasfsdf');

		system.debug('---getSiteObjectAndItems:----->'+getSiteObjectAndItems(formid, RTYPE_SO_SUBFORM, RTYPE_SOI_FORMFIELD, 'fr'));
		system.debug('---getSiteObject:----->'+getSiteObject(formid));	
		system.debug('---getSiteObject:bogus----->'+getSiteObject('bog000000000011'));
		system.debug('---getSiteObjectAndItems:bogus----->'+getSiteObjectAndItems('bog000000000011',RTYPE_SO_SUBFORM, RTYPE_SOI_FORMFIELD, 'en'));
	}


}