DuPont DevSB/src/objects/Qualification__c.object
<CustomObject>
    <description>List of current or past Qualifications and Certifications of this Partner or Account</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Name of the account this Qualification is about</description>
        <inlineHelpText>Name of the account this Qualification is about</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N30000001rblYEAQ</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Qualification</label>
    <nameField>
        <displayFormat>QL{YY}{MM}-{0000}</displayFormat>
        <label>Qualification Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/Qualification_Base.cls
/*******************************************************************************
Copyright © 2011 DuPont. All rights reserved. 
Author: Sreedhar Jagannath
Email: sreedhar.jagannath@ind.dupont.com
Description:  Utility class to check whether user has access on Qualification Record
********************************************************************************/


public with sharing class Qualification_Base {        
    public static boolean hasVisibility(Id qualificationId){          
        boolean rtn=false; 

       try {           
            Qualification__c q=[Select name,account_name__c from Qualification__c where id=:qualificationId];                  
            return true;     
        }  catch(Exception ex){
            return rtn; 
                
        }          
                       
    }  
    
}