DuPont DevSB/src/objects/Rule__c.object
<CustomObject>
    <description>Contains record type specific rules which will return a score, approver or other values based on a criteria</description>
    <fields>
        <fullName>Geo_Region__c</fullName>
        <description>This custom field is used to select the region of the Rule object .</description>
        <label>Geo Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>The checkbox will allow users to control active/inactive rule and manage the rules better.</description>
        <inlineHelpText>Uncheck to make the rule inactive</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Owning_Organization__c</fullName>
        <description>The DuPont organization that owns this record, should be a combination of the accepted abbreviations of SBU(Strategic Business Unit)-BU(Business Unit)-SubBU(Business or Product Line)</description>
        <label>Owning Organization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AGCP</fullName>
                </value>
                <value>
                    <fullName>AGCP-CPC</fullName>
                </value>
                <value>
                    <fullName>AGNH</fullName>
                </value>
                <value>
                    <fullName>AGNH-COZR</fullName>
                </value>
                <value>
                    <fullName>AGNH-Qualicon</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-Carpet Backing</fullName>
                </value>
                <value>
                    <fullName>BI-Env</fullName>
                </value>
                <value>
                    <fullName>BI-Fire Safety</fullName>
                </value>
                <value>
                    <fullName>BI-Landscape Systems</fullName>
                </value>
                <value>
                    <fullName>BI-Surf</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>CORP-Admin General</fullName>
                </value>
                <value>
                    <fullName>CORP-Core</fullName>
                </value>
                <value>
                    <fullName>CORP-Corporate Plans</fullName>
                </value>
                <value>
                    <fullName>CORP-Non-Aligned</fullName>
                </value>
                <value>
                    <fullName>CORS</fullName>
                </value>
                <value>
                    <fullName>CORS-Aviation</fullName>
                </value>
                <value>
                    <fullName>CORS-Corp Remediation</fullName>
                </value>
                <value>
                    <fullName>CORS-Government Affairs</fullName>
                </value>
                <value>
                    <fullName>CORS-Public Affairs</fullName>
                </value>
                <value>
                    <fullName>CR&amp;D</fullName>
                </value>
                <value>
                    <fullName>DA-Nano LLC</fullName>
                </value>
                <value>
                    <fullName>DCF</fullName>
                </value>
                <value>
                    <fullName>DCF ChemSol</fullName>
                </value>
                <value>
                    <fullName>DCF ChemSol-Aniline</fullName>
                </value>
                <value>
                    <fullName>DCF ChemSol-C&amp;D</fullName>
                </value>
                <value>
                    <fullName>DCF ChemSol-C&amp;D-DAHS</fullName>
                </value>
                <value>
                    <fullName>DCF ChemSol-C&amp;D-DWT</fullName>
                </value>
                <value>
                    <fullName>DCF ChemSol-C&amp;D-Industrial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Range__c</fullName>
        <description>Stores the range of  scores and corresponding grades to that scores.</description>
        <label>Range</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <description>This custom field contains the record Type Name.</description>
        <label>Rule Record Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Type__c</fullName>
        <description>For capturing the application where the rule will be used</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dynamic Approval</fullName>
                </value>
                <value>
                    <fullName>Scoring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sobject_Type__c</fullName>
        <description>This custom field is used to recognize the type of SObject.</description>
        <label>Sobject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Write_To__c</fullName>
        <description>The field in the Sobject to which the calculated score has to be written.</description>
        <label>Write To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Rule_Item__c.object
<CustomObject>
    <description>Rule Items is child record of rule with specific field level criteria</description>
    <fields>
        <fullName>Field_API__c</fullName>
        <description>object.FieldAPI Name ex:Lead.Influence_Type__c</description>
        <label>Field API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>The checkbox will allow users to control active/inactive ruleitems and manage the ruleitems better.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <description>This field is used for selecting the operator Type.</description>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>contains</fullName>
                </value>
                <value>
                    <fullName>equals</fullName>
                </value>
                <value>
                    <fullName>excludes</fullName>
                </value>
                <value>
                    <fullName>greaterOrEqual</fullName>
                </value>
                <value>
                    <fullName>greaterThan</fullName>
                </value>
                <value>
                    <fullName>includes</fullName>
                </value>
                <value>
                    <fullName>lessOrEqual</fullName>
                </value>
                <value>
                    <fullName>lessThan</fullName>
                </value>
                <value>
                    <fullName>notContain</fullName>
                </value>
                <value>
                    <fullName>notEquals</fullName>
                </value>
                <value>
                    <fullName>startsWith</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rule__c</fullName>
        <description>This is the Rule Item and the Rule Object master detail relationship field.</description>
        <label>Rule</label>
        <referenceTo>Rule__c</referenceTo>
        <relationshipLabel>Rule Items</relationshipLabel>
        <relationshipName>Rule_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>The return score for application</description>
        <label>Score</label>
        <precision>5</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>The field picklist value to be compared</description>
        <inlineHelpText>The picklist value to be compared with. Note the value has to be exactly same as the one in the field&apos;s picklist</inlineHelpText>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Rule Item</label>
    <nameField>
        <label>Rule Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/RulesEngine.cls
/*******************************************************************************
Copyright © 2013 DuPont. All rights reserved. 
Author: Thomas Snyder, Ankit Gupta
Email: thomas.snyder@usa.dupont.com, tom@3ddd.com, Ankit.Gupta@usa.dupont.com
Description : This apex class contains the logic to identify the EvalResults and the 
              corresponding rules for the particular ruleType .
********************************************************************************/
public with sharing class RulesEngine {

    public static Results getResults(LIST<sObject> sobjects){
        if (sobjects.size()>0) {
            string sobjectType=String.valueOf(sobjects[0].getSObjectType());
            return  getResults(sobjects,sobjectType);
        }
        return new Results();
    }   
    
    
    public static Results getResults(LIST<sObject> sobjects,String soType) { 
         Results rtn=new Results();
         
        try{ 
            //Get all the rules for this soType  
            Map<Id,Rule__c> mapRules = new Map<Id,Rule__c>([
                SELECT id,sobject_type__c,range__c,geo_region__c,rule_type__c,Record_Type__c,Write_To__c,Owning_organization__c,
                (SELECT id,Field_API__c,score__c,value__c,Operator__c from Rule_Items__r ri where ri.IsActive__c= true)
                FROM rule__c r WHERE r.Sobject_Type__c=:soType AND r.IsActive__c = true]);
            
            Rtype.SObjectRTypes orts = new Rtype.SObjectRTypes(sOType);
            
            //TODO: preprocess sobject records to pull in fields from foreign relations
                                
            //loop through sobjs in batch
            for(Sobject sobj : sobjects){               
                EvalResults soEvalResults = new EvalResults(); 
                soEvalResults.record=sobj;        
                string myRT=orts.IdToDevName(String.valueOf(sobj.get('recordTypeId')));
                
                //loop through rules          
                for(Rule__c rule : mapRules.values()){                  
                    if ((rule.geo_region__c ==null || sobj.get('region__c')== rule.geo_region__c ) && 
                        (myRT == rule.record_Type__c || rule.record_Type__c==null ) 
                        && (rule.Owning_organization__c==null || sobj.get('Owning_organization__c')== rule.Owning_organization__c)){ 
                       RuleResult ruleRes=executeRule(rule,sobj);
                       soEvalResults.rules.put(ruleRes.rule.Id,ruleRes); 
                    }
                } //next rule
                
                
                //dont add sobj mapping if no rules
                if  (soEvalResults.rules.size()>0)
                    rtn.mapResults.put(sobj,soEvalResults);
            
            } //next sobj     
        }
        catch(Exception e){
            e.setMessage('capture Exception ');
        }      
        return rtn;
    }
    
    
    //////////////////////////////////////////////////////////////////////////////////////////////
    // determine which rule engine to run  (based on Rule.rule_type__c)
    //  this gives us ability to write new optimized rules without effecting existing code
    //////////////////////////////////////////////////////////////////////////////////////////////
    public static RuleResult executeRule(Rule__c inRule,Sobject sobj) {   //1rule,1sobj
        RuleResult rtn=new RuleResult();
            
        if( inRule.rule_type__c == 'scoring' ){       
            rtn = ScoringEngine.execute(inRule,sobj);       
        }
        if( inRule.rule_type__c == 'scoring2' ){          
            //rtn = ScoringEngine2.execute(inRule,sobj);          
        }
        //add you new rules engines here....
        
        
        //else if( inRule.rule_type__c == 'superfastboolean' ) {        
        //  exampleEngine.execute(inRule,sobj); 
        //}
        return rtn;

     } 
     
    //////////////////////////////////////////////////////////////////////////////////////////////
    //  Inner Classes
    //////////////////////////////////////////////////////////////////////////////////////////////
        
     //many sobj,many rules   
     public class Results{  
        public MAP<sobject,EvalResults> mapResults;   
        public Results() {
            mapResults=new MAP<sobject,EvalResults>();
        }
    } 
    //////////////////////////////////////////////////////////////////////////////////////////////
    //1 sobj,many rules
    public class EvalResults{  
        
            public sobject record;
            public  MAP<Id, RuleResult> rules;  
            EvalResults() {
                rules = new MAP<Id, RuleResult>();
            }
    } 
    
    ////////////////////////////////////////////////////////////////////////////////////////////// 
    //1 sobj,1 rules  
    public class RuleResult {
      public Rule__c Rule;
      public String result;
      public String rating {
      get{
          String rtng;      
          List<Integer> listNum=new List<integer>();
          List<String> listAlpha=new List<String>();

          for(String str : rule.Range__c.split('&')){
            String[] tmp=str.split('=');
            listNum.add(Integer.valueof(tmp[0]));
            listAlpha.add(tmp[1]);      
          }       
       
           for(Integer k=0;k<listNum.size();k++){ 
             if(Decimal.valueof(result) >= listNum.get(k)){ 
                rtng=listAlpha.get(k); 
                break;
             }
          }      
          return rtng;
       } 
      }
    }
        
}