DuPont DevSB/src/objects/Rule__c.object
<CustomObject>
    <description>Contains record type specific rules which will return a score, approver or other values based on a criteria</description>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DuPont DevSB/src/objects/Rule_Item__c.object
<CustomObject>
    <description>Rule Items is child record of rule with specific field level criteria</description>
    <fields>
        <fullName>Field_API__c</fullName>
        <description>object.FieldAPI Name ex:Lead.Influence_Type__c</description>
        <label>Field API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <description>This field is used for selecting the operator Type.</description>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>contains</fullName>
                </value>
                <value>
                    <fullName>equals</fullName>
                </value>
                <value>
                    <fullName>excludes</fullName>
                </value>
                <value>
                    <fullName>greaterOrEqual</fullName>
                </value>
                <value>
                    <fullName>greaterThan</fullName>
                </value>
                <value>
                    <fullName>includes</fullName>
                </value>
                <value>
                    <fullName>lessOrEqual</fullName>
                </value>
                <value>
                    <fullName>lessThan</fullName>
                </value>
                <value>
                    <fullName>notContain</fullName>
                </value>
                <value>
                    <fullName>notEquals</fullName>
                </value>
                <value>
                    <fullName>startsWith</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rule__c</fullName>
        <description>This is the Rule Item and the Rule Object master detail relationship field.</description>
        <label>Rule</label>
        <referenceTo>Rule__c</referenceTo>
        <relationshipLabel>Rule Items</relationshipLabel>
        <relationshipName>Rule_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>The return score for application</description>
        <label>Score</label>
        <precision>5</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>The field picklist value to be compared</description>
        <inlineHelpText>The picklist value to be compared with. Note the value has to be exactly same as the one in the field&apos;s picklist</inlineHelpText>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Rule Item</label>
    <nameField>
        <label>Rule Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/ScoringEngine.cls
/********************************************************************************************
Created By : Ankit Gupta<Ankit.Gupta@usa.dupont.com>
Created Date : 2012/9/3
Last Modified Date: 2013/03/15
Description : This controller class contains the logic to rate and calculate the total score
        the objects based on the Rule and Rule Item .
        
TES20130208 some cleanup and refactor for use with RulesEngine, no change in logic.
TES20130311 re-wrote rules engine so it can be used for multi-recordtypes, objects and later
  enhanced for diff field datatypes and/or operations   
*********************************************************************************************/
public with sharing class ScoringEngine {
   
  public static RulesEngine.RuleResult execute(Rule__c rule,Sobject sobj){ 

      RulesEngine.RuleResult rtn=new RulesEngine.RuleResult();   
      decimal totalScore=0;
      rtn.Rule=rule;   

      //get Describe   
      Util.Describe descr = Util.getDescribe(sobj);   
      
      //loop through rule items
      for(Rule_Item__c ruleItem : rule.rule_items__r) {
        
        Schema.DescribeFieldResult dfr = descr.FieldInfo(ruleItem.Field_API__c);
        if (dfr!=null) {
          
          Schema.SOAPtype soapType=dfr.getSOAPType();
          Schema.Displaytype displayType=dfr.getType();
          
           if (soapType == Schema.Soaptype.STRING) {
             String val=String.valueOf(sobj.get(dfr.getName()));
             if (val==null) {
               if (ruleItem.value__c==null)
                 totalScore+=ruleItem.score__c;
             }
            else {
              if (displayType == Schema.Displaytype.MultiPicklist) {
                //only equal is supported for Muti-picks
                SET<string> arr = new SET<string>();
                arr.addAll(val.split(';'));
                if (arr.contains(ruleItem.value__c))
                  totalScore+=ruleItem.score__c;
              }
               else {
                 if (ruleItem.operator__c=='equals') {
                   if (val==ruleItem.value__c)
                     totalScore+=ruleItem.score__c;
                 }
                 else if (ruleItem.operator__c=='contains') {
                   SET<string> arr = new SET<string>();
                  arr.addAll(ruleItem.value__c.split(';'));
                   if (arr.contains(val))
                    totalScore+=ruleItem.score__c;
                 }
               }
             }
          } //Schema.Soaptype.STRING
          
          //else if (soapType == Schema.Soaptype.INTEGER  ) ...
          //else if (soapType == Schema.Soaptype.DATETIME ) ...
          //else if (soapType == Schema.Soaptype.DATE   ) ...
          //else if (soapType == Schema.Soaptype.BOOLEAN  ) ...
          
        }//valid DFR          
      } //next  ruleItem
      rtn.result=String.valueof(totalScore);
      
    return rtn;
  }
  

 }