DuPont DevSB/src/objects/SpamPattern__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Editable list of spam patterns</description>
    <fields>
        <fullName>regex__c</fullName>
        <description>String regular expression pattern</description>
        <label>regex</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SpamPattern</label>
</CustomObject>

DuPont DevSB/src/classes/Spam.cls
public class Spam
{

Map<string, SpamPattern__c> spamwords;

public Spam()
{
    spamwords = SpamPattern__c.getAll();
    for (string w : spamwords.keySet()) {
        System.debug('SPAMWORD: ' + spamwords.get(w).regex__c);
    }
}

public boolean isSpam(String txt)
{
    boolean spam_status=false;
    for (string w : spamwords.keySet()) {
        if (Pattern.matches(spamwords.get(w).regex__c,txt.toUpperCase())) {spam_status=true;}
    }
    return spam_status;
}
/*--
public static testMethod void testSpam(){
    Spam spm = new Spam();
    String test='href';
    spm.isSpam(test);
}
*/
}