DuPont DevSB/src/objects/Threat_Master__c.object
<CustomObject>
    <fields>
        <fullName>Angle_NBT__c</fullName>
        <label>Angle_NBT</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Straight</fullName>
                </value>
                <value>
                    <fullName>Left</fullName>
                </value>
                <value>
                    <fullName>Right</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Angled_Shot__c</fullName>
        <label>Angled Shot</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>-60</fullName>
                </value>
                <value>
                    <fullName>-45</fullName>
                </value>
                <value>
                    <fullName>-30</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Energy_Level_Joule_NBT__c</fullName>
        <label>Energy Level Joule NBT</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>33</fullName>
                </value>
                <value>
                    <fullName>36</fullName>
                </value>
                <value>
                    <fullName>43</fullName>
                </value>
                <value>
                    <fullName>50</fullName>
                </value>
                <value>
                    <fullName>65</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Energy_Level_NBT__c</fullName>
        <label>Energy Level NBT</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>E1</fullName>
                </value>
                <value>
                    <fullName>E2</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_Of_Stabs__c</fullName>
        <label>No. Of Stabs</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_shots__c</fullName>
        <label>Number of shots</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Penetration_Allowed__c</fullName>
        <label>Penetration Allowed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shooting_Mechnism__c</fullName>
        <label>Shooting Mechnism</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Barrel</fullName>
                </value>
                <value>
                    <fullName>Weapon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shot_Locations__c</fullName>
        <label>Shot  Locations</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NIJ 0101.04</fullName>
                </value>
                <value>
                    <fullName>NIJ 0101.06</fullName>
                </value>
                <value>
                    <fullName>NIJ 0115.00</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stab_Location__c</fullName>
        <label>Stab Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NIJ 0101.04</fullName>
                </value>
                <value>
                    <fullName>NIJ 0101.06</fullName>
                </value>
                <value>
                    <fullName>NIJ 0115.00</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Standard__c</fullName>
        <label>Test Standard</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NIJ 0101.04</fullName>
                </value>
                <value>
                    <fullName>NIJ 0101.06</fullName>
                </value>
                <value>
                    <fullName>TR 03/2008: Rev 10/2008</fullName>
                </value>
                <value>
                    <fullName>German Schutzklasse Oct 2008</fullName>
                </value>
                <value>
                    <fullName>CEN prEN ISO 148763/74</fullName>
                </value>
                <value>
                    <fullName>HP White Protoco</fullName>
                </value>
                <value>
                    <fullName>HOSDB 2007</fullName>
                </value>
                <value>
                    <fullName>Russia GOST R 50744-95</fullName>
                </value>
                <value>
                    <fullName>China GA 68</fullName>
                </value>
                <value>
                    <fullName>China GA 141</fullName>
                </value>
                <value>
                    <fullName>China GA 293</fullName>
                </value>
                <value>
                    <fullName>US MIL Standard</fullName>
                </value>
                <value>
                    <fullName>NIJ 0115.00</fullName>
                </value>
                <value>
                    <fullName>STANG 2911</fullName>
                </value>
                <value>
                    <fullName>STANAG 4296</fullName>
                </value>
                <value>
                    <fullName>STANAG 2920</fullName>
                </value>
                <value>
                    <fullName>US MIL 662E</fullName>
                </value>
                <value>
                    <fullName>Impact Test – DIN 4840</fullName>
                </value>
                <value>
                    <fullName>Impact Test – EN 397</fullName>
                </value>
                <value>
                    <fullName>VAPM BSW &amp; VAPM APR 2006: Stand 14-05-2009</fullName>
                </value>
                <value>
                    <fullName>VAPM KDIW 04 &amp; APR 06: Stand 14-05-2009</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Threat_Level__c</fullName>
        <label>Threat Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>KR1</fullName>
                </value>
                <value>
                    <fullName>KR2</fullName>
                </value>
                <value>
                    <fullName>KR3</fullName>
                </value>
                <value>
                    <fullName>W1</fullName>
                </value>
                <value>
                    <fullName>W2</fullName>
                </value>
                <value>
                    <fullName>W3</fullName>
                </value>
                <value>
                    <fullName>W4</fullName>
                </value>
                <value>
                    <fullName>W5</fullName>
                </value>
                <value>
                    <fullName>SP1</fullName>
                </value>
                <value>
                    <fullName>SP2</fullName>
                </value>
                <value>
                    <fullName>SP3</fullName>
                </value>
                <value>
                    <fullName>I1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>V50__c</fullName>
        <label>V50</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Velocity_V50__c</fullName>
        <label>Velocity_V50</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1002</fullName>
                </value>
                <value>
                    <fullName>1023</fullName>
                </value>
                <value>
                    <fullName>1081</fullName>
                </value>
                <value>
                    <fullName>1095</fullName>
                </value>
                <value>
                    <fullName>1384</fullName>
                </value>
                <value>
                    <fullName>325</fullName>
                </value>
                <value>
                    <fullName>347</fullName>
                </value>
                <value>
                    <fullName>350</fullName>
                </value>
                <value>
                    <fullName>354</fullName>
                </value>
                <value>
                    <fullName>375</fullName>
                </value>
                <value>
                    <fullName>387</fullName>
                </value>
                <value>
                    <fullName>396</fullName>
                </value>
                <value>
                    <fullName>402</fullName>
                </value>
                <value>
                    <fullName>404</fullName>
                </value>
                <value>
                    <fullName>410</fullName>
                </value>
                <value>
                    <fullName>429</fullName>
                </value>
                <value>
                    <fullName>438</fullName>
                </value>
                <value>
                    <fullName>440</fullName>
                </value>
                <value>
                    <fullName>446</fullName>
                </value>
                <value>
                    <fullName>451</fullName>
                </value>
                <value>
                    <fullName>457</fullName>
                </value>
                <value>
                    <fullName>473</fullName>
                </value>
                <value>
                    <fullName>480</fullName>
                </value>
                <value>
                    <fullName>484</fullName>
                </value>
                <value>
                    <fullName>490</fullName>
                </value>
                <value>
                    <fullName>493</fullName>
                </value>
                <value>
                    <fullName>495</fullName>
                </value>
                <value>
                    <fullName>506</fullName>
                </value>
                <value>
                    <fullName>528</fullName>
                </value>
                <value>
                    <fullName>567</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BA Threat Master</label>
    <nameField>
        <label>Threat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Threats Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DuPont DevSB/src/classes/CtrlThreatDropdownService.cls
/*******************************************************************************
(C)2016
Author: krishnaveni duggaraju
Email: krishnaveni.duggaraju@tcs.com
Description:  This class returns the Threatsdropdown values for BA Threats Master.
 ********************************************************************************/
@RestResource(urlMapping = '/ThreatDefaultDropdowns/*')
global class CtrlThreatDropdownService{
 
@HttpPost
global static CtrlKevlarSvcHelper.ReturnThreatDefaultDropDownClass doPost(){
    CtrlKevlarSvcHelper h = new CtrlKevlarSvcHelper();
    List<String> shotLocation = new List<String>();
    List<String> shootingMechnism = new List<String>();
    List<String> numberOfShots = new List<String>();
    List<String> angledShots = new List<String>();
    List<String> energyLevel = new List<String>();
    List<String> jouleList = new List<String>();
    List<String> permissiblePenetrationList = new List<String>();
    List<String> numberOfStabs = new List<String>();
    List<String> stabLocation = new List<String>();
    List<String> VelocityV50= new List<String>();
    List<String> angleNBT= new List<String>();
    List<String> FragmentV50= new List<String>();
    List<String> TestStandard= new List<String>();
    List<String> threatLevel = new List<String>();
       
    List<List<String>> defaultDropdownList = new List<List<String>>();
    RestRequest req = RestContext.request;
    try{   
        system.debug('req.requestBody : ' + req.requestBody.toString());   
        Schema.DescribeFieldResult sl = Threat_Master__c.Shot_Locations__c.getDescribe();    
        List<Schema.PicklistEntry> s = sl.getPicklistValues(); 
        for(Integer i=0;i<s.size();i++)
        {
             shotLocation.add(s[i].getvalue());   
        }
        defaultDropdownList.add(shotLocation);   
        Schema.DescribeFieldResult sm= Threat_Master__c.Shooting_Mechnism__c.getDescribe();    
        List<Schema.PicklistEntry> smValues = sm.getPicklistValues(); 
        for(Integer i=0;i<smValues .size();i++)
        {
             shootingMechnism.add(smValues [i].getvalue());   
        }
        defaultDropdownList.add(shootingMechnism);

        Schema.DescribeFieldResult noOfShots= Threat_Master__c.Number_of_shots__c.getDescribe();    
        List<Schema.PicklistEntry> shotValues = noOfShots.getPicklistValues(); 
        for(Integer i=0;i<shotValues.size();i++)
        {
             numberOfShots.add(shotValues[i].getvalue());   
        }
        
        defaultDropdownList.add(numberOfShots);
        Schema.DescribeFieldResult aShots= Threat_Master__c.Angled_Shot__c.getDescribe();    
        List<Schema.PicklistEntry> asValues = aShots.getPicklistValues(); 
        for(Integer i=0;i<asValues.size();i++)
        {
             angledShots.add(asValues[i].getvalue());   
        }
        
        Schema.DescribeFieldResult eLevel = Threat_Master__c.Energy_Level_NBT__c.getDescribe();    
        List<Schema.PicklistEntry> el = eLevel.getPicklistValues(); 
        for(Integer i=0;i<el.size();i++)
        {
             energyLevel.add(el[i].getvalue());   
        }
        defaultDropdownList.add(energyLevel);   
        Schema.DescribeFieldResult eJoule= Threat_Master__c.Energy_Level_Joule_NBT__c.getDescribe();    
        List<Schema.PicklistEntry> eJouleValues = eJoule.getPicklistValues(); 
        for(Integer i=0;i<eJouleValues .size();i++)
        {
             jouleList.add(eJouleValues[i].getvalue());   
        }
        defaultDropdownList.add(jouleList);

        Schema.DescribeFieldResult penetrationsAllow= Threat_Master__c.Penetration_Allowed__c.getDescribe();    
        List<Schema.PicklistEntry> paValues = penetrationsAllow.getPicklistValues(); 
        for(Integer i=0;i<paValues.size();i++)
        {
             permissiblePenetrationList.add(paValues[i].getvalue());   
        }
        
        defaultDropdownList.add(permissiblePenetrationList);
        
        Schema.DescribeFieldResult noOfStabs= Threat_Master__c.No_Of_Stabs__c.getDescribe();    
        List<Schema.PicklistEntry> nStabs = noOfStabs.getPicklistValues(); 
        for(Integer i=0;i<nStabs.size();i++)
        {
             numberOfStabs.add(nStabs[i].getvalue());   
        }
        
        defaultDropdownList.add(numberOfStabs);
     
     
        Schema.DescribeFieldResult stabLocations= Threat_Master__c.Stab_Location__c.getDescribe();    
        List<Schema.PicklistEntry> stabLoc = stabLocations.getPicklistValues(); 
        for(Integer i=0;i<stabLoc.size();i++)
        {
             stabLocation.add(stabLoc[i].getvalue()); 
        }
        
        defaultDropdownList.add(stabLocation);
        
        Schema.DescribeFieldResult angle_NBT= Threat_Master__c.Angle_NBT__c.getDescribe();    
        List<Schema.PicklistEntry> an = angle_NBT.getPicklistValues(); 
        for(Integer i=0;i<an.size();i++)
        {
             angleNBT.add(an[i].getvalue());   
        }
        defaultDropdownList.add(angleNBT);

       Schema.DescribeFieldResult Velocity_V50= Threat_Master__c.Velocity_V50__c.getDescribe();    
        List<Schema.PicklistEntry> vv = Velocity_V50.getPicklistValues(); 
        for(Integer i=0;i<vv.size();i++)
        {
             VelocityV50.add(vv[i].getvalue());   
        }
        defaultDropdownList.add(VelocityV50);
         
       /*  Schema.DescribeFieldResult Fragment_V50= Threat_Master__c.V50__c.getDescribe();    
        List<Schema.PicklistEntry> fv = Fragment_V50.getPicklistValues(); 
        for(Integer i=0;i<fv.size();i++)
        {
             FragmentV50.add(fv[i].getvalue());   
        }
        defaultDropdownList.add(FragmentV50);
        */
        
        Schema.DescribeFieldResult Test_Standard= Threat_Master__c.Test_Standard__c.getDescribe();    
        List<Schema.PicklistEntry> test = Test_Standard.getPicklistValues(); 
        for(Integer i=0;i<test.size();i++)
        {
             TestStandard.add(test[i].getvalue());   
        }
        defaultDropdownList.add(TestStandard);
        
        
         Schema.DescribeFieldResult threat_Level= Threat_Master__c.Threat_level__c.getDescribe();    
        List<Schema.PicklistEntry> tl = threat_Level.getPicklistValues(); 
        for(Integer i=0;i<tl.size();i++)
        {
             threatLevel.add(tl[i].getvalue());   
        }
        
         if(!defaultDropdownList.isEmpty()){
            return new CtrlKevlarSvcHelper.ReturnThreatDefaultDropDownClass(h.dataSent, h.getMessage('200'),h.getResponseMessage('541'),'541',shotLocation, shootingMechnism, numberOfShots,angledShots,energyLevel, jouleList, permissiblePenetrationList,numberOfStabs,stabLocation,angleNBT,VelocityV50,FragmentV50 ,TestStandard,threatLevel,null, 'No Error');
        }
        else{       
            return new CtrlKevlarSvcHelper.ReturnThreatDefaultDropDownClass(h.dataNotSent, h.getMessage('201'),null,null,null,null,null, null,null,null, null,null,null,null,null,null,null,null,null, '201');
        }   
            
    }
    catch(Exception e){
        System.debug('Error----------'+e.getMessage());
        return new CtrlKevlarSvcHelper.ReturnThreatDefaultDropDownClass(h.dataNotSent, h.getMessage('203'),'Data loading failed!',null,null,null,null,null,null,null,null, null,null,null,null,null,null,null,null, '203');
       
    }           
}
}