DuPont DevSB/src/objects/UserPasswordResetSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Access_Type__c</fullName>
        <label>Access Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Recipient__c</fullName>
        <label>Email Recipient</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Instances_to_skip_Password_reset__c</fullName>
        <description>This field values used in batch class &quot;batchSFARPasswordReset&quot; to skip the password reset requests for that instances.</description>
        <label>Instances to skip Password reset</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>instance__c</fullName>
        <label>instance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>UserPasswordResetSettings</label>
</CustomObject>

DuPont DevSB/src/classes/scheduleBatchSFARPasswordReset_UT.cls
/*************************************************************************************************
Copyright Â© 2016 DuPont. All rights reserved.
Author: Kokkiripalli Vaishnavi
Email: kokkiripalli.vaishnavi@tcs.com
Description: Test class for scheduling Batch Apex for SFAR Password Reset Class
 ********************************************************************************/
@isTest
public class scheduleBatchSFARPasswordReset_UT {
    static testMethod void testschedule() {    
        Test.StartTest();
        
        //KT [11072017]: To create custom setting UserPasswordResetSettings__c data
        UserPasswordResetSettings__c cs = new UserPasswordResetSettings__c(
            Name = 'UserPasswordSettings',
            Access_Type__c = '\'Static\',\'Integrator\'',
            Email_Recipient__c = 'dupontsfdc.crmsupport@tcs.com.test',
            instance__c = 'CRM',
         // Instances_to_skip_Password_reset__c = 'QA,UAT,Sandbox',
            status__c = 'Not Started'
        );
        insert cs;
        
        scheduleBatchSFARPasswordReset shcheduledClass = new scheduleBatchSFARPasswordReset();
        
        String sch = '0 0 0 15 3 ? 2022';
        system.schedule('Test batch schedule', sch, shcheduledClass); 
        Test.stopTest();
    }


}